import {
  createImmutableScopePackage,
  createPlanningSnapshot,
  createProductionProjectAggregate,
  episodeScope,
  projectScope,
  type ProductionProjectAggregate,
  type ProductionRisk,
  type ProductionStudioRevisionLink,
  type RevisionRef,
  type ScopeRef,
} from "@toonstudio/core/production";

const AT = "2026-09-15T12:00:00.000Z";
/** 샘플 시나리오의 "오늘". 화면에서는 실제 오늘 날짜로 옮겨 보여 준다(`rebaseProductionDemoTimeline`). */
export const PRODUCTION_DEMO_ANCHOR_AT = AT;
/**
 * 샘플 프로젝트의 대표 표지 — 브랜드 아트 자산(밤의 우편배달부 키비주얼, `apps/web/public/brand/production-covers-20261009/`).
 * 샘플 전용 값이다. 실제 사용자 프로젝트는 표지를 직접 등록하기 전까지 null(이니셜 폴백)이 정본이며,
 * 이 상수가 기본 팩토리(`createProductionProjectAggregate`)의 기본값을 바꾸지 않는다.
 */
export const PRODUCTION_DEMO_COVER_IMAGE_URL = "/brand/production-covers-20261009/night-mail-carrier-cover.webp";
const PROJECT_ID = "sample-project";
const WORK_ID = "sample-work";
const project = projectScope(PROJECT_ID);
const episode12 = episodeScope(PROJECT_ID, "episode-12");
const episode13 = episodeScope(PROJECT_ID, "episode-13");

type DemoRiskInput = Pick<
  ProductionRisk,
  | "id"
  | "projectId"
  | "scope"
  | "category"
  | "title"
  | "description"
  | "probability"
  | "impact"
  | "ownerAssignmentId"
  | "mitigation"
  | "trigger"
  | "status"
  | "dueAt"
>;

function createDemoRisk(input: DemoRiskInput): ProductionRisk {
  const exposureScore = input.probability * input.impact;
  const priorityScore = Math.min(100, exposureScore * 4);
  const severity: ProductionRisk["severity"] = priorityScore >= 85
    ? "critical"
    : priorityScore >= 70
      ? "high"
      : priorityScore >= 30 ? "warning" : "watch";
  const episodeId = input.scope.kind === "episode"
    ? input.scope.id
    : input.scope.ancestors.find((entry) => entry.kind === "episode")?.id ?? null;
  return Object.freeze({
    ...input,
    revision: 1,
    source: "manual",
    signalIds: Object.freeze([]),
    exposureScore,
    severity,
    priorityScore,
    causeCodes: Object.freeze(["manual"]),
    earlySignals: Object.freeze([]),
    contingency: "필요하면 일정·범위·인력 조정을 검토합니다.",
    affectedTaskIds: Object.freeze([]),
    affectedEpisodeIds: Object.freeze(episodeId ? [episodeId] : []),
    affectedMilestoneIds: Object.freeze([]),
    baselineDueAt: null,
    forecastDueAt: null,
    varianceHours: null,
    responseDueAt: input.dueAt,
    nextReviewAt: input.dueAt,
    acceptedReason: null,
    dismissedReason: null,
    resolutionSummary: null,
    detectedAt: AT,
    lastEvaluatedAt: AT,
    occurredAt: input.status === "occurred" ? AT : null,
    resolvedAt: input.status === "resolved" ? AT : null,
    closedAt: input.status === "closed" ? AT : null,
    createdAt: AT,
    updatedAt: AT,
  });
}

const scene1201: ScopeRef = {
  kind: "scene",
  id: "scene-12-01",
  ancestors: [
    { kind: "project", id: PROJECT_ID },
    { kind: "episode", id: "episode-12" },
  ],
};
const scene1202: ScopeRef = {
  kind: "scene",
  id: "scene-12-02",
  ancestors: [
    { kind: "project", id: PROJECT_ID },
    { kind: "episode", id: "episode-12" },
  ],
};

const storyRevision: RevisionRef = {
  id: "story-episode-12-r4",
  lineage: "narrative",
  revision: 4,
  digest: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  createdAt: "2026-09-14T04:00:00.000Z",
};
const visualRevision: RevisionRef = {
  id: "thumbnail-episode-12-r2",
  lineage: "visual",
  revision: 2,
  digest: "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  createdAt: "2026-09-15T03:20:00.000Z",
};
const integratedRevision: RevisionRef = {
  id: "proof-episode-11-r6",
  lineage: "integrated",
  revision: 6,
  digest: "sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
  createdAt: "2026-09-12T08:30:00.000Z",
};

export function createProductionDemoProject(): ProductionProjectAggregate {
  const base = createProductionProjectAggregate({
    projectId: PROJECT_ID,
    workId: WORK_ID,
    title: "밤의 우편배달부",
    coverImageUrl: PRODUCTION_DEMO_COVER_IMAGE_URL,
    collaborationModel: "co-creator",
    ownerPartyId: "party-producer",
    ownerUserId: "demo-producer",
    ownerDisplayName: "이서진 PD",
    at: AT,
  });
  const producerAssignmentId = base.assignments[0]!.id;

  const parties = [
    ...base.parties,
    {
      id: "party-story",
      accountUserId: "demo-story",
      legalIdentityRef: null,
      publicDisplayName: "강민서",
      internalDisplayName: "강민서 작가",
      contactPartyId: null,
      agencyPartyId: null,
      status: "active" as const,
    },
    {
      id: "party-art",
      accountUserId: "demo-art",
      legalIdentityRef: null,
      publicDisplayName: "윤하림",
      internalDisplayName: "윤하림 작가",
      contactPartyId: null,
      agencyPartyId: null,
      status: "active" as const,
    },
    {
      id: "party-storyboard",
      accountUserId: "demo-storyboard",
      legalIdentityRef: null,
      publicDisplayName: "박시온",
      internalDisplayName: "박시온 콘티 작가",
      contactPartyId: null,
      agencyPartyId: null,
      status: "active" as const,
    },
    {
      id: "party-line",
      accountUserId: "demo-line",
      legalIdentityRef: null,
      publicDisplayName: "최가은",
      internalDisplayName: "최가은 선화 작가",
      contactPartyId: null,
      agencyPartyId: null,
      status: "active" as const,
    },
    {
      id: "party-color",
      accountUserId: "demo-color",
      legalIdentityRef: null,
      publicDisplayName: "오유나",
      internalDisplayName: "오유나 채색 작가",
      contactPartyId: null,
      agencyPartyId: null,
      status: "active" as const,
    },
    {
      id: "party-lettering",
      accountUserId: "demo-lettering",
      legalIdentityRef: null,
      publicDisplayName: "정태오",
      internalDisplayName: "정태오 식자 담당",
      contactPartyId: null,
      agencyPartyId: null,
      status: "active" as const,
    },
    {
      id: "party-editor",
      accountUserId: "demo-editor",
      legalIdentityRef: null,
      publicDisplayName: "한서윤",
      internalDisplayName: "한서윤 편집자",
      contactPartyId: null,
      agencyPartyId: null,
      status: "active" as const,
    },
    {
      id: "party-rights",
      accountUserId: "demo-rights",
      legalIdentityRef: null,
      publicDisplayName: "김로아",
      internalDisplayName: "김로아 권리 검수",
      contactPartyId: null,
      agencyPartyId: null,
      status: "active" as const,
    },
    {
      id: "party-background-vendor",
      accountUserId: null,
      legalIdentityRef: "vendor-legal-background-01",
      publicDisplayName: "문라이트 배경 스튜디오",
      internalDisplayName: "문라이트 배경 스튜디오",
      contactPartyId: null,
      agencyPartyId: null,
      status: "active" as const,
    },
  ];

  const assignments = [
    ...base.assignments,
    {
      id: "assignment-story",
      projectId: PROJECT_ID,
      partyId: "party-story",
      roleType: "story-lead" as const,
      scope: project,
      startsAt: "2026-08-01T00:00:00.000Z",
      endsAt: null,
      capabilities: ["edit-narrative", "approve-story-lock", "review-visual-intent"],
      agreementRevisionRef: "agreement-creators-r3",
      publicCreditRole: "글",
      status: "active" as const,
      lead: true,
    },
    {
      id: "assignment-art",
      projectId: PROJECT_ID,
      partyId: "party-art",
      roleType: "art-lead" as const,
      scope: project,
      startsAt: "2026-08-01T00:00:00.000Z",
      endsAt: null,
      capabilities: ["edit-visual", "approve-thumbnail-lock", "approve-art"],
      agreementRevisionRef: "agreement-creators-r3",
      publicCreditRole: "그림",
      status: "active" as const,
      lead: true,
    },
    {
      id: "assignment-storyboard",
      projectId: PROJECT_ID,
      partyId: "party-storyboard",
      roleType: "storyboard-artist" as const,
      scope: project,
      startsAt: "2026-09-01T00:00:00.000Z",
      endsAt: null,
      capabilities: ["edit-storyboard", "submit-thumbnail", "review-scroll-rhythm"],
      agreementRevisionRef: "agreement-creators-r3",
      publicCreditRole: "콘티",
      status: "active" as const,
      lead: true,
    },
    {
      id: "assignment-line",
      projectId: PROJECT_ID,
      partyId: "party-line",
      roleType: "line-artist" as const,
      scope: project,
      startsAt: "2026-09-01T00:00:00.000Z",
      endsAt: null,
      capabilities: ["edit-line-art", "submit-line-art", "view-approved-inputs"],
      agreementRevisionRef: "agreement-creators-r3",
      publicCreditRole: "선화",
      status: "active" as const,
      lead: true,
    },
    {
      id: "assignment-color",
      projectId: PROJECT_ID,
      partyId: "party-color",
      roleType: "colorist" as const,
      scope: project,
      startsAt: "2026-09-01T00:00:00.000Z",
      endsAt: null,
      capabilities: ["edit-color", "submit-color", "review-palette"],
      agreementRevisionRef: "agreement-creators-r3",
      publicCreditRole: "채색",
      status: "active" as const,
      lead: true,
    },
    {
      id: "assignment-lettering",
      projectId: PROJECT_ID,
      partyId: "party-lettering",
      roleType: "letterer" as const,
      scope: project,
      startsAt: "2026-09-01T00:00:00.000Z",
      endsAt: null,
      capabilities: ["edit-lettering", "submit-lettering", "review-mobile-readability"],
      agreementRevisionRef: "agreement-creators-r3",
      publicCreditRole: "식자",
      status: "active" as const,
      lead: true,
    },
    {
      id: "assignment-editor",
      projectId: PROJECT_ID,
      partyId: "party-editor",
      roleType: "editor" as const,
      scope: project,
      startsAt: "2026-09-01T00:00:00.000Z",
      endsAt: null,
      capabilities: ["review-integrated-proof", "request-changes", "approve-editorial"],
      agreementRevisionRef: "agreement-creators-r3",
      publicCreditRole: "편집",
      status: "active" as const,
      lead: true,
    },
    {
      id: "assignment-rights",
      projectId: PROJECT_ID,
      partyId: "party-rights",
      roleType: "rights-reviewer" as const,
      scope: project,
      startsAt: "2026-09-01T00:00:00.000Z",
      endsAt: null,
      capabilities: ["review-rights", "review-credit", "verify-asset-license"],
      agreementRevisionRef: "agreement-creators-r3",
      publicCreditRole: "권리 검수",
      status: "active" as const,
      lead: true,
    },
    {
      id: "assignment-background-vendor",
      projectId: PROJECT_ID,
      partyId: "party-background-vendor",
      roleType: "background-artist" as const,
      scope: episode12,
      startsAt: "2026-09-17T00:00:00.000Z",
      endsAt: "2026-09-23T00:00:00.000Z",
      capabilities: ["view-approved-inputs", "submit-background-deliverable"],
      agreementRevisionRef: "agreement-background-r1",
      publicCreditRole: "배경",
      status: "active" as const,
      lead: false,
    },
  ];

  const projectBrief = {
    id: "project-brief-r1",
    projectId: PROJECT_ID,
    revision: 1,
    status: "approved" as const,
    title: "밤의 우편배달부",
    logline: "죽은 사람의 편지를 배달하는 청년이 자신의 이름이 적힌 봉투를 발견한다.",
    synopsis: "도시의 밤을 돌며 타인의 미완성 선택을 마주한 배달부가 자신의 과거와 미래를 동시에 받는다.",
    themes: ["선택", "기억", "애도"],
    genreKeys: ["mystery", "drama", "urban-fantasy"],
    audience: ["15–34세 미스터리·드라마 독자"],
    platformProfileRefs: ["vertical-webtoon-r4"],
    businessGoals: ["주간 연재 40화", "시즌 완결 후 해외 번역"],
    constraints: ["15세 이용가", "주 1회 연재", "회차당 60–75컷"],
    rightsBaselineRef: "rights-baseline-r3",
    approvedByAssignmentIds: [producerAssignmentId, "assignment-story", "assignment-art"],
    createdAt: "2026-09-01T02:00:00.000Z",
  };

  const seriesMaster = {
    id: "series-master-r8",
    projectId: PROJECT_ID,
    revision: 8,
    status: "locked" as const,
    premise: "밤 12시 이후 도착하는 편지는 받는 사람이 외면한 선택을 되돌려 준다.",
    genreRules: ["초자연 현상보다 인물의 선택을 먼저 제시", "편지는 거짓말을 하지 않지만 진실 전체를 말하지 않음"],
    characterBibleRevisionRefs: ["character-haeon-r5", "character-dojin-r3"],
    locationBibleRevisionRefs: ["location-night-city-r4", "location-rooftop-r2"],
    worldRules: ["배달부만 수신인이 아닌 편지의 봉인을 볼 수 있다.", "편지를 태우면 관련 기억 하나가 사라진다."],
    terminology: { 야간편지: "자정 이후 도착하는 초자연 우편", 회수인: "미배달 편지를 회수하는 존재" },
    styleRules: ["현재는 차가운 잉크색, 기억은 제한된 주홍 포인트", "공포보다 정적과 여백을 우선"],
    forbiddenElements: ["발신인 얼굴을 12화 이전에 직접 노출", "편지를 만능 시간여행 장치로 사용"],
    sourceEvidenceRefs: ["world-research-note-r7", "character-interview-r3"],
    approvedByAssignmentIds: [producerAssignmentId, "assignment-story", "assignment-art"],
    createdAt: "2026-09-01T03:00:00.000Z",
  };

  const seasonPlan = {
    id: "season-plan-1-r3",
    projectId: PROJECT_ID,
    seasonId: "season-1",
    revision: 3,
    status: "approved" as const,
    title: "받지 못한 답장",
    goal: "주인공이 자신에게 온 편지의 발신인을 추적하며 배달 규칙의 대가를 이해한다.",
    plotArc: ["규칙 학습", "타인의 선택 개입", "자신에게 온 편지 발견", "기억의 대가", "첫 번째 발신인 대면"],
    characterArcRefs: ["arc-haeon-avoidance-to-choice-r2", "arc-dojin-distrust-to-alliance-r1"],
    episodeOrder: ["episode-11", "episode-12", "episode-13", "episode-14"],
    targetEpisodeCount: 20,
    releaseStartsAt: "2026-10-02T12:00:00.000Z",
    releaseCadenceDays: 7,
    budgetCapMinor: 48000000,
    currency: "KRW",
    approvedByAssignmentIds: [producerAssignmentId, "assignment-story", "assignment-art"],
    createdAt: "2026-09-02T02:00:00.000Z",
  };

  const episodePlan12 = {
    id: "episode-plan-12-r3",
    projectId: PROJECT_ID,
    seasonId: "season-1",
    episodeId: "episode-12",
    episodeNumber: 12,
    revision: 3,
    status: "locked" as const,
    title: "돌아온 봉투",
    logline: "해온은 자신에게 온 봉투를 숨기려다 발신인 문양을 발견한다.",
    openingHook: "아무도 없는 우편함에서 물이 떨어진다.",
    coreConflict: "진실을 확인해야 하는 의무와 자신의 과거를 외면하려는 욕망이 충돌한다.",
    turningPoints: ["발신인 문양 발견", "도진이 봉투를 빼앗으려 함", "옥상으로 도망"],
    cliffhanger: "발신인 이름이 해온 자신임이 드러난다.",
    characterRefs: ["character-haeon-r5", "character-dojin-r3"],
    locationRefs: ["location-alley-r4", "location-rooftop-r2"],
    targetCutCount: 68,
    targetScrollHeightPx: 18420,
    dialogueDensity: "medium" as const,
    difficulty: 4 as const,
    riskIds: ["risk-background-capacity", "risk-envelope-reveal"],
    narrativeRevisionRef: storyRevision,
    approvedByAssignmentIds: ["assignment-story", "assignment-art"],
    createdAt: "2026-09-14T04:20:00.000Z",
  };

  const episodePlan13 = {
    ...episodePlan12,
    id: "episode-plan-13-r1",
    episodeId: "episode-13",
    episodeNumber: 13,
    revision: 1,
    status: "draft" as const,
    title: "보낸 적 없는 편지",
    logline: "해온은 미래의 자신이 편지를 보냈다는 가설을 거부한다.",
    openingHook: "봉투 안쪽에서 아직 쓰이지 않은 잉크가 번진다.",
    coreConflict: "정해진 미래를 믿을 것인가 스스로 새 선택을 만들 것인가.",
    turningPoints: ["날짜 불일치 발견"],
    cliffhanger: "사라진 기억 속 장소의 좌표가 나타난다.",
    targetCutCount: 64,
    targetScrollHeightPx: 17200,
    difficulty: 3 as const,
    riskIds: [],
    narrativeRevisionRef: null,
    approvedByAssignmentIds: [],
    createdAt: "2026-09-15T02:00:00.000Z",
  };

  const scenePlans = [
    {
      id: "scene-plan-12-01-r2",
      projectId: PROJECT_ID,
      episodeId: "episode-12",
      sceneId: "scene-12-01",
      order: 1,
      revision: 2,
      status: "locked" as const,
      purpose: "빈 우편함과 젖은 봉투로 위협을 먼저 제시한다.",
      locationRef: "location-alley-r4",
      timeLabel: "자정 직후",
      characterRefs: ["character-haeon-r5"],
      emotionalBeat: "경계 → 불안",
      continuityRefs: ["continuity-red-envelope", "continuity-left-hand-bandage"],
      instructionRefs: ["instruction-reveal"],
      estimatedMinutes: 5.5,
      approvedByAssignmentIds: ["assignment-story", "assignment-art"],
      createdAt: "2026-09-14T05:00:00.000Z",
    },
    {
      id: "scene-plan-12-02-r2",
      projectId: PROJECT_ID,
      episodeId: "episode-12",
      sceneId: "scene-12-02",
      order: 2,
      revision: 2,
      status: "locked" as const,
      purpose: "도진과의 충돌로 해온이 봉투를 숨기려는 동기를 외부화한다.",
      locationRef: "location-rooftop-r2",
      timeLabel: "자정 20분",
      characterRefs: ["character-haeon-r5", "character-dojin-r3"],
      emotionalBeat: "방어 → 안도 → 의심",
      continuityRefs: ["continuity-envelope-wetness"],
      instructionRefs: ["instruction-silence"],
      estimatedMinutes: 8,
      approvedByAssignmentIds: ["assignment-story", "assignment-art"],
      createdAt: "2026-09-14T05:10:00.000Z",
    },
  ];

  const cutPlans = [
    {
      id: "cut-plan-12-001-r2",
      projectId: PROJECT_ID,
      episodeId: "episode-12",
      sceneId: "scene-12-01",
      cutId: "cut-12-001",
      order: 1,
      revision: 2,
      status: "locked" as const,
      framing: "극단적 세로 롱숏",
      camera: "낮은 시점, 우편함을 화면 상단에 배치",
      characterRefs: ["character-haeon-r5"],
      dialogueRefs: [],
      assetRequirementIds: ["asset-night-alley"],
      layerRequirements: ["비 전경", "골목 배경", "인물", "우편함 글로우"],
      estimatedHours: 1.8,
      complexity: 4 as const,
      approvedByAssignmentIds: ["assignment-art"],
      createdAt: "2026-09-14T06:00:00.000Z",
    },
    {
      id: "cut-plan-12-002-r2",
      projectId: PROJECT_ID,
      episodeId: "episode-12",
      sceneId: "scene-12-01",
      cutId: "cut-12-002",
      order: 2,
      revision: 2,
      status: "locked" as const,
      framing: "손 클로즈업",
      camera: "봉투 문양이 보이되 글자는 초점 밖",
      characterRefs: ["character-haeon-r5"],
      dialogueRefs: ["dialogue-12-002"],
      assetRequirementIds: ["asset-red-envelope"],
      layerRequirements: ["손", "붕대", "봉투", "빗물"],
      estimatedHours: 1.2,
      complexity: 3 as const,
      approvedByAssignmentIds: ["assignment-story", "assignment-art"],
      createdAt: "2026-09-14T06:05:00.000Z",
    },
  ];

  const storySnapshot = createPlanningSnapshot({
    id: "snapshot-story-lock-12",
    projectId: PROJECT_ID,
    scope: episode12,
    type: "story-lock",
    sourceRevisionRefs: [storyRevision],
    documentRefs: [projectBrief.id, seriesMaster.id, episodePlan12.id, ...scenePlans.map((entry) => entry.id)],
    approvedByAssignmentIds: ["assignment-story", "assignment-art"],
    createdAt: "2026-09-14T07:00:00.000Z",
  });

  const handoff = {
    id: "handoff-episode-12-r2",
    projectId: PROJECT_ID,
    episodeId: "episode-12",
    handoffRevision: 2,
    status: "clarification-open" as const,
    storySnapshotRef: storyRevision,
    storyLockRef: storyRevision,
    storyBibleRevisionRef: seriesMaster.id,
    characterBibleRevisionRefs: ["character-haeon-r5", "character-dojin-r3"],
    episodeIntentRef: episodePlan12.id,
    beatRefs: ["beat-12-01", "beat-12-02", "beat-12-03", "beat-12-04"],
    sceneRefs: scenePlans.map((entry) => entry.sceneId),
    lockedDialogueRefs: ["dialogue-12-031", "dialogue-12-044"],
    continuityReferenceRefs: ["continuity-red-envelope", "continuity-left-hand-bandage"],
    visualRequirementRefs: ["visual-rain-density", "visual-final-door-silhouette"],
    forbiddenInterpretationRefs: ["do-not-reveal-sender-face"],
    assetRequirementRefs: ["asset-night-alley", "asset-red-envelope", "asset-old-postbox"],
    locationReferenceRefs: ["location-alley-r4", "location-rooftop-r2"],
    costumeReferenceRefs: ["costume-haeon-night-r3"],
    instructions: [
      {
        id: "instruction-reveal",
        scope: episode12,
        priority: "MUST_PRESERVE" as const,
        latitude: "bounded" as const,
        text: "봉투의 발신인 이름은 마지막 컷 전까지 읽을 수 없어야 한다.",
        rationale: "회차 엔딩의 정보 공개 순서를 지킨다.",
        sourceRevisionRef: storyRevision.id,
      },
      {
        id: "instruction-silence",
        scope: episode12,
        priority: "INTENT" as const,
        latitude: "open" as const,
        text: "옥상 장면은 고립감이 먼저 느껴져야 한다.",
        rationale: "다음 회차에서 관계가 회복되는 대비를 만든다.",
        sourceRevisionRef: storyRevision.id,
      },
      {
        id: "instruction-layout",
        scope: episode12,
        priority: "ARTIST_CHOICE" as const,
        latitude: "exploratory" as const,
        text: "계단 이동의 컷 수와 카메라 높이는 그림 작가가 결정한다.",
        rationale: "세로 스크롤 리듬을 시각 연출에 맡긴다.",
        sourceRevisionRef: storyRevision.id,
      },
    ],
    platformProfileRef: "vertical-webtoon-r4",
    technicalDeliveryRuleRef: "delivery-rule-r6",
    rightsAndAiPolicyRef: "rights-ai-policy-r3",
    creditPolicyRef: "credit-policy-r3",
    expectedDeliverables: ["12화 전체 콘티", "핵심 장면 컬러 키 2종"],
    reviewPolicyRef: "review-policy-episode-r2",
    decisionOwnerAssignmentIds: ["assignment-story", "assignment-art"],
    dueAt: "2026-09-18T09:00:00.000Z",
    openRiskAcceptances: [],
    createdByAssignmentId: "assignment-story",
    acceptedByAssignmentId: null,
    acceptedAt: null,
    digest: "sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
    createdAt: "2026-09-14T05:00:00.000Z",
  };

  const scopePackage = createImmutableScopePackage({
    id: "scope-background-episode-12",
    projectId: PROJECT_ID,
    revision: 1,
    status: "published",
    scopes: [episode12],
    inputRevisionRefs: [storyRevision, visualRevision],
    deliverableSpecifications: ["배경 12컷", "원본 PSD 레이어", "사용 에셋·라이선스 목록"],
    acceptanceCriteria: ["캐릭터 레이어와 분리", "원근·광원 continuity 통과", "플랫폼 안전영역 준수"],
    includedRevisionRounds: 2,
    schedule: {
      proposalDueAt: "2026-09-16T09:00:00.000Z",
      startsAt: "2026-09-17T00:00:00.000Z",
      deliveryDueAt: "2026-09-21T09:00:00.000Z",
      reviewResponseHours: 24,
    },
    rightsPolicyRef: "rights-policy-r3",
    aiPolicyRef: "ai-policy-r3",
    creditPolicyRef: "credit-policy-r3",
    compensationTermsRef: "compensation-background-r1",
    informationDisclosureLevel: "nda",
    createdAt: "2026-09-14T08:00:00.000Z",
  });

  const deliverables = [
    {
      id: "deliverable-thumbnail-12",
      projectId: PROJECT_ID,
      scope: episode12,
      type: "thumbnail",
      expectedFormat: "studio-document",
      completionCriteria: ["전체 컷 배치", "대사 안전영역", "클리프행어 공개 순서"],
      currentSubmissionId: "submission-thumbnail-12-r2",
      approvedSubmissionId: null,
    },
    {
      id: "deliverable-background-sample-12",
      projectId: PROJECT_ID,
      scope: scene1201,
      type: "background-sample",
      expectedFormat: "layered-psd",
      completionCriteria: ["2컷 광원 기준", "캐릭터 레이어 분리", "에셋 출처 첨부"],
      currentSubmissionId: "submission-background-sample-r1",
      approvedSubmissionId: "submission-background-sample-r1",
    },
    {
      id: "deliverable-line-art-12",
      projectId: PROJECT_ID,
      scope: episode12,
      type: "line-art",
      expectedFormat: "layered-studio-document",
      completionCriteria: ["캐릭터 모델 일치", "확대 선 품질", "채색 인계 레이어 정리"],
      currentSubmissionId: null,
      approvedSubmissionId: null,
    },
    {
      id: "deliverable-background-final-12",
      projectId: PROJECT_ID,
      scope: episode12,
      type: "background-final",
      expectedFormat: "layered-psd",
      completionCriteria: ["12컷 원본 PSD", "광원·원근 continuity", "라이선스 증빙"],
      currentSubmissionId: null,
      approvedSubmissionId: null,
    },
    {
      id: "deliverable-color-12",
      projectId: PROJECT_ID,
      scope: episode12,
      type: "color-and-effects",
      expectedFormat: "layered-studio-document",
      completionCriteria: ["팔레트 기준 일치", "컷 간 조명 연결", "효과 레이어 분리"],
      currentSubmissionId: null,
      approvedSubmissionId: null,
    },
    {
      id: "deliverable-lettering-12",
      projectId: PROJECT_ID,
      scope: episode12,
      type: "lettering",
      expectedFormat: "integrated-studio-document",
      completionCriteria: ["대사 정본 일치", "모바일 가독성", "효과음·폰트 라이선스"],
      currentSubmissionId: null,
      approvedSubmissionId: null,
    },
    {
      id: "deliverable-proof-12",
      projectId: PROJECT_ID,
      scope: episode12,
      type: "integrated-proof",
      expectedFormat: "vertical-scroll-proof",
      completionCriteria: ["서사·시각·식자 통합 검수", "플랫폼 규격", "필수 lane 승인"],
      currentSubmissionId: null,
      approvedSubmissionId: null,
    },
    {
      id: "deliverable-rights-preflight-12",
      projectId: PROJECT_ID,
      scope: episode12,
      type: "rights-preflight",
      expectedFormat: "signed-manifest-json",
      completionCriteria: ["외부 에셋 라이선스", "AI 사용 증빙", "크레딧 정합성"],
      currentSubmissionId: null,
      approvedSubmissionId: null,
    },
    {
      id: "deliverable-publication-12",
      projectId: PROJECT_ID,
      scope: episode12,
      type: "publication-package",
      expectedFormat: "platform-upload-package",
      completionCriteria: ["게시 후보 revision 고정", "크레딧 preflight", "업로드 규격 검증"],
      currentSubmissionId: null,
      approvedSubmissionId: null,
    },
    {
      id: "deliverable-story-13",
      projectId: PROJECT_ID,
      scope: episode13,
      type: "story-script",
      expectedFormat: "narrative-revision",
      completionCriteria: ["회차 의도", "장면별 감정 변화", "복선·연속성 검수"],
      currentSubmissionId: null,
      approvedSubmissionId: null,
    },
  ];

  const submissions = [
    {
      id: "submission-thumbnail-12-r2",
      projectId: PROJECT_ID,
      deliverableId: "deliverable-thumbnail-12",
      revisionRef: visualRevision,
      submittedByAssignmentId: "assignment-art",
      submittedAt: "2026-09-15T03:30:00.000Z",
      status: "in-review" as const,
      inputRevisionRefs: [storyRevision],
      evidenceRefs: ["thumbnail-diff-r1-r2"],
    },
    {
      id: "submission-background-sample-r1",
      projectId: PROJECT_ID,
      deliverableId: "deliverable-background-sample-12",
      revisionRef: {
        id: "background-sample-r1",
        lineage: "visual" as const,
        revision: 1,
        digest: "sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
        createdAt: "2026-09-18T02:00:00.000Z",
      },
      submittedByAssignmentId: "assignment-background-vendor",
      submittedAt: "2026-09-18T02:05:00.000Z",
      status: "approved" as const,
      inputRevisionRefs: [storyRevision, visualRevision],
      evidenceRefs: ["approval-background-sample-r1"],
    },
  ];

  const studioRevisionLinks: readonly ProductionStudioRevisionLink[] = [
    {
      id: "studio-link-thumbnail-12-r2",
      projectId: PROJECT_ID,
      workId: WORK_ID,
      episodeId: "episode-12",
      studioDocumentRef: "document-episode-12-thumbnail",
      documentRole: "thumbnail",
      studioRevisionRef: visualRevision,
      deliverableId: "deliverable-thumbnail-12",
      submissionId: "submission-thumbnail-12-r2",
      linkedByAssignmentId: "assignment-art",
      status: "submitted",
      linkedAt: "2026-09-15T03:35:00.000Z",
      approvedAt: null,
    },
    {
      id: "studio-link-background-sample-12-r1",
      projectId: PROJECT_ID,
      workId: WORK_ID,
      episodeId: "episode-12",
      studioDocumentRef: "document-episode-12-background-sample",
      documentRole: "background",
      studioRevisionRef: submissions[1]!.revisionRef,
      deliverableId: "deliverable-background-sample-12",
      submissionId: "submission-background-sample-r1",
      linkedByAssignmentId: "assignment-background-vendor",
      status: "approved",
      linkedAt: "2026-09-18T02:10:00.000Z",
      approvedAt: "2026-09-18T02:10:00.000Z",
    },
  ];

  const proposal = {
    id: "proposal-background-vendor-r1",
    projectId: PROJECT_ID,
    scopePackageId: scopePackage.id,
    scopePackageRevision: scopePackage.revision,
    proposerPartyId: "party-background-vendor",
    status: "selected" as const,
    understanding: "야간 골목과 옥상 배경 12컷을 콘티와 광원 continuity에 맞춰 제작합니다.",
    approach: "3D 블로킹 후 2D 페인트오버, 승인 샘플의 광원 룩을 최종 컷에 유지합니다.",
    experienceRefs: ["portfolio-night-city-2025", "portfolio-rooftop-2026"],
    scheduleSummary: "샘플 2컷 1일, 본 작업 3일, 수정 1일",
    milestoneDrafts: [
      { title: "샘플 2컷", dueAt: "2026-09-18T09:00:00.000Z", amountMinor: 200000 },
      { title: "최종 12컷", dueAt: "2026-09-21T09:00:00.000Z", amountMinor: 600000 },
    ],
    totalAmountMinor: 800000,
    currency: "KRW",
    includedRevisionRounds: 2,
    assumptions: ["콘티 revision r2 고정", "캐릭터 작화는 내부팀 제공"],
    exclusions: ["캐릭터 작화", "추가 3D 모델 구매"],
    risks: ["콘티 변경 시 납기·금액 재협의"],
    submittedAt: "2026-09-15T05:00:00.000Z",
  };

  const agreement = {
    id: "agreement-background-r1",
    projectId: PROJECT_ID,
    revision: 1,
    status: "active" as const,
    scopePackageId: scopePackage.id,
    scopePackageRevision: scopePackage.revision,
    selectedProposalId: proposal.id,
    partyIds: ["party-producer", "party-background-vendor"],
    totalAmountMinor: 800000,
    currency: "KRW",
    rightsPolicyRef: "rights-policy-r3",
    creditPolicyRef: "credit-policy-r3",
    compensationPlanRef: "compensation-background-r1",
    confidentialityPolicyRef: "nda-background-r1",
    signedEvidenceRefs: ["signed-contract-background-r1"],
    effectiveAt: "2026-09-16T01:00:00.000Z",
    endsAt: "2026-09-23T00:00:00.000Z",
    createdAt: "2026-09-16T01:00:00.000Z",
  };

  const milestones = [
    {
      id: "milestone-background-sample",
      projectId: PROJECT_ID,
      agreementId: agreement.id,
      title: "샘플 2컷",
      sequence: 1,
      scopeRefs: [scene1201],
      deliverableIds: ["deliverable-background-sample-12"],
      acceptanceCriteria: ["광원과 원근 기준 승인", "라이선스 증빙"],
      amountMinor: 200000,
      currency: "KRW",
      dueAt: "2026-09-18T09:00:00.000Z",
      status: "invoiced" as const,
      acceptedSubmissionIds: ["submission-background-sample-r1"],
    },
    {
      id: "milestone-background-final",
      projectId: PROJECT_ID,
      agreementId: agreement.id,
      title: "최종 12컷",
      sequence: 2,
      scopeRefs: [episode12],
      deliverableIds: ["deliverable-background-final-12"],
      acceptanceCriteria: ["12컷 원본 PSD", "레이어 분리", "라이선스와 AI 사용 영수증"],
      amountMinor: 600000,
      currency: "KRW",
      dueAt: "2026-09-21T09:00:00.000Z",
      status: "in-progress" as const,
      acceptedSubmissionIds: [],
    },
  ];

  const activityNames = [
    "project-created",
    "configure-collaboration",
    "upsert-planning-record",
    "create-planning-snapshot",
    "upsert-handoff",
    "upsert-review-policy",
    "publish-scope-package",
    "upsert-commercial-record",
  ];

  return {
    ...base,
    revision: activityNames.length,
    parties,
    assignments,
    authorityRules: [
      {
        id: "authority-dialogue",
        projectId: PROJECT_ID,
        domain: "dialogue",
        scope: project,
        proposerAssignmentIds: ["assignment-story", "assignment-art"],
        requiredConsultAssignmentIds: ["assignment-art"],
        requiredApproverAssignmentIds: ["assignment-story"],
        decisionAssignmentId: "assignment-story",
        vetoAssignmentIds: ["assignment-story"],
        mediatorAssignmentId: producerAssignmentId,
        quorum: { approvals: 1, eligible: 1 },
        effectiveFrom: "2026-09-01T00:00:00.000Z",
        expiresAt: null,
        agreementRevisionRef: "agreement-creators-r3",
      },
      {
        id: "authority-layout",
        projectId: PROJECT_ID,
        domain: "layout",
        scope: project,
        proposerAssignmentIds: ["assignment-story", "assignment-art"],
        requiredConsultAssignmentIds: ["assignment-story"],
        requiredApproverAssignmentIds: ["assignment-art"],
        decisionAssignmentId: "assignment-art",
        vetoAssignmentIds: [],
        mediatorAssignmentId: producerAssignmentId,
        quorum: { approvals: 1, eligible: 1 },
        effectiveFrom: "2026-09-01T00:00:00.000Z",
        expiresAt: null,
        agreementRevisionRef: "agreement-creators-r3",
      },
      {
        id: "authority-publication",
        projectId: PROJECT_ID,
        domain: "publication",
        scope: project,
        proposerAssignmentIds: [producerAssignmentId],
        requiredConsultAssignmentIds: [],
        requiredApproverAssignmentIds: ["assignment-story", "assignment-art", producerAssignmentId],
        decisionAssignmentId: producerAssignmentId,
        vetoAssignmentIds: ["assignment-story", "assignment-art"],
        mediatorAssignmentId: producerAssignmentId,
        quorum: { approvals: 3, eligible: 3 },
        effectiveFrom: "2026-09-01T00:00:00.000Z",
        expiresAt: null,
        agreementRevisionRef: "agreement-creators-r3",
      },
    ],
    charters: [{
      id: "charter-r2",
      projectId: PROJECT_ID,
      revision: 2,
      status: "active",
      coreExperience: "독자는 매 회차 마지막 세 컷에서 일상의 규칙이 조금씩 뒤집히는 감각을 경험한다.",
      immutablePrinciples: ["초자연 현상보다 인물의 선택을 먼저 보여 준다.", "주인공은 독자보다 먼저 정답을 알 수 없다."],
      experimentalAreas: ["무대사 세로 여백", "소품 색을 이용한 반복 모티프"],
      storyAutonomy: ["플롯과 캐릭터 동기", "대사와 정보 공개 순서"],
      artAutonomy: ["컷 분할", "구도", "선과 색의 스타일"],
      jointDecisionAreas: ["핵심 장면 연출", "캐릭터 핵심 디자인", "게시 후보"],
      feedbackPrinciples: ["취향이 아니라 승인된 의도와 기준을 근거로 말한다."],
      communicationRules: ["차단 질문은 24시간 안에 응답하거나 대체 결정자를 지정한다."],
      confirmedByAssignmentIds: [producerAssignmentId, "assignment-story", "assignment-art"],
      agreementRevisionRef: "agreement-creators-r3",
      createdAt: "2026-09-01T02:00:00.000Z",
    }],
    episodes: [
      {
        id: "episode-collaboration-11",
        projectId: PROJECT_ID,
        episodeId: "episode-11",
        revision: 9,
        state: "published",
        narrativeRevisionRef: storyRevision,
        visualRevisionRef: visualRevision,
        integratedRevisionRef: integratedRevision,
        activeHandoffId: "handoff-episode-11-r2",
        openBlockerCount: 0,
        storyLockApproved: true,
        thumbnailLockApproved: true,
        jointProofApproved: true,
        creditPreflightPassed: true,
        publicationPreflightPassed: true,
        updatedAt: "2026-09-13T00:00:00.000Z",
      },
      {
        id: "episode-collaboration-12",
        projectId: PROJECT_ID,
        episodeId: "episode-12",
        revision: 4,
        state: "art-clarification",
        narrativeRevisionRef: storyRevision,
        visualRevisionRef: visualRevision,
        integratedRevisionRef: null,
        activeHandoffId: handoff.id,
        openBlockerCount: 1,
        storyLockApproved: true,
        thumbnailLockApproved: false,
        jointProofApproved: false,
        creditPreflightPassed: false,
        publicationPreflightPassed: false,
        updatedAt: "2026-09-15T07:20:00.000Z",
      },
      {
        id: "episode-collaboration-13",
        projectId: PROJECT_ID,
        episodeId: "episode-13",
        revision: 1,
        state: "story-drafting",
        narrativeRevisionRef: null,
        visualRevisionRef: null,
        integratedRevisionRef: null,
        activeHandoffId: null,
        openBlockerCount: 0,
        storyLockApproved: false,
        thumbnailLockApproved: false,
        jointProofApproved: false,
        creditPreflightPassed: false,
        publicationPreflightPassed: false,
        updatedAt: "2026-09-15T02:10:00.000Z",
      },
    ],
    handoffs: [handoff],
    clarifications: [
      {
        id: "clarification-envelope-angle",
        handoffId: handoff.id,
        scope: episode12,
        category: "narrative-ambiguity",
        blocking: true,
        question: "마지막 컷 전에도 봉투 뒷면의 문양은 보여도 되나요?",
        askedByAssignmentId: "assignment-art",
        answerOwnerAssignmentId: "assignment-story",
        dueAt: "2026-09-16T03:00:00.000Z",
        status: "open",
        answer: null,
        decisionRecordId: null,
        createdAt: "2026-09-15T03:40:00.000Z",
        updatedAt: "2026-09-15T03:40:00.000Z",
      },
      {
        id: "clarification-rooftop-weather",
        handoffId: handoff.id,
        scope: episode12,
        category: "continuity",
        blocking: false,
        question: "옥상 장면에도 비가 계속 오나요?",
        askedByAssignmentId: "assignment-art",
        answerOwnerAssignmentId: "assignment-story",
        dueAt: null,
        status: "decision-recorded",
        answer: "비는 멈추고 물방울만 남습니다. 다음 장면의 고요함을 위해 소리 효과도 제거합니다.",
        decisionRecordId: "decision-weather-12",
        createdAt: "2026-09-14T08:20:00.000Z",
        updatedAt: "2026-09-14T10:10:00.000Z",
      },
    ],
    branches: [{
      id: "branch-thumbnail-12",
      projectId: PROJECT_ID,
      episodeId: "episode-12",
      type: "thumbnail",
      lineage: "visual",
      baseRevisionRef: { ...visualRevision, id: "thumbnail-episode-12-r1", revision: 1, digest: "sha256:abababababababababababababababababababababababababababababababab" },
      headRevisionRef: visualRevision,
      ownerAssignmentId: "assignment-art",
      purpose: "세로 리듬과 마지막 정보 공개 순서를 탐색한다.",
      mergeTarget: "visual",
      visibility: "team",
      allowedScopes: [episode12],
      expiresAt: null,
      status: "review",
    }],
    mergeRequests: [{
      id: "merge-thumbnail-12-r2",
      projectId: PROJECT_ID,
      episodeId: "episode-12",
      sourceBranchId: "branch-thumbnail-12",
      targetLineage: "visual",
      baseRevisionRef: { ...visualRevision, id: "thumbnail-episode-12-r1", revision: 1, digest: "sha256:abababababababababababababababababababababababababababababababab" },
      proposedRevisionRef: visualRevision,
      mergedRevisionRef: null,
      summary: "옥상 무대사 여백을 늘리고 봉투 문양 노출을 마지막 네 컷으로 이동",
      changedScopes: [episode12],
      affectedDecisionIds: ["decision-envelope-reveal"],
      affectedApprovalIds: [storySnapshot.id],
      requiredReviewLanes: ["narrative", "visual-direction", "production"],
      mergePolicyId: "review-policy-episode-r2",
      status: "ready-for-review",
      createdByAssignmentId: "assignment-art",
      createdAt: "2026-09-15T03:30:00.000Z",
    }],
    reviewPolicies: [{
      id: "review-policy-episode-r2",
      projectId: PROJECT_ID,
      scope: episode12,
      responseDueHours: 24,
      expiredReviewAction: "escalate",
      lanes: [
        { lane: "narrative", eligibleAssignmentIds: ["assignment-story"], requiredAssignmentIds: ["assignment-story"], quorum: 1, vetoAssignmentIds: ["assignment-story"], blocksPublication: true },
        { lane: "visual-direction", eligibleAssignmentIds: ["assignment-art"], requiredAssignmentIds: ["assignment-art"], quorum: 1, vetoAssignmentIds: ["assignment-art"], blocksPublication: true },
        { lane: "production", eligibleAssignmentIds: [producerAssignmentId], requiredAssignmentIds: [producerAssignmentId], quorum: 1, vetoAssignmentIds: [], blocksPublication: true },
      ],
    }],
    reviewDecisions: [{
      id: "review-narrative-round-1",
      reviewRoundId: "thumbnail-round-1",
      lane: "narrative",
      assignmentId: "assignment-story",
      value: "approve-with-conditions",
      reasonCode: "preserve-reveal-order",
      evidenceScopeRefs: [episode12],
      conditions: ["봉투 문양 노출 범위를 질문 답변 후 확정"],
      createdAt: "2026-09-15T05:30:00.000Z",
    }],
    tasks: [
      {
        id: "task-episode-12-thumbnail",
        projectId: PROJECT_ID,
        scope: episode12,
        processKey: "thumbnail",
        title: "12화 콘티와 세로 리듬",
        status: "internal-review",
        assignmentIds: ["assignment-storyboard"],
        reviewerAssignmentIds: ["assignment-art", "assignment-story", producerAssignmentId],
        inputRevisionRefs: [storyRevision],
        outputDeliverableIds: ["deliverable-thumbnail-12"],
        dependencyTaskIds: [],
        dueAt: "2026-09-18T09:00:00.000Z",
        estimateHours: { optimistic: 12, likely: 16, pessimistic: 22 },
        completionCriteria: ["전체 컷 배치", "대사 안전영역", "클리프행어 정보 공개 순서"],
        sourceAgreementMilestoneId: null,
      },
      {
        id: "task-episode-12-line-art",
        projectId: PROJECT_ID,
        scope: episode12,
        processKey: "line-art",
        title: "12화 캐릭터 선화 42컷",
        status: "needs-input",
        assignmentIds: ["assignment-line"],
        reviewerAssignmentIds: ["assignment-art", "assignment-editor"],
        inputRevisionRefs: [visualRevision],
        outputDeliverableIds: ["deliverable-line-art-12"],
        dependencyTaskIds: ["task-episode-12-thumbnail"],        dueAt: "2026-09-20T09:00:00.000Z",
        estimateHours: { optimistic: 20, likely: 28, pessimistic: 36 },
        completionCriteria: ["캐릭터 모델·의상 continuity", "확대 선 품질", "채색 인계 레이어 정리"],
        sourceAgreementMilestoneId: null,
      },
      {
        id: "task-episode-12-background",
        projectId: PROJECT_ID,
        scope: episode12,
        processKey: "background",
        title: "12화 야간 배경 12컷 외주",
        status: "blocked",
        assignmentIds: ["assignment-background-vendor"],
        reviewerAssignmentIds: ["assignment-art", "assignment-rights"],
        inputRevisionRefs: [visualRevision],
        outputDeliverableIds: ["deliverable-background-sample-12", "deliverable-background-final-12"],
        dependencyTaskIds: ["task-episode-12-thumbnail"],
        dueAt: "2026-09-21T09:00:00.000Z",
        estimateHours: { optimistic: 14, likely: 20, pessimistic: 30 },
        completionCriteria: ["PSD 레이어 분리", "광원 continuity", "라이선스 목록"],
        sourceAgreementMilestoneId: "milestone-background-final",
      },
      {
        id: "task-episode-12-color",
        projectId: PROJECT_ID,
        scope: episode12,
        processKey: "color",
        title: "12화 밑색·명암·이펙트",
        status: "draft",
        assignmentIds: ["assignment-color"],
        reviewerAssignmentIds: ["assignment-art", "assignment-editor"],        inputRevisionRefs: [visualRevision],
        outputDeliverableIds: ["deliverable-color-12"],
        dependencyTaskIds: ["task-episode-12-line-art", "task-episode-12-background"],
        dueAt: "2026-09-23T09:00:00.000Z",
        estimateHours: { optimistic: 18, likely: 26, pessimistic: 34 },
        completionCriteria: ["팔레트 기준 일치", "컷 간 조명 연결", "효과 레이어 분리"],
        sourceAgreementMilestoneId: null,
      },
      {
        id: "task-episode-12-lettering",
        projectId: PROJECT_ID,
        scope: episode12,
        processKey: "lettering",
        title: "12화 말풍선·효과음·식자",
        status: "draft",
        assignmentIds: ["assignment-lettering"],
        reviewerAssignmentIds: ["assignment-editor", "assignment-story"],
        inputRevisionRefs: [storyRevision, visualRevision],
        outputDeliverableIds: ["deliverable-lettering-12"],
        dependencyTaskIds: ["task-episode-12-color"],
        dueAt: "2026-09-24T03:00:00.000Z",
        estimateHours: { optimistic: 6, likely: 9, pessimistic: 13 },
        completionCriteria: ["대사 정본 일치", "모바일 가독성", "효과음·폰트 라이선스"],
        sourceAgreementMilestoneId: null,
      },
      {
        id: "task-episode-12-rights",
        projectId: PROJECT_ID,
        scope: episode12,
        processKey: "rights-preflight",
        title: "12화 에셋·AI·크레딧 권리 검수",
        status: "in-progress",        assignmentIds: ["assignment-rights"],
        reviewerAssignmentIds: [producerAssignmentId, "assignment-editor"],
        inputRevisionRefs: [storyRevision, visualRevision],
        outputDeliverableIds: ["deliverable-rights-preflight-12"],
        dependencyTaskIds: [],
        dueAt: "2026-09-23T03:00:00.000Z",
        estimateHours: { optimistic: 3, likely: 5, pessimistic: 8 },
        completionCriteria: ["외부 에셋 라이선스", "AI 사용 증빙", "크레딧 manifest 정합성"],
        sourceAgreementMilestoneId: null,
      },
      {
        id: "task-episode-12-proof",
        projectId: PROJECT_ID,
        scope: episode12,
        processKey: "joint-proof",
        title: "12화 통합 원고 공동 교정",
        status: "draft",
        assignmentIds: ["assignment-editor"],
        reviewerAssignmentIds: ["assignment-story", "assignment-art", producerAssignmentId],
        inputRevisionRefs: [storyRevision, visualRevision],
        outputDeliverableIds: ["deliverable-proof-12"],
        dependencyTaskIds: ["task-episode-12-lettering", "task-episode-12-rights"],
        dueAt: "2026-09-24T09:00:00.000Z",
        estimateHours: { optimistic: 4, likely: 7, pessimistic: 10 },
        completionCriteria: ["서사·시각·식자 통합 비교", "플랫폼 규격", "필수 lane 승인"],
        sourceAgreementMilestoneId: null,
      },
      {
        id: "task-episode-12-publication",
        projectId: PROJECT_ID,
        scope: episode12,
        processKey: "publication",        title: "12화 게시 패키지와 예약 공개",
        status: "draft",
        assignmentIds: [producerAssignmentId],
        reviewerAssignmentIds: ["assignment-editor", "assignment-rights"],
        inputRevisionRefs: [storyRevision, visualRevision],
        outputDeliverableIds: ["deliverable-publication-12"],
        dependencyTaskIds: ["task-episode-12-proof", "task-episode-12-rights"],
        dueAt: "2026-09-25T09:00:00.000Z",
        estimateHours: { optimistic: 2, likely: 3, pessimistic: 5 },
        completionCriteria: ["게시 후보 revision 고정", "크레딧·권리 preflight", "업로드 규격 검증"],
        sourceAgreementMilestoneId: null,
      },
      {
        id: "task-episode-13-story",
        projectId: PROJECT_ID,
        scope: episode13,
        processKey: "story",
        title: "13화 대본 2차 초안",
        status: "in-progress",
        assignmentIds: ["assignment-story"],
        reviewerAssignmentIds: [producerAssignmentId, "assignment-editor"],
        inputRevisionRefs: [storyRevision],
        outputDeliverableIds: ["deliverable-story-13"],
        dependencyTaskIds: [],
        dueAt: "2026-09-19T09:00:00.000Z",
        estimateHours: { optimistic: 6, likely: 9, pessimistic: 13 },
        completionCriteria: ["복선 회수 계약 반영", "장면별 감정 변화 기록"],
        sourceAgreementMilestoneId: null,
      },
    ],
    deliverables,
    submissions,
    studioRevisionLinks,
    changeRequests: [{
      id: "change-ending-dialogue-12",
      projectId: PROJECT_ID,
      episodeId: "episode-12",
      stage: "post-thumbnail-lock",
      sourceRevisionRef: storyRevision,
      proposedRevisionRef: { ...storyRevision, id: "story-episode-12-r5", revision: 5, digest: "sha256:1212121212121212121212121212121212121212121212121212121212121212" },
      changedScopes: [scene1202],
      reason: "플랫폼 편집부가 마지막 대사의 정보량을 줄여 달라고 요청함",
      requestedByAssignmentId: producerAssignmentId,
      status: "impact-analysis",
      createdAt: "2026-09-15T09:00:00.000Z",
    }],
    scopePackages: [scopePackage],
    scopePackageRevisionArchive: [],
    scopePackageAddenda: [],
    contributions: [
      { id: "contribution-story-12", projectId: PROJECT_ID, partyId: "party-story", assignmentId: "assignment-story", scope: episode12, revisionRef: storyRevision, contributionType: "story-script", approvedAt: "2026-09-14T04:20:00.000Z", approvalId: storySnapshot.id },
      { id: "contribution-thumbnail-12", projectId: PROJECT_ID, partyId: "party-art", assignmentId: "assignment-art", scope: episode12, revisionRef: visualRevision, contributionType: "thumbnail-layout", approvedAt: null, approvalId: null },
    ],
    creditManifests: [{
      id: "credit-episode-12-r1",
      projectId: PROJECT_ID,
      episodeId: "episode-12",
      revision: 1,
      status: "review",
      contentRevisionRefs: [storyRevision, visualRevision],
      entries: [
        { id: "credit-story", partyId: "party-story", publicName: "강민서", roleLabel: "글", scopes: [episode12], order: 1, media: ["episode", "metadata"], anonymous: false },
        { id: "credit-art", partyId: "party-art", publicName: "윤하림", roleLabel: "그림", scopes: [episode12], order: 2, media: ["episode", "metadata"], anonymous: false },
        { id: "credit-background", partyId: "party-background-vendor", publicName: "문라이트 배경 스튜디오", roleLabel: "배경", scopes: [episode12], order: 3, media: ["episode"], anonymous: false },
      ],
      approvedByAssignmentIds: ["assignment-story"],
      agreementRevisionRefs: ["agreement-creators-r3", agreement.id],
      createdAt: "2026-09-14T09:00:00.000Z",
    }],
    rightsInterests: [
      { id: "rights-story-authorship", projectId: PROJECT_ID, partyId: "party-story", type: "authorship-claim", scope: project, status: "verified", agreementRevisionRef: "agreement-creators-r3", evidenceRefs: ["contract-evidence-r3"], startsAt: "2026-08-01T00:00:00.000Z", endsAt: null },
      { id: "rights-art-authorship", projectId: PROJECT_ID, partyId: "party-art", type: "authorship-claim", scope: project, status: "verified", agreementRevisionRef: "agreement-creators-r3", evidenceRefs: ["contract-evidence-r3"], startsAt: "2026-08-01T00:00:00.000Z", endsAt: null },
      { id: "rights-ai-training", projectId: PROJECT_ID, partyId: "party-art", type: "ai-training-consent", scope: project, status: "asserted", agreementRevisionRef: "agreement-creators-r3", evidenceRefs: ["opt-out-ai-training-r1"], startsAt: "2026-08-01T00:00:00.000Z", endsAt: null },
    ],
    compensationPlans: [{
      id: "compensation-plan-r3",
      projectId: PROJECT_ID,
      revision: 3,
      status: "active",
      fixedFeeTerms: ["회차별 최소 보장", "유상 수정 3회차부터 별도 ChangeOrder"],
      revenueShareRules: [
        { id: "revenue-domestic", revenueSource: "domestic-serialization", basis: "gross", deductions: [], partySharesBasisPoints: { "party-story": 3500, "party-art": 4500, "party-producer": 2000 }, recoupmentRef: null },
        { id: "revenue-video", revenueSource: "video", basis: "net", deductions: ["직접 외부 제작비", "플랫폼 수수료 — 계약상 상한 적용"], partySharesBasisPoints: { "party-story": 3000, "party-art": 3000, "party-producer": 4000 }, recoupmentRef: "recoupment-video-r1" },
      ],
      statementFrequency: "quarterly",
      auditRight: true,
      agreementRevisionRef: "agreement-creators-r3",
      createdAt: "2026-09-01T00:00:00.000Z",
    }],
    projectBriefs: [projectBrief],
    seriesMasters: [seriesMaster],
    seasonPlans: [seasonPlan],
    episodePlans: [episodePlan12, episodePlan13],
    scenePlans,
    cutPlans,
    planningSnapshots: [storySnapshot],
    assetRequirements: [
      { id: "asset-night-alley", projectId: PROJECT_ID, scope: scene1201, category: "location", title: "야간 골목 세트", specification: "3점 투시, 비 온 노면, 기존 우편함 위치 유지", sourcePlanRefs: [scenePlans[0]!.id, cutPlans[0]!.id], sourcing: "external", rightsRequirements: ["상업 연재 및 해외 번역 이용 허용", "원본 PSD 인계"], requiredByAt: "2026-09-18T00:00:00.000Z", status: "sourcing" },
      { id: "asset-red-envelope", projectId: PROJECT_ID, scope: scene1201, category: "prop", title: "붉은 봉투", specification: "문양과 글자 레이어 분리, 젖은 상태 variation", sourcePlanRefs: [cutPlans[1]!.id], sourcing: "internal", rightsRequirements: [], requiredByAt: "2026-09-17T00:00:00.000Z", status: "ready" },
      { id: "asset-rooftop", projectId: PROJECT_ID, scope: scene1202, category: "3d", title: "옥상 3D 블로킹", specification: "난간·출입문·물탱크 카메라 프리셋", sourcePlanRefs: [scenePlans[1]!.id], sourcing: "existing", rightsRequirements: ["프로젝트 라이선스 확인"], requiredByAt: "2026-09-18T00:00:00.000Z", status: "ready" },
    ],
    risks: [
      createDemoRisk({ id: "risk-background-capacity", projectId: PROJECT_ID, scope: episode12, category: "capacity", title: "내부 배경 capacity 부족", description: "12화 배경 18컷 중 12컷을 내부 일정으로 처리할 수 없습니다.", probability: 4, impact: 4, ownerAssignmentId: producerAssignmentId, mitigation: "승인 협력사에 12컷을 ScopePackage로 발주", trigger: "내부 가용 시간이 20시간 미만", status: "mitigating", dueAt: "2026-09-16T00:00:00.000Z" }),
      createDemoRisk({ id: "risk-envelope-reveal", projectId: PROJECT_ID, scope: episode12, category: "story", title: "발신인 정보 조기 노출", description: "봉투 문양과 글자가 너무 일찍 식별될 위험", probability: 3, impact: 5, ownerAssignmentId: "assignment-story", mitigation: "MUST_PRESERVE 지시와 Narrative lane 검수", trigger: "마지막 4컷 이전에 식별 가능", status: "open", dueAt: "2026-09-18T00:00:00.000Z" }),
    ],
    decisions: [
      { id: "decision-envelope-reveal", projectId: PROJECT_ID, scope: episode12, domain: "canon", question: "봉투 문양을 마지막 컷 전에 보여도 되는가?", decision: "문양은 허용하되 글자와 발신인 식별 요소는 가린다.", rationale: "클리프행어의 정보 공개 순서를 보존한다.", alternatives: ["봉투 전체를 숨김", "발신인을 그림자 처리"], evidenceRefs: [storySnapshot.id], decidedByAssignmentId: "assignment-story", consultedAssignmentIds: ["assignment-art"], supersedesDecisionId: null, createdAt: "2026-09-15T10:00:00.000Z" },
      { id: "decision-background-outsourcing", projectId: PROJECT_ID, scope: episode12, domain: "schedule", question: "배경 12컷을 외주화할 것인가?", decision: "승인 협력사에 샘플·최종 2단계로 발주한다.", rationale: "연재일을 지키면서 내부 작화 lead가 핵심 컷에 집중한다.", alternatives: ["회차 컷 수 축소", "연재일 3일 연기"], evidenceRefs: [scopePackage.id], decidedByAssignmentId: producerAssignmentId, consultedAssignmentIds: ["assignment-art", "assignment-story"], supersedesDecisionId: null, createdAt: "2026-09-15T10:30:00.000Z" },
    ],
    proposals: [proposal],
    agreements: [agreement],
    changeOrders: [],
    contractMilestones: milestones,
    deliveryRevisions: [{
      id: "delivery-background-sample-r1",
      projectId: PROJECT_ID,
      agreementId: agreement.id,
      milestoneId: "milestone-background-sample",
      revision: 1,
      submissionIds: ["submission-background-sample-r1"],
      sourceObjectRefs: ["object-background-sample-psd"],
      licenseEvidenceRefs: ["license-3d-city-kit-r2"],
      aiUseReceiptRefs: ["ai-use-none-attestation-r1"],
      checksum: "sha256:f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0",
      knownLimitations: ["최종 컷에서 빗물 밀도는 내부 작화와 함께 재조정"],
      status: "accepted",
      submittedByAssignmentId: "assignment-background-vendor",
      submittedAt: "2026-09-18T02:05:00.000Z",
      acceptedAt: "2026-09-18T06:00:00.000Z",
    }],
    invoices: [{
      id: "invoice-background-sample",
      projectId: PROJECT_ID,
      agreementId: agreement.id,
      milestoneId: "milestone-background-sample",
      issuerPartyId: "party-background-vendor",
      recipientPartyId: "party-producer",
      amountMinor: 200000,
      currency: "KRW",
      status: "verified",
      externalInvoiceRef: "tax-invoice-background-20260918",
      issuedAt: "2026-09-18T07:00:00.000Z",
      dueAt: "2026-09-25T00:00:00.000Z",
    }],
    paymentRecords: [{
      id: "payment-background-sample",
      projectId: PROJECT_ID,
      agreementId: agreement.id,
      invoiceId: "invoice-background-sample",
      payerPartyId: "party-producer",
      payeePartyId: "party-background-vendor",
      amountMinor: 200000,
      currency: "KRW",
      status: "recorded-pending-verification",
      provider: null,
      externalPaymentRef: null,
      evidenceRefs: [],
      verifiedByAssignmentId: null,
      paidAt: null,
      createdAt: "2026-09-18T07:10:00.000Z",
    }],
    disputes: [],
    auditEvents: activityNames.map((action, index) => ({
      id: `demo-event-${index + 1}`,
      projectId: PROJECT_ID,
      aggregateRevision: index + 1,
      actorPartyId: index % 2 === 0 ? "party-story" : "party-art",
      action,
      targetType: index === 0 ? "project" : "production-item",
      targetId: index === 0 ? PROJECT_ID : `demo-target-${index}`,
      beforeDigest: null,
      afterDigest: null,
      reason: null,
      occurredAt: new Date(Date.parse(AT) + index * 1000).toISOString(),
    })),
    updatedAt: AT,
  };
}
