/** Shell metadata only. Do not import page/navigation modules into this table. */
export const CREATOR_RESOURCE_TITLES: Record<string, string> = {
  "/home": "내 홈",
  "/team": "협업 홈",
  "/team/people": "사람·권한 관리",
  "/team/organization": "조직 홈",
  "/team/recruiting": "인재·지원 관리",
  "/collaborate": "구인·의뢰",
  "/production/projects": "제작 프로젝트",
  "/make": "만들기",
  "/discover": "찾기",
  "/my": "내 공간",
  "/help": "도움말 센터",
  "/status": "서비스 상태",
  "/brand-film": "툰스튜디오 브랜드 필름",
  "/product-tour": "툰스튜디오 전체 제품 투어",
  "/events": "이벤트",
  "/events/beta-open": "베타 오픈 이벤트",
  "/accessibility": "접근성",
  "/now": "오늘의 영감",
  "/research": "창작 리서치 데스크",
  "/research/assets": "창작 레퍼런스 아틀라스",
  "/research/catalog": "작품 리서치 랩",
  "/research/catalog/notebook": "작품 비교·기획 노트",
  "/research/books": "글로벌 만화·도서 판본 탐색",
  "/research/3d-assets": "무료 3D·HDRI·텍스처 재료실",
  "/research/material-assets": "ambientCG CC0 PBR·3D 소재",
  "/research/space-assets": "NASA 우주·과학 레퍼런스",
  "/research/vam": "V&A 패션·디자인 자료실",
  "/research/rijksmuseum": "Rijksmuseum 고증 자료실",
  "/research/fonts": "Google Fonts 레터링 매처",
  "/research/creatures": "생물·크리처 디자인 도감",
  "/research/music-metadata": "음악가·BGM 메타데이터",
  "/research/archive": "역사 자료 아카이브",
  "/research/weather-light": "날씨·빛 연출 도우미",
  "/research/open-data": "공개 데이터 창작실",
  "/research/open-data/kheritage": "국가유산 고증 검색",
  "/research/open-data/neis": "학교물 배경 설정",
  "/research/open-data/tourapi": "한국 장소 장면 설계",
  "/research/open-data/korean": "한국어 대사·말투 연구",
  "/research/open-data/smithsonian": "Smithsonian 문화유산 검색",
  "/research/open-data/wikimedia": "백과 조회 관심 신호",
  "/research/open-data/europeana": "Europeana 문화유산 통합검색",
  "/research/open-data/dpla": "DPLA 역사 자료 통합검색",
  "/creator-hub": "창작 허브",
  "/opportunities": "작가 기회센터",
  "/ecosystem": "창작자 생태계",
  "/ecosystem/education": "웹툰 성장 · 교육 허브",
  "/ecosystem/collaboration": "작가 IP 협업 · 협찬",
  "/ecosystem/fandom": "팬덤 · 코스프레 허브",
  "/ecosystem/library": "만화 · 웹툰 라이브러리",
  "/creator-hub/references": "창작 레퍼런스 아틀라스",
  "/learn/process": "웹툰 제작 과정",
  "/learn/careers": "웹툰 진로·직무 안내",
  "/learn/education": "웹툰 교육기관 찾기",
  "/learn/resources": "웹툰 교육 자료 허브",
  "/learn/classroom": "웹툰 교육기관 활용",
  "/learn/recipes": "웹툰 제작 레시피",
  "/story-lab": "스토리 연구실",
  "/discover/works": "만화·작법서 탐색",
  "/publishing": "연재·출판 준비실",
  "/studio/3d/dcc/build": "3D 공간 제작",
  "/studio/3d/dcc/cad": "정밀 CAD",
  "/studio/3d/dcc/material": "재질·UV",
  "/studio/3d/dcc/model": "3D 모델링",
  "/studio/3d/dcc/sculpt": "3D 조형",
  "/studio/3d/dcc/shot": "컷·선화",
  "/studio/ai-lab": "외부 AI Runtime · 개발자 프리뷰",
  "/insights/resources": "공식 자료·API 안내",
  "/about/data": "데이터 출처·상업 이용 준비",
  "/about/crawler": "공개 데이터 수집 정책",
  "/membership": "멤버십",
  "/membership/usage": "멤버십 이용 내역",
  "/account/points": "포인트 지갑",
  "/read/spatial": "공간 리더",
  "/creators": "창작자 디렉터리",
  "/research/open-creation": "오픈 창작",
  "/research/packs": "콘텐츠 팩",
  "/research/open-data/ambientcg": "ambientCG 공개 데이터",
  "/research/open-data/vam": "V&A 공개 데이터",
  "/research/open-data/nasa": "NASA 공개 데이터",
  "/research/open-data/gbif": "GBIF 생물 공개 데이터",
  "/research/open-data/musicbrainz": "MusicBrainz 공개 데이터",
  "/research/open-data/internetarchive": "Internet Archive 공개 데이터",
};
