import { useEffect, useRef, useState } from "react";

import { CareerConfirmationPanel } from "./CareerConfirmationPanel";

import { CREATOR_HIRING_ROLES } from "../../../../../../packages/contracts/src/creator-hiring";
import { CollabField, CollabNotice, collabButton, collabInput, collabPrimary } from "../collaboration-ui";


import type { CreatorActivitySummary, CreatorCareerInput, CreatorCareerItem, CreatorCareerVersion } from "../../../../../../packages/contracts/src/creator-hiring";

import Link from "@/shared/navigation/router-link";
import { api, getApiErrorMessage } from "@/platform/api";

const root = "/collaborations/career";
const empty = (): CreatorCareerInput => ({ title: "", role: "lineart", startMonth: "", endMonth: null, episodeFrom: null, episodeTo: null, scope: "", contribution: "", portfolioUrl: "", rights: "pending", visibility: "private", expectedRevision: 0 });
export function CreatorCareerPanel({ onResumeCreated }: { onResumeCreated: () => void }) {
  const imports = useRef(new Map<string, string>());
  const [items, setItems] = useState<CreatorCareerItem[]>([]), [edit, setEdit] = useState<{ id: string | null; input: CreatorCareerInput } | null>(null), [versions, setVersions] = useState<CreatorCareerVersion[]>([]);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [note, setNote] = useState(""), [refresh, setRefresh] = useState(0), [penName, setPenName] = useState(""), [loaded, setLoaded] = useState(false);
  useEffect(() => { const c = new AbortController(); setLoaded(false); void api.get<CreatorCareerItem[]>(`${root}/me`, { signal: c.signal }).then((v) => { if (!c.signal.aborted) { setItems(v); setLoaded(true); } }).catch(async (e) => { const m = await getApiErrorMessage(e, "경력을 불러오지 못했어요."); if (!c.signal.aborted) { setError(m); setLoaded(true); } }); return () => c.abort(); }, [refresh]);
  async function act(work: () => Promise<unknown>, message: string) { if (busy) return; setBusy(true); setError(""); setNote(""); try { await work(); setRefresh((v) => v + 1); setNote(message); } catch (e) { setError(await getApiErrorMessage(e, "요청을 처리하지 못했어요.")); } finally { setBusy(false); } }
  function inputOf(item: CreatorCareerItem): CreatorCareerInput { return { title: item.title, role: item.role, startMonth: item.startMonth, endMonth: item.endMonth, episodeFrom: item.episodeFrom, episodeTo: item.episodeTo, scope: item.scope, contribution: item.contribution, portfolioUrl: item.portfolioUrl, rights: item.rights, visibility: item.visibility, expectedRevision: item.revision }; }
  return <section className="space-y-4 rounded-2xl border border-line p-5"><h2 className="text-xl font-bold">경력·포트폴리오</h2><p className="text-sm leading-6 text-fg-3">새 경력은 비공개로 시작합니다. 경력은 본인 작성이며 검증된 경력 배지가 아닙니다. 전시는 공개 링크만 제공하며 원고·이미지·증빙을 업로드하지 않습니다.</p><div className="flex flex-wrap gap-2"><button className={collabPrimary} disabled={busy} onClick={() => setEdit({ id: null, input: empty() })}>경력 작성</button><Link className={collabButton} href="/collaborate/gallery">공개 링크 전시 보기</Link></div>{error && <CollabNotice error>{error}</CollabNotice>}{note && <CollabNotice>{note}</CollabNotice>}
    {edit && <CareerEditor key={`${edit.id}:${edit.input.expectedRevision}`} initial={edit.input} busy={busy} onSave={(input) => { void act(async () => { if (edit.id) await api.patch(`${root}/${edit.id}`, input); else await api.post(root, input); setEdit(null); }, "경력 버전을 저장했어요."); }} />}
    {!loaded && !error && <div role="status" aria-label="경력을 불러오는 중" className="space-y-3" aria-hidden="true"><div className="skeleton h-28 rounded-xl" /><div className="skeleton h-28 rounded-xl" /></div>}
    {loaded && items.length === 0 && !error && <div className="rounded-xl border border-dashed border-line px-4 py-8 text-center"><img src="/images/empty-library.webp" alt="" aria-hidden="true" loading="lazy" decoding="async" className="mx-auto mb-4 h-28 w-full max-w-xs rounded-xl border border-line/60 object-cover" /><p className="text-sm font-medium text-fg">등록한 경력이 없어요.</p><p className="mt-1 text-xs leading-6 text-fg-3">경력을 정리해 두면 상대방 확인을 받거나 비공개 이력서로 가져올 수 있어요. 새 경력은 비공개로 시작합니다.</p><button className={`${collabButton} mt-4`} disabled={busy} onClick={() => setEdit({ id: null, input: empty() })}>첫 경력 작성하기</button></div>}{items.map((i) => <article className="space-y-3 rounded border border-line bg-panel p-4" key={i.id}><h3 className="font-bold">{i.title} · 버전 {i.revision} · {i.visibility === "public" ? "링크 공개" : "비공개"}</h3><p>{CREATOR_HIRING_ROLES[i.role]} · {i.startMonth}~{i.endMonth ?? "진행 중"}</p><p className="text-sm whitespace-pre-wrap">{i.contribution}</p><div className="flex flex-wrap gap-2"><button className={collabButton} disabled={busy} onClick={() => setEdit({ id: i.id, input: inputOf(i) })}>수정·권리 설정</button><button className={collabButton} disabled={busy} onClick={() => { void act(async () => { setVersions(await api.get<CreatorCareerVersion[]>(`${root}/${i.id}/versions`)); }, "변경되지 않는 저장 버전을 불러왔어요."); }}>버전·이력서로 가져오기</button><button className={collabButton} disabled={busy} onClick={() => { void act(() => api.post(`${root}/${i.id}/revoke`, {}), "공유 권리를 철회하고 전시에서 숨겼어요. 외부 사이트의 원본 링크는 직접 관리해 주세요."); }}>권리 철회·전시 숨기기</button><button className={collabButton} disabled={busy} onClick={() => { if (globalThis.confirm("이 경력과 저장 버전을 삭제할까요? 이미 별도로 만든 이력서는 이력서 관리에서 삭제할 수 있습니다.")) void act(() => api.delete(`${root}/${i.id}?revision=${i.revision}`), "경력과 공개 전시를 삭제했어요."); }}>삭제</button></div></article>)}
    <CareerConfirmationPanel items={items} />
    {versions.length > 0 && <section className="space-y-3 rounded border border-line p-4"><h3 className="font-bold">경력 버전에서 이력서 만들기</h3><CollabField label="이력서에 쓸 활동명"><input maxLength={60} className={collabInput} value={penName} onChange={(e) => setPenName(e.target.value)} /></CollabField><p className="text-sm">서버가 선택한 버전의 출처와 현재 권리를 확인해 복사합니다. 경력 수정은 제출본을 바꾸지 않으며, 권리 철회는 연결된 이력서 제출을 막고 제출본 내용을 지웁니다.</p>{versions.map((v) => <article key={v.id} className="space-y-2 border-t border-line pt-3"><p>버전 {v.revision} · {v.content.title} · {v.content.contribution}</p><button className={collabButton} disabled={busy || !penName.trim() || v.content.rights === "pending"} onClick={() => { void act(async () => { const key = JSON.stringify([v.careerId, v.id, penName]); if (!imports.current.has(key)) imports.current.set(key, crypto.randomUUID()); await api.post(`${root}/${v.careerId}/versions/${v.id}/resume`, { penName, mutationId: imports.current.get(key)! }); imports.current.delete(key); onResumeCreated(); }, "비공개 이력서를 만들었어요. 이력서 목록에서 확인·수정하고 공고에서 제출할 수 있습니다."); }}>이 버전으로 비공개 이력서 만들기</button></article>)}</section>}
  </section>;
}
function CareerEditor({ initial, busy, onSave }: { initial: CreatorCareerInput; busy: boolean; onSave: (v: CreatorCareerInput) => void }) {
  const [v, set] = useState(initial);
  const change = <K extends keyof CreatorCareerInput>(key: K, value: CreatorCareerInput[K]) => set((old) => ({ ...old, [key]: value }));
  return <form className="space-y-3 rounded border border-line p-4" onSubmit={(e) => { e.preventDefault(); onSave(v); }}><fieldset disabled={busy} className="space-y-3"><CollabField label="경력·작품 이름"><input required maxLength={100} className={collabInput} value={v.title} onChange={(e) => change("title", e.target.value)} /></CollabField><CollabField label="담당 역할"><select className={collabInput} value={v.role} onChange={(e) => change("role", e.target.value as typeof v.role)}>{Object.entries(CREATOR_HIRING_ROLES).map(([k, s]) => <option key={k} value={k}>{s}</option>)}</select></CollabField>
    <div className="grid gap-3 sm:grid-cols-2"><CollabField label="시작 월"><input required type="month" min="1900-01" max="2199-12" className={collabInput} value={v.startMonth} onChange={(e) => change("startMonth", e.target.value)} /></CollabField><CollabField label="종료 월 (진행 중이면 비우기)"><input type="month" min={v.startMonth || "1900-01"} max="2199-12" className={collabInput} value={v.endMonth ?? ""} onChange={(e) => change("endMonth", e.target.value || null)} /></CollabField></div>
    <div className="grid gap-3 sm:grid-cols-2">{(["episodeFrom", "episodeTo"] as const).map((k) => <CollabField key={k} label={k === "episodeFrom" ? "시작 회차" : "종료 회차"}><input type="number" min={0} max={100000} className={collabInput} value={v[k] ?? ""} onChange={(e) => change(k, e.target.value ? Number(e.target.value) : null)} /></CollabField>)}</div>
    {([ ["scope", "공개 가능한 작업 범위"], ["contribution", "직접 기여한 작업"] ] as const).map(([key, label]) => <CollabField key={key} label={label}><textarea required maxLength={800} className={collabInput} value={v[key]} onChange={(e) => change(key, e.target.value)} /></CollabField>)}
    <CollabField label="공유 가능한 HTTPS 포트폴리오 주소"><input type="url" required maxLength={500} className={collabInput} value={v.portfolioUrl} onChange={(e) => change("portfolioUrl", e.target.value)} /></CollabField><CollabField label="공유 권리"><select className={collabInput} value={v.rights} onChange={(e) => set({ ...v, rights: e.target.value as typeof v.rights, visibility: e.target.value === "pending" ? "private" : v.visibility })}><option value="pending">권리 미확인 · 비공개</option><option value="owned">본인 소유</option><option value="authorized">권리자의 공유 허락을 받음</option></select></CollabField><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={v.visibility === "public"} disabled={v.rights === "pending"} onChange={(e) => change("visibility", e.target.checked ? "public" : "private")} />이 내용과 링크를 공개 전시에 표시합니다</label><p className="text-xs">공개 시 작업 범위·기여·기간·회차·활동명도 표시됩니다. 비공개 프로젝트 정보와 연락처를 포함하지 마세요.</p><button type="submit" className={collabPrimary}>새 경력 버전 저장</button></fieldset></form>;
}
export function CreatorActivityPanel() {
  const [data, setData] = useState<CreatorActivitySummary | null>(null), [error, setError] = useState("");
  useEffect(() => { const c = new AbortController(); void api.get<CreatorActivitySummary>(`${root}/activity/me`, { signal: c.signal }).then((v) => { if (!c.signal.aborted) setData(v); }).catch(async (e) => { const m = await getApiErrorMessage(e, "활동 기록을 불러오지 못했어요."); if (!c.signal.aborted) setError(m); }); return () => c.abort(); }, []);
  return <section className="space-y-3 rounded-2xl border border-line p-5"><h2 className="text-xl font-bold">협업 참여 기록</h2><p className="text-sm">현재 자동 적립은 연결되지 않았습니다. 실제 제작 완료의 검증된 서버 이벤트가 연결되기 전에는 지원·초대·프로필 작성으로 점수를 만들지 않습니다. 기록은 능력·경력 검증·유료 등급과 별개이며 채용에 영향을 주지 않습니다.</p>{error && <CollabNotice error>{error}</CollabNotice>}{!data && !error && <div role="status" aria-label="협업 참여 기록을 불러오는 중" className="space-y-2" aria-hidden="true"><div className="skeleton h-12 rounded-lg" /><div className="skeleton h-12 rounded-lg" /></div>}{data && <><p>레벨 {data.level} · 유효 활동 {data.points}점</p>{data.events.length === 0 && <div className="rounded-xl border border-dashed border-line px-4 py-6 text-center"><p className="text-sm font-medium text-fg">기록된 활동이 없어요.</p><p className="mt-1 text-xs leading-6 text-fg-3">검증된 제작 완료가 기록되면 이곳에 표시됩니다.</p></div>}<ul>{data.events.map((e) => <li key={e.id} className="py-2 text-sm">{new Date(e.occurredAt).toLocaleString("ko-KR")} · {e.kind === "award" ? "검증된 제작 완료 기록" : "기록 취소"} · {e.points}점</li>)}</ul></>}</section>;
}

// 갤러리 페이지는 전용 파일로 분리했고, 기존 라우트 import 경로를 유지하려고 여기서 다시 내보낸다.
export { CreatorCareerGalleryPage } from "./CreatorCareerGalleryPage";
