import type { EngineeringAtlasEntry } from "./engineering-atlas-types";
import type { LocalizedText } from "./engineering-story-content";

/**
 * 기술 도감 · platform-ops 카테고리 — 품질 게이트 카드(경계 래칫, 접근성 스모크, 테스트 수 정의와 직렬 레인).
 * 수치는 2026-10-08에 스크립트·git 추적 파일로 다시 계산한 값이며, GitHub 쪽 브랜치 보호 같은 설정은 저장소 파일로 확인할 수 없다.
 */

const t = (ko: string, en: string): LocalizedText => ({ ko, en });

const MODULE_BOUNDARY_RATCHET: EngineeringAtlasEntry = {
  id: "module-boundary-ratchet",
  category: "platform-ops",
  name: "Architecture boundary ratchet",
  title: t("나쁜 import는 새로 늘지 못하게, 숫자로 잠그는 경계 래칫", "A boundary ratchet that locks the count of bad imports so none can be added"),
  status: "live",
  tagline: t(
    "17개 규칙의 위반 개수를 JSON 상한에 고정해, 늘어나는 순간 CI가 실패합니다.",
    "It pins the violation count of 17 rules to a JSON ceiling, and CI fails the moment one grows.",
  ),
  background: [
    t(
      "큰 건물을 한 번에 허물고 다시 지을 수 없을 때는 '지금보다 나빠지지는 않게' 못을 박아 두는 방법이 있습니다. ToonStudio는 웹·관리자·API 앱이 서로의 코드를 직접 가져다 쓰면(import) 따로 배포하기 어려워지고, 한 화면 폴더가 다른 폴더의 속을 깊이 들여다보면 고치기 어려워진다고 봅니다. 그래서 이미 있는 위반은 숫자로 동결하고, 새 위반이 한 건이라도 늘면 CI가 실패하게 했습니다. 톱니가 한쪽으로만 도는 래칫(ratchet)과 같은 발상입니다.",
      "When a big building cannot be torn down and rebuilt at once, you can at least nail things down so they never get worse. ToonStudio holds that if the web, admin and API apps import each other's code directly they become hard to deploy separately, and if one screen folder reaches deep into another folder's internals it becomes hard to change. So existing violations are frozen as numbers, and CI fails as soon as even one new violation appears. It is the idea of a ratchet, a gear that only turns one way.",
    ),
    t(
      "검사기(scripts/validate-app-boundaries.mjs)는 apps와 packages의 src를 돌며 import·export·동적 import·require 지정자를 정규식으로 뽑고, @/ 같은 별칭을 저장소 경로로 바꾼 뒤 17개 규칙(config/architecture-boundary-ratchet.json의 키) 중 어디에 걸리는지 셉니다. 웹·관리자·API 사이 6방향, 실험 앱과 패키지의 앱 참조, 계약 패키지의 금지 import, 테스트가 다른 앱 소스를 가리키는 경우, 그리고 웹 안의 shared→domains와 도메인 간 깊은 import입니다. 센 값이 JSON 상한을 넘으면 예시와 함께 실패합니다.",
      "The checker (scripts/validate-app-boundaries.mjs) walks the src of apps and packages, pulls import, export, dynamic import and require specifiers with regular expressions, converts aliases such as @/ into repository paths and counts which of 17 rules each one hits (the keys of config/architecture-boundary-ratchet.json). The rules cover six directions between web, admin and API, lab apps and packages referencing apps, forbidden imports in the contracts package, tests that point at another app's source, and, inside the web app, shared-to-domains and deep cross-domain imports. If a count exceeds the JSON ceiling it fails with examples.",
    ),
    t(
      "같은 일을 의존성 그래프 도구(dependency-cruiser)나 ESLint 경계 플러그인으로도 할 수 있습니다. 이 저장소는 앱 사이 경계는 자체 검사기로, 웹 안의 4계층(app → domains → shared → infrastructure)은 ESLint boundaries 규칙으로 따로 지킵니다. 자체 검사기를 고른 문서상의 근거는 찾지 못했습니다. 상한을 JSON에 두고 PR로만 바꾸게 하면 레거시를 허용한 채 속도를 유지하면서 새 위반만 막습니다. 같은 발상이 폴더별 파일 수, 린트 경고 수(상한 2,421), 파일 크기에도 쓰입니다.",
      "The same job can be done with a dependency-graph tool (dependency-cruiser) or an ESLint boundaries plugin. This repository guards the boundaries between apps with its own checker and the four layers inside the web app (app, domains, shared, infrastructure) separately with ESLint boundaries rules. No written rationale for choosing a custom checker was found. Keeping the ceiling in JSON and changing it only through a PR tolerates legacy code, keeps speed and still blocks only new violations. The same idea is used for file counts per folder, lint warnings (ceiling 2,421) and file sizes.",
    ),
    t(
      "정직하게 말할 점: 0이 아니라 동결입니다. 웹 shared→domains 25건이 남아 있고, 도메인 간 깊은 import는 상한 58에 실측 48(2026-10-08 실행)이라 10칸 여유가 있어 그 안에서는 새 위반도 통과합니다. 상한은 PR로 올릴 수 있고(baseline 갱신 옵션은 방향을 검사하지 않음) 막는 것은 리뷰뿐인데 CODEOWNERS 파일은 없고 브랜치 보호 설정은 저장소로 확인할 수 없습니다. 정규식 방식이라 동적으로 만든 경로는 놓칩니다.",
      "To be honest: it is a freeze, not zero. 25 web shared-to-domains imports remain, and deep cross-domain imports have a ceiling of 58 against a measured 48 (run on 2026-10-08), so 10 slots of slack let new violations pass inside that margin. The ceiling can be raised in a PR (the baseline-update option does not check direction), and only review stands in the way; there is no CODEOWNERS file and branch protection settings cannot be confirmed from the repository. Being regex-based, it misses dynamically built paths.",
    ),
  ],
  keyPoints: [
    t("17개 규칙의 위반 수를 JSON 상한에 동결", "17 rules' violation counts frozen at a JSON ceiling"),
    t("상한을 넘으면 예시와 함께 CI 실패", "Exceeding the ceiling fails CI with examples"),
    t("0이 아닌 동결: 깊은 import 실측 48, 상한 58", "A freeze, not zero: 48 deep imports measured, ceiling 58"),
    t("상한은 PR로 오를 수 있어 리뷰가 마지막 방어선", "The ceiling can rise in a PR, so review is the last guard"),
  ],
  diagram: {
    id: "module-boundary-ratchet-diagram",
    kind: "graph",
    title: t("import 한 줄이 상한과 만나는 길", "How one import line meets the ceiling"),
    caption: t(
      "소스에서 뽑은 import를 17개 규칙으로 세어 JSON 상한과 비교하고, 넘으면 CI가 실패합니다.",
      "Imports extracted from source are counted per rule and compared with the JSON ceiling; CI fails when one is over.",
    ),
    alt: t(
      "앱과 패키지의 소스 파일에서 import 지정자를 정규식으로 뽑고, 별칭을 실제 경로로 바꾼 뒤 17개 규칙별로 개수를 셉니다. 센 값을 상한 JSON과 비교해 상한을 넘으면 예시와 함께 CI가 실패하고, 같거나 적으면 통과합니다. baseline 갱신 옵션은 현재 값으로 상한 JSON을 덮어쓰며 PR로만 반영됩니다.",
      "Import specifiers are extracted with regular expressions from the source files of apps and packages, aliases are turned into real paths, and counts are taken per each of 17 rules. The counts are compared with the ceiling JSON: over it, CI fails with examples; equal or lower, it passes. The baseline-update option overwrites the ceiling JSON with current values and reaches the repository only through a PR.",
    ),
    nodes: [
      { id: "src", label: t("소스 파일", "Source files"), sub: t("앱·패키지 src", "App and package src"), tone: "local", shape: "pill", at: [0, 1] },
      { id: "scan", label: t("import 추출", "Extract imports"), sub: t("정규식 3종", "3 regexes"), tone: "neutral", at: [1, 1] },
      { id: "norm", label: t("경로 정규화", "Normalize paths"), sub: t("별칭 → 실제 경로", "Alias to real path"), tone: "neutral", at: [2, 1] },
      { id: "rules", label: t("규칙별 집계", "Count per rule"), sub: t("17개 키", "17 keys"), tone: "neutral", at: [3, 1] },
      { id: "gate", label: t("상한 초과?", "Over limit?"), sub: t("실측 > 상한", "count > cap"), tone: "warn", shape: "diamond", at: [4, 1] },
      { id: "json", label: t("상한 JSON", "Ceiling JSON"), sub: t("PR로만 변경", "Changed via PR"), tone: "server", shape: "cylinder", at: [4, 2] },
      { id: "fail", label: t("CI 실패", "CI fails"), sub: t("예시 5건 출력", "Prints 5 examples"), tone: "warn", at: [5, 0] },
      { id: "pass", label: t("통과", "Pass"), sub: t("같거나 적으면", "Equal or fewer"), tone: "good", shape: "pill", at: [5, 1] },
    ],
    edges: [
      { from: "src", to: "scan" },
      { from: "scan", to: "norm" },
      { from: "norm", to: "rules" },
      { from: "rules", to: "gate" },
      { from: "json", to: "gate", label: t("상한", "cap") },
      { from: "gate", to: "fail", label: t("예", "yes") },
      { from: "gate", to: "pass", label: t("아니오", "no") },
      { from: "rules", to: "json", style: "dashed", label: t("덮어쓰기", "overwrite") },
    ],
  },
  usage: [
    {
      feature: t("PR·푸시마다 도는 경계 검사 (코어 CI의 product 샤드)", "Boundary check on every PR and push (product shard of core CI)"),
      role: t(
        "validate:architecture가 경계 래칫을 포함해 실행됩니다. 앱·패키지 경로가 바뀌는 PR에는 전용 Architecture boundaries 워크플로도 돌고, 로컬 pre-push 훅도 같은 검사를 합니다.",
        "validate:architecture runs the boundary ratchet. A PR touching app or package paths also triggers the dedicated Architecture boundaries workflow, and the local pre-push hook runs the same check.",
      ),
      paths: [
        "scripts/validate-app-boundaries.mjs",
        "config/architecture-boundary-ratchet.json",
        ".github/workflows/architecture-boundaries.yml",
        "scripts/ci-core-regression-shards-impl.mjs",
        "docs/architecture/modular-monorepo-target.md",
      ],
    },
    {
      feature: t("따로 배포할 수 있는 관리자 앱 (Admin)", "An admin app that can be deployed on its own"),
      role: t(
        "관리자 ↔ 웹·API의 직접 import가 0으로 고정되어, Admin을 따로 타입 검사하고 빌드할 수 있는 상태를 지킵니다.",
        "Direct imports between admin and web or API are pinned at zero, which keeps Admin typecheckable and buildable on its own.",
      ),
      paths: ["apps/admin-web/vite.config.ts", ".github/workflows/architecture-boundaries.yml"],
    },
    {
      feature: t("웹 도메인 응집 (shared → domains, 도메인 간 깊은 import)", "Web domain cohesion (shared to domains, deep cross-domain imports)"),
      role: t(
        "공유 코드가 특정 도메인을 거꾸로 가져오거나 한 도메인이 다른 도메인의 속을 깊이 들여다보는 일을 새로 늘리지 못합니다. 공개 진입점(public*)과 integrations 경로는 허용합니다.",
        "Shared code can no longer newly pull from a specific domain, and one domain cannot newly reach deep into another. Public entry points (public*) and integrations paths are allowed.",
      ),
      paths: ["apps/web/src/domains", "eslint.config.mjs"],
    },
    {
      feature: t("같은 발상의 다른 래칫 (폴더별 파일 수 · 경고 수 · 파일 크기)", "Sibling ratchets (files per folder, warnings, file size)"),
      role: t(
        "소스 레이아웃 래칫은 폴더별 파일 수와 린트 경고 상한을, 파일 크기 테스트는 신규 파일 1,000줄과 기존 거대 파일 327개의 기록 줄 수를 천장으로 삼습니다.",
        "The source-layout ratchet caps files per folder and lint warnings, and the file-size test caps new files at 1,000 lines and 327 existing giants at their recorded line counts.",
      ),
      paths: [
        "config/architecture-source-ratchet.json",
        "scripts/validate-source-layout.mjs",
        "apps/web/src/shared/lib/__tests__/file-size-ratchet.test.ts",
      ],
    },
  ],
  samples: [
    {
      kind: "simplified",
      title: t("상한을 넘은 항목만 실패로 돌려주기", "Reporting only the items that exceed their ceiling"),
      language: "ts",
      code: [
        "type Counts = Record<string, number>;",
        "",
        "/** 상한이 있는 항목만 비교한다. 같거나 적으면 통과, 많으면 실패 메시지를 돌려준다 */",
        "export function ratchetFailures(counts: Counts, budgets: Counts): string[] {",
        "  const failures: string[] = [];",
        "  for (const [key, value] of Object.entries(counts)) {",
        "    const budget = budgets[key];",
        '    if (typeof budget === "number" && value > budget) {',
        "      failures.push(`${key} increased to ${value} (budget ${budget})`);",
        "    }",
        "  }",
        "  return failures;",
        "}",
        "",
        "// ratchetFailures({ webSharedToDomain: 26 }, { webSharedToDomain: 25 })",
        '//   → ["webSharedToDomain increased to 26 (budget 25)"]',
      ].join("\n"),
      codeEn: [
        "type Counts = Record<string, number>;",
        "",
        "/** Compare only items that have a ceiling: equal or fewer passes, more returns a failure message */",
        "export function ratchetFailures(counts: Counts, budgets: Counts): string[] {",
        "  const failures: string[] = [];",
        "  for (const [key, value] of Object.entries(counts)) {",
        "    const budget = budgets[key];",
        '    if (typeof budget === "number" && value > budget) {',
        "      failures.push(`${key} increased to ${value} (budget ${budget})`);",
        "    }",
        "  }",
        "  return failures;",
        "}",
        "",
        "// ratchetFailures({ webSharedToDomain: 26 }, { webSharedToDomain: 25 })",
        '//   → ["webSharedToDomain increased to 26 (budget 25)"]',
      ].join("\n"),
      explain: t(
        "상한이 숫자가 아닌 키(관찰만 하는 항목)는 건너뜁니다. 실제 검사기는 같은 비교를 17개 키에 적용하고 실패 항목마다 예시 import를 최대 5건 출력합니다.",
        "A key whose ceiling is not a number (observe-only) is skipped. The real checker applies the same comparison to 17 keys and prints up to 5 example imports for each failing key.",
      ),
      source: "scripts/validate-app-boundaries.mjs",
      verify: "types",
    },
    {
      kind: "simplified",
      title: t("import 한 줄을 래칫 규칙에 대응시키기", "Mapping one import line to a ratchet rule"),
      language: "ts",
      code: [
        'const WEB_SRC = "apps/web/src";',
        "",
        "function domainOf(path: string): string | null {",
        "  const match = new RegExp(`^${WEB_SRC}/domains/([^/]+)/`).exec(path);",
        "  return match?.[1] ?? null;",
        "}",
        "",
        "/** import 한 줄(파일 → 대상)이 어느 규칙에 걸리는지 알려준다. 걸리지 않으면 null */",
        "export function classify(file: string, target: string): string | null {",
        "  if (file.startsWith(`${WEB_SRC}/shared/`) && target.startsWith(`${WEB_SRC}/domains/`)) {",
        '    return "webSharedToDomain"; // 공유 코드가 특정 도메인을 거꾸로 가져온다',
        "  }",
        "  const from = domainOf(file);",
        "  const to = domainOf(target);",
        "  if (from && to && from !== to) {",
        "    const isPublic = target.includes(`/domains/${to}/public`);",
        '    const isIntegration = target.includes("/integrations/");',
        '    if (!isPublic && !isIntegration) return "webCrossDomainDeepImport";',
        "  }",
        "  return null;",
        "}",
      ].join("\n"),
      codeEn: [
        'const WEB_SRC = "apps/web/src";',
        "",
        "function domainOf(path: string): string | null {",
        "  const match = new RegExp(`^${WEB_SRC}/domains/([^/]+)/`).exec(path);",
        "  return match?.[1] ?? null;",
        "}",
        "",
        "/** Tells which rule one import line (file to target) hits, or null when it hits none */",
        "export function classify(file: string, target: string): string | null {",
        "  if (file.startsWith(`${WEB_SRC}/shared/`) && target.startsWith(`${WEB_SRC}/domains/`)) {",
        '    return "webSharedToDomain"; // shared code pulls from a specific domain',
        "  }",
        "  const from = domainOf(file);",
        "  const to = domainOf(target);",
        "  if (from && to && from !== to) {",
        "    const isPublic = target.includes(`/domains/${to}/public`);",
        '    const isIntegration = target.includes("/integrations/");',
        '    if (!isPublic && !isIntegration) return "webCrossDomainDeepImport";',
        "  }",
        "  return null;",
        "}",
      ].join("\n"),
      explain: t(
        "다른 도메인의 공개 진입점(public*)과 integrations 경로는 깊은 import로 세지 않습니다. 실제 검사기는 같은 판정을 관리자 앱에도 적용하고 앱 간 6방향 등 나머지 규칙을 더합니다.",
        "A public entry point of another domain (public*) and integrations paths do not count as deep imports. The real checker applies the same decision to the admin app and adds the other rules such as the six directions between apps.",
      ),
      source: "scripts/validate-app-boundaries.mjs",
      verify: "types",
    },
  ],
  links: [
    {
      title: "eslint-plugin-boundaries",
      url: "https://github.com/javierbrea/eslint-plugin-boundaries",
      kind: "repo",
      note: t("앱 안의 계층 규칙을 ESLint로 거는 도구", "Enforces layer rules inside an app with ESLint"),
    },
    {
      title: "dependency-cruiser",
      url: "https://github.com/sverweij/dependency-cruiser",
      kind: "repo",
      note: t("의존성 그래프를 검사하는 대안 도구", "An alternative tool that checks the dependency graph"),
    },
    {
      title: "ESLint · --max-warnings",
      url: "https://eslint.org/docs/latest/use/command-line-interface#--max-warnings",
      kind: "docs",
      note: t("경고 수 상한을 두는 ESLint 옵션", "The ESLint option that caps the warning count"),
    },
  ],
  chapterIds: ["quality", "architecture"],
  talk: {
    pitch: t(
      "큰 코드베이스에서 나쁜 구조를 한 번에 없애기는 어렵습니다. 그래서 나쁜 import의 개수를 센 뒤 그 숫자를 JSON 상한에 못 박았습니다. 앱끼리 직접 가져다 쓰는 여섯 방향은 0건이고, 웹 안에서 공유 코드가 도메인을 거꾸로 부르는 25건은 더 늘지 못합니다. 늘어나는 순간 CI가 실패하고, 줄였다면 상한도 함께 내립니다.",
      "Removing bad structure from a big codebase in one go is hard. So we count bad imports and nail that number to a JSON ceiling. Direct imports between apps are zero in all six directions, and the 25 cases where shared code calls back into a domain on the web side cannot grow. The moment a count grows, CI fails, and if you reduce it you lower the ceiling too.",
    ),
    analogy: t(
      "자전거 체인의 톱니(래칫)처럼 한 방향으로만 돕니다. 나빠지는 쪽으로는 돌지 않게 걸어 둔 장치입니다.",
      "Like the ratchet on a bike chain, it turns one way only: a catch that keeps things from turning toward worse.",
    ),
    questions: [
      {
        question: t("왜 0으로 만들지 않고 동결인가요?", "Why freeze instead of driving it to zero?"),
        answer: t(
          "이미 쌓인 위반을 한 번에 갚으면 기능 개발이 멈춥니다. 새 위반만 막으면 속도를 유지한 채 개선 PR이 숫자를 조금씩 낮춰 갑니다.",
          "Paying off all existing violations at once would stall feature work. Blocking only new ones keeps speed while improvement PRs lower the number step by step.",
        ),
      },
      {
        question: t("실측과 상한이 다른 이유는요?", "Why do the measured count and the ceiling differ?"),
        answer: t(
          "도메인 간 깊은 import는 상한 58, 실측 48입니다(2026-10-08 실행). 줄인 뒤 상한을 함께 내리지 않아 10칸 여유가 남은 상태이고, 조이려면 baseline을 갱신하는 PR이 필요합니다.",
          "Deep cross-domain imports have a ceiling of 58 and a measured 48 (run on 2026-10-08). The ceiling was not lowered along with the reduction, leaving 10 slots of slack, and tightening it takes a PR that updates the baseline.",
        ),
      },
      {
        question: t("상한을 올리는 PR은 막히나요?", "Is a PR that raises the ceiling blocked?"),
        answer: t(
          "코드로는 막지 않습니다. baseline 갱신 옵션은 현재 값으로 덮어쓸 뿐 방향을 검사하지 않고, 방어선은 코드 리뷰입니다. 저장소에는 CODEOWNERS가 없고 브랜치 보호 설정은 저장소만으로 확인할 수 없습니다.",
          "Not by code. The baseline-update option just overwrites with current values without checking direction, and the guard is code review. The repository has no CODEOWNERS file and branch protection cannot be confirmed from the repository alone.",
        ),
      },
    ],
    pitfall: t(
      "'위반이 계속 줄기만 한다'고 말하면 틀립니다. 상한은 PR로 올릴 수 있으니 '새 위반을 막는다'고 말하세요. 앱 간 import 0건은 정규식 검사기 기준이라 동적으로 조립한 경로나 타입 전용 import 구분은 하지 못합니다. 웹 안의 4계층 ESLint 규칙은 분류된 폴더에만 적용되고, 나머지 shared는 이 래칫이 셉니다.",
      "Saying 'violations only ever shrink' is wrong. The ceiling can be raised in a PR, so say 'it blocks new violations'. Zero imports between apps is by the regex checker, which cannot see dynamically built paths or tell type-only imports apart. The ESLint four-layer rules apply only to classified folders, and the rest of shared is counted by this ratchet.",
    ),
  },
  technologies: ["Node.js", "TypeScript", "ESLint", "GitHub Actions"],
  facts: [
    {
      value: "17",
      label: t("경계 규칙(래칫 키) 수", "Number of boundary rules (ratchet keys)"),
      source: "config/architecture-boundary-ratchet.json",
    },
    {
      value: "25 / 25",
      label: t("웹 shared → domains: 실측 / 상한 (2026-10-08 스크립트 실행)", "Web shared to domains: measured / ceiling (script run on 2026-10-08)"),
      source: "scripts/validate-app-boundaries.mjs",
    },
    {
      value: "48 / 58",
      label: t("도메인 간 깊은 import: 실측 / 상한 (2026-10-08 스크립트 실행)", "Deep cross-domain imports: measured / ceiling (script run on 2026-10-08)"),
      source: "scripts/validate-app-boundaries.mjs",
    },
  ],
  reviewedAt: "2026-10-07",
};

const AXE_A11Y_MATRIX: EngineeringAtlasEntry = {
  id: "axe-a11y-matrix",
  category: "platform-ops",
  name: "axe accessibility smoke and sitewide matrix",
  title: t("접근성 점검은 두 겹: 매 PR의 axe 스모크와 수동 전수 매트릭스", "Accessibility in two layers: an axe smoke on every PR and a manual sitewide matrix"),
  status: "live",
  tagline: t(
    "코어 CI는 핵심 16개 시나리오를 axe로 검사하고, 전체 화면은 수동 매트릭스로 봅니다.",
    "Core CI checks 16 key scenarios with axe, and the whole site is covered by a manual matrix.",
  ),
  background: [
    t(
      "접근성은 시각·청각·운동 능력이 다른 사람도 화면을 쓸 수 있게 하는 품질입니다. 스크린 리더(화면을 소리로 읽어 주는 프로그램)가 읽을 이름이 없는 버튼, 배경과 글자색이 비슷해 읽기 어려운 문구, 손가락으로 누르기엔 너무 작은 버튼이 대표적인 문제입니다. 사람이 매번 확인하기는 어려워서, 브라우저로 화면을 실제로 열어 규칙 모음(axe-core)으로 자동 검사하는 테스트를 CI에 둡니다.",
      "Accessibility is the quality that lets people with different sight, hearing and motor abilities use a screen. Typical problems are a button with no name for a screen reader (a program that reads the screen aloud), text too close in color to its background, and buttons too small for a finger. People cannot check this every time, so CI opens real screens in a browser and checks them automatically against a rule set (axe-core).",
    ),
    t(
      "PR마다 도는 스모크(e2e/a11y-smoke.spec.ts)는 데스크톱 10개 라우트와 모바일 4개 라우트를 엽니다. 모든 /api 요청을 가로채 세션만 비로그인 200으로 답하고 나머지는 503으로 돌려, 서비스 장애 배너가 떠 있는 상태도 검사합니다. 화면이 준비되고 폰트와 끝이 정해진 애니메이션이 끝난 뒤에 axe를 wcag2a·wcag2aa·wcag21aa·wcag22aa 태그로 실행하고, serious·critical 위반만 실패로 칩니다. 모바일에서는 44px 이상 터치 영역과 알림 배너·음악 플레이어의 터치 겹침도 따로 잽니다.",
      "The smoke test that runs on every PR (e2e/a11y-smoke.spec.ts) opens 10 desktop routes and 4 mobile routes. It intercepts every /api call, answering only the session check as signed out with 200 and everything else with 503, so the outage-banner state is checked too. After the screen is ready and the fonts and finite animations have finished, it runs axe with the wcag2a, wcag2aa, wcag21aa and wcag22aa tags and fails only on serious and critical violations. On mobile it separately measures 44 px touch targets and whether the notice banner and the music player block each other's taps.",
    ),
    t(
      "전체 화면은 별도의 사이트 전역 감사(scripts/audit-sitewide-visual-ux.mjs)가 맡습니다. 라우트를 코드에서 자동으로 모아(2026-10-08 목록 출력 382개) 테마 9종, 데스크톱·모바일 두 크기, 표준·고대비 선호·강제 색상(forced colors) 세 프로필로 열고 가로 넘침, 이름 없는 버튼, 깨진 이미지, 대비 부족을 셉니다. 이 감사는 수동 실행이거나 해당 워크플로 파일이 바뀐 PR에서만 자동으로 돕니다. 시간이 오래 걸리는 전수 검사를 매 PR에 얹지 않으려는 선택입니다.",
      "A separate sitewide audit (scripts/audit-sitewide-visual-ux.mjs) covers the whole site. It collects routes from code (382 in the 2026-10-08 listing) and opens them in 9 themes, two sizes (desktop and mobile) and three profiles (standard, preferred high contrast, forced colors), counting horizontal overflow, nameless buttons, broken images and low contrast. It runs manually or automatically only on a PR that changes its workflow file, a choice that keeps a slow exhaustive check off every PR.",
    ),
    t(
      "자동 검사는 접근성 문제의 일부만 잡습니다. 키보드 순서, 대체 텍스트가 뜻하는 바, 스크린 리더로 들었을 때의 이해는 사람이 확인해야 하는데 저장소에서 그런 수동 점검의 근거는 찾지 못했습니다. 두 검사 모두 비로그인 상태에서 Vite 개발 서버로 돌고, 캔버스 안의 그림은 axe의 검사 대상이 아닙니다. 그래서 로그인 이후 화면과 프로덕션 번들의 접근성은 이 검사로 보증하지 않습니다.",
      "Automated checks catch only part of accessibility problems. Keyboard order, what the alt text means and how it sounds in a screen reader need people, and no record of such manual checks was found in the repository. Both checks run signed out against the Vite dev server, and the drawing inside the canvas is not something axe inspects. So accessibility after sign-in and in the production bundle is not guaranteed by these checks.",
    ),
  ],
  keyPoints: [
    t("코어 CI: 핵심 16개 시나리오를 axe로 검사, serious 이상만 실패", "Core CI: 16 key scenarios checked with axe, only serious or worse fails"),
    t("API는 일부러 503: 장애 배너가 떠도 접근성이 유지되는지 확인", "API returns 503 on purpose: checks access holds with the outage banner"),
    t("382개 화면 × 9테마 전수 감사는 수동, PR 게이트가 아님", "The 382-route by 9-theme audit is manual, not a PR gate"),
    t("자동 검사는 일부만: 키보드·스크린 리더 수동 점검 근거는 없음", "Automation covers only part; no record of manual keyboard or screen-reader checks"),
  ],
  diagram: {
    id: "axe-a11y-matrix-diagram",
    kind: "sequence",
    title: t("axe 스모크 테스트 한 건의 진행", "One axe smoke test, step by step"),
    caption: t(
      "API는 503으로 막고, 화면이 안정된 뒤에 axe를 돌려 serious·critical 위반만 실패로 칩니다.",
      "The API is blocked with 503, and axe runs once the screen is stable; only serious and critical violations fail.",
    ),
    alt: t(
      "테스트가 먼저 모든 API 요청을 가로채는 대역을 등록하고 라우트를 엽니다. 화면의 세션 요청에는 비로그인 200으로, 나머지 요청에는 503으로 답합니다. 화면이 준비 신호를 보내면 테스트는 폰트와 끝이 정해진 애니메이션이 끝나기를 기다린 뒤 axe-core를 WCAG 태그 네 가지로 실행하고, 돌아온 위반 중 serious와 critical만 실패로 처리합니다.",
      "The test first registers a stub that intercepts every API call and then opens the route. The page's session request gets a signed-out 200 and every other request gets 503. When the page signals it is ready, the test waits for fonts and finite animations to finish, runs axe-core with four WCAG tags, and treats only serious and critical violations among the results as failures.",
    ),
    actors: [
      { id: "test", label: t("테스트", "Test"), sub: t("a11y-smoke 스펙", "a11y-smoke spec"), tone: "local" },
      { id: "app", label: t("화면", "Page"), sub: t("Vite 개발 서버 · 비로그인", "Vite dev server, signed out"), tone: "local" },
      { id: "stub", label: t("API 대역", "API stub"), sub: t("세션만 200, 나머지 503", "Session 200, rest 503"), tone: "neutral" },
      { id: "axe", label: t("axe-core", "axe-core"), sub: t("접근성 규칙 모음", "Accessibility rule set"), tone: "external" },
    ],
    messages: [
      { from: "test", to: "stub", label: t("/api 요청 가로채기 등록", "Register /api interception"), note: t("세션만 200, 나머지는 503", "Session only 200, rest 503") },
      { from: "test", to: "app", label: t("라우트 열기", "Open the route"), note: t("데스크톱 10개 · 모바일 4개", "10 desktop, 4 mobile") },
      { from: "app", to: "stub", label: t("세션·데이터 요청", "Session and data calls") },
      { from: "stub", to: "app", label: t("503 (세션만 200)", "503 (session 200)"), style: "dashed", note: t("서비스 장애 배너가 뜬 상태", "With the outage banner showing") },
      { from: "app", to: "test", label: t("화면 준비 신호", "Route ready signal"), style: "dashed", note: t("data-route-state 확인", "Checks data-route-state") },
      { from: "test", to: "app", label: t("폰트·애니메이션 대기", "Wait for fonts and animations"), note: t("끝이 있는 것만, 최대 5초", "Finite ones only, up to 5 s") },
      { from: "test", to: "axe", label: t("WCAG 태그 4종으로 검사", "Run with 4 WCAG tags"), note: t("wcag2a · 2aa · 21aa · 22aa", "wcag2a, 2aa, 21aa, 22aa") },
      { from: "axe", to: "test", label: t("위반 목록", "Violation list"), style: "dashed" },
      { from: "test", to: "test", label: t("serious·critical만 실패", "Fail on serious and critical only"), note: t("moderate·minor는 비차단", "Moderate and minor do not block") },
    ],
  },
  usage: [
    {
      feature: t("모든 PR의 접근성 스모크 (코어 CI a11y 잡)", "Accessibility smoke on every PR (a11y job of core CI)"),
      role: t(
        "홈·탐색·커뮤니티·마켓·스튜디오·제작·설정 등 핵심 화면이 심각한 접근성 위반 없이 열리는지 확인하며, 이 잡이 실패하면 core가 통과하지 못합니다.",
        "It checks that key screens such as Home, Discover, Community, Market, Studio, Production and Settings open without serious accessibility violations, and core cannot pass if this job fails.",
      ),
      paths: ["e2e/a11y-smoke.spec.ts", "playwright.a11y.config.ts", ".github/workflows/ci.yml"],
      route: "/discover",
    },
    {
      feature: t("모바일 터치 영역과 겹침 검사", "Mobile touch-target and overlap checks"),
      role: t(
        "390px 화면에서 검색 결과가 44px 이상인지, 서비스 장애 알림과 음악 플레이어가 320·390·430px 폭에서 서로의 터치를 가리지 않는지 버튼 아홉 지점으로 확인합니다.",
        "On a 390 px screen it checks that search results are at least 44 px and, at 320, 390 and 430 px widths, that the outage notice and the music player do not cover each other's taps, probing nine points per button.",
      ),
      paths: ["e2e/a11y-smoke.spec.ts"],
      route: "/studio",
    },
    {
      feature: t("사이트 전역 시각·접근성 감사 (수동)", "Sitewide visual and accessibility audit (manual)"),
      role: t(
        "라우트 382개를 테마 9종과 고대비·강제 색상 프로필로 열어 가로 넘침, 이름 없는 버튼, 대비 부족 같은 문제를 보고합니다. 강제 색상 프로필에서는 시스템 색이 저자 색을 덮어 대비 비율이 의미 없으므로 axe를 끕니다.",
        "It opens 382 routes in 9 themes and the high-contrast and forced-colors profiles and reports horizontal overflow, nameless buttons and low contrast. In the forced-colors profile axe is switched off because system colors override authored colors and contrast ratios become meaningless.",
      ),
      paths: [
        "scripts/audit-sitewide-visual-ux.mjs",
        ".github/workflows/sitewide-theme-exhaustive-matrix.yml",
        "apps/web/src/shared/lib/theme-presets.ts",
      ],
      route: "/accessibility",
    },
    {
      feature: t("코드 단계의 정적 접근성 규칙 (jsx-a11y)", "Static accessibility rules at the code stage (jsx-a11y)"),
      role: t(
        "웹 앱의 린트 설정에 jsx-a11y 규칙이 들어 있어 레이블 연결 같은 문제를 브라우저를 열기 전에 잡습니다. 일부 파일은 규칙 몇 개를 의도적으로 끈 예외 목록이 있습니다.",
        "The web app's lint config includes jsx-a11y rules that catch problems such as missing label association before any browser opens. A few files have a deliberate list of switched-off rules.",
      ),
      paths: ["eslint.config.mjs"],
    },
  ],
  samples: [
    {
      kind: "simplified",
      title: t("병합을 막을 위반만 골라 요약하기", "Picking only the blocking violations into a summary"),
      language: "ts",
      code: [
        "interface AxeViolation {",
        "  id: string;",
        "  impact?: string | null;",
        "  nodes: Array<{ target: unknown }>;",
        "}",
        "",
        'const BLOCKING = new Set(["serious", "critical"]);',
        "",
        "/** 병합을 막을 위반(serious·critical)만 골라 읽기 쉬운 요약으로 만든다. 비어 있어야 통과 */",
        "export function blockingSummary(violations: readonly AxeViolation[]) {",
        "  return violations",
        "    .filter((v) => v.impact != null && BLOCKING.has(v.impact))",
        "    .map((v) => ({",
        "      id: v.id,",
        "      impact: v.impact,",
        "      targets: v.nodes.slice(0, 5).map((n) => n.target), // 위치는 5곳까지만 보여준다",
        "    }));",
        "}",
        "",
        "// expect(blockingSummary(result.violations)).toEqual([])",
      ].join("\n"),
      codeEn: [
        "interface AxeViolation {",
        "  id: string;",
        "  impact?: string | null;",
        "  nodes: Array<{ target: unknown }>;",
        "}",
        "",
        'const BLOCKING = new Set(["serious", "critical"]);',
        "",
        "/** Keep only the blocking violations (serious and critical) as a readable summary; it must be empty to pass */",
        "export function blockingSummary(violations: readonly AxeViolation[]) {",
        "  return violations",
        "    .filter((v) => v.impact != null && BLOCKING.has(v.impact))",
        "    .map((v) => ({",
        "      id: v.id,",
        "      impact: v.impact,",
        "      targets: v.nodes.slice(0, 5).map((n) => n.target), // show at most 5 locations",
        "    }));",
        "}",
        "",
        "// expect(blockingSummary(result.violations)).toEqual([])",
      ].join("\n"),
      explain: t(
        "실제 스펙은 axe의 결과 객체를 이렇게 걸러 낸 뒤 비어 있는지 단언합니다. moderate·minor 위반은 보고만 하고 실패로 치지 않아 오탐 비용을 줄입니다.",
        "The real spec filters axe's result object this way and asserts that it is empty. Moderate and minor violations are not counted as failures, which lowers the cost of false positives.",
      ),
      source: "e2e/a11y-smoke.spec.ts",
      verify: "types",
    },
    {
      kind: "simplified",
      title: t("끝이 있는 애니메이션이 끝날 때까지만 기다리기", "Waiting only for finite animations to finish"),
      language: "ts",
      code: [
        "/** 끝이 정해진 애니메이션이 모두 끝날 때까지 기다린다(최대 5초). 무한 반복 효과는 기다리지 않는다 */",
        "export async function settleFiniteAnimations(limitMs = 5_000): Promise<void> {",
        "  const deadline = performance.now() + limitMs;",
        "  const pending = () =>",
        "    document.getAnimations().filter((animation) => {",
        "      const iterations = animation.effect?.getTiming().iterations ?? 1;",
        '      return animation.playState === "running" && Number.isFinite(iterations);',
        "    });",
        "  while (pending().length > 0 && performance.now() < deadline) {",
        "    await Promise.allSettled(pending().map((animation) => animation.finished));",
        "  }",
        "}",
        "// 페이드 중간의 반투명한 색으로 대비를 재면 사용자가 읽는 상태가 아닌데도 거짓 실패가 난다",
      ].join("\n"),
      codeEn: [
        "/** Wait until every finite animation has finished (up to 5 s); do not wait for infinite loops */",
        "export async function settleFiniteAnimations(limitMs = 5_000): Promise<void> {",
        "  const deadline = performance.now() + limitMs;",
        "  const pending = () =>",
        "    document.getAnimations().filter((animation) => {",
        "      const iterations = animation.effect?.getTiming().iterations ?? 1;",
        '      return animation.playState === "running" && Number.isFinite(iterations);',
        "    });",
        "  while (pending().length > 0 && performance.now() < deadline) {",
        "    await Promise.allSettled(pending().map((animation) => animation.finished));",
        "  }",
        "}",
        "// Measuring contrast on a half-faded color gives false failures in a state no user actually reads",
      ].join("\n"),
      explain: t(
        "스펙 안에 이름 없이 들어 있는 브라우저 쪽 코드를 함수로 풀어 쓴 예입니다. 페이지 진입 연출이 0.5~1.1초 동안 내용을 페이드시키므로, 중간 프레임으로 대비를 재면 판정이 흔들립니다.",
        "This unwraps the spec's inline browser code into a function. The page entrance effect fades content for about 0.5 to 1.1 seconds, so measuring contrast on a mid-frame makes the verdict flaky.",
      ),
      source: "e2e/a11y-smoke.spec.ts",
      verify: "types",
    },
  ],
  links: [
    {
      title: "Playwright · Accessibility testing",
      url: "https://playwright.dev/docs/accessibility-testing",
      kind: "docs",
      note: t("Playwright와 axe를 함께 쓰는 공식 안내", "The official guide to using axe with Playwright"),
    },
    {
      title: "axe-core",
      url: "https://github.com/dequelabs/axe-core",
      kind: "repo",
      note: t("접근성 규칙 모음의 저장소", "Repository of the accessibility rule set"),
    },
    {
      title: "WCAG 2.2",
      url: "https://www.w3.org/TR/WCAG22/",
      kind: "spec",
      note: t("웹 콘텐츠 접근성 지침", "The Web Content Accessibility Guidelines"),
    },
    {
      title: "Understanding Target Size (Minimum)",
      url: "https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html",
      kind: "spec",
      note: t("터치 영역 크기 기준의 해설", "Explains the touch-target size criterion"),
    },
    {
      title: "MDN · forced-colors",
      url: "https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/At-rules/@media/forced-colors",
      kind: "docs",
      note: t("Windows 고대비 모드를 감지하는 미디어 쿼리", "The media query that detects Windows high-contrast mode"),
    },
    {
      title: "Playwright · Emulation",
      url: "https://playwright.dev/docs/emulation",
      kind: "docs",
      note: t("고대비·강제 색상 같은 환경을 흉내 내는 방법", "How to emulate environments such as high contrast and forced colors"),
    },
  ],
  chapterIds: ["quality"],
  talk: {
    pitch: t(
      "접근성은 두 겹으로 점검합니다. 병합 전 필수 단계에서는 핵심 화면을 axe로 자동 검사하고 심각한 위반이 있으면 병합을 막습니다. 일부러 API를 503으로 만들어 장애 배너가 떠 있는 화면도 봅니다. 전체 382개 화면을 아홉 가지 테마와 고대비·강제 색상 모드로 훑는 감사는 시간이 오래 걸려 수동으로 돌립니다. 자동 검사가 접근성 전부를 보증하지는 않는다는 점도 함께 말씀드립니다.",
      "Accessibility is checked in two layers. In the mandatory pre-merge step, key screens are checked automatically with axe, and serious violations block the merge. The API is deliberately set to 503 so that screens with the outage banner are inspected too. The audit that sweeps all 382 screens in nine themes and in high-contrast and forced-colors modes takes a long time and is run manually. I also want to say that automated checks do not guarantee all of accessibility.",
    ),
    analogy: t(
      "자동차로 치면 매번 하는 간이 점검(스모크)과 정기 종합검사(전수 매트릭스)의 차이입니다.",
      "Like a car: a quick check every time (the smoke) versus a periodic full inspection (the matrix).",
    ),
    questions: [
      {
        question: t("스크린 리더로 직접 써 보았나요?", "Have you tried it with a real screen reader?"),
        answer: t(
          "저장소에서는 그런 수동 테스트의 기록을 찾지 못했습니다. 자동 검사는 일부만 잡기 때문에 사람이 확인해야 하는 영역으로 남아 있습니다.",
          "No record of such manual testing was found in the repository. Because automated checks catch only part of the problems, that remains an area for people to verify.",
        ),
      },
      {
        question: t("왜 API를 503으로 막고 검사하나요?", "Why block the API with 503 while checking?"),
        answer: t(
          "서비스 장애 배너가 보이는 상태에서도 화면이 읽히는지 보기 위해서입니다. 세션 확인만 비로그인 200으로 답합니다. 대신 로그인 이후의 화면은 이 스모크가 보증하지 않습니다.",
          "To see whether the screen stays readable with the outage banner showing. Only the session check answers as signed out with 200. In exchange, this smoke does not guarantee screens after sign-in.",
        ),
      },
      {
        question: t("모든 PR이 382개 화면을 검사하나요?", "Does every PR check all 382 screens?"),
        answer: t(
          "아니요. 코어 PR 게이트는 16개 시나리오이고, 382개 화면 매트릭스는 수동이거나 그 워크플로 파일이 바뀐 PR에서만 자동으로 돕니다.",
          "No. The core PR gate runs 16 scenarios, and the 382-route matrix runs manually or automatically only on a PR that changes its workflow file.",
        ),
      },
    ],
    pitfall: t(
      "'키보드·모션 감소·강제 색상까지 PR마다 점검한다'고 말하면 과장입니다. 코어에서 매번 도는 것은 axe 스모크(모션 감소 설정 포함)이고, 강제 색상은 수동 매트릭스에 있으며, 키보드 조작 점검은 a11y-smoke 스펙에 없습니다. 검사는 개발 서버·비로그인 조건이고 moderate 이하 위반은 실패로 치지 않습니다.",
      "Saying 'keyboard, reduced motion and forced colors are checked on every PR' is an overstatement. What runs every time in core is the axe smoke (with a reduced-motion setting), forced colors live in the manual matrix, and keyboard operation checks are not in the a11y-smoke spec. The checks run against a dev server while signed out, and moderate or lower violations do not count as failures.",
    ),
  },
  technologies: ["Playwright", "axe-core", "WCAG 2.2", "Vite", "GitHub Actions"],
  facts: [
    {
      value: "16",
      label: t("코어 접근성 스모크 테스트 수 (데스크톱 라우트 10 · 모바일 라우트 4 · 터치 시나리오 2)", "Core accessibility smoke tests (10 desktop routes, 4 mobile routes, 2 touch scenarios)"),
      source: "e2e/a11y-smoke.spec.ts",
    },
    {
      value: "382",
      label: t("사이트 전역 감사가 코드에서 모은 라우트 수 (2026-10-08 목록 출력)", "Routes the sitewide audit collects from code (listing printed on 2026-10-08)"),
      source: "scripts/audit-sitewide-visual-ux.mjs",
    },
    {
      value: "44 px",
      label: t("모바일 터치 영역 기준", "Mobile touch-target threshold"),
      source: "e2e/a11y-smoke.spec.ts",
    },
  ],
  reviewedAt: "2026-10-07",
};

const TEST_HONESTY_AND_TIME_BUDGET_ISOLATION: EngineeringAtlasEntry = {
  id: "test-honesty-and-time-budget-isolation",
  category: "platform-ops",
  name: "Honest test counts and serial timing lane",
  title: t("테스트 수는 정의와 함께, 시간을 재는 테스트는 혼자서", "Test counts with their definition, and timing tests run alone"),
  status: "live",
  tagline: t(
    "병합을 막는 코어가 직접 지정한 테스트는 수집된 약 6,500개 중 약 17%입니다.",
    "The merge-blocking core names about 17% of the roughly 6,500 collected tests.",
  ),
  background: [
    t(
      "'테스트가 몇 개예요?'는 발표에서 가장 자주 나오는 질문인데, 답은 무엇을 세느냐에 따라 달라집니다. 테스트 파일 수, 테스트 케이스 수, 병합을 막는 테스트 수는 서로 다릅니다. ToonStudio는 수치를 부풀리지 않으려고 세 가지를 나눠 셉니다. Vitest가 수집하는 파일은 2026-10-08 추적 파일 기준 6,569개(apps·deploy·packages·scripts·tests 다섯 루트)이고, 병합을 막는 코어가 직접 지정한 파일은 약 1,144개(약 17%, 경로 부분 일치로 계산한 값)이며, 시간 예산 때문에 따로 도는 파일이 21개입니다.",
      "'How many tests do you have?' is the question that comes up most in talks, and the answer depends on what you count. Test files, test cases and tests that block a merge are different numbers. To avoid inflating figures, ToonStudio counts three things separately. Vitest collects 6,569 files (tracked files on 2026-10-08, five roots: apps, deploy, packages, scripts and tests); the merge-blocking core names about 1,144 of them directly (about 17%, computed with substring path matching); and 21 files run apart because of time budgets.",
    ),
    t(
      "수를 조용히 잃지 않게 하는 장치도 있습니다. vitest.config.ts의 TEST_ROOTS가 수집 루트를 명시하고, verify-toolchain-coverage 스크립트는 루트별 테스트 파일 수와 tsc가 보는 파일 수가 기록된 하한 밑으로 줄면 실패합니다. 총합이 아니라 루트별로 보는 이유는 한 폴더가 통째로 비어도 다른 폴더의 증가분이 총합을 가려, 아무것도 검사하지 않은 채 초록이 되기 때문입니다. 단 하한 기준선은 2026-09-06 기록(3,367)이라 오늘 값보다 훨씬 낮아 대량 삭제는 잡지 못합니다.",
      "There is also a guard against quietly losing tests. TEST_ROOTS in vitest.config.ts names the collection roots, and the verify-toolchain-coverage script fails if the test-file count per root or the number of files tsc sees drops below a recorded floor. It looks per root rather than at the total because when one folder goes empty, growth elsewhere hides it in the total and the run stays green while checking nothing. But the floor baseline was recorded on 2026-09-06 (3,367), far below today's value, so it cannot catch a mass deletion.",
    ),
    t(
      "시간을 재는 테스트는 따로 다뤄야 합니다. '몇 밀리초 안에 끝난다'는 단언은 같이 도는 다른 테스트의 부하까지 재서 불안정해집니다. 같은 커밋이 조용한 머신에서 20번 모두 통과하고 부하 속에서는 12% 실패한 사례가 코드 주석에 있습니다. 임계값을 풀면 회귀를 못 잡으니 값은 그대로 두고 실행 방식을 바꿨습니다. 시간을 재는 18개 파일과 CPU 참조 3개를 루트 실행에서 빼고, 워커 1개·파일 병렬 없음인 직렬 레인에서 따로 돌립니다.",
      "Tests that measure time need separate handling. An assertion like 'finishes within a few milliseconds' also measures the load of other tests running alongside, and turns flaky. A code comment records the same commit passing 20 of 20 runs on a quiet machine and failing 12% of the time under load. Loosening the threshold would stop it catching regressions, so the values stay and the way of running changed. The 18 timing files and 3 CPU-reference files are removed from the root run and run apart in a serial lane with one worker and no file parallelism.",
    ),
    t(
      "시간 예산 자체도 기계 의존을 줄였습니다. 같은 프로세스에서 같은 순간에 잰 기준 연산 대비 비율(기본 1.5배)로 판정하고, 여러 번 측정한 값 중 가장 낮은 비율이 예산을 넘어야만 실패합니다. 한계도 있습니다. 직렬 레인은 PR마다 최대 35분 제한을 차지하고, 전체 pnpm test는 PR의 별도 진단 워크플로(Full Test Diagnostic)에서 돌지만 core·verify 집계에는 들어가지 않습니다. 브랜치 보호 설정은 저장소 파일로 확인할 수 없습니다.",
      "The time budgets themselves were made less machine-dependent. They are judged as a ratio against a reference computation measured at the same moment in the same process (1.5 times by default), and fail only if the lowest ratio across several measurements exceeds the budget. There are limits too. The serial lane takes up to a 35-minute limit on every PR, and the full pnpm test runs in a separate diagnostic workflow on PRs (Full Test Diagnostic) but is not part of the core and verify aggregate. Branch protection settings cannot be confirmed from the repository files.",
    ),
  ],
  keyPoints: [
    t("파일·케이스·병합 차단 테스트는 서로 다른 숫자", "Files, cases and merge-blocking tests are different numbers"),
    t("수집 하한은 루트별: 폴더가 비면 총합이 가려도 실패", "Floors are per root: an emptied folder fails even if the total hides it"),
    t("시간을 재는 21개 파일은 임계값 그대로 직렬 레인에서", "21 timing files run in a serial lane with thresholds unchanged"),
    t("교정된 시간 예산: 기준 연산 대비 비율, 최저 비율로 판정", "Calibrated budgets: a ratio to a reference, judged on the lowest ratio"),
  ],
  diagram: {
    id: "test-honesty-and-time-budget-isolation-diagram",
    kind: "layers",
    title: t("병합을 막는 것과 막지 않는 것", "What blocks a merge and what does not"),
    caption: t(
      "core는 7개 게이트가 모두 성공해야 통과하고, 전체 테스트 수집은 그 집계 밖의 진단입니다.",
      "core passes only when all 7 gates succeed, and the full test collection is diagnostics outside that aggregate.",
    ),
    alt: t(
      "맨 위 verify는 core가 성공일 때만 통과합니다. core는 lint, typecheck, static, serial, a11y, build, database 일곱 게이트가 모두 실제로 성공해야 통과합니다. 그 아래 static은 코어가 직접 지정한 약 1,144개 테스트를 다섯 샤드로 돌리고, serial은 시간을 재는 21개 파일을 워커 한 개로 돌립니다. 수집 하한 검사는 루트별 파일 수가 줄면 실패시킵니다. 맨 아래 전체 진단은 수집된 6,569개 전체를 돌리지만 core 집계에는 들어가지 않습니다.",
      "At the top, verify passes only when core succeeds. core passes only when all seven gates (lint, typecheck, static, serial, a11y, build and database) actually succeed. Below, static runs about 1,144 tests named directly by the core in five shards, and serial runs the 21 timing files with a single worker. The collection-floor check fails when a root's file count drops. At the bottom, the full diagnostic runs all 6,569 collected files but is not part of the core aggregate.",
    ),
    layers: [
      {
        id: "verify",
        label: t("verify · 병합 가능 여부", "verify · can it merge"),
        sub: t("core가 success일 때만 통과", "Passes only if core is success"),
        tone: "good",
      },
      {
        id: "core",
        label: t("core · 7개 게이트 집계", "core · aggregate of 7 gates"),
        sub: t("skipped·cancelled·누락도 실패로 처리", "Skipped, cancelled and missing count as failure"),
        tone: "warn",
        chips: ["lint", "typecheck", "static", "serial", "a11y", "build · database"],
      },
      {
        id: "static",
        label: t("static · 코어 지정 테스트", "static · tests named by core"),
        sub: t("394줄 목록 → 약 1,144개(약 17%), 5개 샤드", "394-line list, about 1,144 files (17%), 5 shards"),
        tone: "neutral",
      },
      {
        id: "serial",
        label: t("serial · 시간 예산 직렬 레인", "serial · timing budget lane"),
        sub: t("시간 18 + CPU 참조 3 = 21개, 워커 1개", "18 timing + 3 CPU reference = 21, one worker"),
        tone: "neutral",
      },
      {
        id: "floor",
        label: t("수집 하한 · 줄면 실패", "Collection floor · fails if lower"),
        sub: t("루트별 테스트 파일 수와 tsc 입력 수를 기록값과 비교", "Compares per-root test files and tsc inputs with recorded values"),
        tone: "neutral",
      },
      {
        id: "diagnostic",
        label: t("집계 밖 · 전체 진단", "Outside the aggregate · full run"),
        sub: t("Full Test Diagnostic(PR)과 야간 진단이 6,569개 전부 실행", "Full Test Diagnostic (PR) and nightly runs cover all 6,569"),
        tone: "external",
      },
    ],
    brackets: [
      { label: t("코어 안에서 테스트를 도는 두 레인", "Two lanes that run tests inside core"), layerIds: ["static", "serial"] },
      { label: t("병합 집계 밖", "Outside the merge aggregate"), layerIds: ["diagnostic"] },
    ],
  },
  usage: [
    {
      feature: t("병합 판정 코어 (CI · core/verify)", "The merge verdict core (CI core and verify)"),
      role: t(
        "lint·typecheck·static·serial·a11y·build·database 7개가 모두 실제 success여야 core가 통과하고, verify는 core만 확인합니다. skipped·cancelled·누락은 실패로 칩니다.",
        "core passes only when all seven (lint, typecheck, static, serial, a11y, build and database) actually succeed, and verify checks core alone. Skipped, cancelled and missing results count as failure.",
      ),
      paths: [".github/workflows/ci.yml", "scripts/ci-core-gate.mjs"],
    },
    {
      feature: t("코어 회귀 샤드 (큐레이션 테스트)", "Core regression shards (curated tests)"),
      role: t(
        "ci-required-vitest-targets.txt의 394줄을 5개 샤드로 결정적으로 나눠 돌립니다. product 샤드는 아키텍처·CSP·수집 하한 검사도 함께 실행합니다.",
        "The 394 lines of ci-required-vitest-targets.txt are split deterministically into five shards. The product shard also runs the architecture, CSP and collection-floor checks.",
      ),
      paths: ["scripts/ci-required-vitest-targets.txt", "scripts/ci-core-regression-shards-impl.mjs"],
    },
    {
      feature: t("브러시 성능 테스트의 직렬 레인과 교정된 시간 예산", "Serial lane and calibrated time budgets for brush performance tests"),
      role: t(
        "루트 실행에서 뺀 21개 파일을 워커 1개로 한 번에 하나씩 돌리고, 분할이 어긋나지 않는지 테스트가 지킵니다. 예산은 기준 연산 대비 비율로 판정합니다.",
        "The 21 files removed from the root run execute one at a time with a single worker, a test guards that the split stays consistent, and budgets are judged as a ratio to a reference computation.",
      ),
      paths: [
        "vitest.perf.config.ts",
        "vitest.perf-budget-files.mjs",
        "tests/vitest-perf-budget-partition.test.ts",
        "apps/web/src/domains/creator/brush/studio-perf-calibration.ts",
      ],
    },
    {
      feature: t("테스트·타입 검사 수집 하한", "Collection floors for tests and type checking"),
      role: t(
        "수집 루트를 설정 파일에서 읽어 루트별 테스트 파일 수와 tsc가 실제로 보는 파일 수를 기록된 하한과 비교합니다. 줄어든 삭제는 --update로 기록을 갱신해 커밋에 드러나게 합니다.",
        "It reads the collection roots from the config file and compares per-root test-file counts and the number of files tsc actually sees with recorded floors. A deliberate deletion re-records the floor with --update so the drop shows in the commit.",
      ),
      paths: ["vitest.config.ts", "scripts/verify-toolchain-coverage.mjs", "scripts/toolchain-coverage-baseline.json"],
    },
  ],
  samples: [
    {
      kind: "simplified",
      title: t("루트별 하한 밑으로 줄면 실패", "Failing when a root drops below its floor"),
      language: "ts",
      code: [
        "/** 루트별 테스트 파일 수가 기록된 하한 밑으로 내려가면 실패 메시지를 돌려준다 */",
        "export function floorFailures(",
        "  actual: Readonly<Record<string, number>>,",
        "  floor: Readonly<Record<string, number>>,",
        "): string[] {",
        "  return Object.entries(floor).flatMap(([root, min]) => {",
        "    const now = actual[root] ?? 0; // 수집 루트가 통째로 사라지면 0개로 본다",
        "    return now < min ? [`${root}: ${min} → ${now}`] : [];",
        "  });",
        "}",
        "",
        "// 총합이 아니라 루트별로 보는 이유: 한 트리가 비어도 다른 트리의 증가분이 총합을 가린다",
        '// floorFailures({ apps: 6000, tests: 0 }, { apps: 3122, tests: 54 }) → ["tests: 54 → 0"]',
      ].join("\n"),
      codeEn: [
        "/** Return a failure message when a root's test-file count falls below its recorded floor */",
        "export function floorFailures(",
        "  actual: Readonly<Record<string, number>>,",
        "  floor: Readonly<Record<string, number>>,",
        "): string[] {",
        "  return Object.entries(floor).flatMap(([root, min]) => {",
        "    const now = actual[root] ?? 0; // a root that vanishes entirely counts as zero files",
        "    return now < min ? [`${root}: ${min} → ${now}`] : [];",
        "  });",
        "}",
        "",
        "// Per root, not the total, because growth in one tree hides an emptied tree in the sum",
        '// floorFailures({ apps: 6000, tests: 0 }, { apps: 3122, tests: 54 }) → ["tests: 54 → 0"]',
      ].join("\n"),
      explain: t(
        "실제 스크립트는 루트 목록을 vitest.config.ts에서 읽어 복제하지 않고, 설정에서 사라진 루트도 실패로 잡으며, tsc 입력 파일 수에도 같은 하한을 적용합니다. 허용 감소폭은 0입니다.",
        "The real script reads the root list from vitest.config.ts instead of copying it, also fails on a root that disappeared from the config, and applies the same floor to the tsc input count. The allowed shortfall is zero.",
      ),
      source: "scripts/verify-toolchain-coverage.mjs",
      verify: "types",
    },
    {
      kind: "simplified",
      title: t("기준 연산 대비 비율로 시간 예산 판정하기", "Judging a time budget as a ratio to a reference"),
      language: "ts",
      code: [
        "interface Sample {",
        "  referenceMs: number; // 기준 연산이 걸린 시간",
        "  workMs: number; // 검사 대상이 걸린 시간",
        "}",
        "",
        "/** 한 번의 측정: 짝지어 잰 표본에서 각각 최솟값을 고른다. 방해는 시간을 더할 뿐 덜어 주지 않기 때문이다 */",
        "export function reduce(samples: readonly Sample[]): number {",
        "  const referenceMs = Math.min(...samples.map((s) => s.referenceMs));",
        "  const workMs = Math.min(...samples.map((s) => s.workMs));",
        "  return workMs / referenceMs; // 기계가 느리면 분자와 분모가 함께 커져 비율은 거의 그대로다",
        "}",
        "",
        "/** 위반은 모든 측정이 인정해야 성립한다: 가장 낮은 비율이 예산(기본 1.5배)을 넘을 때만 실패 */",
        "export function judge(passRatios: readonly number[], maxRatio = 1.5): boolean {",
        "  return Math.min(...passRatios) <= maxRatio;",
        "}",
        "",
        "// judge([1.83, 0.92, 1.1]) → true (가장 낮은 0.92가 예산 이하라 통과)",
      ].join("\n"),
      codeEn: [
        "interface Sample {",
        "  referenceMs: number; // time the reference computation took",
        "  workMs: number; // time the code under test took",
        "}",
        "",
        "/** One measurement: take the minimum of each side from paired samples, since interference only adds time */",
        "export function reduce(samples: readonly Sample[]): number {",
        "  const referenceMs = Math.min(...samples.map((s) => s.referenceMs));",
        "  const workMs = Math.min(...samples.map((s) => s.workMs));",
        "  return workMs / referenceMs; // a slower machine inflates both sides, so the ratio barely moves",
        "}",
        "",
        "/** A violation must be earned by every measurement: fail only if the lowest ratio exceeds the budget (1.5 by default) */",
        "export function judge(passRatios: readonly number[], maxRatio = 1.5): boolean {",
        "  return Math.min(...passRatios) <= maxRatio;",
        "}",
        "",
        "// judge([1.83, 0.92, 1.1]) → true (the lowest, 0.92, is within budget, so it passes)",
      ].join("\n"),
      explain: t(
        "코드 주석에 기록된 값(과부하 컨테이너에서 같은 작업이 1.83과 0.92를 오갔고, 2배 느려진 작업은 1.94 아래로 내려간 적이 없다)에 맞춰 기본 예산을 1.5로 잡았다고 설명합니다. 실제 구현은 기준 연산을 같은 구간에서 번갈아 재고 한 번 통과하면 측정을 끝냅니다.",
        "The code comment explains the 1.5 default as set from recorded values: on an overloaded container the same job swung between 1.83 and 0.92, while a job made twice as slow never fell below 1.94. The real implementation alternates the reference with the work in the same window and stops after one passing measurement.",
      ),
      source: "apps/web/src/domains/creator/brush/studio-perf-calibration.ts",
      verify: "types",
    },
  ],
  links: [
    {
      title: "Vitest · fileParallelism",
      url: "https://vitest.dev/config/fileparallelism",
      kind: "docs",
      note: t("파일을 병렬로 돌릴지 정하는 설정", "The setting that decides whether files run in parallel"),
    },
    {
      title: "Vitest · include",
      url: "https://vitest.dev/config/include",
      kind: "docs",
      note: t("어떤 파일을 테스트로 수집할지 정하는 설정", "The setting that decides which files are collected as tests"),
    },
    {
      title: "Vitest · Coverage",
      url: "https://vitest.dev/guide/coverage.html",
      kind: "guide",
      note: t("커버리지 계측이 실행 시간을 바꾸는 이유 이해에 도움", "Helps explain why coverage instrumentation changes run time"),
    },
    {
      title: "Vitest · Test filtering",
      url: "https://vitest.dev/guide/filtering.html",
      kind: "guide",
      note: t("경로 문자열로 실행할 테스트를 고르는 방법", "How tests are selected by a path string"),
    },
    {
      title: "MDN · Performance.now()",
      url: "https://developer.mozilla.org/en-US/docs/Web/API/Performance/now",
      kind: "docs",
      note: t("시간 측정에 쓰는 고해상도 시계", "The high-resolution clock used for timing"),
    },
  ],
  chapterIds: ["quality", "performance"],
  talk: {
    pitch: t(
      "테스트가 몇 개냐는 질문에는 정의를 먼저 말합니다. 수집되는 테스트 파일은 약 6,500개이고, 병합을 막는 코어가 직접 지정한 것은 그중 약 17%입니다. 나머지는 PR의 전체 진단과 야간 점검에서 돕니다. 시간을 재는 21개 파일은 임계값을 풀지 않고 혼자 도는 직렬 레인으로 옮겨, 기계 부하 때문에 흔들리는 일을 줄였습니다.",
      "When asked how many tests there are, start with the definition. About 6,500 test files are collected, and the merge-blocking core names about 17% of them directly. The rest run in the full diagnostic on PRs and in nightly checks. The 21 files that measure time were moved to a serial lane where they run alone, without loosening any threshold, to cut the flakiness caused by machine load.",
    ),
    analogy: t(
      "체중계 위에서 짐을 나르며 몸무게를 재면 값이 흔들립니다. 혼자 조용히 올라가 재야 정확한 것과 같습니다.",
      "Weighing yourself while carrying boxes gives a shaky reading; you have to step on quietly and alone to get an accurate one.",
    ),
    questions: [
      {
        question: t("테스트가 몇 개인가요?", "How many tests are there?"),
        answer: t(
          "정의에 따라 다릅니다. 수집 파일은 6,569개(2026-10-08 추적 파일 기준), 코어가 직접 지정한 파일은 약 1,144개(경로 부분 일치 계산), 직렬 레인은 21개입니다. 테스트 케이스(it) 수는 실행으로 확인하지 않았습니다.",
          "It depends on the definition: 6,569 collected files (tracked files on 2026-10-08), about 1,144 named directly by core (substring path matching), and 21 in the serial lane. The number of test cases (it) was not confirmed by running.",
        ),
      },
      {
        question: t("PR마다 전체 테스트가 도나요?", "Does the full suite run on every PR?"),
        answer: t(
          "전체 pnpm test는 PR의 별도 진단 워크플로(Full Test Diagnostic, 45분 제한)에서 돌지만 core·verify 집계에는 들어가지 않습니다. 병합을 막는 것은 core입니다. 브랜치 보호 설정은 저장소만으로 확인할 수 없습니다.",
          "The full pnpm test runs in a separate diagnostic workflow on PRs (Full Test Diagnostic, 45-minute limit) but is not part of the core and verify aggregate. What blocks a merge is core. Branch protection cannot be confirmed from the repository alone.",
        ),
      },
      {
        question: t("flaky 테스트는 임계값을 늘려서 해결하나요?", "Do you fix flaky tests by loosening thresholds?"),
        answer: t(
          "아니요. 임계값은 그대로 두고 실행 방식을 바꿉니다. 시간을 재는 파일을 직렬 레인으로 빼고, 예산은 기준 연산 대비 비율로 판정합니다. 느린 러너는 흡수하지만 동시 실행의 경합은 직렬화로만 풀립니다.",
          "No. The thresholds stay and the way of running changes. Timing files move to a serial lane and budgets are judged as a ratio to a reference computation. A slow runner is absorbed by the ratio, but contention from concurrent runs is solved only by serializing.",
        ),
      },
    ],
    pitfall: t(
      "'테스트 6,500개가 매 PR을 막는다'는 틀린 말입니다. 병합을 막는 것은 큐레이션한 코어이고, 수집 하한 기준선(3,367, 2026-09-06 기록)이 낡아 대량 삭제는 못 잡습니다. 정적 선언 수(it 개수)는 실행된 케이스 수가 아니며, 전체 실행 시간은 현재 값을 이 저장소 기록으로 확인하지 못했으니 말하지 마세요.",
      "'6,500 tests block every PR' is wrong. What blocks a merge is the curated core, and the collection-floor baseline (3,367, recorded 2026-09-06) is stale and cannot catch a mass deletion. The static count of declarations (it) is not the number of executed cases, and the current full-run time could not be confirmed from the repository, so do not quote one.",
    ),
  },
  technologies: ["Vitest", "GitHub Actions", "TypeScript", "Node.js"],
  facts: [
    {
      value: "6,569",
      label: t("Vitest 수집 5개 루트의 테스트 파일 수 (2026-10-08, git 추적 파일 기준)", "Test files in the five Vitest roots (tracked files, 2026-10-08)"),
      source: "scripts/verify-toolchain-coverage.mjs",
    },
    {
      value: "394",
      label: t("코어 게이트가 직접 지정한 Vitest 대상 줄 수", "Lines of Vitest targets named directly by the core gate"),
      source: "scripts/ci-required-vitest-targets.txt",
    },
    {
      value: "21",
      label: t("직렬 레인 파일 수 (시간 예산 18 + CPU 참조 3)", "Files in the serial lane (18 timing budgets + 3 CPU references)"),
      source: "vitest.serial-test-files.mjs",
    },
    {
      value: "1.5x",
      label: t("교정된 시간 예산의 기본 허용 비율", "Default allowed ratio of a calibrated time budget"),
      source: "apps/web/src/domains/creator/brush/studio-perf-calibration.ts",
    },
  ],
  reviewedAt: "2026-10-07",
};

export const PLATFORM_OPS_QUALITY_CARDS: readonly EngineeringAtlasEntry[] = [
  MODULE_BOUNDARY_RATCHET,
  AXE_A11Y_MATRIX,
  TEST_HONESTY_AND_TIME_BUDGET_ISOLATION,
];
