import { CREATOR, D, row, t, watch } from "./engineering-map-competitors-kit";

import type { EngineeringMapRow } from "./engineering-map-types";

/**
 * 경쟁·참고 제품 지도의 행 — 2D 애니메이션·모션 영역(셀·벡터 애니메이션, 리깅, 모션 그래픽).
 * 쓰는 규칙은 engineering-map-competitors-kit.ts 머리말을 따른다.
 */

const RADAR = "docs/studio-commercial-clean-room-radar-2026-07-28.md";
const INTAKE = "docs/benchmarks/studio-competitive-intake-2026-09-02.md";
const EMERGING_INTAKE = "docs/benchmarks/studio-emerging-research-intake-2026-09-02.md";
const COMPETITOR_REGISTRY = "docs/benchmarks/studio-competitor-registry.json";
const EMERGING_REGISTRY = "docs/benchmarks/studio-emerging-product-registry.json";

export const COMPETITOR_ROWS_ANIMATION: readonly EngineeringMapRow[] = [
  row({
    id: "toon-boom-harmony",
    name: "Toon Boom Harmony",
    domain: D.animation,
    url: "https://www.toonboom.com/products/harmony",
    what: t(
      "2D 셀 애니메이션·리깅 전문 프로그램입니다. 질감이 있는 벡터 붓과, 뼈·곡선·점을 섞어 질감이 찢어지지 않게 변형하는 가중 변형이 비교 대상이었습니다.",
      "A professional 2D cel animation and rigging program. Its textured vector brush and weighted deformation, which blends bones, curves and points so textures do not tear, were compared.",
    ),
    learned: t(
      "배움: 고칠 수 있는 중심선 위에 질감 씨앗을 따로 두어 변형 뒤에도 질감을 다시 만들고, 거리로 가중해 섞은 변형. 이 제품의 코드·소재는 가져오지 않음(clean-room).",
      "Learned: keep a texture seed apart from the editable centerline so texture is regenerated after transforms, and blend deformation by distance weights. None of its code or materials is imported (clean-room).",
    ),
    overlap: t("가중 변형 제공자(Worker), 퍼핏 워프, 프레임 애니메이션 타임라인.", "The weighted-deformation provider (Worker), puppet warp and the frame-animation timeline."),
    evidence: [RADAR, INTAKE, COMPETITOR_REGISTRY, `${CREATOR}/studio-weighted-deformation-provider.ts`, `${CREATOR}/studio-puppet-warp.ts`, `${CREATOR}/studio-frame-animation.ts`],
  }),
  row({
    id: "moho",
    name: "Moho",
    domain: D.animation,
    url: "https://moho.lostmarble.com/",
    what: t(
      "뼈(본) 기반 2D 벡터 애니메이션 프로그램입니다. 관절 회전에 따라 모양을 보정하는 ‘스마트 본’이 비교 대상이었습니다.",
      "A bone-based 2D vector animation program. Its 'Smart Bones', which correct shapes as joints rotate, were compared.",
    ),
    learned: t(
      "배움: 뼈·표정 값을 재사용 가능한 보정 변형에 잇는 구조. 여러 구동값이 부딪칠 때의 규칙을 명시하고, 결과를 결정적으로 굽는(bake) 형태로 구현.",
      "Learned: link bone and expression values to reusable corrective shapes, state the rule for conflicting drivers, and bake the result deterministically.",
    ),
    overlap: t("보정 구동 그래프(corrective-driver graph) 코어와 결정적 bake.", "The corrective-driver graph core and its deterministic bake."),
    evidence: [RADAR, INTAKE, COMPETITOR_REGISTRY, `${CREATOR}/studio-corrective-driver-graph.ts`],
  }),
  row({
    id: "live2d-cubism",
    name: "Live2D Cubism",
    domain: D.animation,
    url: "https://www.live2d.com/en/cubism/",
    what: t(
      "일러스트를 움직이는 2D 캐릭터로 만드는 리깅 도구입니다. 부모·자식 ‘디포머’로 그림을 망가뜨리지 않고 변형하는 방식이 비교 대상이었습니다.",
      "A rigging tool that turns illustrations into moving 2D characters. Its parent and child 'deformers' that bend art without damaging it were compared.",
    ),
    learned: t(
      "배움: 메시·워프·회전 디포머 그래프와 매개변수 키폼, 결정적 보간, 물리는 선택 제공자로 둠. 퍼핏·워프 코어와 합치는 설계 단계이며 완료로 세지 않음.",
      "Learned: a graph of mesh, warp and rotation deformers with parameter keyforms, deterministic interpolation, and physics as an optional provider. It is at the design stage with the puppet and warp core, not counted as finished.",
    ),
    overlap: t("퍼핏 워프와 가중 변형 제공자(통합 설계 대상).", "Puppet warp and the weighted-deformation provider (integration is at the design stage)."),
    evidence: [RADAR, INTAKE, COMPETITOR_REGISTRY, `${CREATOR}/studio-puppet-warp.ts`],
  }),
  row({
    id: "spine",
    name: "Spine",
    domain: D.animation,
    url: "https://esotericsoftware.com/",
    what: t(
      "뼈대로 2D 캐릭터를 움직이는 스켈레톤 애니메이션 도구입니다. 메시 변형, 제약, 런타임으로 내보내기가 제품군 단위로 비교됐습니다.",
      "A skeletal animation tool that moves 2D characters with bones. Mesh deformation, constraints and runtime export were compared at the product-group level.",
    ),
    learned: t(
      "배움(제품군 기록): 메시 변형·제약·스킨, 물리와 동작 동기화, 런타임 내보내기. 이 제품만의 적용 위치와 불채택은 문서에 따로 없음(미확인).",
      "Learned (group-level record): mesh deformation, constraints and skins, physics and motion sync, and runtime export. No product-specific adoption or exclusion is recorded (unconfirmed).",
    ),
    overlap: t("겹치는 ToonStudio 기능은 문서에 적혀 있지 않음(미확인).", "No overlapping ToonStudio feature is recorded (unconfirmed)."),
    evidence: [INTAKE, COMPETITOR_REGISTRY],
  }),
  row({
    id: "rive",
    name: "Rive",
    domain: D.animation,
    url: "https://rive.app/",
    what: t(
      "상호작용에 반응하는 벡터 애니메이션을 만들어 앱·웹에 넣는 도구입니다. 상태 머신과 런타임 내보내기가 제품군 단위로 비교됐고, 소프트 에지 수식은 공개 런타임에서 참고했습니다.",
      "A tool for making interactive vector animation that ships inside apps and the web. Its state machine and runtime export were compared at group level, and a soft-edge formula was referenced from its open runtime.",
    ),
    learned: t(
      "배움: 상호작용 상태 머신·런타임 내보내기(제품군 기록)와, 브러시 실험실의 가우스 CDF 소프트 에지 수식(MIT, 출처 표기 후 재구현). 제품 자체의 적용 위치는 문서에 없음.",
      "Learned: an interactive state machine and runtime export (group-level record), and the brush lab's Gaussian-CDF soft-edge formula (MIT, reimplemented with attribution). No product-level adoption is recorded.",
    ),
    overlap: t("브러시 실험실의 소프트 에지 커버리지 계산.", "The brush lab's soft-edge coverage calculation."),
    evidence: [INTAKE, COMPETITOR_REGISTRY, "docs/engines/labs-brush-engine-references-2026-10-01.md"],
  }),
  row({
    id: "toonsquid",
    name: "ToonSquid",
    domain: D.animation,
    url: "https://toonsquid.com/",
    what: t(
      "태블릿에서 그림과 애니메이션을 함께 만드는 모바일 애니메이션 앱입니다. 카메라, 리깅, 오디오를 한 타임라인에 잇는 흐름이 제품군 단위로 비교됐습니다.",
      "A mobile animation app for drawing and animating together on a tablet. Its flow linking camera, rigging and audio on one timeline was compared at the product-group level.",
    ),
    learned: t(
      "배움(제품군 기록): 프레임 노출·어니언 스킨, 키프레임과 모션 패스, 오디오 파형·표식을 한 타임라인에서. 이 제품만의 적용 위치는 문서에 따로 없음(미확인).",
      "Learned (group-level record): frame exposure and onion skin, keyframes and motion paths, audio waveform and markers on one timeline. No product-specific place of adoption is recorded (unconfirmed).",
    ),
    overlap: t("애니메이션 타임라인 패널과 애니매틱 작업 공간.", "The animation timeline panel and the animatic workspace."),
    evidence: [INTAKE, COMPETITOR_REGISTRY, `${CREATOR}/StudioAnimTimelinePanel.tsx`, `${CREATOR}/animatic/StudioAnimaticWorkspacePanel.tsx`],
  }),
  row({
    id: "opentoonz",
    name: "OpenToonz",
    domain: D.animation,
    url: "https://opentoonz.github.io/e/",
    what: t(
      "오픈소스 2D 셀 애니메이션 제작 도구입니다. 엑스시트(프레임 노출표), 이펙트, 스캔 정리가 관찰 초점이었고, 브러시 실험실은 개념만 참고했습니다.",
      "An open-source 2D cel animation production tool. Its xsheet (frame exposure sheet), effects and scan cleanup were the focus, and the brush lab used only its concepts.",
    ),
    learned: t(
      "배움: 코드는 복제하지 않고 ‘상한 패턴·표면 어댑터’ 개념만 참고(BSD-3). 에셋과 일부 하위 파일은 별도 라이선스라 열람·복제 대상에서 제외.",
      "Learned: no code is copied; only its 'upper-bound patterns and surface adapters' concepts are referenced (BSD-3). Its assets and some sub-files carry other licenses, so they are excluded.",
    ),
    overlap: t("브러시 실험실 엔진 참고 문헌 원장.", "The brush-lab engine reference ledger."),
    evidence: ["docs/engines/labs-brush-engine-references-2026-10-01.md", COMPETITOR_REGISTRY],
  }),
  row({
    id: "jitter",
    name: "Jitter",
    domain: D.animation,
    url: "https://jitter.video/",
    what: t(
      "브라우저에서 빠르게 모션 그래픽을 만드는 서비스입니다. AI가 만든 결과를 그대로 고칠 수 있는 점, 표(CSV)로 변형을 대량 생성하는 점이 관찰 대상이었습니다.",
      "A service for making motion graphics quickly in the browser. Its editable AI results and bulk variant generation from CSV data were observed.",
    ),
    learned: t(
      "적용 방향(계획): AI·템플릿 결과를 한 장의 영상이 아니라 편집 가능한 레이어·효과·타임라인 클립으로 받고, 컷·말풍선·제목을 변수로 묶어 회차 변형을 일괄 생성. 완료로 세지 않음.",
      "Planned direction: take AI and template output as editable layers, effects and timeline clips instead of flat video, and bind cuts, balloons and titles to variables for episode variants. Not counted as finished.",
    ),
    overlap: t("효과 그래프와 일괄 변형 생성(계획 단계).", "The effect graph and batch variant generation (planned)."),
    evidence: [EMERGING_INTAKE, EMERGING_REGISTRY],
  }),
  row({
    id: "lumiere-graphics",
    name: "Lumiere Graphics",
    domain: D.animation,
    url: "https://lumiere.graphics/",
    what: t(
      "실시간 절차적 효과(Kuwahara 붓터치 필터, 빛 번짐, 할레이션, ASCII)를 쓰는 모션 그래픽 도구입니다.",
      "A motion-graphics tool built on real-time procedural effects (Kuwahara paint-stroke filter, glare, halation, ASCII).",
    ),
    learned: t(
      "적용 방향(계획): 필터 그래프의 미리보기와 내보내기가 같은 매개변수를 쓰고, 효과를 드래그할 때 60fps를 목표로 하되 못 지키면 해상도를 낮춤. 완료로 세지 않음.",
      "Planned direction: the filter graph's preview and export share the same parameters, effects target 60 fps while dragging, and resolution drops when that fails. Not counted as finished.",
    ),
    overlap: t("비파괴 효과 스택과 라이브 필터(적용 방향).", "The non-destructive effect stack and live filters (planned direction)."),
    evidence: [EMERGING_INTAKE, EMERGING_REGISTRY],
  }),
  row({
    id: "typeflow",
    name: "TypeFlow",
    domain: D.animation,
    url: "https://www.typeflow.studio/",
    what: t(
      "글자가 움직이는 영상(키네틱 타이포)을 템플릿으로 만드는 서비스입니다. 글자만 바꾸면 실시간으로 보이고 4K로 내보냅니다.",
      "A service for kinetic-type video made from templates. You swap the text, see it live, and export in 4K.",
    ),
    learned: t(
      "적용 방향(계획): 템플릿→글자 교체→실시간 미리보기→고해상도 출력의 짧은 길을 제목·효과음 글자에 적용. 완료로 세지 않음.",
      "Planned direction: apply its short path from template to text swap to live preview to high-resolution export to titles and sound-effect lettering. Not counted as finished.",
    ),
    overlap: t("제목·효과음 글자의 변수 묶음과 내보내기(적용 방향).", "Variable binding and export for titles and sound-effect lettering (planned direction)."),
    evidence: [EMERGING_INTAKE, EMERGING_REGISTRY],
  }),
  row({
    id: "trangram",
    name: "Trangram",
    domain: D.animation,
    url: "https://www.trangram.com/",
    what: t(
      "벡터 도형이 부드럽게 변하는 애니메이션을 만드는 도구입니다. 벡터 모프, 모서리 둥글리기, 도형 합치기(불리언), 선 따라 그리기(트림 패스)가 관찰 대상이었습니다.",
      "A tool for animation where vector shapes morph smoothly. Vector morph, corner rounding, boolean operations and trim paths were observed.",
    ),
    learned: t(
      "적용 방향(계획): 벡터 노드의 불리언·트림·모프를 키프레임 가능한 속성으로 통합. 완료로 세지 않음.",
      "Planned direction: fold the vector node's boolean, trim and morph into properties that can be keyframed. Not counted as finished.",
    ),
    overlap: t("벡터 노드와 키프레임 속성(적용 방향).", "Vector nodes and keyframeable properties (planned direction)."),
    evidence: [EMERGING_INTAKE, EMERGING_REGISTRY],
  }),

  /* ── 감시 목록에만 있는 애니메이션·모션 제품 ── */
  watch({
    id: "procreate-dreams",
    name: "Procreate Dreams",
    domain: D.animation,
    url: "https://procreate.com/dreams",
    registry: "competitor",
    category: "animation-2d",
    priority: "P1",
    focus: t("타임라인, 손으로 움직임을 녹화하는 퍼포밍, 키프레임, 오디오, 터치 애니메이션", "timeline, performing (recording motion by hand), keyframes, audio and touch animation"),
  }),
  watch({
    id: "tvpaint-animation",
    name: "TVPaint Animation",
    domain: D.animation,
    url: "https://tvpaint.com/fr",
    registry: "competitor",
    category: "animation-2d",
    priority: "P1",
    focus: t("래스터 애니메이션, 타임라인, 라이트 테이블, 스토리보드, 브러시", "raster animation, timeline, light table, storyboard and brushes"),
  }),
  watch({
    id: "pencil2d",
    name: "Pencil2D",
    domain: D.animation,
    url: "https://www.pencil2d.org/",
    registry: "competitor",
    category: "animation-2d",
    priority: "P2",
    focus: t("프레임 애니메이션, 래스터·벡터, 어니언 스킨, 오픈소스, 단순한 화면", "frame animation, raster and vector, onion skin, open source and a simple UI"),
  }),
  watch({
    id: "synfig-studio",
    name: "Synfig Studio",
    domain: D.animation,
    url: "https://www.synfig.org/",
    registry: "competitor",
    category: "animation-2d",
    priority: "P2",
    focus: t("벡터 트위닝, 본, 매개변수, 오픈소스, 렌더", "vector tweening, bones, parameters, open source and rendering"),
  }),
  watch({
    id: "wick-editor",
    name: "Wick Editor",
    domain: D.animation,
    url: "https://www.wickeditor.com/",
    registry: "competitor",
    category: "animation-2d",
    priority: "P2",
    focus: t("브라우저 애니메이션, 상호작용, 프레임, 스크립팅, 오픈소스", "browser animation, interactivity, frames, scripting and open source"),
    extraEvidence: [EMERGING_REGISTRY],
  }),
  watch({
    id: "dragonbones",
    name: "DragonBones",
    domain: D.animation,
    url: "https://dragonbones.github.io/",
    registry: "competitor",
    category: "rigging-avatar",
    priority: "P2",
    focus: t("스켈레톤 애니메이션, 메시, 런타임, 오픈소스, 내보내기", "skeletal animation, mesh, runtime, open source and export"),
  }),
  watch({
    id: "callipeg",
    name: "Callipeg",
    domain: D.animation,
    url: "https://callipeg.com/",
    registry: "emerging",
    category: "mobile-drawing",
    priority: "P1",
    focus: t("모바일 애니메이션, 어니언 스킨, 오디오 타임라인, 제스처, 스타일러스", "mobile animation, onion skin, audio timeline, gestures and stylus"),
  }),
  watch({
    id: "expressive-animator",
    name: "Expressive Animator",
    domain: D.animation,
    url: "https://expressive.app/expressive-animator/",
    registry: "emerging",
    category: "animation-2d",
    priority: "P1",
    focus: t("SVG 애니메이션, 이징, 타임라인, 웹 내보내기, 모션 패스", "SVG animation, easing, timeline, web export and motion paths"),
  }),
  watch({
    id: "glaxnimate",
    name: "Glaxnimate",
    domain: D.animation,
    url: "https://glaxnimate.org/",
    registry: "emerging",
    category: "animation-2d",
    priority: "P1",
    focus: t("벡터 트위닝, Lottie, 애니메이션 SVG, 도킹 UI, 파이썬 확장", "vector tweening, Lottie, animated SVG, a dockable UI and Python extensions"),
  }),
  watch({
    id: "construct-animate",
    name: "Construct Animate",
    domain: D.animation,
    url: "https://www.construct.net/en/animation-software",
    registry: "emerging",
    category: "animation-2d",
    priority: "P1",
    focus: t("WebGPU, 버전 관리하기 좋은 파일, 브러시 자원, 애니메이션 편집기, 브라우저 실행", "WebGPU, source-control-friendly files, brush resources, an animation editor and a browser runtime"),
  }),
  watch({
    id: "matte",
    name: "Matte",
    domain: D.animation,
    registry: "emerging",
    category: "animation-2d",
    priority: "P0",
    focus: t("브라우저 타임라인, 클립 자르기, 모션 프리셋, 빠른 미리보기", "a browser timeline, clip trimming, motion presets and fast preview"),
  }),
  watch({
    id: "pikimov",
    name: "Pikimov",
    domain: D.animation,
    url: "https://pikimov.com/",
    registry: "emerging",
    category: "animation-2d",
    priority: "P1",
    focus: t("브라우저 영상 편집, 모션 그래픽, 로컬 처리, 타임라인, 효과", "browser video editing, motion graphics, local processing, timeline and effects"),
  }),
  watch({
    id: "svgator",
    name: "SVGator",
    domain: D.animation,
    url: "https://www.svgator.com/",
    registry: "emerging",
    category: "animation-2d",
    priority: "P1",
    focus: t("SVG 애니메이션, 패스 변형, 인터랙티브 내보내기, 타임라인, 웹 성능", "SVG animation, path morphing, interactive export, timeline and web performance"),
  }),
  watch({
    id: "cavalry",
    name: "Cavalry",
    domain: D.animation,
    url: "https://cavalry.scenegroup.co/",
    registry: "emerging",
    category: "animation-2d",
    priority: "P1",
    focus: t("절차적 애니메이션, 데이터 기반, 변형기, 동적 렌더, 모션 디자인", "procedural animation, data-driven work, deformers, dynamic rendering and motion design"),
  }),
  watch({
    id: "linearity-move",
    name: "Linearity Move",
    domain: D.animation,
    url: "https://www.linearity.io/move/",
    registry: "emerging",
    category: "animation-2d",
    priority: "P1",
    focus: t("자동 애니메이션, 모션 디자인, 벡터 가져오기, 템플릿, 모바일 작업", "auto-animate, motion design, vector import, templates and mobile workflow"),
  }),
];
