import type { EngineeringAtlasEntry } from "./engineering-atlas-types";
import type { LocalizedText } from "./engineering-story-content";

/**
 * 기술 도감 · platform-ops 카테고리 — 엣지·배포·헬스 카드.
 * 계약과 작성 규칙은 engineering-atlas-types.ts 를 따른다. 사실은 2026-10-07 기준 코드·테스트·문서로 확인했고,
 * 운영 대시보드(Cloudflare·Render)의 실제 값은 열람하지 않았다.
 */

const t = (ko: string, en: string): LocalizedText => ({ ko, en });

const STATIC_FIRST_EDGE_GATEWAY: EngineeringAtlasEntry = {
  id: "static-first-edge-gateway",
  category: "platform-ops",
  name: "Static-first edge gateway",
  title: t("정적은 곧장, 동적만 Worker가 먼저", "Static goes straight through; only dynamic paths meet the Worker first"),
  status: "configured",
  tagline: t(
    "화면 파일은 Static Assets가 곧장 내주고, Worker는 26개 경로 패턴만 먼저 받습니다.",
    "Static Assets serve the screens directly; the Worker first sees only 26 path patterns.",
  ),
  background: [
    t(
      "웹사이트를 열 때마다 서버가 일을 해야 한다면 방문자가 늘수록 비용과 대기 시간이 함께 늘어납니다. ToonStudio는 홈·랭킹·스튜디오 같은 화면 파일과 작품 목록 JSON을 미리 만들어 Cloudflare Static Assets(코드를 돌리지 않고 파일만 내주는 보관소)에 두고 그대로 내줍니다. 편의점 진열대에서 물건을 집어 가는 손님은 점원을 부르지 않는 것과 같습니다.",
      "If a server had to work on every page view, cost and waiting time would grow with the audience. ToonStudio builds the screen files and catalog JSON ahead of time and leaves them in Cloudflare Static Assets (a store that hands out files without running code). It is like a shopper taking an item off a convenience-store shelf without calling a clerk.",
    ),
    t(
      "Worker(Cloudflare 위에서 도는 작은 프로그램)는 wrangler.jsonc의 run_worker_first 26개 패턴에 맞는 요청만 먼저 받습니다. API·Socket.IO가 4개, 링크 미리보기(Open Graph)용 페이지가 16개, 25 MiB를 넘는 대형 파일이 6개입니다. Worker 안에서도 ① /api/health는 곧바로 답하고 ② 사람이 연 미리보기 페이지는 다시 정적 보관소로 돌려보내며 ③ 카카오톡 같은 크롤러일 때만 Core API에 메타태그 HTML을 요청하고 ④ 나머지 API는 용도별 7개 길(core, public-read, social, playground, admin, realtime, large-asset) 중 하나로만 보냅니다.",
      "The Worker (a small program running on Cloudflare) first receives only requests that match the 26 run_worker_first patterns in wrangler.jsonc: 4 for the API and Socket.IO, 16 for link-preview (Open Graph) pages and 6 for files over 25 MiB. Inside the Worker, (1) /api/health is answered on the spot, (2) a preview page opened by a person is handed back to static assets, (3) only a crawler such as KakaoTalk's makes the Core API render meta-tag HTML, and (4) every other API call goes to exactly one of seven routes: core, public-read, social, playground, admin, realtime or large-asset.",
    ),
    t(
      "대안은 모든 요청을 Worker 하나가 받아 프록시하는 방식입니다. 이러면 화면 파일 하나하나가 Worker 호출이 되어 무료 한도에 빨리 닿습니다. 직접 운영하는 리버스 프록시는 서버를 따로 관리해야 합니다. 정적 우선 구조는 Worker 호출과 잠든 Core API를 깨우는 일을 동적 경로로만 한정합니다. 25 MiB를 넘는 파일은 Static Assets에 올릴 수 없어 압축 사본, R2 저장소, (설정했을 때만) 지정 원본 순서로 내주고, 모두 비면 Core API를 깨우는 대신 503으로 닫습니다.",
      "One alternative is a single Worker that proxies every request, but then each screen file becomes a Worker invocation and the free allowance runs out quickly. A self-run reverse proxy means managing another server. The static-first layout limits Worker invocations and wake-ups of the sleeping Core API to dynamic paths. Files over 25 MiB cannot live in Static Assets, so they are served from a compressed copy, then R2, then (only if configured) a named origin, and if all are empty the gateway answers 503 instead of waking the Core API.",
    ),
    t(
      "한계도 분명합니다. 먼저-실행 목록은 사람이 관리하고, 목록을 넓히면 정적 트래픽이 곧바로 Worker 호출량이 됩니다. SPA 모드에서는 없는 파일도 index.html을 200으로 돌려주므로 sw.js 같은 필수 파일이 빠진 채 배포되는 사고를 배포 전 검증 스크립트가 따로 막아야 합니다. 이 설정이 실제 운영 대시보드에 반영된 상태는 저장소만으로 확인할 수 없습니다.",
      "The limits are real. The worker-first list is maintained by people, and widening it turns static traffic into Worker invocations. In SPA mode a missing file still returns index.html with status 200, so a separate pre-deploy check must stop releases that ship without a required file such as sw.js. And whether this configuration is what the production dashboard shows cannot be confirmed from the repository alone.",
    ),
  ],
  keyPoints: [
    t("정적 파일은 Worker를 실행하지 않고 곧장 응답", "Static files are served without running the Worker"),
    t("먼저-실행 패턴 26개: API 4 · 미리보기 16 · 대형 파일 6", "26 worker-first patterns: 4 API, 16 previews, 6 large files"),
    t("크롤러일 때만 Core API에 메타태그 HTML을 요청", "Only crawlers make the Core API render meta-tag HTML"),
    t("설정이 틀리면 몰래 우회하지 않고 503으로 닫음", "A bad setting closes with 503 instead of detouring silently"),
  ],
  diagram: {
    id: "static-first-edge-gateway-diagram",
    kind: "graph",
    title: t("요청이 Cloudflare 안에서 갈라지는 길", "How a request splits inside Cloudflare"),
    caption: t(
      "패턴에 걸리지 않는 요청은 Worker 없이 파일로 끝나고, 걸린 요청만 Worker가 하나의 길로 보냅니다.",
      "Requests that miss the patterns end as plain files; only matches reach the Worker, which picks one route.",
    ),
    alt: t(
      "브라우저의 요청은 먼저 26개 먼저-실행 패턴과 비교됩니다. 맞지 않으면 Static Assets가 파일을 바로 돌려줍니다. 맞으면 Worker가 받아 헬스 확인은 즉답하고, 사람이 연 미리보기는 Static Assets로 돌려보내며, 대형 파일은 압축 사본과 R2에서 내주고, API와 크롤러 요청은 오리진으로 전달합니다. 설정이 잘못되면 503으로 닫습니다.",
      "A browser request is first compared with the 26 worker-first patterns. If it does not match, Static Assets return the file directly. If it matches, the Worker answers health checks itself, sends human-opened previews back to Static Assets, serves large files from compressed copies and R2, and forwards API and crawler requests to the origin. A bad configuration closes with 503.",
    ),
    nodes: [
      { id: "browser", label: t("브라우저", "Browser"), tone: "local", shape: "pill", at: [0, 1] },
      { id: "gate", label: t("패턴 일치?", "Pattern match?"), sub: t("26개 패턴", "26 patterns"), tone: "neutral", shape: "diamond", at: [1, 1] },
      { id: "assets", label: t("Static Assets", "Static Assets"), sub: t("Worker 실행 없음", "No Worker run"), tone: "edge", at: [1, 0] },
      { id: "worker", label: t("Worker", "Worker"), sub: t("동적·크롤러·대형 파일", "Dynamic, crawler, large"), tone: "edge", at: [2, 1] },
      { id: "live", label: t("엣지 즉답", "Edge answer"), sub: t("/api/health/live", "/api/health/live"), tone: "edge", shape: "pill", at: [3, 0] },
      { id: "large", label: t("대형 파일", "Large files"), sub: t("압축 사본 → R2", "Compressed copy, R2"), tone: "edge", shape: "cylinder", at: [3, 2] },
      { id: "closed", label: t("503으로 닫기", "Close with 503"), sub: t("몰래 우회 안 함", "No silent detour"), tone: "warn", at: [2, 2] },
      { id: "origin", label: t("오리진", "Origin"), sub: t("Render Core API 등", "Render Core API, etc."), tone: "server", at: [4, 1] },
    ],
    edges: [
      { from: "browser", to: "gate" },
      { from: "gate", to: "assets", label: t("아니오", "no") },
      { from: "gate", to: "worker", label: t("예", "yes") },
      { from: "worker", to: "live", label: t("헬스", "health") },
      { from: "worker", to: "assets", style: "dashed", label: t("사람 탐색", "human") },
      { from: "worker", to: "large", label: t("대형", "large") },
      { from: "worker", to: "origin", label: t("API·봇", "API, bots") },
      { from: "worker", to: "closed", style: "dashed", label: t("설정 오류", "bad config") },
    ],
    groups: [
      {
        id: "edge",
        label: t("Cloudflare 엣지", "Cloudflare edge"),
        tone: "edge",
        nodeIds: ["gate", "assets", "worker", "live", "large", "closed"],
      },
    ],
  },
  usage: [
    {
      feature: t("홈·랭킹·스튜디오 화면 열기", "Opening Home, Ranking and Studio screens"),
      role: t(
        "화면 파일과 카탈로그 JSON을 Static Assets가 Worker 없이 응답합니다. 없는 경로는 SPA 모드로 index.html이 받습니다.",
        "Static Assets answer screen files and catalog JSON without the Worker. Unknown paths fall back to index.html in SPA mode.",
      ),
      paths: ["deploy/cloudflare-static/wrangler.jsonc", "deploy/cloudflare-static/src/index.ts#createCloudflareStaticGateway"],
      route: "/",
    },
    {
      feature: t("카카오톡·디스코드 링크 미리보기", "KakaoTalk and Discord link previews"),
      role: t(
        "알려진 크롤러 User-Agent일 때만 Core API의 /api/og에서 메타태그 HTML을 받고, 사람은 정적 화면을 받습니다.",
        "Only known crawler user agents get meta-tag HTML from the Core API's /api/og; people get the static screen.",
      ),
      paths: ["deploy/cloudflare-static/src/index.ts#isCrawlerRequest", "apps/api/src/modules/og/og-page.ts"],
      route: "/market",
    },
    {
      feature: t("스튜디오 첫 진입 · 대형 WASM/ONNX 다운로드", "First Studio visit · large WASM/ONNX downloads"),
      role: t(
        "25 MiB를 넘는 파일 6종은 압축 사본, R2, 지정 원본 순서로 내주며 Core API를 파일 서버로 깨우지 않습니다.",
        "Six files over 25 MiB are served from a compressed copy, then R2, then a named origin, and never wake the Core API as a file server.",
      ),
      paths: ["deploy/cloudflare-static/src/large-static-assets.ts", "scripts/prepare-cloudflare-static-assets.mts"],
      route: "/studio",
    },
    {
      feature: t("로그인·저장·커뮤니티 API 호출", "Sign-in, saving and community API calls"),
      role: t(
        "동적 요청은 일곱 갈래 중 한 곳으로만 전달하고, 설정이 잘못되면 core로 몰래 돌리지 않고 503으로 닫습니다.",
        "A dynamic request goes to exactly one of seven routes, and a bad setting closes with 503 instead of quietly falling back to core.",
      ),
      paths: ["deploy/cloudflare-static/src/index.ts#classifyDynamicRoute", "deploy/cloudflare-static/src/index.test.ts"],
    },
  ],
  samples: [
    {
      kind: "simplified",
      title: t("정적 우선 게이트웨이의 뼈대", "The skeleton of a static-first gateway"),
      language: "ts",
      code: [
        "// 실제 구현(deploy/cloudflare-static/src/index.ts)의 순서만 남긴 뼈대",
        "interface Env {",
        "  ASSETS: { fetch(request: Request): Promise<Response> };",
        "  CORE_API_ORIGIN: string; // 경로·쿼리가 없는 HTTPS 오리진",
        "}",
        "const CRAWLER = /bot|crawl|facebookexternalhit|kakaotalk|discord/iu;",
        "",
        "export default {",
        "  async fetch(request: Request, env: Env): Promise<Response> {",
        "    const url = new URL(request.url);",
        "    // ① 엣지 즉답: 잠든 오리진을 깨우지 않는다",
        '    if (url.pathname === "/api/health/live") {',
        '      return Response.json({ status: "ok" }, { headers: { "cache-control": "no-store" } });',
        "    }",
        '    const isApi = url.pathname.startsWith("/api/");',
        '    const isSharePage = url.pathname.startsWith("/title/");',
        '    const crawler = CRAWLER.test(request.headers.get("user-agent") ?? "");',
        "    // ② 정적 우선: API가 아니면 파일이 답한다. 공유 페이지도 사람이면 정적으로",
        "    if (!isApi && !(isSharePage && crawler)) return env.ASSETS.fetch(request);",
        "    // ③ 동적 요청만 오리진으로. 설정이 틀리면 몰래 우회하지 않고 닫는다",
        '    if (!env.CORE_API_ORIGIN.startsWith("https://")) return new Response("CORE_API_UNAVAILABLE", { status: 503 });',
        "    const upstream = new URL(url.pathname + url.search, env.CORE_API_ORIGIN);",
        '    return fetch(new Request(upstream, request), { redirect: "manual" });',
        "  },",
        "};",
      ].join("\n"),
      codeEn: [
        "// Only the order of the real implementation (deploy/cloudflare-static/src/index.ts) is kept",
        "interface Env {",
        "  ASSETS: { fetch(request: Request): Promise<Response> };",
        "  CORE_API_ORIGIN: string; // an HTTPS origin without path or query",
        "}",
        "const CRAWLER = /bot|crawl|facebookexternalhit|kakaotalk|discord/iu;",
        "",
        "export default {",
        "  async fetch(request: Request, env: Env): Promise<Response> {",
        "    const url = new URL(request.url);",
        "    // (1) Answer at the edge: do not wake a sleeping origin",
        '    if (url.pathname === "/api/health/live") {',
        '      return Response.json({ status: "ok" }, { headers: { "cache-control": "no-store" } });',
        "    }",
        '    const isApi = url.pathname.startsWith("/api/");',
        '    const isSharePage = url.pathname.startsWith("/title/");',
        '    const crawler = CRAWLER.test(request.headers.get("user-agent") ?? "");',
        "    // (2) Static first: files answer unless it is an API call or a crawler on a share page",
        "    if (!isApi && !(isSharePage && crawler)) return env.ASSETS.fetch(request);",
        "    // (3) Only dynamic requests reach the origin; a bad setting closes instead of detouring",
        '    if (!env.CORE_API_ORIGIN.startsWith("https://")) return new Response("CORE_API_UNAVAILABLE", { status: 503 });',
        "    const upstream = new URL(url.pathname + url.search, env.CORE_API_ORIGIN);",
        '    return fetch(new Request(upstream, request), { redirect: "manual" });',
        "  },",
        "};",
      ].join("\n"),
      explain: t(
        "순서가 정책입니다. 먼저 엣지에서 즉답하고, 그다음 정적 파일로 끝낼 수 있는 요청을 걸러 낸 뒤, 정말 동적인 요청만 오리진으로 보냅니다. 실제 코드는 여기에 7개 길 분류와 비밀 헤더가 더해집니다.",
        "The order is the policy: answer at the edge first, finish whatever static files can handle, and send only truly dynamic requests to the origin. The real code adds the seven-route classification and a secret header.",
      ),
      source: "deploy/cloudflare-static/src/index.ts",
      verify: "types",
    },
    {
      kind: "teaching",
      title: t("대형 파일의 폴백 사다리", "The fallback ladder for large files"),
      language: "ts",
      code: [
        "// 25 MiB 초과 파일: 압축 사본 → R2 → 지정 원본 → 503 (Core API는 깨우지 않는다)",
        "type Source = () => Promise<Response | null>;",
        "",
        "export async function serveLarge(sources: readonly Source[]): Promise<Response> {",
        "  for (const source of sources) {",
        "    try {",
        "      const response = await source();",
        "      if (response) return response; // 처음 답한 계층이 이긴다",
        "    } catch {",
        "      // 한 계층이 실패해도 다음 계층으로 넘어간다",
        "    }",
        "  }",
        '  return new Response(JSON.stringify({ error: "LARGE_ASSET_UNAVAILABLE" }), { status: 503 });',
        "}",
      ].join("\n"),
      codeEn: [
        "// Files over 25 MiB: compressed copy, R2, named origin, then 503 (never wake the Core API)",
        "type Source = () => Promise<Response | null>;",
        "",
        "export async function serveLarge(sources: readonly Source[]): Promise<Response> {",
        "  for (const source of sources) {",
        "    try {",
        "      const response = await source();",
        "      if (response) return response; // the first layer that answers wins",
        "    } catch {",
        "      // a failing layer falls through to the next one",
        "    }",
        "  }",
        '  return new Response(JSON.stringify({ error: "LARGE_ASSET_UNAVAILABLE" }), { status: 503 });',
        "}",
      ].join("\n"),
      explain: t(
        "각 계층은 '답할 수 없으면 null, 고장이면 예외'로 신호를 줍니다. 호출자는 위에서 아래로 시도하다가 모두 비면 명시적 503을 돌려줍니다.",
        "Each layer signals null when it has nothing and throws when it breaks. The caller tries them in order and returns an explicit 503 when every layer is empty.",
      ),
      verify: "types",
    },
  ],
  links: [
    {
      title: "Cloudflare · Workers Static Assets",
      url: "https://developers.cloudflare.com/workers/static-assets/",
      kind: "docs",
      note: t("정적 자산을 Worker 없이 내주는 방식의 공식 개요", "Official overview of serving assets without running a Worker"),
    },
    {
      title: "Cloudflare · Static Assets routing (run_worker_first)",
      url: "https://developers.cloudflare.com/workers/static-assets/routing/worker-script/",
      kind: "docs",
      note: t("어떤 요청을 Worker가 먼저 받을지 정하는 설정", "The setting that decides which requests reach the Worker first"),
    },
    {
      title: "Cloudflare · Static Assets billing and limitations",
      url: "https://developers.cloudflare.com/workers/static-assets/billing-and-limitations/",
      kind: "docs",
      note: t("파일 크기 한도 등 제한 사항", "Limits such as the per-file size cap"),
    },
    {
      title: "Cloudflare · R2 Workers API",
      url: "https://developers.cloudflare.com/r2/api/workers/workers-api-reference/",
      kind: "docs",
      note: t("대형 파일을 R2에서 Range로 읽는 API", "The API for reading large files from R2 with ranges"),
    },
  ],
  chapterIds: ["infrastructure", "cost-engineering"],
  talk: {
    pitch: t(
      "ToonStudio의 화면 파일은 미리 만들어 Cloudflare 정적 보관소에 두고, 방문자에게는 서버를 거치지 않고 그대로 내줍니다. 로그인이나 저장처럼 계산이 필요한 요청, 그리고 링크 미리보기를 만드는 로봇의 요청만 Worker가 먼저 받아 알맞은 서버로 보냅니다. 그래서 무료 플랜의 호출 한도와 서버를 깨우는 일을 꼭 필요한 곳에만 씁니다.",
      "ToonStudio builds its screen files ahead of time, keeps them in Cloudflare's static store and hands them to visitors without touching a server. Only requests that need computing, such as sign-in or saving, and the robots that build link previews reach the Worker first, which forwards them to the right server. That keeps the free plan's call allowance and server wake-ups for where they are really needed.",
    ),
    analogy: t(
      "화면 파일은 편의점 진열대, 동적 요청은 계산대 점원입니다. 물건만 집어 가는 손님은 점원을 부르지 않습니다.",
      "Screen files are the shelf of a convenience store and dynamic requests are the cashier. A shopper who only picks up an item never calls the cashier.",
    ),
    questions: [
      {
        question: t("Worker가 멈추면 사이트 전체가 멈추나요?", "If the Worker stops, does the whole site stop?"),
        answer: t(
          "정적 요청은 Worker를 거치지 않아 화면 파일 응답에는 영향이 없습니다. 영향을 받는 것은 Worker가 먼저 받는 26개 경로(API, 공유 미리보기, 대형 파일)입니다. README는 이 영역 라우트의 실패 모드를 fail-open이라고 적지만, 실제 동작은 Cloudflare 문서와 대시보드로 따로 확인해야 합니다.",
          "Static requests bypass the Worker, so screen files are unaffected. What can be affected are the 26 worker-first paths (API, share previews, large files). The README describes this zone route's failure mode as fail-open, but the real behavior needs to be checked against Cloudflare's documentation and the dashboard.",
        ),
      },
      {
        question: t("Render 무료 서버가 잠들어 있으면 화면은 어떻게 되나요?", "What does the user see while the free Render server is asleep?"),
        answer: t(
          "배포 빌드의 기본값이 정적 카탈로그(VITE_CATALOG_SOURCE=static)라서 홈·랭킹·검색 같은 목록은 정적 JSON과 브라우저 안 엔진으로 열립니다. 로그인·저장·커뮤니티처럼 서버가 필요한 기능만 깨어날 때까지 기다리거나 안내를 봅니다.",
          "The deployment build defaults to the static catalog (VITE_CATALOG_SOURCE=static), so lists such as Home, Ranking and Search open from static JSON and an in-browser engine. Only features that need the server, like sign-in, saving and community, wait for it to wake or show a notice.",
        ),
      },
      {
        question: t("왜 크롤러만 Core API를 부르나요?", "Why do only crawlers call the Core API?"),
        answer: t(
          "대부분의 링크 미리보기 로봇은 자바스크립트를 실행하지 않아 SPA 안의 메타태그를 읽지 못합니다. 그래서 알려진 User-Agent일 때만 Core API의 /api/og에서 작품별 메타태그 HTML을 받아 주고, 사람의 방문은 정적 보관소가 처리합니다.",
          "Most link-preview robots do not run JavaScript and cannot read meta tags inside an SPA. So only for known user agents does the gateway fetch per-page meta-tag HTML from the Core API's /api/og, while human visits are handled by the static store.",
        ),
      },
      {
        question: t("무료 한도는 몇 건인가요?", "How many requests does the free tier allow?"),
        answer: t(
          "Worker 호출 한도 숫자는 저장소에 기록된 값이 없어 말씀드리지 않겠습니다. 저장소 정책은 Workers를 '무료 허용량 안에서 앱 상한 80%'로 분류하고 자동 유료 전환을 금지합니다(config/free-infrastructure-policy.json). 정확한 한도는 공식 가격표와 대시보드로 확인해야 합니다.",
          "The repository records no number for the Worker call allowance, so I will not quote one. The policy classifies Workers as a free allowance with an 80% application cap and forbids automatic paid failover (config/free-infrastructure-policy.json). The exact limit must be checked on the official pricing page and the dashboard.",
        ),
      },
    ],
    pitfall: t(
      "'정적 요청은 Worker를 실행하지 않는다'에는 예외가 있습니다. 먼저-실행 26개 패턴에 걸리는 요청, 특히 링크 미리보기 크롤러와 대형 파일은 Worker를 탑니다. 이 카드는 코드와 설정만 확인했고 운영 대시보드의 실제 상태와 사용량은 확인하지 않았습니다.",
      "'Static requests never run the Worker' has exceptions: requests that match the 26 worker-first patterns, notably link-preview crawlers and large files, do run it. This card checked code and configuration only; the real dashboard state and usage were not checked.",
    ),
  },
  technologies: ["Cloudflare Static Assets", "Cloudflare Workers", "Cloudflare", "Render", "Open Graph"],
  facts: [
    {
      value: "26",
      label: t("Worker가 먼저 받는 경로 패턴 수(테스트가 목록을 고정)", "Worker-first path patterns (a test pins the list)"),
      source: "deploy/cloudflare-static/wrangler.jsonc",
    },
    {
      value: "25 MiB",
      label: t("Static Assets 개별 파일 한도(코드 상수)", "Per-file limit for Static Assets (code constant)"),
      source: "deploy/cloudflare-static/src/large-static-assets.ts",
    },
    {
      value: "6",
      label: t("별도 경로로 내주는 대형 파일 패턴", "Large-file patterns served through the separate path"),
      source: "deploy/cloudflare-static/src/large-static-assets.ts",
    },
  ],
  reviewedAt: "2026-10-07",
};

const MANUAL_SHA_RELEASE_GATE: EngineeringAtlasEntry = {
  id: "manual-sha-release-gate",
  category: "platform-ops",
  name: "Manual SHA release gate",
  title: t("머지는 배포가 아니다: 승인한 커밋 하나만 손으로 올립니다", "Merging is not releasing: one approved commit, shipped by hand"),
  status: "live",
  tagline: t(
    "배포는 사람이 승인한 40자리 커밋 하나만, 워크플로의 배포 명령은 코드로 검사합니다.",
    "Only one human-approved 40-character commit ships, and workflow deploy commands are flagged by a code check.",
  ),
  background: [
    t(
      "코드를 합치는 일(머지)과 사용자에게 내보내는 일(배포)을 한 버튼에 묶으면, 검토가 덜 끝난 코드나 유료 자원을 켜는 설정이 한꺼번에 나갈 수 있습니다. ToonStudio는 둘을 떼어 놓았습니다. Render 서비스는 autoDeployTrigger를 끈 상태라 push만으로는 운영이 바뀌지 않고, Cloudflare 정적 웹은 사람이 승인한 커밋 번호(SHA, 코드 버전의 40자리 지문) 하나만 배포 스크립트가 받아 줍니다.",
      "Tying merging code (merge) and shipping it to users (release) to one button can send half-reviewed code or a paid-resource setting out together. ToonStudio keeps them apart. The Render services have autoDeployTrigger turned off, so a push alone changes nothing in production, and the Cloudflare static site accepts only one human-approved commit number (a SHA, a 40-character fingerprint of a code version) in the release script.",
    ),
    t(
      "프로덕션 모드의 배포 스크립트는 다섯 문턱을 모두 넘어야 wrangler 배포까지 갑니다. ① 승인 문구 환경변수가 정해진 값인가 ② 승인 SHA가 소문자 40자리인가 ③ 현재 브랜치가 main인가 ④ 작업 폴더에 커밋되지 않은 변경이 없는가 ⑤ 지금 HEAD가 승인 SHA와 정확히 같은가. 원격에 쓰지 않는 dry-run 모드는 번들과 설정만 검사합니다.",
      "In production mode the release script must clear five hurdles before it reaches the wrangler deploy: (1) the approval-phrase environment variable has the expected value, (2) the approved SHA is 40 lowercase hex characters, (3) the current branch is main, (4) the working folder has no uncommitted changes, and (5) HEAD equals the approved SHA exactly. The dry-run mode, which writes nothing remote, only checks the bundle and settings.",
    ),
    t(
      "사람의 약속에만 기대지 않으려고 '배포 금지'도 코드로 검사합니다. 정책 스캐너가 .github/workflows의 모든 파일을 읽어 run: 안의 셸 명령을 단어 단위로 풀고, 주석·echo·heredoc 속 글은 건너뛴 채 실제 실행 위치의 wrangler 배포나 Render 배포 요청이 있으면 검사를 실패시킵니다. 트리거, 환경 승인, 수동 실행 어느 것도 예외가 되지 않습니다.",
      "To avoid relying on human promises, even the ban on deploying is checked by code. A policy scanner reads every file in .github/workflows, splits each run: command into shell words, skips text in comments, echo and heredocs, and fails the check whenever a wrangler deploy or a Render deploy request sits in an executable position. No trigger, environment approval or manual dispatch counts as an exemption.",
    ),
    t(
      "대안은 GitHub Environments의 승인 검토자와 자동 배포, 또는 Argo CD 같은 GitOps입니다. 이 프로젝트는 속도를 일부 내주고 비용과 검토 통제를 택했습니다. 대신 수동 절차가 병목이 될 수 있고, 스크립트가 보장하는 것은 '내 컴퓨터의 HEAD가 승인 SHA와 같다'까지라 승인한 사람이 누구인지는 별도 기록과 리뷰로 남겨야 합니다.",
      "Alternatives are GitHub Environments with required reviewers plus automatic deploys, or GitOps tools such as Argo CD. This project gave up some speed for cost and review control. The price is that a manual step can become a bottleneck, and the script only guarantees that 'HEAD on my machine equals the approved SHA', so who approved it must be kept in separate records and reviews.",
    ),
  ],
  keyPoints: [
    t("머지와 배포를 분리: push로는 운영이 바뀌지 않음", "Merge and release are separate: a push changes nothing live"),
    t("승인 SHA 40자리 · main · 깨끗한 작업 폴더 · HEAD 일치", "Approved 40-char SHA, main, clean tree, HEAD must match"),
    t("정책 스캐너가 워크플로 안의 배포 명령을 실패 처리(배포 전 점검)", "A policy scanner fails any deploy command in a workflow (pre-release check)"),
    t("롤백은 직전 검증 SHA를 다시 수동 배포", "Rollback means redeploying the previous verified SHA by hand"),
  ],
  diagram: {
    id: "manual-sha-release-gate-diagram",
    kind: "sequence",
    title: t("승인된 SHA가 운영에 오르는 순서", "How an approved SHA reaches production"),
    caption: t(
      "병합은 배포가 아니고, 스크립트가 HEAD와 승인 SHA의 일치를 확인한 뒤에야 원격에 씁니다.",
      "Merging is not releasing; the script writes remotely only after HEAD matches the approved SHA.",
    ),
    alt: t(
      "사람이 검토한 커밋을 main에 병합하는 것까지는 배포가 아닙니다. 정책 스캐너는 워크플로 안에 배포 명령이 있는지 따로 검사합니다(배포 전 점검과 수동 readiness 워크플로에서 실행). 배포할 때는 사람이 승인 문구와 40자리 SHA를 스크립트에 주고, 스크립트가 브랜치와 작업 폴더와 HEAD를 확인한 뒤 Cloudflare에 그 SHA만 배포합니다. 문제가 생기면 직전 검증 SHA로 다시 수동 배포합니다.",
      "Merging a reviewed commit into main is not a release. A policy scanner, run by the pre-release check and the manual readiness workflow, separately checks that no workflow contains a deploy command. To release, a person gives the script the approval phrase and a 40-character SHA, the script checks the branch, working folder and HEAD, and only then deploys that SHA to Cloudflare. If something goes wrong, the previous verified SHA is redeployed by hand.",
    ),
    actors: [
      { id: "ci", label: t("정책 스캐너", "Policy scanner"), sub: t("워크플로 전체 검사", "Scans every workflow"), tone: "good" },
      { id: "git", label: t("Git 저장소", "Git repo"), sub: t("main · HEAD", "main, HEAD"), tone: "neutral" },
      { id: "human", label: t("승인자(사람)", "Approver"), sub: t("검토·SHA 지정", "Reviews, names the SHA"), tone: "warn" },
      { id: "script", label: t("배포 스크립트", "Release script"), sub: t("5중 문턱", "Five hurdles"), tone: "neutral" },
      { id: "edge", label: t("Cloudflare", "Cloudflare"), sub: t("Assets + Worker", "Assets + Worker"), tone: "edge" },
    ],
    messages: [
      { from: "human", to: "git", label: t("검토한 커밋을 main에 병합", "Merge the reviewed commit"), note: t("여기까지는 배포가 아님", "Not a release yet") },
      { from: "ci", to: "git", label: t("워크플로 명령을 정적 검사", "Scan workflow commands"), note: t("배포 명령이 있으면 검사 실패", "Any deploy command fails the check") },
      { from: "human", to: "script", label: t("승인 문구 + 40자리 SHA", "Approval phrase + 40-char SHA"), note: t("환경변수로 전달", "Passed as environment variables") },
      { from: "script", to: "git", label: t("main? 변경 없음? HEAD?", "main? clean? HEAD?"), note: t("문턱 3~5번을 확인", "Checks hurdles 3 to 5") },
      { from: "git", to: "script", label: t("현재 HEAD 값", "Current HEAD value"), style: "dashed", note: t("승인 SHA와 같아야 통과", "Must equal the approved SHA") },
      { from: "script", to: "edge", label: t("wrangler로 이 SHA만 배포", "Deploy only this SHA"), note: t("원격 쓰기는 여기가 처음", "First remote write happens here") },
      { from: "edge", to: "human", label: t("배포 결과 확인", "Check the result"), style: "dashed" },
      { from: "human", to: "script", label: t("문제 시 직전 SHA로 재배포", "If broken, redeploy previous SHA"), note: t("수동 재배포", "A manual redeploy") },
    ],
  },
  usage: [
    {
      feature: t("정적 웹 수동 배포 (Cloudflare Static Assets + Worker)", "Manual static-site release (Cloudflare Static Assets + Worker)"),
      role: t(
        "프로덕션 모드에서만 다섯 문턱을 검사하고, 통과한 SHA만 wrangler로 올립니다. dry-run은 번들과 변수만 검사합니다.",
        "Only in production mode does it check the five hurdles and ship the SHA that passes through wrangler. The dry run only checks the bundle and variables.",
      ),
      paths: ["scripts/deploy-cloudflare-static.mjs", "deploy/cloudflare-static/README.md"],
    },
    {
      feature: t("Core API 수동 릴리스 (Render)", "Manual Core API release (Render)"),
      role: t(
        "render.yaml에서 autoDeployTrigger를 끄고 플랫폼 헬스체크를 /api/health/live로 고정해 push가 곧 권위 전환이 되지 않게 합니다.",
        "render.yaml turns autoDeployTrigger off and pins the platform health check to /api/health/live, so a push never switches authority.",
      ),
      paths: ["render.yaml", "AGENTS.md"],
    },
    {
      feature: t("배포 금지 정책 검사 (verify:free-infrastructure)", "Deploy-ban policy check (verify:free-infrastructure)"),
      role: t(
        "워크플로를 정적으로 읽어 wrangler 배포나 Render 배포 요청이 나오면 실패시키고, 되살아난 퇴역 인프라 파일도 막습니다. 배포 전 점검과 수동 readiness 워크플로가 실행하며 코어 CI 잡에는 없습니다.",
        "It reads workflows statically, fails on any wrangler deploy or Render deploy request, and also blocks retired infrastructure files that come back. The pre-release check and the manual readiness workflow run it; the core CI jobs do not.",
      ),
      paths: [
        "scripts/release-workflow-policy.mjs#validateReleaseWorkflows",
        "scripts/free-infrastructure-policy.mjs",
        "config/free-infrastructure-policy.json",
      ],
    },
  ],
  samples: [
    {
      kind: "simplified",
      title: t("승인 SHA와 HEAD가 같을 때만 통과", "Pass only when HEAD equals the approved SHA"),
      language: "ts",
      code: [
        "// git 호출을 주입받아 5중 문턱 중 SHA·브랜치·작업 폴더·HEAD를 검사한다",
        "type Git = (...args: string[]) => string;",
        "",
        "export function assertReleasable(approvedSha: string | undefined, git: Git): void {",
        "  if (!approvedSha || !/^[0-9a-f]{40}$/u.test(approvedSha)) {",
        '    throw new Error("소문자 40자리 SHA가 필요합니다");',
        "  }",
        '  const branch = git("branch", "--show-current");',
        '  if (branch !== "main") throw new Error(`main에서만 배포합니다(현재: ${branch || "detached"})`);',
        '  if (git("status", "--porcelain") !== "") throw new Error("작업 폴더가 깨끗해야 합니다");',
        '  if (git("rev-parse", "HEAD") !== approvedSha) throw new Error("HEAD가 승인 SHA와 다릅니다");',
        "}",
        "",
        "// 사용: assertReleasable(sha, (...a) => execFileSync(\"git\", a, { encoding: \"utf8\" }).trim());",
      ].join("\n"),
      codeEn: [
        "// git is injected; this checks the SHA, branch, working folder and HEAD hurdles",
        "type Git = (...args: string[]) => string;",
        "",
        "export function assertReleasable(approvedSha: string | undefined, git: Git): void {",
        "  if (!approvedSha || !/^[0-9a-f]{40}$/u.test(approvedSha)) {",
        '    throw new Error("a lowercase 40-character SHA is required");',
        "  }",
        '  const branch = git("branch", "--show-current");',
        '  if (branch !== "main") throw new Error(`releases only from main (current: ${branch || "detached"})`);',
        '  if (git("status", "--porcelain") !== "") throw new Error("the working folder must be clean");',
        '  if (git("rev-parse", "HEAD") !== approvedSha) throw new Error("HEAD differs from the approved SHA");',
        "}",
        "",
        "// usage: assertReleasable(sha, (...a) => execFileSync(\"git\", a, { encoding: \"utf8\" }).trim());",
      ].join("\n"),
      explain: t(
        "실제 스크립트는 같은 검사를 인라인으로 하고 승인 문구 환경변수까지 확인합니다. git 호출을 인자로 받으면 시험에서 가짜 git을 꽂아 모든 실패 경로를 확인할 수 있습니다.",
        "The real script performs the same checks inline and also verifies the approval-phrase variable. Taking git as a parameter lets a test plug in a fake git and exercise every failure path.",
      ),
      source: "scripts/deploy-cloudflare-static.mjs",
      verify: "types",
    },
    {
      kind: "teaching",
      title: t("글이 아니라 실행 위치에서 배포 명령 찾기", "Finding a deploy command by position, not by prose"),
      language: "ts",
      code: [
        "// 주석·echo 같은 '글'은 건너뛰고 실제 실행 위치의 wrangler 배포만 찾는다(단순화)",
        'const PROSE = new Set(["echo", "printf", "grep", "cat"]);',
        'const PUBLISHING = new Set(["deploy", "publish", "rollback"]);',
        "",
        "export function publishesToCloudflare(commandLine: string): boolean {",
        "  const [executable = \"\", subcommand = \"\", ...rest] = commandLine.trim().split(/\\s+/u);",
        "  if (PROSE.has(executable)) return false; // 따옴표 속 예시는 배포가 아니다",
        '  if (executable !== "wrangler") return false;',
        '  const dryRun = rest.includes("--dry-run");',
        "  return PUBLISHING.has(subcommand) && !dryRun;",
        "}",
        "",
        '// publishesToCloudflare("echo wrangler deploy") === false',
        '// publishesToCloudflare("wrangler deploy") === true',
      ].join("\n"),
      codeEn: [
        "// Skip prose such as comments and echo; find only wrangler deploys in executable position (simplified)",
        'const PROSE = new Set(["echo", "printf", "grep", "cat"]);',
        'const PUBLISHING = new Set(["deploy", "publish", "rollback"]);',
        "",
        "export function publishesToCloudflare(commandLine: string): boolean {",
        "  const [executable = \"\", subcommand = \"\", ...rest] = commandLine.trim().split(/\\s+/u);",
        "  if (PROSE.has(executable)) return false; // an example in quotes is not a deploy",
        '  if (executable !== "wrangler") return false;',
        '  const dryRun = rest.includes("--dry-run");',
        "  return PUBLISHING.has(subcommand) && !dryRun;",
        "}",
        "",
        '// publishesToCloudflare("echo wrangler deploy") === false',
        '// publishesToCloudflare("wrangler deploy") === true',
      ].join("\n"),
      explain: t(
        "실제 스캐너는 따옴표·heredoc·pnpm 스크립트 재귀까지 해석합니다. 여기서는 '문장 속 단어와 실행되는 명령은 다르다'는 핵심 아이디어만 남겼습니다.",
        "The real scanner also handles quotes, heredocs and recursion into pnpm scripts. This keeps only the core idea that a word in a sentence is not an executed command.",
      ),
      verify: "types",
    },
  ],
  links: [
    {
      title: "Cloudflare · Wrangler commands",
      url: "https://developers.cloudflare.com/workers/wrangler/commands/",
      kind: "docs",
      note: t("deploy·versions·rollback 명령의 공식 설명", "Official reference for deploy, versions and rollback"),
    },
    {
      title: "Render · Deploys",
      url: "https://render.com/docs/deploys",
      kind: "docs",
      note: t("자동 배포를 끄는 방법과 배포 동작", "How auto-deploy is turned off and how deploys behave"),
    },
    {
      title: "Render · Blueprint spec",
      url: "https://render.com/docs/blueprint-spec",
      kind: "spec",
      note: t("render.yaml 필드의 정의", "Definition of the render.yaml fields"),
    },
    {
      title: "GitHub Docs · Managing environments for deployment",
      url: "https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/manage-environments",
      kind: "guide",
      note: t("대안: 승인 검토자를 두는 자동 배포 방식", "An alternative: automated deploys with required reviewers"),
    },
  ],
  chapterIds: ["delivery", "cost-engineering"],
  talk: {
    pitch: t(
      "ToonStudio에서는 코드를 합치는 일과 서비스에 올리는 일이 다릅니다. 올릴 때는 사람이 승인한 커밋 번호 하나만 배포 스크립트에 넘기고, 스크립트는 main 브랜치인지, 작업 폴더가 깨끗한지, 지금 코드가 그 번호와 같은지를 모두 확인합니다. 그리고 정책 스캐너가 워크플로 안에 배포 명령이 숨어 있으면 실패시켜서, '자동 배포 금지'를 약속이 아니라 코드로 점검합니다. 이 스캐너는 배포 전 점검(verify:free-infrastructure)과 수동 readiness 워크플로에서 돕니다.",
      "At ToonStudio, merging code and shipping it are different acts. To ship, a person passes one approved commit number to the release script, which checks that the branch is main, the working folder is clean and the code equals that number. A policy scanner also fails any workflow that hides a deploy command, so 'no automatic deploys' is checked by code, not by promise; it runs in the pre-release check (verify:free-infrastructure) and the manual readiness workflow.",
    ),
    analogy: t(
      "비행기 출발 직전 체크리스트와 같습니다. 기장이 서명한 승인서(SHA)와 실제 기체(HEAD)가 일치해야만 활주로로 나갑니다.",
      "It is like a pre-departure checklist: the plane taxis out only when the captain's signed approval (the SHA) matches the actual aircraft (HEAD).",
    ),
    questions: [
      {
        question: t("수동 배포가 병목 아닌가요?", "Isn't manual release a bottleneck?"),
        answer: t(
          "의도한 트레이드오프입니다. 무료 플랜 중심 운영에서 push 한 번으로 권위나 비용이 바뀌지 않게 하려고 속도를 일부 포기했습니다. 정적 웹은 수동 배포, Core API는 Render 수동 릴리스만 쓴다고 AGENTS.md에 적혀 있습니다.",
          "It is a deliberate trade-off. In a free-plan setup, some speed is given up so that a single push cannot change authority or cost. AGENTS.md states that the static site is released by hand and the Core API only through manual Render releases.",
        ),
      },
      {
        question: t("승인한 사람이 진짜인지는 어떻게 아나요?", "How do you know the approver is genuine?"),
        answer: t(
          "스크립트가 확인하는 것은 승인 문구와 SHA가 일치하는지까지입니다. 누가 승인했는지는 코드로 증명하지 않으므로 리뷰와 운영 기록이 따로 필요합니다.",
          "The script checks that the approval phrase is set and the SHA matches. It does not prove who approved, so review and operations records are needed separately.",
        ),
      },
      {
        question: t("배포가 잘못되면 어떻게 되돌리나요?", "How do you roll back a bad release?"),
        answer: t(
          "정적 웹은 직전 검증 SHA를 같은 절차로 다시 수동 배포합니다(deploy/cloudflare-static/README.md). 새 DB 권위에 쓰기가 시작된 뒤에는 원장을 자동으로 되돌리지 않는다는 규칙도 docs/FREE_INFRASTRUCTURE.md에 있습니다.",
          "The static site is rolled back by redeploying the previous verified SHA through the same procedure (deploy/cloudflare-static/README.md). docs/FREE_INFRASTRUCTURE.md also says the ledger is not reverted automatically once writes to a new database authority have started.",
        ),
      },
    ],
    pitfall: t(
      "이 카드는 게이트 코드와 정책을 설명할 뿐, 운영 대시보드에 지금 올라가 있는 SHA는 확인하지 않았습니다. Render는 render.yaml 이 소스 빌드(node 런타임)로 선언돼 있지만, 2026-10-08 Render API 읽기 전용 조회에서 운영 서비스(toonspectrum-core-api)는 SHA 태그 컨테이너 이미지(수동 워크플로 api-container-release.yml)를 api 트리거로 배포 중임을 확인했습니다(서비스 설정 전체를 본 것은 아닙니다).",
      "This card explains the gate code and policy; it did not check which SHA is live on the dashboards. render.yaml declares a source build (the node runtime), but a read-only Render API query on 2026-10-08 showed the production service (toonspectrum-core-api) running a SHA-tagged container image (the manual api-container-release.yml workflow) deployed via the api trigger; this is not a view of the full service settings.",
    ),
  },
  technologies: ["Cloudflare Workers", "Render", "GitHub Actions", "Wrangler"],
  facts: [
    {
      value: "40",
      label: t("승인 SHA의 길이(소문자 16진수)", "Length of the approved SHA (lowercase hex)"),
      source: "scripts/deploy-cloudflare-static.mjs",
    },
    {
      value: "98",
      label: t("정책 스캐너가 읽는 워크플로 파일 수(작성 시점)", "Workflow files the policy scanner reads (at writing time)"),
      source: ".github/workflows",
    },
  ],
  reviewedAt: "2026-10-07",
};

const HEALTH_LIVE_READY_CAPABILITIES: EngineeringAtlasEntry = {
  id: "health-live-ready-capabilities",
  category: "platform-ops",
  name: "Health checks: live, ready, capabilities",
  title: t("잠든 서버와 고장 난 서버를 구분하는 헬스체크 3단", "Three health tiers that tell a sleeping server from a broken one"),
  status: "live",
  tagline: t(
    "live는 DB를 깨우지 않고, ready는 배포 점검에서, capabilities는 기능별 상태를 말합니다.",
    "live never wakes the database, ready serves release checks, capabilities reports per-feature state.",
  ),
  background: [
    t(
      "무료 서버는 한동안 요청이 없으면 잠들었다가 다음 요청에 깨어나며, 이때 첫 응답이 늦습니다. 이 지연을 '고장'으로 보여 주면 사용자가 불안해하고, 정말 고장 났는데 괜찮다고 답하면 운영자가 놓칩니다. 그래서 점검을 세 단으로 나눴습니다. 가게 문이 열렸는지(live), 계산대와 금고까지 준비됐는지(ready), 지금 어느 코너를 쓸 수 있는지(capabilities)입니다.",
      "A free server falls asleep after a while without requests and wakes on the next one, so the first reply is slow. Showing that delay as a 'failure' alarms users, while answering 'fine' during a real failure lets operators miss it. So checks come in three tiers: is the shop door open (live), are the register and safe ready too (ready), and which counters can be used now (capabilities).",
    ),
    t(
      "live는 아무것도 확인하지 않고 {status: 'ok'}만 답합니다(DB·스키마·소켓·외부 서비스 의존 없음). Render 플랫폼 점검이 이 경로만 쓰고, Cloudflare 엣지도 /api/health와 /api/health/live에는 서버를 거치지 않고 직접 답합니다. ready는 DB 연결, 스키마 구조(필수 릴레이션 199개), 실시간 어댑터, 객체 저장소, 조정 저장소, 작업 큐 실행기를 모두 확인하고 하나라도 안 되면 503 SERVICE_NOT_READY를 돌려줍니다. 성공한 결과만 5초 캐시하고 실패는 매번 다시 확인합니다.",
      "live checks nothing and only answers {status: 'ok'} (no database, schema, socket or external-service dependency). Render's platform check uses only this path, and the Cloudflare edge answers /api/health and /api/health/live itself without reaching the server. ready verifies the database connection, the schema structure (199 required relations), the realtime adapter, object storage, the coordination store and the job-queue executor, and returns 503 SERVICE_NOT_READY if any fails. Only a success is cached, for 5 seconds; failures are rechecked every time.",
    ),
    t(
      "capabilities는 ready 결과를 11개 기능의 available·degraded·unavailable로 번역합니다. DB가 죽어도 공개 카탈로그와 스튜디오 로컬 편집은 늘 available이라, 로컬 우선 원칙이 API 계약에 박혀 있습니다. 브라우저는 이 경로를 60초마다 확인하고, 페이지를 연 지 90초 안에 한 번도 성공하지 못한 채 응답이 늦거나 502·503·504가 오면 장애 대신 '연결 준비 중'으로 분류해 6초마다 다시 확인합니다. Retry-After를 실은 503처럼 서버가 일부러 보낸 오류는 진짜 기능 저하로 봅니다.",
      "capabilities translates the ready result into available, degraded or unavailable for 11 features. Even when the database is down, the public catalog and local Studio editing stay available, so the local-first principle is written into the API contract. The browser checks this path every 60 seconds; if nothing has succeeded within 90 seconds of opening the page and replies are slow or 502, 503 or 504 arrive, it shows 'connecting' instead of an outage and rechecks every 6 seconds. An error the server sends on purpose, such as a 503 carrying Retry-After, counts as real degradation.",
    ),
    t(
      "대안은 외부 핑으로 서버를 항상 깨워 두는 방법인데, DEPLOY.md에는 무료 인스턴스에 월 사용 시간 한도가 있다고 적혀 있어 그 시간을 소모합니다. 한계도 있습니다. live만 DB를 깨우지 않습니다. capabilities는 안에서 ready 점검을 그대로 호출하므로, 탭이 열려 있는 동안 브라우저가 60초마다 DB 점검을 일으킵니다(성공 결과는 5초 캐시). '헬스체크가 DB를 깨우지 않는다'는 말은 live에만 해당합니다.",
      "One alternative is pinging the server from outside to keep it awake, but DEPLOY.md records a monthly usage-hours cap for free instances, which that would burn. There is a limit too: only live leaves the database alone. capabilities calls the ready check inside, so while a tab is open the browser triggers a database check every 60 seconds (a success is cached for 5 seconds). 'Health checks do not wake the database' is true only for live.",
    ),
  ],
  keyPoints: [
    t("live: 의존성 0, DB를 깨우지 않는 생존 확인", "live: zero dependencies, a liveness check that spares the DB"),
    t("ready: DB·스키마·저장소까지 점검, 실패는 503", "ready: checks DB, schema and storage; failure is 503"),
    t("capabilities: 기능 11개를 available·degraded·unavailable로", "capabilities: 11 features as available, degraded or unavailable"),
    t("첫 90초의 지연은 장애가 아닌 '연결 준비 중'으로 표시", "Slowness in the first 90 s reads as 'connecting', not an outage"),
  ],
  diagram: {
    id: "health-live-ready-capabilities-diagram",
    kind: "layers",
    title: t("헬스체크 3단과 브라우저의 해석", "Three health tiers and how the browser reads them"),
    caption: t(
      "아래로 갈수록 더 많은 것을 확인하고, 브라우저는 느린 응답을 장애가 아닌 준비 중으로 해석합니다.",
      "Each lower tier checks more, and the browser reads a slow reply as warming up rather than an outage.",
    ),
    alt: t(
      "맨 위 live는 의존성 없이 생존만 확인하며 Render 점검과 엣지가 씁니다. 다음 ready는 DB와 스키마와 저장소까지 확인해 실패하면 503을 냅니다. capabilities는 ready 결과를 기능 11개의 상태로 바꿔 브라우저에 줍니다. 브라우저는 처음 90초 안의 느린 응답과 게이트웨이 오류를 장애가 아니라 연결 준비 중으로 표시합니다.",
      "At the top, live checks only that the process is alive, with no dependencies, and is used by Render and the edge. ready also checks the database, schema and storage and answers 503 on failure. capabilities turns the ready result into the state of 11 features for the browser. The browser shows slow replies and gateway errors in the first 90 seconds as connecting, not as an outage.",
    ),
    layers: [
      {
        id: "live",
        label: t("live · 살아 있나?", "live: is it up?"),
        sub: t("의존성 0. Render 점검과 엣지 즉답이 쓰며 DB를 깨우지 않음", "No dependencies. Used by Render and the edge; never wakes the DB"),
        tone: "edge",
        chips: ["Cloudflare Workers", "Render"],
      },
      {
        id: "ready",
        label: t("ready · 준비됐나?", "ready: is it prepared?"),
        sub: t("DB·스키마·저장소 점검. 실패는 503, 성공만 5초 캐시", "Checks DB, schema and storage. Failure is 503; success cached 5 s"),
        tone: "server",
        chips: ["PostgreSQL", "Upstash Redis"],
      },
      {
        id: "capabilities",
        label: t("capabilities · 무엇을 쓰나?", "capabilities: what works?"),
        sub: t("ready 결과를 기능 11개의 상태로 번역해 브라우저에 전달", "Turns ready into the state of 11 features for the browser"),
        tone: "server",
        chips: ["NestJS"],
      },
      {
        id: "browser",
        label: t("브라우저 · 연결 준비 중 안내", "Browser: connecting notice"),
        sub: t("첫 90초의 지연과 502·503·504는 장애 대신 준비 중으로 표시", "Slow replies and 502/503/504 in the first 90 s read as warming up"),
        tone: "local",
      },
    ],
    brackets: [
      { label: t("서버 API가 답하는 3단", "Three tiers the API answers"), layerIds: ["live", "ready", "capabilities"] },
    ],
  },
  usage: [
    {
      feature: t("서버 연결 준비 중 안내 (무료 서버가 깨는 첫 구간)", "Connecting notice (the first stretch while the free server wakes)"),
      role: t(
        "60초마다 capabilities를 확인하고, 첫 90초 안의 지연·게이트웨이 오류는 장애 배너 대신 연결 준비 안내로 보여 줍니다.",
        "Checks capabilities every 60 seconds and shows slow replies and gateway errors in the first 90 seconds as a connecting notice instead of an outage banner.",
      ),
      paths: [
        "apps/web/src/platform/service-capability-state.ts",
        "apps/web/src/app/service-state/ServiceDegradedBanner.tsx",
      ],
      route: "/",
    },
    {
      feature: t("기능별 상태 배지 (커뮤니티·마켓·클라우드 저장·협업·AI)", "Per-feature status (community, market, cloud save, collaboration, AI)"),
      role: t(
        "ready 결과를 11개 기능으로 번역해 어느 기능만 쓸 수 없는지 알려 줍니다. 스튜디오 로컬 편집은 늘 available입니다.",
        "Translates the ready result into 11 features so users learn which ones are unavailable. Local Studio editing is always available.",
      ),
      paths: [
        "apps/api/src/modules/health/health.service.ts#checkCapabilities",
        "apps/api/src/modules/health/health.controller.ts",
      ],
    },
    {
      feature: t("Render 플랫폼 점검과 엣지 즉답", "Render's platform check and the edge answer"),
      role: t(
        "Render는 /api/health/live만 호출하고, Cloudflare Worker는 같은 경로에 서버를 거치지 않고 답합니다.",
        "Render calls only /api/health/live, and the Cloudflare Worker answers the same path without reaching the server.",
      ),
      paths: ["render.yaml", "deploy/cloudflare-static/src/index.ts#edgeLivenessResponse"],
    },
    {
      feature: t("배포 후 점검 (릴리스 게이트)", "Post-release check (release gate)"),
      role: t(
        "live를 먼저, ready를 다음으로 호출하고 리다이렉트와 응답 형식 이탈을 실패로 처리합니다.",
        "Calls live first and ready next, and fails on redirects or a response outside the expected contract.",
      ),
      paths: ["scripts/verify-render-core-origin.mjs", "apps/api/src/modules/health/health-readiness.repository.ts"],
    },
  ],
  samples: [
    {
      kind: "simplified",
      title: t("live는 비워 두고, ready는 모두 확인하고, capabilities는 번역하기", "Empty live, thorough ready, translating capabilities"),
      language: "ts",
      code: [
        "type Check = () => Promise<boolean>;",
        'type CapabilityState = "available" | "unavailable";',
        "",
        "export function createHealth(checks: { database: Check; objectStorage: Check }) {",
        "  const ready = async () => {",
        "    const [database, objectStorage] = await Promise.all([",
        "      checks.database().catch(() => false),",
        "      checks.objectStorage().catch(() => false),",
        "    ]);",
        "    return { ready: database && objectStorage, database, objectStorage };",
        "  };",
        "  return {",
        '    live: () => ({ status: "ok" as const }), // 의존성 0: 프로세스가 답하면 충분하다',
        "    ready, // 배포 후 점검에서 부른다",
        "    capabilities: async () => {",
        "      const report = await ready();",
        '      const state = (ok: boolean): CapabilityState => (ok ? "available" : "unavailable");',
        "      return {",
        '        publicCatalog: "available" as CapabilityState, // DB가 죽어도 정적 카탈로그는 열린다',
        "        communityWrite: state(report.database),",
        "        studioCloudSave: state(report.database && report.objectStorage),",
        "      };",
        "    },",
        "  };",
        "}",
      ].join("\n"),
      codeEn: [
        "type Check = () => Promise<boolean>;",
        'type CapabilityState = "available" | "unavailable";',
        "",
        "export function createHealth(checks: { database: Check; objectStorage: Check }) {",
        "  const ready = async () => {",
        "    const [database, objectStorage] = await Promise.all([",
        "      checks.database().catch(() => false),",
        "      checks.objectStorage().catch(() => false),",
        "    ]);",
        "    return { ready: database && objectStorage, database, objectStorage };",
        "  };",
        "  return {",
        '    live: () => ({ status: "ok" as const }), // zero dependencies: an answer is enough',
        "    ready, // called by the post-release check",
        "    capabilities: async () => {",
        "      const report = await ready();",
        '      const state = (ok: boolean): CapabilityState => (ok ? "available" : "unavailable");',
        "      return {",
        '        publicCatalog: "available" as CapabilityState, // the static catalog opens even if the DB is down',
        "        communityWrite: state(report.database),",
        "        studioCloudSave: state(report.database && report.objectStorage),",
        "      };",
        "    },",
        "  };",
        "}",
      ].join("\n"),
      explain: t(
        "live에는 await가 하나도 없다는 점이 핵심입니다. 실제 구현은 기능 11개와 5초 성공 캐시, 동시 요청이 하나의 in-flight Promise를 공유하는 처리까지 더합니다.",
        "The point is that live contains no await at all. The real implementation adds 11 features, a 5-second success cache and sharing one in-flight Promise between concurrent requests.",
      ),
      source: "apps/api/src/modules/health/health.service.ts",
      verify: "types",
    },
    {
      kind: "simplified",
      title: t("느린 응답을 장애와 준비 중으로 가르기", "Telling a slow reply from an outage"),
      language: "ts",
      code: [
        "const WARMUP_WINDOW_MS = 90_000; // 코드 주석의 기록값: 직접 측정한 수치가 아니다",
        "const COLD_GATEWAY_STATUSES = new Set([502, 503, 504]);",
        "",
        "interface ProbeError {",
        "  status?: number;",
        "  timedOut?: boolean;",
        "  retryAfterSeconds?: number;",
        "}",
        "",
        "export function classifyFailure(error: ProbeError, openedAtMs: number, confirmedBefore: boolean, nowMs: number) {",
        "  // 서버가 일부러 Retry-After를 실었다면 절전 해제가 아니라 진짜 기능 저하다",
        '  if (error.retryAfterSeconds) return "degraded" as const;',
        "  const looksCold = error.timedOut === true || COLD_GATEWAY_STATUSES.has(error.status ?? 0);",
        "  const inWindow = !confirmedBefore && nowMs - openedAtMs < WARMUP_WINDOW_MS;",
        '  return looksCold && inWindow ? ("warming-up" as const) : ("degraded" as const);',
        "}",
      ].join("\n"),
      codeEn: [
        "const WARMUP_WINDOW_MS = 90_000; // the value recorded in a code comment, not a measurement",
        "const COLD_GATEWAY_STATUSES = new Set([502, 503, 504]);",
        "",
        "interface ProbeError {",
        "  status?: number;",
        "  timedOut?: boolean;",
        "  retryAfterSeconds?: number;",
        "}",
        "",
        "export function classifyFailure(error: ProbeError, openedAtMs: number, confirmedBefore: boolean, nowMs: number) {",
        "  // a deliberate Retry-After means real degradation, not a wake-up",
        '  if (error.retryAfterSeconds) return "degraded" as const;',
        "  const looksCold = error.timedOut === true || COLD_GATEWAY_STATUSES.has(error.status ?? 0);",
        "  const inWindow = !confirmedBefore && nowMs - openedAtMs < WARMUP_WINDOW_MS;",
        '  return looksCold && inWindow ? ("warming-up" as const) : ("degraded" as const);',
        "}",
      ].join("\n"),
      explain: t(
        "세 조건이 모두 맞아야 '준비 중'입니다. 응답이 늦거나 게이트웨이 오류이고, 페이지를 연 지 90초 안이며, 이 페이지에서 아직 한 번도 성공하지 못했을 때입니다.",
        "All three conditions must hold for 'warming up': a slow reply or gateway error, within 90 seconds of opening the page, and no success yet on this page.",
      ),
      source: "apps/web/src/platform/service-capability-state.ts",
      verify: "types",
    },
  ],
  links: [
    {
      title: "Render · Health checks",
      url: "https://render.com/docs/health-checks",
      kind: "docs",
      note: t("플랫폼 헬스체크 경로의 동작", "How the platform health-check path behaves"),
    },
    {
      title: "Render · Free instances",
      url: "https://render.com/docs/free",
      kind: "docs",
      note: t("무료 인스턴스의 절전과 제한", "Spin-down and limits of free instances"),
    },
    {
      title: "Kubernetes · Liveness, readiness and startup probes",
      url: "https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/",
      kind: "guide",
      note: t("live와 ready를 나누는 개념의 출처", "The origin of splitting live from ready"),
    },
    {
      title: "MDN · Retry-After",
      url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Retry-After",
      kind: "docs",
      note: t("서버가 일부러 보낸 지연 안내 헤더", "The header a server uses to ask for a delay on purpose"),
    },
  ],
  chapterIds: ["infrastructure", "troubleshooting-evidence"],
  talk: {
    pitch: t(
      "무료 서버는 잠들었다 깨어나는 데 시간이 걸립니다. 그래서 헬스체크를 셋으로 나눴습니다. live는 아무것도 확인하지 않고 살아 있다고만 답해서 서버나 DB를 깨우지 않고, ready는 DB와 저장소까지 확인해 배포 직후 점검에 쓰며, capabilities는 기능별로 지금 쓸 수 있는지를 알려 줍니다. 브라우저는 처음 90초의 느린 응답을 장애가 아니라 '연결 준비 중'으로 보여 줍니다.",
      "A free server takes time to wake from sleep, so health checks come in three kinds. live checks nothing and only says it is alive, so it does not wake the server or the database. ready also checks the database and storage and is used right after a release. capabilities tells each feature whether it can be used now. The browser shows slow replies in the first 90 seconds as 'connecting', not as an outage.",
    ),
    analogy: t(
      "가게에 비유하면 live는 '불이 켜져 있나', ready는 '계산대와 금고가 다 준비됐나', capabilities는 '지금 어느 코너가 열려 있나'입니다.",
      "In shop terms: live asks whether the lights are on, ready whether the register and safe are all set, and capabilities which counters are open right now.",
    ),
    questions: [
      {
        question: t("왜 ready를 상시 모니터링하지 않나요?", "Why isn't ready monitored all the time?"),
        answer: t(
          "DB와 외부 서비스를 호출해 무료 한도를 쓰기 때문입니다. 그래서 플랫폼 점검은 live만 쓰고, ready는 배포 후 점검 스크립트(live 다음 ready 순서)에서 부릅니다. 다만 브라우저의 capabilities 호출은 안에서 ready 점검을 거칩니다.",
          "It calls the database and external services and spends free allowance. So the platform check uses only live, and ready is called by the post-release script (live first, then ready). Note that the browser's capabilities call runs the ready check inside.",
        ),
      },
      {
        question: t("서버가 깨는 동안 사용자는 무엇을 보나요?", "What does the user see while the server wakes up?"),
        answer: t(
          "장애 배너 대신 '연결 준비' 안내를 보고, 6초마다 자동으로 다시 확인합니다. 깨어난 뒤 첫 성공은 '복구' 알림도 띄우지 않습니다.",
          "A 'connecting' notice instead of an outage banner, with an automatic recheck every 6 seconds. The first success after waking does not raise a 'recovered' notice either.",
        ),
      },
      {
        question: t("DB가 죽으면 앱 전체가 멈추나요?", "If the database dies, does the whole app stop?"),
        answer: t(
          "공개 카탈로그와 스튜디오 로컬 편집은 capabilities에서 늘 available입니다. 커뮤니티 쓰기나 클라우드 저장처럼 DB가 필요한 기능만 unavailable로 표시됩니다.",
          "The public catalog and local Studio editing are always available in capabilities. Only features that need the database, such as community writes and cloud save, show unavailable.",
        ),
      },
    ],
    pitfall: t(
      "무료 서버의 절전 기준 시간과 첫 응답 지연은 공급자 정책이라 바뀔 수 있고, 이 카드는 직접 측정하지 않았으므로 숫자로 말하지 마세요. 또 '헬스체크가 DB를 깨우지 않는다'는 live에만 맞습니다. capabilities는 내부에서 ready 점검(DB 포함)을 부르고, 탭이 열려 있으면 브라우저가 60초마다 이를 호출합니다.",
      "The idle time before a free server sleeps and the delay of the first reply are provider policy that can change, and this card did not measure them, so do not quote numbers. And 'health checks do not wake the database' holds only for live: capabilities runs the ready check (database included) inside, and an open tab calls it every 60 seconds.",
    ),
  },
  technologies: ["Render", "NestJS", "Cloudflare Workers", "PostgreSQL", "React"],
  facts: [
    {
      value: "199",
      label: t("ready가 확인하는 필수 릴레이션 수(코드 목록)", "Required relations the ready check verifies (code list)"),
      source: "apps/api/src/modules/health/health-readiness.repository.ts",
    },
    {
      value: "5 s",
      label: t("성공한 ready 보고의 캐시 시간", "Cache time for a successful ready report"),
      source: "apps/api/src/modules/health/health.service.ts",
    },
    {
      value: "90 s / 6 s",
      label: t("연결 준비 중 판정 창과 재확인 간격(코드 상수)", "Warm-up window and recheck interval (code constants)"),
      source: "apps/web/src/platform/service-capability-state.ts",
    },
  ],
  reviewedAt: "2026-10-07",
};

export const PLATFORM_OPS_EDGE_CARDS: readonly EngineeringAtlasEntry[] = [
  STATIC_FIRST_EDGE_GATEWAY,
  MANUAL_SHA_RELEASE_GATE,
  HEALTH_LIVE_READY_CAPABILITIES,
];
