import type { EngineeringAtlasEntry } from "./engineering-atlas-types";
import type { LocalizedText } from "./engineering-story-content";

/**
 * 기술 도감 · platform-ops 카테고리 — 거래·원장 카드(결제 멱등·웹훅 재조정, 지갑 예약-정산, 외부 쓰기 영수증).
 * 사실은 2026-10-07 기준 코드·테스트·문서로 확인했다. 결제 공급자 키·계정·운영 활성 여부는 열람하지 않았다.
 */

const t = (ko: string, en: string): LocalizedText => ({ ko, en });

const PAYMENT_IDEMPOTENCY_WEBHOOK_RECONCILE: EngineeringAtlasEntry = {
  id: "payment-idempotency-webhook-reconcile",
  category: "platform-ops",
  name: "Payment idempotency and webhook reconciliation",
  title: t("결제는 금액을 서버가 쥐고, 애매하면 다시 결제하지 않고 조회합니다", "Payments: the server holds the amount, and when unsure it queries instead of charging again"),
  status: "configured",
  tagline: t(
    "클라이언트 금액과 웹훅 본문을 믿지 않고, 불확실하면 재승인 대신 결제 조회로 확정합니다.",
    "It trusts neither the client's amount nor the webhook body, and when unsure it settles by querying instead of re-approving.",
  ),
  background: [
    t(
      "온라인 결제에서 가장 무서운 사고는 두 번 청구되는 일과, 브라우저가 보낸 금액을 믿어서 싼 값에 사 가는 일입니다. ToonStudio의 후원·마켓 결제는 두 원칙을 지킵니다. 금액은 서버가 주문을 만들 때 DB에 적어 둔 값만 기준으로 삼고(브라우저가 보낸 금액은 대조용), 응답이 애매하면 다시 승인하지 않고 결제사에 상태를 조회해 확정합니다. 은행 창구에서 '송금 확인 중' 화면이 뜨면 다시 송금하지 않고 조회부터 하는 것과 같습니다.",
      "The scariest accidents in online payment are being charged twice and trusting an amount sent by the browser so that someone buys at a lower price. ToonStudio's support and market payments follow two principles. The amount is whatever the server wrote into the database when the order was made (the browser's amount is only for comparison), and when a reply is ambiguous it queries the payment provider for the status instead of approving again. It is like not re-sending a bank transfer when the screen says 'checking' but looking it up first.",
    ),
    t(
      "후원 결제의 흐름. ① createOrder가 주문 ID와 금액을 READY로 저장하고 승인용 멱등 키(UUID)를 미리 발급합니다. ② confirm이 브라우저가 보낸 {paymentKey, orderId, amount}의 금액을 DB 금액과 대조하고, 이미 승인된 주문이면 그대로 돌려줍니다. ③ 결제사 승인 API를 부를 때 저장된 키를 Idempotency-Key 헤더로 보냅니다. ④ 타임아웃·네트워크 오류·5xx·429처럼 '성공했을 수도 있는' 실패(uncertain)면 재승인 대신 결제 조회로 최종 상태를 확인하고, 조회마저 실패하면 503으로 '확인 중'이라 안내합니다. ⑤ reconcile이 주문 ID·총액·통화(KRW)·상태를 서버 주문과 다시 대조한 뒤에만 반영합니다.",
      "The support-payment flow: (1) createOrder stores the order ID and amount as READY and issues an approval idempotency key (a UUID) in advance. (2) confirm compares the amount in the browser's {paymentKey, orderId, amount} with the database amount and returns an already-approved order as is. (3) When calling the provider's approval API it sends the stored key as an Idempotency-Key header. (4) For a failure that might have succeeded, such as a timeout, network error, 5xx or 429 (uncertain), it checks the final state by querying instead of re-approving, and if even the query fails it answers 503 with a 'checking' notice. (5) reconcile applies the result only after matching order ID, total, currency (KRW) and status against the server's order.",
    ),
    t(
      "웹훅은 사실이 아니라 단서입니다. 본문에서 orderId와 paymentKey만 꺼내 서버 주문을 찾고, 결제사에 다시 조회한 결과만 반영합니다. 위조한 웹훅은 서버가 한 번 더 조회하게 만들 뿐 상태를 바꾸지 못합니다. 마켓 구매는 같은 패턴에 클라이언트의 requestId(UUID)를 주문 생성 멱등 키로 쓰고, 검증된 결제에서만 구매 권한(entitlement)을 부여하거나 회수하며, 웹훅 이벤트는 본문 해시의 unique 제약으로 중복을 거릅니다.",
      "A webhook is a hint, not a fact. Only orderId and paymentKey are taken from the body to find the server's order, and only what the provider returns when queried again is applied. A forged webhook merely makes the server query once more and cannot change any state. Market purchases follow the same pattern, using the client's requestId (a UUID) as the order-creation idempotency key, granting or revoking the purchase right (entitlement) only from a verified payment, and filtering duplicate webhook events with a unique constraint on a body hash.",
    ),
    t(
      "키 모드도 맞춰야 합니다. 클라이언트 키와 시크릿 키의 test_/live_ 접두사가 같아야 하고, live는 별도 허용 스위치가 켜져야 서버가 준비된 것으로 봅니다. 결제는 스위치와 키 쌍이 모두 있어야 열리는 기본 비활성(fail-closed)입니다. 한계: 이 코드는 요청 시점 재조정과 관리자 재동기화에 기대고, 별도의 정기 재조정 배치는 확인하지 못했습니다.",
      "Key modes must match too. The client and secret keys must share the test_ or live_ prefix, and live counts as server-ready only when a separate allow switch is on. Payments are fail-closed by default and open only when the switches and a key pair are all present. A limit: this code relies on reconciliation at request time and on an operator resync, and no separate periodic reconciliation job was found.",
    ),
  ],
  keyPoints: [
    t("금액은 서버가 저장한 값만 기준, 브라우저 금액은 대조용", "Only the server-stored amount counts; the browser's is for comparison"),
    t("불확실한 실패는 재승인이 아니라 결제 조회로 확정", "An uncertain failure is settled by a query, not a re-approval"),
    t("웹훅은 단서: 식별자만 꺼내고 결제사에 다시 조회", "A webhook is a hint: take ids only, then query the provider again"),
    t("스위치와 키 쌍이 있어야 열리는 기본 비활성", "Off by default; opens only with switches and a key pair"),
  ],
  diagram: {
    id: "payment-idempotency-webhook-reconcile-diagram",
    kind: "sequence",
    title: t("승인과 웹훅이 같은 조회로 모이는 길", "Approval and webhook converge on the same query"),
    caption: t(
      "승인 응답이 애매해도, 웹훅이 와도, 결제사에 다시 물어본 값만 주문에 반영합니다.",
      "Whether the approval reply is unclear or a webhook arrives, only a value re-fetched from the provider reaches the order.",
    ),
    alt: t(
      "브라우저가 주문을 만들면 서버가 금액과 멱등 키를 DB에 저장합니다. 승인 요청이 오면 서버는 금액을 DB와 대조한 뒤 저장된 멱등 키로 결제사에 승인을 요청합니다. 응답이 지연되거나 5xx·429면 재승인하지 않고 결제 조회로 상태를 확정하고, 주문과 대조한 뒤에만 DB에 반영합니다. 결제사의 웹훅이 와도 본문은 단서일 뿐이어서 다시 조회한 값만 반영합니다.",
      "When the browser makes an order, the server stores the amount and an idempotency key in the database. On an approval request, the server compares the amount with the database and asks the provider to approve with the stored key. If the reply is slow, 5xx or 429, it does not approve again but confirms by querying, and writes to the database only after matching the order. When a provider webhook arrives its body is only a hint, and only the re-queried value is applied.",
    ),
    actors: [
      { id: "browser", label: t("브라우저", "Browser"), sub: t("금액을 보낼 수 있음", "Can send an amount"), tone: "local" },
      { id: "api", label: t("Core API", "Core API"), sub: t("대조하고 조정", "Compares, reconciles"), tone: "server" },
      { id: "db", label: t("주문 DB", "Order DB"), sub: t("금액·멱등 키 보관", "Keeps amount, key"), tone: "server" },
      { id: "toss", label: t("결제사", "Provider"), sub: t("승인·조회·웹훅", "Approve, query, webhook"), tone: "external" },
    ],
    messages: [
      { from: "browser", to: "api", label: t("주문 만들기", "Create an order"), note: t("금액은 서버가 검증해 저장", "The server validates and stores it") },
      { from: "api", to: "db", label: t("READY 주문 + 승인 멱등 키 저장", "Save READY order + approval key"), note: t("이후엔 DB 값만 기준", "From now on the DB value rules") },
      { from: "browser", to: "api", label: t("승인 요청 {paymentKey, orderId, amount}", "Approve {paymentKey, orderId, amount}"), note: t("금액이 DB와 다르면 거절", "Rejected if it differs from the DB") },
      { from: "api", to: "toss", label: t("승인 API + Idempotency-Key", "Approve API + Idempotency-Key"), note: t("저장해 둔 키를 헤더로 전송", "Sends the stored key as a header") },
      { from: "toss", to: "api", label: t("지연 · 5xx · 429 (불확실)", "Slow, 5xx or 429 (uncertain)"), style: "dashed", note: t("성공했을 수도 있는 실패", "A failure that may have succeeded") },
      { from: "api", to: "toss", label: t("재승인이 아니라 결제 조회", "Query, not re-approve"), note: t("조회로 최종 상태를 확정", "The query settles the final state") },
      { from: "toss", to: "api", label: t("결제 상태 · 총액 · 통화", "Status, total, currency"), style: "dashed" },
      { from: "api", to: "db", label: t("주문과 대조한 뒤에만 반영", "Apply only after matching"), note: t("주문 ID·총액·KRW·상태 일치", "Order ID, total, KRW and status agree") },
      { from: "toss", to: "api", label: t("웹훅 (본문은 단서)", "Webhook (body is a hint)"), style: "dashed", note: t("orderId·paymentKey만 꺼냄", "Only orderId and paymentKey are read") },
      { from: "api", to: "toss", label: t("웹훅이 와도 다시 조회", "Query again on a webhook"), note: t("조회한 결과만 반영", "Only the queried result is applied") },
    ],
  },
  usage: [
    {
      feature: t("운영비 후원 결제", "Operating-cost support payments"),
      role: t(
        "주문 생성·승인·웹훅·환불·재동기화를 한 서비스가 맡고, 승인 응답이 불확실하면 조회로 확정합니다. 관리자 화면에서 재동기화와 전액 취소를 부를 수 있습니다.",
        "One service handles order creation, approval, webhooks, refunds and resync, settling an uncertain approval by querying. Operators can trigger resync and full cancellation from the admin screen.",
      ),
      paths: [
        "apps/api/src/modules/supporter-payment/supporter-payment.service.ts",
        "apps/api/src/modules/supporter-payment/supporter-toss.provider.ts",
        "apps/web/src/domains/legal/supporter-payment-api.ts",
      ],
      route: "/support-us",
    },
    {
      feature: t("마켓 유료 리소스 구매와 구매 권한", "Paid market resources and purchase rights"),
      role: t(
        "requestId로 주문 생성을 멱등하게 만들고, 검증된 결제에서만 구매 권한을 부여하며 취소되면 회수합니다. 웹훅 이벤트는 본문 해시로 중복을 거릅니다.",
        "A requestId makes order creation idempotent, purchase rights are granted only from verified payments and revoked on cancellation, and webhook events are de-duplicated by body hash.",
      ),
      paths: [
        "apps/api/src/modules/commerce/commerce.service.ts",
        "apps/api/src/modules/commerce/commerce-runtime.ts",
      ],
    },
    {
      feature: t("키 모드·스위치 검사 (기본 비활성)", "Key-mode and switch checks (off by default)"),
      role: t(
        "test_/live_ 접두사가 맞고, live는 허용 스위치가 켜졌을 때만 서버 준비로 인정해 잘못된 환경 혼합을 막습니다.",
        "It requires matching test_ and live_ prefixes and counts live as ready only when the allow switch is on, preventing mixed environments.",
      ),
      paths: ["apps/api/src/modules/supporter-payment/supporter-payment.config.ts", "render.yaml"],
    },
    {
      feature: t("웹훅 식별자 추출", "Extracting webhook identifiers"),
      role: t(
        "본문에서 orderId와 paymentKey만 길이를 제한해 꺼내고, 나머지는 신뢰하지 않습니다.",
        "Only orderId and paymentKey are taken from the body with length limits; nothing else is trusted.",
      ),
      paths: ["apps/api/src/modules/supporter-payment/supporter-payment-webhook.ts"],
    },
  ],
  samples: [
    {
      kind: "simplified",
      title: t("금액은 서버 기준, 불확실하면 조회로 확정", "Server-side amount; settle by query when uncertain"),
      language: "ts",
      code: [
        "export class UncertainError extends Error {} // 타임아웃·5xx·429: 성공했을 수도 있는 실패",
        "",
        "interface Order { id: string; amount: number; paymentKey?: string; done: boolean; idempotencyKey: string }",
        "interface Gateway {",
        "  confirm(order: Order, paymentKey: string, idempotencyKey: string): Promise<number>; // 승인된 금액",
        "  query(paymentKey: string): Promise<number>; // 조회로 확인한 금액",
        "}",
        "",
        "export async function confirm(order: Order, paymentKey: string, amount: number, gateway: Gateway): Promise<Order> {",
        '  if (amount !== order.amount) throw new Error("금액은 서버가 보관한 값만 신뢰한다");',
        "  if (order.done && order.paymentKey === paymentKey) return order; // 재호출은 멱등",
        "  let paid: number;",
        "  try {",
        "    paid = await gateway.confirm(order, paymentKey, order.idempotencyKey);",
        "  } catch (error) {",
        "    if (!(error instanceof UncertainError)) throw error;",
        "    paid = await gateway.query(paymentKey); // 불확실하면 '재승인'이 아니라 '조회'로 확정한다",
        "  }",
        '  if (paid !== order.amount) throw new Error("결제사 금액이 주문과 다르다");',
        "  return { ...order, paymentKey, done: true };",
        "}",
      ].join("\n"),
      codeEn: [
        "export class UncertainError extends Error {} // timeout, 5xx, 429: a failure that may have succeeded",
        "",
        "interface Order { id: string; amount: number; paymentKey?: string; done: boolean; idempotencyKey: string }",
        "interface Gateway {",
        "  confirm(order: Order, paymentKey: string, idempotencyKey: string): Promise<number>; // approved amount",
        "  query(paymentKey: string): Promise<number>; // amount confirmed by a query",
        "}",
        "",
        "export async function confirm(order: Order, paymentKey: string, amount: number, gateway: Gateway): Promise<Order> {",
        '  if (amount !== order.amount) throw new Error("only the amount the server stored is trusted");',
        "  if (order.done && order.paymentKey === paymentKey) return order; // a repeated call is idempotent",
        "  let paid: number;",
        "  try {",
        "    paid = await gateway.confirm(order, paymentKey, order.idempotencyKey);",
        "  } catch (error) {",
        "    if (!(error instanceof UncertainError)) throw error;",
        "    paid = await gateway.query(paymentKey); // when unsure, settle by 'query', not by 're-approve'",
        "  }",
        '  if (paid !== order.amount) throw new Error("the provider amount differs from the order");',
        "  return { ...order, paymentKey, done: true };",
        "}",
      ].join("\n"),
      explain: t(
        "실제 코드는 ProductionExternalHttpError의 uncertain 플래그로 분기하고, 조회까지 실패하면 503으로 '확인 중'을 안내합니다. 결제사 이름과 응답 형식은 인터페이스 뒤로 숨겼습니다.",
        "The real code branches on the uncertain flag of ProductionExternalHttpError and answers 503 'checking' if even the query fails. The provider's name and reply shape are hidden behind an interface.",
      ),
      source: "apps/api/src/modules/supporter-payment/supporter-payment.service.ts",
      verify: "types",
    },
    {
      kind: "simplified",
      title: t("웹훅은 단서: 식별자만 꺼내 다시 조회", "A webhook as a hint: take identifiers, then query again"),
      language: "ts",
      code: [
        "interface Payment { orderId: string; totalAmount: number; status: string }",
        "interface Gateway { query(paymentKey: string): Promise<Payment> }",
        "interface OrderRow { orderId: string; amount: number; paymentKey: string | null }",
        "",
        "/** 웹훅 본문은 단서일 뿐이다: 식별자만 꺼내고, 결제사에 다시 물어본 값만 반영한다 */",
        "export async function onWebhook(body: unknown, find: (orderId: string) => OrderRow | undefined, gateway: Gateway) {",
        '  const data = typeof body === "object" && body !== null ? (body as Record<string, unknown>) : {};',
        '  const orderId = typeof data.orderId === "string" ? data.orderId.slice(0, 64) : "";',
        "  const row = find(orderId);",
        "  if (!row?.paymentKey) return { received: true as const }; // 모르는 주문은 조용히 무시한다",
        "  const payment = await gateway.query(row.paymentKey); // 위조 웹훅은 재조회만 일으킨다",
        "  if (payment.orderId !== row.orderId || payment.totalAmount !== row.amount) {",
        '    throw new Error("결제사 응답이 주문과 다르다");',
        "  }",
        "  return { received: true as const, status: payment.status };",
        "}",
      ].join("\n"),
      codeEn: [
        "interface Payment { orderId: string; totalAmount: number; status: string }",
        "interface Gateway { query(paymentKey: string): Promise<Payment> }",
        "interface OrderRow { orderId: string; amount: number; paymentKey: string | null }",
        "",
        "/** A webhook body is only a hint: take the identifiers and apply only what the provider returns on a re-query */",
        "export async function onWebhook(body: unknown, find: (orderId: string) => OrderRow | undefined, gateway: Gateway) {",
        '  const data = typeof body === "object" && body !== null ? (body as Record<string, unknown>) : {};',
        '  const orderId = typeof data.orderId === "string" ? data.orderId.slice(0, 64) : "";',
        "  const row = find(orderId);",
        "  if (!row?.paymentKey) return { received: true as const }; // an unknown order is quietly ignored",
        "  const payment = await gateway.query(row.paymentKey); // a forged webhook only causes a re-query",
        "  if (payment.orderId !== row.orderId || payment.totalAmount !== row.amount) {",
        '    throw new Error("the provider reply differs from the order");',
        "  }",
        "  return { received: true as const, status: payment.status };",
        "}",
      ].join("\n"),
      explain: t(
        "웹훅 서명을 직접 검증하는 대신 '다시 물어보기'로 신뢰를 얻는 방식입니다. 실제 서비스는 결제 키 모드와 영수증 URL(https만 허용) 검사를 더하고, 마켓은 본문 해시로 중복 이벤트를 거릅니다.",
        "Instead of verifying a webhook signature itself, trust comes from asking again. The real service adds payment key-mode and receipt-URL checks (https only), and the market side filters duplicate events by body hash.",
      ),
      source: "apps/api/src/modules/supporter-payment/supporter-payment.service.ts",
      verify: "types",
    },
  ],
  links: [
    {
      title: "Toss Payments · Developer Center",
      url: "https://docs.tosspayments.com/reference",
      kind: "docs",
      note: t("승인·조회·취소 API 레퍼런스", "Reference for the approve, query and cancel APIs"),
    },
    {
      title: "Stripe · Idempotent requests",
      url: "https://docs.stripe.com/api/idempotent_requests",
      kind: "guide",
      note: t("멱등 키 개념을 보여 주는 일반 참고 자료", "A general reference showing the idempotency-key concept"),
    },
    {
      title: "IETF · The Idempotency-Key HTTP Header Field (draft)",
      url: "https://datatracker.ietf.org/doc/draft-ietf-httpapi-idempotency-key-header/",
      kind: "spec",
      note: t("표준화 진행 중인 초안 문서", "A draft document still on its way to standardization"),
    },
    {
      title: "MDN · Idempotent (HTTP)",
      url: "https://developer.mozilla.org/en-US/docs/Glossary/Idempotent",
      kind: "docs",
      note: t("멱등의 정의", "The definition of idempotent"),
    },
  ],
  chapterIds: ["infrastructure", "troubleshooting-evidence"],
  talk: {
    pitch: t(
      "결제에서는 금액을 서버만 압니다. 브라우저가 보낸 금액은 서버에 저장된 값과 맞는지 확인하는 데만 씁니다. 결제사 응답이 애매하면 다시 결제를 시도하지 않고 먼저 조회해서 결과를 확정하고, 결제사가 보내는 웹훅도 그대로 믿지 않고 한 번 더 조회한 값만 반영합니다. 그래서 이중 결제나 위조 알림으로 주문 상태가 바뀌기 어렵습니다.",
      "In payments only the server knows the amount; the browser's amount is used just to check it matches what the server stored. If the provider's reply is unclear, it does not try to charge again but queries first to settle the result, and a provider webhook is not believed outright either: only the value fetched by one more query is applied. That makes it hard for a double charge or a forged notice to change an order.",
    ),
    analogy: t(
      "택배 기사가 '배송 완료' 문자를 보냈다고 바로 믿지 않고, 택배 조회 사이트에서 직접 확인하는 것과 같습니다.",
      "Like not believing a courier's 'delivered' text until you check the tracking site yourself.",
    ),
    questions: [
      {
        question: t("웹훅 서명 검증은 하나요?", "Is the webhook signature verified?"),
        answer: t(
          "이 코드는 서명 대신 '재조회'로 검증합니다. 웹훅 본문에서 식별자만 꺼내 결제사에 다시 묻고, 그 결과만 반영합니다. 중복 웹훅은 마켓에서 본문 해시 unique로 거릅니다.",
          "This code verifies by re-querying instead of a signature: it takes identifiers from the body, asks the provider again and applies only that result. In the market, duplicate webhooks are filtered by a unique body hash.",
        ),
      },
      {
        question: t("테스트 결제와 실결제가 섞이면요?", "What if test and live payments get mixed?"),
        answer: t(
          "클라이언트 키와 시크릿 키의 test_/live_ 접두사가 같아야 하고, 주문에 모드를 저장한 뒤 모드가 다른 설정이면 503으로 거절합니다. live는 별도 허용 스위치가 있어야 합니다.",
          "The client and secret keys must share the test_ or live_ prefix, the mode is stored with the order, and a mismatching configuration is refused with 503. Live also needs a separate allow switch.",
        ),
      },
      {
        question: t("지금 실제 결제가 켜져 있나요?", "Are real payments switched on right now?"),
        answer: t(
          "확인하지 못했습니다. render.yaml은 스위치와 키를 값 없이 선언만 하고 '명시적 스위치와 키 쌍이 있어야 열린다'고 적습니다. 운영 활성 여부는 대시보드에서 확인해야 합니다.",
          "I could not confirm. render.yaml declares the switches and keys without values and states that they open only with explicit switches and a key pair. Whether it is active in production must be checked on the dashboard.",
        ),
      },
    ],
    pitfall: t(
      "정직하게 말할 비대칭 두 가지. 첫째, 후원 승인에는 uncertain일 때 조회하는 분기가 있지만 마켓 승인(commerce)에는 같은 분기가 보이지 않습니다. 같은 멱등 키 재호출과 웹훅 재조회가 보완하는 구조로 보이나 확인하지 못했습니다. 둘째, 후원·마켓 결제 서비스를 직접 검증하는 단위 테스트는 찾지 못했고, 키 모드 설정과 웹훅 식별자 추출만 테스트가 있습니다.",
      "Two asymmetries to state honestly. First, support-payment approval has a branch that queries when uncertain, but market approval (commerce) shows no such branch; repeating the call with the same idempotency key and webhook re-queries seem to compensate, which was not verified. Second, no unit tests were found that directly exercise the support or market payment services; only the key-mode configuration and webhook identifier extraction have tests.",
    ),
  },
  technologies: ["NestJS", "PostgreSQL", "Drizzle ORM", "Idempotency-Key", "Toss Payments"],
  facts: [
    {
      value: "1,000 ~ 1,000,000 KRW",
      label: t("후원 금액의 허용 범위", "Allowed range of a support amount"),
      source: "packages/core/src/supporter-payment.ts",
    },
    {
      value: "300 / 10 minutes",
      label: t("후원 주문 생성의 전역 상한(10분 창)", "Global cap on support-order creation (10-minute window)"),
      source: "apps/api/src/modules/supporter-payment/supporter-payment.service.ts",
    },
  ],
  reviewedAt: "2026-10-07",
};

const WALLET_RESERVE_CAPTURE_LEDGER: EngineeringAtlasEntry = {
  id: "wallet-reserve-capture-ledger",
  category: "platform-ops",
  name: "Wallet reserve-capture ledger",
  title: t("예약 → 정산 2단계로 움직이는 크레딧 지갑 원장", "A credit-wallet ledger that moves in two steps: reserve, then settle"),
  status: "configured",
  tagline: t(
    "잔액을 먼저 예약해 묶고 실제 사용량만 정산하며, 같은 요청은 몇 번을 보내도 같은 영수증을 받습니다.",
    "Balance is reserved first and only actual usage is settled; the same request always gets the same receipt.",
  ),
  background: [
    t(
      "포인트나 크레딧을 숫자 하나로만 두면, 동시에 두 요청이 들어올 때 같은 잔액을 두 번 쓰는 사고가 납니다. 그래서 호텔 보증금처럼 2단계로 씁니다. 먼저 필요한 만큼을 예약해 잔액에서 묶어 두고, 작업이 끝나면 실제로 쓴 만큼만 정산(capture)하고 남은 것은 해제(release)해 돌려줍니다. 같은 요청을 몇 번 보내도 같은 결과를 받도록 멱등 키도 둡니다.",
      "If points or credits are held as a single number, two simultaneous requests can spend the same balance twice. So it works in two steps like a hotel deposit: first reserve what is needed so it is set aside from the balance, then when the work ends settle (capture) only what was really used and release the rest back. An idempotency key also makes repeats of the same request return the same result.",
    ),
    t(
      "예약은 한 트랜잭션 안에서 이어집니다. ① 사용자·자산 단위 advisory lock으로 같은 사람의 요청을 한 줄로 세우고 ② 같은 멱등 키의 예약이 있으면 그 결과를 돌려주고 ③ 하루 한도(KST 날짜 경계)를 검사하고 ④ 조건부 UPDATE(WHERE 가용 ≥ 요청)로 가용 잔액을 예약 잔액으로 옮기고 ⑤ 우선순위와 만료가 빠른 순으로 lot(적립 묶음)를 잠가 배정하고 ⑥ 원장에 reserve를 적습니다. 배정 합계가 요청과 다르면 롤백합니다.",
      "A reservation runs inside one transaction: (1) a per-user and per-asset advisory lock lines up requests from the same person; (2) if a reservation with the same idempotency key exists, its result is returned; (3) the daily limit (on a KST day boundary) is checked; (4) a conditional UPDATE (WHERE available >= requested) moves the available balance to reserved; (5) lots (grant batches) are locked and allocated by priority and earliest expiry; (6) a reserve entry is written to the ledger. If the allocation does not sum to the request, everything rolls back.",
    ),
    t(
      "정산은 예약 행을 FOR UPDATE로 잠그고, 이미 reserved가 아니면 현재 상태를 그대로 돌려줘 중복 정산에도 안전합니다. 실제 사용량이 요청 이하일 때만 받아들여 capture와 release 원장을 각각 남기고, 예약은 10분 뒤 만료됩니다. 코드의 조건부 UPDATE와 별개로 DB 자체도 가용 잔액이 음수가 되지 못하게 CHECK 제약을 걸고 멱등 키에 UNIQUE 제약을 걸어 이중으로 막습니다.",
      "Settlement locks the reservation row with FOR UPDATE and, if it is no longer reserved, returns the current state, so a duplicate settlement is safe. It accepts only an actual usage at or below the request, writes capture and release ledger entries, and reservations expire after 10 minutes. Apart from the code's conditional UPDATE, the database itself forbids a negative available balance with a CHECK constraint and a UNIQUE constraint on idempotency keys, a double defense.",
    ),
    t(
      "대안은 SELECT ... FOR UPDATE만 쓰거나 SERIALIZABLE 격리입니다. advisory lock은 계정 행이 아직 없을 때의 경쟁까지 같은 논리 키로 줄 세울 수 있어 택했습니다. 한계: 한 사용자의 폭주 요청은 대기열이 되고, 현재 구현은 판매가 꺼진 상태(creditPurchasesEnabled=false)이며 서버 AI·렌더 기능에 아직 연결되지 않았습니다.",
      "Alternatives are plain SELECT ... FOR UPDATE or SERIALIZABLE isolation. An advisory lock was chosen because the same logical key also lines up races when the account row does not exist yet. Limits: a burst from one user becomes a queue, and the current implementation has sales switched off (creditPurchasesEnabled=false) and is not yet wired into server AI or render features.",
    ),
  ],
  keyPoints: [
    t("잔액은 예약 → 정산(capture/release) 2단계로 움직임", "Balance moves in two steps: reserve, then capture or release"),
    t("사용자별 advisory lock + 멱등 키로 동시·중복 요청을 한 줄로", "A per-user advisory lock plus idempotency key serialize duplicates"),
    t("조건부 UPDATE가 곧 잔액 검사, DB CHECK가 이중 방어", "A conditional UPDATE is the balance check; DB CHECKs back it up"),
    t("구현·테스트 완료, 판매 비활성, 외부 호출부 미연결", "Implemented and tested, sales off, no external caller wired yet"),
  ],
  diagram: {
    id: "wallet-reserve-capture-ledger-diagram",
    kind: "sequence",
    title: t("예약에서 정산까지 한 건의 흐름", "One request from reservation to settlement"),
    caption: t(
      "예약이 잔액을 묶고, 정산이 실제 사용량만 확정하며, 두 단계 모두 같은 요청을 다시 받아도 결과가 같습니다.",
      "Reservation sets the balance aside and settlement confirms only real usage; both steps give the same result when repeated.",
    ),
    alt: t(
      "호출한 기능이 예약을 요청하면 서비스는 사용자별 advisory lock을 잡고 같은 멱등 키의 예약이 있는지 먼저 봅니다. 없으면 조건부 UPDATE로 잔액을 묶고 lot를 잠가 배정한 뒤 예약 ID를 돌려줍니다. 작업이 끝나면 실제 사용량으로 정산을 요청하고, 서비스는 예약 행을 잠가 상태를 확인한 뒤 capture와 release를 원장에 기록합니다.",
      "When a calling feature asks for a reservation, the service takes a per-user advisory lock and first looks for a reservation with the same idempotency key. If none, a conditional UPDATE sets the balance aside, lots are locked and allocated, and a reservation ID is returned. When the work ends the caller requests settlement with the actual usage, and the service locks the reservation row, checks its state and writes capture and release entries to the ledger.",
    ),
    actors: [
      { id: "caller", label: t("호출한 기능", "Calling feature"), sub: t("예: 서버 AI·렌더", "e.g. server AI, render"), tone: "neutral" },
      { id: "service", label: t("지갑 서비스", "Wallet service"), sub: t("트랜잭션으로 처리", "Runs in a transaction"), tone: "server" },
      { id: "db", label: t("PostgreSQL", "PostgreSQL"), sub: t("계정·lot·원장", "Account, lots, ledger"), tone: "server" },
    ],
    messages: [
      { from: "caller", to: "service", label: t("예약 요청 (멱등 키 포함)", "Reserve (with idempotency key)"), note: t("기능·사용 단위·키", "Feature, units, key") },
      { from: "service", to: "db", label: t("advisory lock (사용자·자산)", "Advisory lock (user, asset)"), note: t("같은 사람의 요청을 한 줄로", "Lines up one person's requests") },
      { from: "service", to: "db", label: t("같은 키의 예약이 있나?", "A reservation with this key?"), note: t("있으면 그 결과를 그대로 반환", "If so, return its result as is") },
      { from: "service", to: "db", label: t("조건부 UPDATE: 가용 ≥ 요청", "Conditional UPDATE: avail ≥ ask"), note: t("잔액 검사가 곧 차감", "The balance check is the debit") },
      { from: "service", to: "db", label: t("lot를 FOR UPDATE로 잠그고 배정", "Lock lots FOR UPDATE, allocate"), note: t("우선순위 → 만료 빠른 순", "Priority, then earliest expiry") },
      { from: "service", to: "caller", label: t("예약 ID (reserved)", "Reservation ID (reserved)"), style: "dashed" },
      { from: "caller", to: "service", label: t("작업 끝: 실제 사용량으로 정산", "Done: settle with actual usage"), note: t("실사용 ≤ 요청일 때만", "Only when actual ≤ requested") },
      { from: "service", to: "db", label: t("예약 행 FOR UPDATE · 상태 확인", "Lock reservation, check state"), note: t("reserved가 아니면 현재 상태 반환", "If not reserved, return the state") },
      { from: "service", to: "db", label: t("capture · release 원장 기록", "Write capture and release entries"), note: t("(계정, 멱등 키) unique", "(account, idempotency key) unique") },
    ],
  },
  usage: [
    {
      feature: t("멤버십 화면의 Studio Credit·Reward Point 현황", "Studio Credit and Reward Point status on the membership screen"),
      role: t(
        "개요·정책·권한 조회 API가 지갑 계정과 월 포함 크레딧, 등급 정책을 보여 줍니다. 멤버십은 아직 결제 상품이 아니라 권한 등급입니다.",
        "Overview, policy and entitlement APIs show wallet accounts, monthly included credits and plan policy. Membership is still a permission tier, not a paid product.",
      ),
      paths: [
        "apps/api/src/modules/membership-wallet/membership-wallet.controller.ts",
        "apps/web/src/platform/membership-wallet-client.ts",
        "docs/membership-points-fair-use.md",
      ],
      route: "/membership/usage",
    },
    {
      feature: t("활동 포인트 적립 (클라이언트 신고 가능 활동)", "Activity-point grants (activities a client may report)"),
      role: t(
        "정책에서 claimMode가 client인 활동만 클라이언트가 신고할 수 있고, 활동별 일일 한도와 소스 키 unique로 중복 적립을 막습니다.",
        "Only activities whose policy claimMode is client may be reported by a client, and per-activity daily limits and a unique source key prevent duplicate grants.",
      ),
      paths: ["apps/api/src/modules/membership-wallet/membership-wallet.service.ts#claimClientActivityPoints"],
    },
    {
      feature: t("예약 → 정산 코어 (서버 AI·렌더 연결 전)", "Reserve-settle core (before server AI and render are connected)"),
      role: t(
        "reserveStudioCredits, captureCreditReservation, releaseCreditReservation이 구현되어 있고 서비스 시험이 있습니다. 서비스 밖의 호출부는 찾지 못했습니다.",
        "reserveStudioCredits, captureCreditReservation and releaseCreditReservation are implemented with service tests. No caller outside the service was found.",
      ),
      paths: [
        "apps/api/src/modules/membership-wallet/membership-wallet.service.ts#reserveStudioCredits",
        "apps/api/src/modules/membership-wallet/membership-wallet.service.test.ts",
      ],
    },
    {
      feature: t("DB 안전망 (CHECK·UNIQUE)", "Database safety net (CHECK and UNIQUE)"),
      role: t(
        "가용 잔액이 음수가 되지 못하게 하고, 예약·원장의 멱등 키와 lot 소스 키에 unique를 걸어 코드가 놓쳐도 중복을 막습니다.",
        "It stops available balances from going negative and puts unique constraints on reservation and ledger idempotency keys and lot source keys, blocking duplicates even if the code misses.",
      ),
      paths: ["apps/api/src/platform/database/migrations/0075_membership_wallet_policy.sql"],
    },
  ],
  samples: [
    {
      kind: "simplified",
      title: t("advisory lock + 멱등 조회 + 조건부 UPDATE", "Advisory lock + idempotent lookup + conditional UPDATE"),
      language: "ts",
      code: [
        "interface Tx {",
        "  query(sql: string, params?: unknown[]): Promise<{ rows: Array<{ id: string }>; rowCount: number | null }>;",
        "}",
        "",
        "/** 한 트랜잭션 안에서 실행한다(BEGIN/COMMIT은 호출자가 감싼다) */",
        "export async function reserve(tx: Tx, user: string, amount: number, idemKey: string): Promise<string> {",
        "  // ① 사용자별 직렬화: 같은 사람의 요청은 한 줄로 선다",
        '  await tx.query("SELECT pg_advisory_xact_lock(hashtext($1))", [`wallet:${user}`]);',
        "  // ② 멱등: 같은 키의 예약이 있으면 새로 만들지 않고 그 결과를 돌려준다",
        '  const dup = await tx.query("SELECT id FROM reservation WHERE user_id = $1 AND idem_key = $2", [user, idemKey]);',
        "  if (dup.rows[0]) return dup.rows[0].id;",
        "  // ③ 조건부 UPDATE가 곧 잔액 검사다: 부족하면 바뀐 행이 0이다",
        "  const debit = await tx.query(",
        '    "UPDATE account SET available = available - $2, reserved = reserved + $2 WHERE user_id = $1 AND available >= $2",',
        "    [user, amount],",
        "  );",
        '  if (!debit.rowCount) throw new Error("잔액이 부족합니다");',
        '  const created = await tx.query("INSERT INTO reservation (user_id, idem_key, amount) VALUES ($1, $2, $3) RETURNING id", [user, idemKey, amount]);',
        '  return created.rows[0]?.id ?? "";',
        "}",
      ].join("\n"),
      codeEn: [
        "interface Tx {",
        "  query(sql: string, params?: unknown[]): Promise<{ rows: Array<{ id: string }>; rowCount: number | null }>;",
        "}",
        "",
        "/** Runs inside one transaction (the caller wraps BEGIN and COMMIT) */",
        "export async function reserve(tx: Tx, user: string, amount: number, idemKey: string): Promise<string> {",
        "  // (1) Per-user serialization: one person's requests line up",
        '  await tx.query("SELECT pg_advisory_xact_lock(hashtext($1))", [`wallet:${user}`]);',
        "  // (2) Idempotency: if a reservation with this key exists, return it instead of creating another",
        '  const dup = await tx.query("SELECT id FROM reservation WHERE user_id = $1 AND idem_key = $2", [user, idemKey]);',
        "  if (dup.rows[0]) return dup.rows[0].id;",
        "  // (3) The conditional UPDATE is the balance check: zero rows change when the balance is short",
        "  const debit = await tx.query(",
        '    "UPDATE account SET available = available - $2, reserved = reserved + $2 WHERE user_id = $1 AND available >= $2",',
        "    [user, amount],",
        "  );",
        '  if (!debit.rowCount) throw new Error("insufficient balance");',
        '  const created = await tx.query("INSERT INTO reservation (user_id, idem_key, amount) VALUES ($1, $2, $3) RETURNING id", [user, idemKey, amount]);',
        '  return created.rows[0]?.id ?? "";',
        "}",
      ].join("\n"),
      explain: t(
        "테이블·컬럼 이름은 설명용으로 줄였습니다. 실제 구현은 여기에 하루 한도 검사, lot 잠금과 배정, 원장 기록, 배정 합계 불변식 검사를 더합니다.",
        "Table and column names are shortened for explanation. The real implementation adds the daily-limit check, lot locking and allocation, ledger writes and an allocation-sum invariant check.",
      ),
      source: "apps/api/src/modules/membership-wallet/membership-wallet.service.ts",
      verify: "types",
    },
    {
      kind: "simplified",
      title: t("실제 사용량만 정산하고 중복 정산은 무시하기", "Settling only actual usage and ignoring duplicates"),
      language: "ts",
      code: [
        'type Status = "reserved" | "captured" | "released";',
        "interface Reservation { status: Status; requested: number }",
        "",
        "export type Settlement =",
        '  | { kind: "already-settled" }',
        '  | { kind: "settled"; captured: number; released: number };',
        "",
        "/** 실제 사용량만 capture 하고 나머지는 release 한다. 이미 정산된 예약은 그대로 둔다 */",
        "export function settle(reservation: Reservation, actual: number): Settlement {",
        '  if (reservation.status !== "reserved") return { kind: "already-settled" }; // 중복 정산에도 안전하다',
        "  if (!Number.isSafeInteger(actual) || actual < 0 || actual > reservation.requested) {",
        '    throw new Error("실제 사용량이 올바르지 않습니다");',
        "  }",
        '  return { kind: "settled", captured: actual, released: reservation.requested - actual };',
        "}",
        "",
        '// settle({ status: "reserved", requested: 10 }, 7) → captured 7, released 3',
      ].join("\n"),
      codeEn: [
        'type Status = "reserved" | "captured" | "released";',
        "interface Reservation { status: Status; requested: number }",
        "",
        "export type Settlement =",
        '  | { kind: "already-settled" }',
        '  | { kind: "settled"; captured: number; released: number };',
        "",
        "/** Capture only the actual usage and release the rest; leave an already-settled reservation alone */",
        "export function settle(reservation: Reservation, actual: number): Settlement {",
        '  if (reservation.status !== "reserved") return { kind: "already-settled" }; // a duplicate settlement is safe',
        "  if (!Number.isSafeInteger(actual) || actual < 0 || actual > reservation.requested) {",
        '    throw new Error("the actual usage is not valid");',
        "  }",
        '  return { kind: "settled", captured: actual, released: reservation.requested - actual };',
        "}",
        "",
        '// settle({ status: "reserved", requested: 10 }, 7) → captured 7, released 3',
      ].join("\n"),
      explain: t(
        "순수 함수로 줄인 정산 규칙입니다. 실제로는 예약 행을 FOR UPDATE로 잠근 트랜잭션 안에서 lot별 배정을 되돌리고 원장 두 줄을 남깁니다.",
        "The settlement rule reduced to a pure function. In reality it runs inside a transaction that locks the reservation row FOR UPDATE, unwinds the per-lot allocations and writes two ledger entries.",
      ),
      source: "apps/api/src/modules/membership-wallet/membership-wallet.service.ts",
      verify: "types",
    },
  ],
  links: [
    {
      title: "PostgreSQL · Explicit locking (advisory locks)",
      url: "https://www.postgresql.org/docs/current/explicit-locking.html",
      kind: "docs",
      note: t("pg_advisory_xact_lock의 의미와 사용법", "What pg_advisory_xact_lock means and how to use it"),
    },
    {
      title: "PostgreSQL · INSERT ... ON CONFLICT",
      url: "https://www.postgresql.org/docs/current/sql-insert.html",
      kind: "docs",
      note: t("멱등 쓰기를 만드는 ON CONFLICT", "ON CONFLICT, the tool for idempotent writes"),
    },
    {
      title: "PostgreSQL · SELECT ... FOR UPDATE",
      url: "https://www.postgresql.org/docs/current/sql-select.html",
      kind: "docs",
      note: t("행 잠금으로 동시 갱신을 막는 방법", "Preventing concurrent updates with row locks"),
    },
  ],
  chapterIds: ["cost-engineering", "infrastructure"],
  talk: {
    pitch: t(
      "크레딧은 숫자 하나가 아니라 장부입니다. 쓰기 전에 필요한 만큼을 예약해서 잔액에서 묶고, 일이 끝나면 실제로 쓴 만큼만 확정하고 남는 것은 돌려줍니다. 같은 사용자의 요청은 DB 잠금으로 한 줄로 세우고, 같은 요청 키는 몇 번 보내도 같은 영수증을 받습니다. 현재는 구현과 시험이 끝났고 판매는 꺼져 있으며 서버 AI와는 아직 연결 전입니다.",
      "Credit is a ledger, not a single number. Before spending, the needed amount is reserved and set aside from the balance; when the work ends only the amount really used is confirmed and the rest goes back. One user's requests are lined up by a database lock, and repeating a request key returns the same receipt. Today the implementation and tests are done, sales are off and it is not yet wired to server AI.",
    ),
    analogy: t(
      "호텔 체크인 때 보증금을 잡아 두었다가 퇴실 때 실제 사용액만 청구하고 나머지를 풀어 주는 것과 같습니다.",
      "Like a hotel taking a deposit at check-in, billing only the actual usage at checkout and releasing the rest.",
    ),
    questions: [
      {
        question: t("포인트가 현금인가요?", "Are points cash?"),
        answer: t(
          "아니요. 문서는 Reward Point를 출금·환전 불가로, Studio Credit을 변동원가가 큰 작업의 사용량을 통제하는 소모성 재화로 정의합니다. 현재는 직접 판매하지 않습니다(creditPurchasesEnabled=false).",
          "No. The documentation defines Reward Point as non-withdrawable and non-exchangeable, and Studio Credit as a consumable that controls usage of high variable-cost work. It is not sold directly now (creditPurchasesEnabled=false).",
        ),
      },
      {
        question: t("동시에 두 번 눌러도 이중 차감이 안 되나요?", "Does a double click still avoid double deduction?"),
        answer: t(
          "같은 사용자·자산은 advisory lock으로 한 줄이 되고, 같은 멱등 키의 예약은 새로 만들지 않고 기존 결과를 돌려줍니다. 코드를 우회해도 DB의 CHECK와 UNIQUE 제약이 한 번 더 막습니다.",
          "The same user and asset are lined up by the advisory lock, and a reservation with the same idempotency key returns the existing result rather than creating another. Even if code were bypassed, the database's CHECK and UNIQUE constraints block it once more.",
        ),
      },
      {
        question: t("AI 호출은 이 지갑을 쓰나요?", "Do AI calls use this wallet?"),
        answer: t(
          "지금은 아닙니다. 예약·정산 함수를 서비스 밖에서 부르는 코드를 찾지 못했고, 개인 API 키와 로컬 처리는 차감하지 않는 정책입니다.",
          "Not today. No code was found calling the reserve and settle functions outside the service, and the policy is that personal API keys and local processing are not deducted.",
        ),
      },
    ],
    pitfall: t(
      "'운영 중인 결제 시스템'이라고 말하면 틀립니다. 구현과 시험이 있고 판매는 꺼져 있으며, 예약·정산 함수의 서비스 밖 호출부는 apps와 packages에서 찾지 못했습니다(테스트 제외). 멤버십 화면의 개요와 활동 포인트 적립 API는 웹이 호출합니다. 운영 DB에 지갑 테이블이 적용되어 있는지는 확인하지 못했습니다.",
      "Calling it a live payment system is wrong. It is implemented and tested, sales are off, and no caller of the reserve and settle functions outside the service was found in apps or packages (tests excluded). The web does call the membership overview and activity-point APIs. Whether the wallet tables are applied in the production database was not checked.",
    ),
  },
  technologies: ["PostgreSQL", "NestJS", "Advisory lock", "Idempotency key"],
  facts: [
    {
      value: "10 minutes",
      label: t("예약의 만료 시간(TTL)", "Reservation expiry (TTL)"),
      source: "apps/api/src/modules/membership-wallet/membership-wallet.service.ts",
    },
    {
      value: "UTC+9",
      label: t("일일 한도의 날짜 경계(KST)", "Day boundary of the daily limit (KST)"),
      source: "apps/api/src/modules/membership-wallet/membership-wallet.service.ts",
    },
  ],
  reviewedAt: "2026-10-07",
};

const EXTERNAL_WRITES_UNCERTAIN_RECEIPTS: EngineeringAtlasEntry = {
  id: "external-writes-uncertain-receipts",
  category: "platform-ops",
  name: "External writes: idempotency, receipts and uncertain",
  title: t("외부에 쓰기 전에 지문을 만들고, 애매하면 다시 쏘지 않습니다", "Fingerprint before writing outward, and never re-fire when unsure"),
  status: "configured",
  tagline: t(
    "외부 쓰기는 요청 지문과 영수증으로 재생하고, 불확실한 결과는 자동으로 다시 실행하지 않습니다.",
    "External writes replay from a request fingerprint and receipt, and an uncertain result is never re-run automatically.",
  ),
  background: [
    t(
      "Notion에 작업을 만들거나 Slack에 메시지를 보내는 일처럼 외부 서비스에 쓰는 요청은, 네트워크가 끊겨도 실제로는 성공했을 수 있습니다. 이때 다시 보내면 작업이 두 개 생기거나 메시지가 두 번 갑니다. 그래서 외부 쓰기마다 요청의 지문과 영수증을 남깁니다. 같은 요청이 다시 오면 새로 실행하지 않고 이전 결과를 돌려주고, 결과가 애매하면 '불확실(uncertain)'로 기록해 사람이 공급자 상태를 확인한 뒤 새 요청 ID로 재조정하게 합니다.",
      "A request that writes to an outside service, such as creating a Notion task or sending a Slack message, may really have succeeded even if the network dropped. Sending it again then creates two tasks or two messages. So every external write leaves a fingerprint of the request and a receipt. A repeated request is not run again but gets the earlier result, and an ambiguous outcome is recorded as 'uncertain' so a person checks the provider's state and reconciles with a new request ID.",
    ),
    t(
      "모든 외부 호출은 한 함수(externalFetchJson)를 지납니다. 리다이렉트는 따라가지 않고 오류로 막고, 시간 제한을 두며, 응답 본문은 1 MiB까지만 읽습니다. 실패는 확정 실패(대부분의 4xx)와 불확실한 실패(타임아웃·네트워크·리다이렉트·과대 응답·5xx·429)로 나뉩니다. 통합 런타임의 execute는 ① 프로젝트 접근 권한 확인 ② 요청 지문 계산 ③ dryRun이면 네트워크 없이 계획만 반환 ④ 실제 실행은 dryRun=false와 confirm=true가 모두 필요 ⑤ 영수증을 잠가 같은 지문이면 성공 결과를 재생하고 다른 지문이면 충돌 처리 ⑥ 실행 뒤 succeeded·failed·uncertain을 기록합니다.",
      "Every external call goes through one function, externalFetchJson. It blocks redirects as errors rather than following them, applies a timeout and reads at most 1 MiB of the body. Failures split into definite failures (most 4xx) and uncertain ones (timeout, network, redirect, oversized reply, 5xx, 429). The integration runtime's execute (1) checks project access, (2) computes the request fingerprint, (3) for a dryRun returns only a plan with no network, (4) needs both dryRun=false and confirm=true for a real run, (5) locks the receipt, replaying a successful result for the same fingerprint and rejecting a different one as a conflict, and (6) records succeeded, failed or uncertain afterwards.",
    ),
    t(
      "영수증 상태에 따라 다시 실행해도 되는지가 갈립니다. 성공은 재생, 확정 실패는 다시 시도 가능, 진행 중이거나 불확실은 새로 실행하지 않고 막습니다. 웹훅을 내보낼 때는 HMAC-SHA256으로 본문을 서명하고, 재전송(replay)을 막으려고 배달 ID·타임스탬프·본문을 묶은 배달 서명을 함께 보냅니다. 본문만 서명하면 가로챈 요청을 그대로 다시 보낼 수 있기 때문입니다.",
      "The receipt state decides whether re-running is allowed: success is replayed, a definite failure may be retried, and an in-progress or uncertain one is blocked rather than run again. Outgoing webhooks are signed with HMAC-SHA256, and a delivery signature binding delivery ID, timestamp and body is sent too, to stop replays. Signing only the body would let a captured request be sent again as is.",
    ),
    t(
      "대안은 아웃박스 패턴과 워커 큐(QStash 어댑터가 저장소에 있음)로 백그라운드에서 재시도하는 방식입니다. 이 구현은 요청 시점의 동기 실행이며 백그라운드 재조정 워커는 확인하지 못했습니다. 외부 쓰기는 운영자 자격증명과 공급자 승인이 갖춰져야 열리므로, 실제로 켜진 공급자는 이 저장소로 확인할 수 없습니다.",
      "An alternative is the outbox pattern with a worker queue (a QStash adapter exists in the repository) retrying in the background. This implementation runs synchronously at request time, and no background reconciliation worker was found. External writes open only after operator credentials and provider approval, so which providers are really on cannot be confirmed from this repository.",
    ),
  ],
  keyPoints: [
    t("외부 호출은 한 함수로: 리다이렉트 차단 · 시간 제한 · 1 MiB 상한", "One function for outbound calls: no redirects, timeout, 1 MiB cap"),
    t("dry-run은 네트워크 없이 계획만, 실행은 confirm 필요", "dry-run plans without network; live runs need confirm"),
    t("같은 요청은 영수증 재생, 불확실하면 자동 재실행 금지", "Repeats replay the receipt; uncertain is never auto-re-run"),
    t("웹훅은 HMAC 서명에 배달 ID·시각을 묶어 재전송 방어", "Webhooks use HMAC plus delivery ID and time against replays"),
  ],
  diagram: {
    id: "external-writes-uncertain-receipts-diagram",
    kind: "graph",
    title: t("외부 쓰기 한 건이 지나는 판단", "The decisions one external write passes"),
    caption: t(
      "계획만 볼 수도 있고, 실행하면 영수증이 재생·충돌·차단·기록 중 하나로 결정합니다.",
      "You can only plan, or run; then the receipt decides among replay, conflict, block and record.",
    ),
    alt: t(
      "요청이 오면 먼저 dry-run인지 판단합니다. dry-run이면 네트워크 없이 계획만 돌려줍니다. 실행이면 요청 지문으로 영수증을 확인해, 같은 요청의 성공은 재생하고 내용이 다르면 충돌, 진행 중이거나 불확실이면 막습니다. 새 요청이면 외부 공급자를 호출하고 결과를 성공, 실패, 불확실 중 하나의 영수증으로 기록합니다.",
      "When a request arrives, the first question is whether it is a dry run. If so, only a plan is returned with no network use. Otherwise the receipt is checked by request fingerprint: a past success is replayed, different content is a conflict, and an in-progress or uncertain one is blocked. A new request calls the external provider and records the result as a succeeded, failed or uncertain receipt.",
    ),
    nodes: [
      { id: "req", label: t("외부 쓰기 요청", "External write"), tone: "local", shape: "pill", at: [0, 1] },
      { id: "dry", label: t("dry-run?", "dry-run?"), sub: t("기본값은 예", "default: yes"), tone: "neutral", shape: "diamond", at: [1, 1] },
      { id: "plan", label: t("계획만 반환", "Plan only"), sub: t("네트워크·영수증 없음", "No network, no receipt"), tone: "good", at: [1, 0] },
      { id: "receipt", label: t("영수증 확인", "Check receipt"), sub: t("요청 지문 + mutationId", "Fingerprint + mutationId"), tone: "server", shape: "cylinder", at: [2, 1] },
      { id: "replay", label: t("이전 결과 재생", "Replay result"), sub: t("성공했던 같은 요청", "Same past success"), tone: "good", at: [2, 0] },
      { id: "block", label: t("충돌 · 진행 중 · 불확실", "Conflict or in flight"), sub: t("자동 재실행 금지", "No auto re-run"), tone: "warn", at: [2, 2] },
      { id: "call", label: t("공급자 호출", "Call provider"), sub: t("실행 허용 후 단 한 번", "Once, after allow"), tone: "external", shape: "cloud", at: [3, 1] },
      { id: "record", label: t("결과 기록", "Record result"), sub: t("성공 · 실패 · 불확실", "ok, failed, uncertain"), tone: "server", at: [4, 1] },
    ],
    edges: [
      { from: "req", to: "dry" },
      { from: "dry", to: "plan", label: t("예", "yes") },
      { from: "dry", to: "receipt", label: t("실행", "run") },
      { from: "receipt", to: "replay", label: t("성공", "ok") },
      { from: "receipt", to: "block", label: t("막음", "block") },
      { from: "receipt", to: "call", label: t("새 요청", "new") },
      { from: "call", to: "record" },
    ],
  },
  usage: [
    {
      feature: t("연동 작업대 (Notion·Linear·Jira·Trello·Slack·Teams·Figma·Zoom 등)", "Integration workbench (Notion, Linear, Jira, Trello, Slack, Teams, Figma, Zoom and more)"),
      role: t(
        "프로젝트 권한을 확인한 뒤 dry-run으로 계획을 보고, confirm과 안정적인 mutationId로 실행합니다. 영수증 기록으로 같은 요청의 재시도가 안전합니다.",
        "After project permissions are checked, a dry run shows the plan, and a live run uses confirm and a stable mutationId. The receipt history makes retrying the same request safe.",
      ),
      paths: [
        "apps/api/src/modules/integration-platform/integration-runtime.service.ts#execute",
        "apps/api/src/modules/integration-platform/integration-runtime.repository.ts",
        "apps/web/src/domains/integrations/IntegrationRuntimeWorkbench.tsx",
      ],
      route: "/settings/integrations",
    },
    {
      feature: t("모든 서버→외부 호출의 공통 프리미티브", "The shared primitive for every server-to-outside call"),
      role: t(
        "리다이렉트 차단, 시간 제한, 응답 크기 상한, 불확실한 실패의 분류를 한곳에서 하고, 결제 승인도 이 분류를 씁니다.",
        "Redirect blocking, timeouts, a response-size cap and the classification of uncertain failures happen in one place, and payment approval uses this classification too.",
      ),
      paths: ["apps/api/src/modules/production-collaboration/production-integration-http.ts"],
    },
    {
      feature: t("서명된 웹훅 보내기", "Sending signed webhooks"),
      role: t(
        "본문을 정규화한 뒤 HMAC-SHA256으로 서명하고, 배달 ID·타임스탬프·본문을 묶은 배달 서명을 함께 보냅니다.",
        "The body is canonicalized and signed with HMAC-SHA256, and a delivery signature binding delivery ID, timestamp and body is sent with it.",
      ),
      paths: [
        "apps/api/src/modules/production-collaboration/production-notification-provider.ts",
        "apps/api/src/modules/integration-platform/integration-platform.service.ts#developerManifest",
      ],
      route: "/developers",
    },
  ],
  samples: [
    {
      kind: "simplified",
      title: t("'성공했을 수도 있는 실패'를 가르는 외부 호출", "An outbound call that separates 'might have succeeded' failures"),
      language: "ts",
      code: [
        "export class ExternalError extends Error {",
        "  constructor(readonly code: string, readonly status: number | null, readonly uncertain: boolean) {",
        "    super(code);",
        "  }",
        "}",
        "",
        "export async function externalFetch(url: string, init: RequestInit, timeoutMs: number): Promise<Response> {",
        "  let response: Response;",
        "  try {",
        '    response = await fetch(url, { ...init, redirect: "manual", signal: AbortSignal.timeout(timeoutMs) });',
        "  } catch (error) {",
        '    const timedOut = error instanceof DOMException && error.name === "TimeoutError";',
        '    throw new ExternalError(timedOut ? "external_timeout" : "external_network_error", null, true); // 응답을 못 받았다',
        "  }",
        "  if (response.status >= 300 && response.status < 400) {",
        '    throw new ExternalError("external_redirect_blocked", response.status, true); // 리다이렉트는 따라가지 않는다',
        "  }",
        "  if (!response.ok) {",
        "    // 5xx·429는 서버가 처리했을 수도 있어 uncertain, 그 외 4xx는 확정 실패다",
        "    throw new ExternalError(`external_http_${response.status}`, response.status, response.status >= 500 || response.status === 429);",
        "  }",
        "  return response;",
        "}",
      ].join("\n"),
      codeEn: [
        "export class ExternalError extends Error {",
        "  constructor(readonly code: string, readonly status: number | null, readonly uncertain: boolean) {",
        "    super(code);",
        "  }",
        "}",
        "",
        "export async function externalFetch(url: string, init: RequestInit, timeoutMs: number): Promise<Response> {",
        "  let response: Response;",
        "  try {",
        '    response = await fetch(url, { ...init, redirect: "manual", signal: AbortSignal.timeout(timeoutMs) });',
        "  } catch (error) {",
        '    const timedOut = error instanceof DOMException && error.name === "TimeoutError";',
        '    throw new ExternalError(timedOut ? "external_timeout" : "external_network_error", null, true); // no reply was received',
        "  }",
        "  if (response.status >= 300 && response.status < 400) {",
        '    throw new ExternalError("external_redirect_blocked", response.status, true); // redirects are not followed',
        "  }",
        "  if (!response.ok) {",
        "    // 5xx and 429 may have been processed, so uncertain; other 4xx are definite failures",
        "    throw new ExternalError(`external_http_${response.status}`, response.status, response.status >= 500 || response.status === 429);",
        "  }",
        "  return response;",
        "}",
      ].join("\n"),
      explain: t(
        "실제 함수는 호출자의 AbortSignal과 타임아웃을 결합하고, 본문을 1 MiB까지만 읽으며, 실패 본문은 4,096자만 보존합니다. 이 분류가 결제 승인의 '조회로 확정'과 통합 런타임의 'uncertain 영수증'을 모두 이끕니다.",
        "The real function combines the caller's AbortSignal with the timeout, reads at most 1 MiB and keeps only 4,096 characters of a failure body. This classification drives both the payment 'settle by query' and the runtime's 'uncertain receipt'.",
      ),
      source: "apps/api/src/modules/production-collaboration/production-integration-http.ts",
      verify: "types",
    },
    {
      kind: "simplified",
      title: t("영수증 상태로 재생·재시도·차단 정하기", "Choosing replay, retry or block from the receipt state"),
      language: "ts",
      code: [
        'type ReceiptState = "pending" | "succeeded" | "failed" | "uncertain";',
        "interface Receipt { digest: string; state: ReceiptState; response?: unknown }",
        "",
        "export function resolveReceipt(existing: Receipt, digest: string) {",
        '  if (existing.digest !== digest) throw new Error("같은 요청 ID에 다른 내용이 왔다(충돌)");',
        "  switch (existing.state) {",
        '    case "succeeded":',
        "      return { replay: existing.response, retry: false } as const; // 이전 결과를 그대로 돌려준다",
        '    case "failed":',
        "      return { replay: undefined, retry: true } as const; // 확정 실패는 다시 시도해도 안전하다",
        "    default:",
        "      // pending·uncertain: 새로 쏘지 않는다. 사람이 공급자 상태를 보고 새 요청 ID로 재조정한다",
        "      throw new Error(`이전 시도가 ${existing.state} 상태다`);",
        "  }",
        "}",
      ].join("\n"),
      codeEn: [
        'type ReceiptState = "pending" | "succeeded" | "failed" | "uncertain";',
        "interface Receipt { digest: string; state: ReceiptState; response?: unknown }",
        "",
        "export function resolveReceipt(existing: Receipt, digest: string) {",
        '  if (existing.digest !== digest) throw new Error("different content arrived for the same request ID (conflict)");',
        "  switch (existing.state) {",
        '    case "succeeded":',
        "      return { replay: existing.response, retry: false } as const; // return the earlier result as is",
        '    case "failed":',
        "      return { replay: undefined, retry: true } as const; // a definite failure is safe to retry",
        "    default:",
        "      // pending or uncertain: never fire again; a person checks the provider and reconciles with a new request ID",
        "      throw new Error(`the earlier attempt is ${existing.state}`);",
        "  }",
        "}",
      ].join("\n"),
      explain: t(
        "실제 저장소는 (프로젝트, 행위자, mutationId) 영수증을 사용자·UTC 창 단위 advisory lock 안에서 FOR UPDATE로 잠근 뒤 이 판정을 합니다. 지문은 {projectId, request}에서 계산합니다.",
        "The real repository makes this decision after locking the (project, actor, mutationId) receipt with FOR UPDATE inside a per-user, per-UTC-window advisory lock. The fingerprint is computed from {projectId, request}.",
      ),
      source: "apps/api/src/modules/integration-platform/integration-runtime.repository.ts",
      verify: "types",
    },
  ],
  links: [
    {
      title: "RFC 2104 · HMAC",
      url: "https://datatracker.ietf.org/doc/html/rfc2104",
      kind: "spec",
      note: t("웹훅 서명에 쓰는 HMAC의 정의", "The definition of HMAC used for webhook signing"),
    },
    {
      title: "Stripe · Verify webhook signatures manually",
      url: "https://docs.stripe.com/webhooks#verify-manually",
      kind: "guide",
      note: t("타임스탬프 허용 창과 재전송 방어의 일반 예", "A general example of timestamp tolerance and replay defense"),
    },
    {
      title: "MDN · AbortSignal.any()",
      url: "https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/any_static",
      kind: "docs",
      note: t("호출자 신호와 타임아웃 신호를 합치는 방법", "Combining a caller's signal with a timeout signal"),
    },
    {
      title: "Notion API",
      url: "https://developers.notion.com/guides/get-started/overview",
      kind: "docs",
      note: t("연동 대상 공급자의 공식 문서 예시", "An example of a connected provider's official docs"),
    },
  ],
  chapterIds: ["infrastructure", "troubleshooting-evidence"],
  talk: {
    pitch: t(
      "외부 서비스에 무언가를 쓸 때는 보내기 전에 요청의 지문을 만들고, 결과를 영수증으로 남깁니다. 같은 요청이 다시 오면 다시 쏘지 않고 이전 영수증을 돌려주고, 결과가 애매하면 '불확실'로 기록한 뒤 자동으로 다시 시도하지 않습니다. 사람이 공급자 상태를 확인하고 새 요청으로 정리하는 구조입니다. 실행 전에는 네트워크 없이 계획만 보는 dry-run도 있습니다.",
      "Before writing to an outside service, a fingerprint of the request is made and the result is kept as a receipt. A repeated request is not fired again but gets the earlier receipt, and an ambiguous result is recorded as 'uncertain' and never retried automatically; a person checks the provider's state and settles it with a new request. Before running there is also a dry run that shows only a plan, with no network.",
    ),
    analogy: t(
      "등기우편의 접수증과 같습니다. 같은 접수번호로 다시 접수하면 새로 보내지 않고 기존 건을 알려 줍니다.",
      "Like a registered-mail receipt: filing again with the same number does not send a new letter but shows the existing case.",
    ),
    questions: [
      {
        question: t("공급자 비밀번호를 받나요?", "Does it take provider passwords?"),
        answer: t(
          "아니요. 서버 비밀은 운영자만 설정하고, 브라우저는 요청 JSON만 보냅니다. 개발자 매니페스트도 공급자 비밀번호를 받지 않으며 원본 프로젝트 파일은 별도 허가가 필요하다고 선언합니다.",
          "No. Server secrets are set only by operators and the browser sends only request JSON. The developer manifest also declares that provider passwords are not accepted and raw project files need a separate grant.",
        ),
      },
      {
        question: t("불확실한 건은 어떻게 풀리나요?", "How does an uncertain case get resolved?"),
        answer: t(
          "응답에 '자동 재실행하지 말고 공급자 상태를 확인하라'고 안내하고 영수증을 uncertain으로 남깁니다. 공급자에서 실제 결과를 확인한 뒤 새 요청 ID로 다시 처리하는 것이 약속입니다.",
          "The reply tells the caller not to re-run automatically but to check the provider, and the receipt stays uncertain. The agreed path is to confirm the real outcome at the provider and then act with a new request ID.",
        ),
      },
      {
        question: t("웹훅을 받는 쪽은 무엇을 해야 하나요?", "What should the receiver of a webhook do?"),
        answer: t(
          "서명을 상수 시간으로 비교하고, 타임스탬프가 허용 시간 창(개발자 계약은 300초) 안인지 보고, 배달 ID 중복을 거르는 것이 모범 사례입니다. 본문만 서명하면 재전송을 막지 못합니다.",
          "Best practice is to compare the signature in constant time, check the timestamp is within the tolerance window (300 seconds in the developer contract) and de-duplicate the delivery ID. Signing only the body cannot stop replays.",
        ),
      },
    ],
    pitfall: t(
      "개발자 매니페스트가 안내하는 타임스탬프 헤더 이름(x-toonstudio-timestamp)과 실제로 보내는 헤더(X-ToonStudio-Delivery-Timestamp와 배달 서명)가 다릅니다. 외부 개발자 문서를 만들기 전에 정정이 필요합니다. 또 운영에서 켜진 공급자와 실계정 영수증은 확인하지 못했고, 백그라운드 재조정 워커는 찾지 못했습니다.",
      "The timestamp header name the developer manifest advertises (x-toonstudio-timestamp) differs from what is actually sent (X-ToonStudio-Delivery-Timestamp plus a delivery signature); it needs correcting before external developer docs are written. Also, the providers actually enabled in production and real-account receipts were not checked, and no background reconciliation worker was found.",
    ),
  },
  technologies: ["NestJS", "PostgreSQL", "HMAC", "AbortController", "Idempotency-Key"],
  facts: [
    {
      value: "1 MiB",
      label: t("외부 응답 본문의 읽기 상한(기본 인자)", "Read cap on an external response body (default argument)"),
      source: "apps/api/src/modules/production-collaboration/production-integration-http.ts",
    },
    {
      value: "11",
      label: t("통합 런타임 커넥터 수", "Integration runtime connectors"),
      source: "apps/api/src/modules/integration-platform/integration-runtime.contract.ts",
    },
    {
      value: "300 s",
      label: t("개발자 계약의 웹훅 재전송 허용 창", "Webhook replay window in the developer contract"),
      source: "apps/api/src/modules/integration-platform/integration-platform.service.ts",
    },
  ],
  reviewedAt: "2026-10-07",
};

export const PLATFORM_OPS_TRANSACTION_CARDS: readonly EngineeringAtlasEntry[] = [
  PAYMENT_IDEMPOTENCY_WEBHOOK_RECONCILE,
  WALLET_RESERVE_CAPTURE_LEDGER,
  EXTERNAL_WRITES_UNCERTAIN_RECEIPTS,
];
