/**
 * 실제로 설치해 쓰는 라이브러리의 라이선스 현황.
 *
 * 수집 기준 (2026-10-07 실측): 워크스페이스 전 패키지(루트, apps/*, packages/*,
 * tests/integration/*)의 package.json에서 직접 의존성(dependencies와
 * optionalDependencies, workspace 내부 패키지 제외) 117개를 뽑고, 라이선스 명과
 * 공식 링크(url)는 설치된 패키지의 package.json license·homepage·repository
 * 필드에서 확인했다. 버전은 pnpm-lock.yaml importers가 고정한 직접 resolved
 * version만 적는다 — 전이 관계로만 고정된 버전은 이 표에 넣지 않는다.
 * 재측정과 차분 확인은 scripts/collect-engineering-licenses.mjs가 맡는다.
 * 전이 의존성과 개발 전용 도구(devDependencies: Vite, Vitest, Playwright, ESLint,
 * TypeScript 등)는 이 표의 범위가 아니며, 전이 의존성 전체는 배포 빌드가 생성하는
 * dist/legal/THIRD_PARTY_NOTICES.generated.md와 pnpm audit:licenses가 맡는다.
 */
import type { LocalizedText } from "./engineering-story-content";

export type EngineeringLicenseSurface = "web" | "api" | "mobile" | "labs";

/** weak-copyleft: MPL·LGPL처럼 파일·라이브러리 단위 카피레프트. noncommercial: 비상업 조건. custom-license: 표준 SPDX가 아닌 자체 라이선스. */
export type EngineeringLicenseFlag = "weak-copyleft" | "noncommercial" | "custom-license";

export interface EngineeringLibraryLicense {
  readonly name: string;
  readonly version: string;
  readonly license: string;
  /**
   * 설치본 package.json의 homepage(없으면 repository)에서 확인한 공식 링크. 자체 패키지 등 출처가 없는 항목과,
   * 홈페이지 도메인이 사라져(DNS 실패, 2026-10-07 확인) 대체 주소를 확정하지 못한 colormix만 비운다.
   * 평문 http와 이동·변경된 주소(simplify-js, reflect-metadata 등)는 2026-10-07에 최종 https 주소로 바꿨다.
   */
  readonly url?: string;
  readonly surface: EngineeringLicenseSurface;
  readonly flag?: EngineeringLicenseFlag;
  readonly role: LocalizedText;
}

export const ENGINEERING_LIBRARY_LICENSE_REVIEWED_AT = "2026-10-07";

export const ENGINEERING_LIBRARY_LICENSES: readonly EngineeringLibraryLicense[] = [
  {
    name: "@automerge/automerge",
    version: "3.5.0",
    license: "MIT",
    url: "https://github.com/automerge/automerge/tree/main/javascript",
    surface: "web",
    role: { ko: "오프라인 작업 브랜치의 문서 병합", en: "Merging offline work-branch documents" },
  },
  {
    name: "@babylonjs/core",
    version: "9.19.0",
    license: "Apache-2.0",
    url: "https://www.babylonjs.com",
    surface: "web",
    role: { ko: "Babylon.js 3D 엔진 코어(캐릭터 랩 등)", en: "Babylon.js 3D engine core (character lab and more)" },
  },
  {
    name: "@babylonjs/loaders",
    version: "9.19.0",
    license: "Apache-2.0",
    url: "https://www.babylonjs.com",
    surface: "web",
    role: { ko: "Babylon.js 3D 자산 로더", en: "Babylon.js 3D asset loaders" },
  },
  {
    name: "@dimforge/rapier3d-deterministic-compat",
    version: "0.19.3",
    license: "Apache-2.0",
    url: "https://rapier.rs",
    surface: "web",
    role: { ko: "결정적 3D 물리 시뮬레이션", en: "Deterministic 3D physics simulation" },
  },
  {
    name: "@gltf-transform/core",
    version: "4.4.2",
    license: "MIT",
    url: "https://gltf-transform.dev/",
    surface: "web",
    role: { ko: "glTF 자산 변환 파이프라인 코어", en: "Core of the glTF asset transform pipeline" },
  },
  {
    name: "@gltf-transform/extensions",
    version: "4.4.2",
    license: "MIT",
    url: "https://gltf-transform.dev/extensions",
    surface: "web",
    role: { ko: "glTF 확장(KHR 등) 처리", en: "Handling glTF extensions such as KHR" },
  },
  {
    name: "@gltf-transform/functions",
    version: "4.4.2",
    license: "MIT",
    url: "https://gltf-transform.dev/functions",
    surface: "web",
    role: { ko: "glTF 최적화·변환 함수군", en: "glTF optimization and transform functions" },
  },
  {
    name: "@heejun/deskcloud",
    version: "0.1.0",
    license: "MIT",
    surface: "web",
    role: { ko: "자체 데스크 클라우드 연동", en: "First-party desk-cloud integration" },
  },
  {
    name: "@hookform/resolvers",
    version: "5.4.0",
    license: "MIT",
    url: "https://react-hook-form.com",
    surface: "web",
    role: { ko: "폼 검증 스키마 리졸버 연결", en: "Connecting form validation schema resolvers" },
  },
  {
    name: "@huggingface/transformers",
    version: "4.3.0",
    license: "Apache-2.0",
    url: "https://github.com/huggingface/transformers.js#readme",
    surface: "web",
    role: { ko: "리서치 데스크 한글 질의의 기기 안 번역(Transformers.js)", en: "On-device translation of the research desk's Korean queries (Transformers.js)" },
  },
  {
    name: "@mediapipe/tasks-vision",
    version: "0.10.35",
    license: "Apache-2.0",
    url: "https://mediapipe.dev/",
    surface: "web",
    role: { ko: "웹캠 포즈·손·얼굴 추적", en: "Webcam pose, hand and face tracking" },
  },
  {
    name: "@pixiv/three-vrm",
    version: "3.5.3",
    license: "MIT",
    url: "https://github.com/pixiv/three-vrm",
    surface: "web",
    role: { ko: "VRM 캐릭터 모델 로딩과 표현", en: "Loading and posing VRM character models" },
  },
  {
    name: "@radix-ui/react-dialog",
    version: "1.1.16",
    license: "MIT",
    url: "https://www.radix-ui.com/primitives",
    surface: "web",
    role: { ko: "다이얼로그 UI 프리미티브", en: "Dialog UI primitive" },
  },
  {
    name: "@radix-ui/react-dropdown-menu",
    version: "2.1.17",
    license: "MIT",
    url: "https://www.radix-ui.com/primitives",
    surface: "web",
    role: { ko: "드롭다운 메뉴 UI 프리미티브", en: "Dropdown menu UI primitive" },
  },
  {
    name: "@radix-ui/react-select",
    version: "2.3.0",
    license: "MIT",
    url: "https://www.radix-ui.com/primitives",
    surface: "web",
    role: { ko: "셀렉트 UI 프리미티브", en: "Select UI primitive" },
  },
  {
    name: "@react-three/drei",
    version: "10.7.7",
    license: "MIT",
    url: "https://github.com/pmndrs/drei",
    surface: "web",
    role: { ko: "React Three Fiber 보조 컴포넌트 모음", en: "Helper components for React Three Fiber" },
  },
  {
    name: "@react-three/fiber",
    version: "9.6.1",
    license: "MIT",
    url: "https://github.com/pmndrs/react-three-fiber#readme",
    surface: "web",
    role: { ko: "Three.js의 React 렌더러", en: "React renderer for Three.js" },
  },
  {
    name: "@remotion/player",
    version: "4.0.514",
    license: "Remotion License",
    url: "https://www.remotion.dev/docs/player",
    surface: "web",
    flag: "custom-license",
    role: { ko: "제품 투어 영상의 인페이지 플레이어", en: "In-page player for product-tour films" },
  },
  {
    name: "@resvg/resvg-wasm",
    version: "2.6.2",
    license: "MPL-2.0",
    url: "https://github.com/yisibl/resvg-js",
    surface: "web",
    flag: "weak-copyleft",
    role: { ko: "SVG 래스터화 WASM", en: "SVG rasterization WASM" },
  },
  {
    name: "@sparkjsdev/spark",
    version: "2.2.0",
    license: "MIT",
    url: "https://sparkjs.dev/",
    surface: "web",
    role: { ko: "3D 가우시안 스플랫 참조 렌더링", en: "3D Gaussian splat reference rendering" },
  },
  {
    name: "@sqlite.org/sqlite-wasm",
    version: "3.53.0-build1",
    license: "Apache-2.0",
    url: "https://github.com/sqlite/sqlite-wasm#readme",
    surface: "web",
    role: { ko: "브라우저 로컬 데이터베이스(SQLite WASM)", en: "Browser-local database (SQLite WASM)" },
  },
  {
    name: "@tanstack/react-virtual",
    version: "3.14.13",
    license: "MIT",
    url: "https://tanstack.com/virtual/latest",
    surface: "web",
    role: { ko: "긴 목록의 가상 스크롤", en: "Virtual scrolling for long lists" },
  },
  {
    name: "@techstark/opencv-js",
    version: "5.0.0-release.1",
    license: "Apache-2.0",
    url: "https://github.com/TechStark/opencv-js#readme",
    surface: "web",
    role: { ko: "이미지 처리 연산(OpenCV WASM)", en: "Image processing operations (OpenCV WASM)" },
  },
  {
    name: "@thorvg/webcanvas",
    version: "1.1.2",
    license: "MIT",
    url: "https://www.thorvg.org/",
    surface: "web",
    role: { ko: "ThorVG 벡터 렌더러 엔진 패키지", en: "ThorVG vector renderer engine package" },
  },
  {
    name: "ag-psd",
    version: "31.0.1",
    license: "MIT",
    url: "https://github.com/Agamnentzar/ag-psd",
    surface: "web",
    role: { ko: "PSD 파일 읽기와 쓰기", en: "Reading and writing PSD files" },
  },
  {
    name: "bezier-js",
    version: "6.1.4",
    license: "MIT",
    url: "https://github.com/Pomax/bezierjs",
    surface: "web",
    role: { ko: "벡터 잉크의 베지어 곡선 계산", en: "Bézier curve math for vector ink" },
  },
  {
    name: "canvaskit-wasm",
    version: "0.41.1",
    license: "BSD-3-Clause",
    url: "https://github.com/google/skia/tree/main/modules/canvaskit",
    surface: "web",
    role: { ko: "Skia(CanvasKit) 렌더러 WASM", en: "Skia (CanvasKit) renderer WASM" },
  },
  {
    name: "closed-chain-ik",
    version: "0.0.3",
    license: "Apache-2.0",
    url: "https://github.com/gkjohnson/closed-chain-ik-js#readme",
    surface: "web",
    role: { ko: "캐릭터 리깅의 IK 솔버", en: "IK solver for character rigging" },
  },
  {
    name: "clsx",
    version: "2.1.1",
    license: "MIT",
    url: "https://github.com/lukeed/clsx",
    surface: "web",
    role: { ko: "클래스 이름 조합 유틸리티", en: "Class-name composition utility" },
  },
  {
    name: "cmdk",
    version: "1.1.1",
    license: "MIT",
    url: "https://github.com/pacocoursey/cmdk#readme",
    surface: "web",
    role: { ko: "커맨드 팔레트 UI", en: "Command palette UI" },
  },
  {
    name: "colorjs.io",
    version: "0.7.1",
    license: "MIT",
    url: "https://colorjs.io",
    surface: "web",
    role: { ko: "색공간 변환 계산", en: "Color-space conversion math" },
  },
  {
    name: "colormix",
    version: "3.2.0",
    license: "MIT",
    surface: "web",
    role: { ko: "브러시 안료 혼합 계산", en: "Pigment mixing math for brushes" },
  },
  {
    name: "culori",
    version: "4.0.2",
    license: "MIT",
    url: "https://github.com/Evercoder/culori",
    surface: "web",
    role: { ko: "색상 변환과 보간", en: "Color conversion and interpolation" },
  },
  {
    name: "embla-carousel-autoplay",
    version: "8.6.0",
    license: "MIT",
    url: "https://www.embla-carousel.com",
    surface: "web",
    role: { ko: "캐러셀 자동 재생 플러그인", en: "Carousel autoplay plugin" },
  },
  {
    name: "embla-carousel-react",
    version: "8.6.0",
    license: "MIT",
    url: "https://www.embla-carousel.com",
    surface: "web",
    role: { ko: "홈과 쇼케이스의 캐러셀", en: "Carousels on home and showcase surfaces" },
  },
  {
    name: "fit-curve",
    version: "0.2.0",
    license: "MIT",
    url: "https://github.com/soswow/fit-curve",
    surface: "web",
    role: { ko: "획을 곡선으로 피팅", en: "Fitting strokes to curves" },
  },
  {
    name: "harfbuzzjs",
    version: "1.4.0",
    license: "MIT",
    url: "https://harfbuzz.github.io/harfbuzzjs",
    surface: "web",
    role: { ko: "식자 텍스트 셰이핑 WASM", en: "Text shaping WASM for lettering" },
  },
  {
    name: "html-to-image",
    version: "1.11.13",
    license: "MIT",
    url: "https://github.com/bubkoo/html-to-image#readme",
    surface: "web",
    role: { ko: "DOM을 이미지로 내보내기", en: "Exporting DOM to images" },
  },
  {
    name: "konva",
    version: "10.3.0",
    license: "MIT",
    url: "https://konvajs.org/",
    surface: "web",
    role: { ko: "2D 캔버스 편집 표면", en: "2D canvas editing surface" },
  },
  {
    name: "korean-lunar-calendar",
    version: "0.4.0",
    license: "MIT",
    url: "https://github.com/usingsky/korean_lunar_calendar_js#readme",
    surface: "web",
    role: { ko: "음력 날짜 변환", en: "Korean lunar calendar conversion" },
  },
  {
    name: "ktx2-encoder",
    version: "0.6.0",
    license: "MIT",
    url: "https://github.com/gz65555/ktx2-encoder",
    surface: "web",
    role: { ko: "KTX2 텍스처 인코딩", en: "KTX2 texture encoding" },
  },
  {
    name: "ky",
    version: "2.0.2",
    license: "MIT",
    url: "https://github.com/sindresorhus/ky",
    surface: "web",
    role: { ko: "HTTP 클라이언트", en: "HTTP client" },
  },
  {
    name: "lazy-brush",
    version: "2.0.2",
    license: "MIT",
    url: "https://github.com/dulnan/lazy-brush",
    surface: "web",
    role: { ko: "브러시 획 안정화", en: "Brush stroke stabilization" },
  },
  {
    name: "lucide-react",
    version: "1.17.0",
    license: "ISC",
    url: "https://lucide.dev",
    surface: "web",
    role: { ko: "UI 아이콘 세트", en: "UI icon set" },
  },
  {
    name: "lunar-typescript",
    version: "1.8.6",
    license: "MIT",
    url: "https://github.com/6tail/lunar-typescript",
    surface: "web",
    role: { ko: "음력과 절기 계산", en: "Lunar calendar and solar-term calculation" },
  },
  {
    name: "manifold-3d",
    version: "3.5.1",
    license: "Apache-2.0",
    url: "https://github.com/elalish/manifold#readme",
    surface: "web",
    role: { ko: "3D 메시 boolean 연산", en: "3D mesh boolean operations" },
  },
  {
    name: "meshoptimizer",
    version: "1.2.0",
    license: "MIT",
    url: "https://github.com/zeux/meshoptimizer",
    surface: "web",
    role: { ko: "3D 메시 압축과 최적화", en: "3D mesh compression and optimization" },
  },
  {
    name: "mixbox",
    version: "2.0.0",
    license: "CC-BY-NC-4.0",
    url: "https://scrtwpns.com/mixbox",
    surface: "web",
    flag: "noncommercial",
    role: { ko: "안료 스펙트럴 혼합 — 브러시 V6 안료 provider가 정적으로 import하고, 라이선스 프로필이 비상업 조건을 게이트합니다(기본값 noncommercial-full)", en: "Spectral pigment mixing — statically imported by the Brush V6 pigment provider, with the license profile gating the non-commercial terms (default noncommercial-full)" },
  },
  {
    name: "motion",
    version: "12.40.0",
    license: "MIT",
    url: "https://github.com/motiondivision/motion",
    surface: "web",
    role: { ko: "UI 애니메이션 라이브러리", en: "UI animation library" },
  },
  {
    name: "multiformats",
    version: "14.0.5",
    license: "Apache-2.0 OR MIT",
    url: "https://github.com/multiformats/js-multiformats#readme",
    surface: "web",
    role: { ko: "IPFS CID 생성·파싱과 해시 검증의 기반 라이브러리", en: "Base library for IPFS CID creation, parsing and hash verification" },
  },
  {
    name: "onnxruntime-web",
    version: "1.27.0",
    license: "MIT",
    url: "https://github.com/Microsoft/onnxruntime",
    surface: "web",
    role: { ko: "브라우저 안 AI 추론 런타임", en: "In-browser AI inference runtime" },
  },
  {
    name: "opencascade.js",
    version: "1.1.1",
    license: "LGPL-2.1-only",
    url: "https://github.com/donalffons/opencascade.js",
    surface: "web",
    flag: "weak-copyleft",
    role: { ko: "CAD 정밀 형상 연산 WASM", en: "CAD precision geometry WASM" },
  },
  {
    name: "openskp",
    version: "1.3.0",
    license: "MIT",
    url: "https://openskp.com",
    surface: "web",
    role: { ko: "SketchUp .skp 파일을 브라우저에서 GLB로 변환", en: "Converting SketchUp .skp files to GLB in the browser" },
  },
  {
    name: "p5.brush",
    version: "2.2.1",
    license: "MIT",
    url: "https://p5-brush.cargo.site/",
    surface: "web",
    role: { ko: "자연 매체 브러시(standalone 진입점)", en: "Natural-media brushes (standalone entry)" },
  },
  {
    name: "paper",
    version: "0.12.18",
    license: "MIT",
    url: "https://paperjs.org/",
    surface: "web",
    role: { ko: "벡터 경로와 기하 연산", en: "Vector path and geometry operations" },
  },
  {
    name: "pdf-lib",
    version: "1.17.1",
    license: "MIT",
    url: "https://pdf-lib.js.org",
    surface: "web",
    role: { ko: "PDF 워크벤치의 병합·재배열·회전·분할(브라우저 안 실행)", en: "Merge, reorder, rotate and split in the PDF workbench (runs in the browser)" },
  },
  {
    name: "pdfjs-dist",
    version: "6.4.299",
    license: "Apache-2.0",
    url: "https://mozilla.github.io/pdf.js/",
    surface: "web",
    role: { ko: "PDF 워크벤치의 페이지 썸네일 렌더링(지연 로드)", en: "Page thumbnail rendering for the PDF workbench (lazy-loaded)" },
  },
  {
    name: "perfect-freehand",
    version: "1.2.3",
    license: "MIT",
    url: "https://github.com/steveruizok/perfect-freehand",
    surface: "web",
    role: { ko: "필압 기반 획 윤곽 생성", en: "Pressure-based stroke outline generation" },
  },
  {
    name: "phaser",
    version: "3.90.0",
    license: "MIT",
    url: "https://phaser.io",
    surface: "web",
    role: { ko: "가상 스튜디오 2D 월드 엔진", en: "2D world engine for the virtual studio" },
  },
  {
    name: "pixi.js",
    version: "8.19.0",
    license: "MIT",
    url: "https://pixijs.com/",
    surface: "web",
    role: { ko: "2D 렌더링 표면", en: "2D rendering surface" },
  },
  {
    name: "polygon-clipping",
    version: "0.15.7",
    license: "MIT",
    url: "https://github.com/mfogel/polygon-clipping",
    surface: "web",
    role: { ko: "획 벡터화의 폴리곤 연산", en: "Polygon operations for stroke vectorization" },
  },
  {
    name: "qrcode",
    version: "1.5.4",
    license: "MIT",
    url: "https://github.com/soldair/node-qrcode",
    surface: "web",
    role: { ko: "공유 링크 QR 코드 생성", en: "QR code generation for share links" },
  },
  {
    name: "rbush",
    version: "4.0.1",
    license: "MIT",
    url: "https://github.com/mourner/rbush",
    surface: "web",
    role: { ko: "렌더 장면 공간 인덱스", en: "Spatial index for render scenes" },
  },
  {
    name: "react",
    version: "19.2.7",
    license: "MIT",
    url: "https://react.dev/",
    surface: "web",
    role: { ko: "UI 런타임", en: "UI runtime" },
  },
  {
    name: "react-dom",
    version: "19.2.7",
    license: "MIT",
    url: "https://react.dev/",
    surface: "web",
    role: { ko: "React DOM 렌더러", en: "React DOM renderer" },
  },
  {
    name: "react-hook-form",
    version: "7.77.0",
    license: "MIT",
    url: "https://react-hook-form.com",
    surface: "web",
    role: { ko: "폼 상태 관리", en: "Form state management" },
  },
  {
    name: "react-konva",
    version: "19.2.4",
    license: "MIT",
    url: "https://github.com/konvajs/react-konva",
    surface: "web",
    role: { ko: "Konva의 React 바인딩", en: "React bindings for Konva" },
  },
  {
    name: "react-router-dom",
    version: "7.18.2",
    license: "MIT",
    url: "https://github.com/remix-run/react-router",
    surface: "web",
    role: { ko: "클라이언트 라우팅", en: "Client routing" },
  },
  {
    name: "recast-navigation",
    version: "0.43.1",
    license: "MIT",
    url: "https://github.com/isaac-mason/recast-navigation-js",
    surface: "web",
    role: { ko: "3D 내비메시 경로 탐색", en: "3D navmesh pathfinding" },
  },
  {
    name: "remotion",
    version: "4.0.514",
    license: "Remotion License",
    url: "https://www.remotion.dev/docs/remotion",
    surface: "web",
    flag: "custom-license",
    role: { ko: "홍보·투어 영상의 프로그램 렌더링", en: "Programmatic rendering of promo and tour films" },
  },
  {
    name: "rhino3dm",
    version: "8.32.1",
    license: "MIT",
    url: "https://github.com/mcneel/rhino3dm#readme",
    surface: "web",
    role: { ko: "openNURBS 3D 파일 WASM", en: "openNURBS 3D file WASM" },
  },
  {
    name: "roughjs",
    version: "4.6.6",
    license: "MIT",
    url: "https://roughjs.com",
    surface: "web",
    role: { ko: "손그림풍 벡터 렌더링", en: "Hand-drawn style vector rendering" },
  },
  {
    name: "simplify-js",
    version: "1.2.4",
    license: "BSD-2-Clause",
    url: "https://mourner.github.io/simplify-js/",
    surface: "web",
    role: { ko: "경로 단순화", en: "Path simplification" },
  },
  {
    name: "socket.io-client",
    version: "4.8.3",
    license: "MIT",
    url: "https://github.com/socketio/socket.io/tree/main/packages/socket.io-client#readme",
    surface: "web",
    role: { ko: "실시간 협업 소켓 클라이언트", en: "Realtime collaboration socket client" },
  },
  {
    name: "spectral.js",
    version: "3.0.0",
    license: "MIT",
    url: "https://github.com/rvanwijnen/spectral.js#readme",
    surface: "web",
    role: { ko: "브러시 랩의 스펙트럴 색 혼합", en: "Spectral color mixing in the brush lab" },
  },
  {
    name: "tailwind-merge",
    version: "3.6.0",
    license: "MIT",
    url: "https://github.com/dcastil/tailwind-merge",
    surface: "web",
    role: { ko: "Tailwind 클래스 병합 유틸리티", en: "Tailwind class merging utility" },
  },
  {
    name: "three",
    version: "0.184.0",
    license: "MIT",
    url: "https://threejs.org/",
    surface: "web",
    role: { ko: "3D 렌더링 엔진", en: "3D rendering engine" },
  },
  {
    name: "three-bvh-csg",
    version: "0.0.18",
    license: "MIT",
    url: "https://github.com/gkjohnson/three-bvh-csg#readme",
    surface: "web",
    role: { ko: "메시 CSG(boolean) 연산", en: "Mesh CSG (boolean) operations" },
  },
  {
    name: "three-mesh-bvh",
    version: "0.9.13",
    license: "MIT",
    url: "https://github.com/gkjohnson/three-mesh-bvh#readme",
    surface: "web",
    role: { ko: "메시 가속 구조(BVH)", en: "Mesh acceleration structure (BVH)" },
  },
  {
    name: "wasm-vips",
    version: "0.0.18",
    license: "MIT",
    url: "https://github.com/kleisauke/wasm-vips",
    surface: "web",
    role: { ko: "대형 이미지 내보내기 처리(libvips WASM) — 래퍼는 MIT, 번들된 libvips·libheif 등은 LGPL이며 엔진 레지스트리는 'LGPL 격리 배포가 필요한 후보'로 기록합니다", en: "Large-image export processing (libvips WASM) — the wrapper is MIT while bundled libvips, libheif and others are LGPL; the engine registry records it as a candidate requiring LGPL-isolated deployment" },
  },
  {
    name: "web-ifc",
    version: "0.0.77",
    license: "MPL-2.0",
    url: "https://github.com/ThatOpen/engine_web-ifc",
    surface: "web",
    flag: "weak-copyleft",
    role: { ko: "IFC 건축 모델 로딩 WASM", en: "IFC building model loading WASM" },
  },
  {
    name: "xatlasjs",
    version: "0.2.0",
    license: "MIT",
    url: "https://github.com/repalash/xatlas.js#readme",
    surface: "web",
    role: { ko: "3D UV 아틀라스 생성", en: "3D UV atlas generation" },
  },
  {
    name: "yjs",
    version: "13.6.31",
    license: "MIT",
    url: "https://docs.yjs.dev",
    surface: "web",
    role: { ko: "CRDT 실시간 공동 편집", en: "CRDT realtime co-editing" },
  },
  {
    name: "zod",
    version: "4.4.3",
    license: "MIT",
    url: "https://zod.dev",
    surface: "web",
    role: { ko: "스키마 검증", en: "Schema validation" },
  },
  {
    name: "zustand",
    version: "5.0.14",
    license: "MIT",
    url: "https://github.com/pmndrs/zustand",
    surface: "web",
    role: { ko: "클라이언트 상태 관리", en: "Client state management" },
  },
  {
    name: "@libsql/client",
    version: "0.17.3",
    license: "MIT",
    url: "https://github.com/tursodatabase/libsql-client-ts",
    surface: "api",
    role: { ko: "API의 libSQL 데이터베이스 클라이언트", en: "libSQL database client for the API" },
  },
  {
    name: "@msgpack/msgpack",
    version: "2.8.0",
    license: "ISC",
    url: "https://msgpack.org/",
    surface: "api",
    role: { ko: "실시간 메시지 MessagePack 직렬화", en: "MessagePack serialization for realtime messages" },
  },
  {
    name: "@nestjs/common",
    version: "11.1.24",
    license: "MIT",
    url: "https://nestjs.com",
    surface: "api",
    role: { ko: "API 서버 프레임워크 공통 모듈", en: "API server framework common module" },
  },
  {
    name: "@nestjs/core",
    version: "11.1.24",
    license: "MIT",
    url: "https://nestjs.com",
    surface: "api",
    role: { ko: "API 서버 프레임워크 코어", en: "API server framework core" },
  },
  {
    name: "@nestjs/platform-express",
    version: "11.1.24",
    license: "MIT",
    url: "https://nestjs.com",
    surface: "api",
    role: { ko: "API의 Express 플랫폼 어댑터", en: "Express platform adapter for the API" },
  },
  {
    name: "@nestjs/platform-socket.io",
    version: "11.1.28",
    license: "MIT",
    url: "https://nestjs.com",
    surface: "api",
    role: { ko: "API 실시간 게이트웨이의 Socket.IO 어댑터", en: "Socket.IO adapter for the API realtime gateway" },
  },
  {
    name: "@nestjs/websockets",
    version: "11.1.28",
    license: "MIT",
    url: "https://github.com/nestjs/nest",
    surface: "api",
    role: { ko: "API 웹소켓 게이트웨이", en: "API WebSocket gateways" },
  },
  {
    name: "@socket.io/postgres-adapter",
    version: "0.5.0",
    license: "MIT",
    url: "https://github.com/socketio/socket.io-postgres-adapter",
    surface: "api",
    role: { ko: "Socket.IO 다중 인스턴스 어댑터", en: "Multi-instance adapter for Socket.IO" },
  },
  {
    name: "drizzle-orm",
    version: "0.45.2",
    license: "Apache-2.0",
    url: "https://orm.drizzle.team",
    surface: "api",
    role: { ko: "API의 PostgreSQL ORM", en: "PostgreSQL ORM for the API" },
  },
  {
    name: "express",
    version: "4.22.2",
    license: "MIT",
    url: "https://expressjs.com/",
    surface: "api",
    role: { ko: "API HTTP 서버(Nest 플랫폼)", en: "API HTTP server (Nest platform)" },
  },
  {
    name: "fast-xml-parser",
    version: "5.10.1",
    license: "MIT",
    url: "https://github.com/NaturalIntelligence/fast-xml-parser",
    surface: "api",
    role: { ko: "외부 피드와 임포트의 XML 파싱", en: "XML parsing for external feeds and imports" },
  },
  {
    name: "google-auth-library",
    version: "10.7.0",
    license: "Apache-2.0",
    url: "https://github.com/googleapis/google-cloud-node-core/tree/main/packages/google-auth-library-nodejs",
    surface: "api",
    role: { ko: "Google OAuth 토큰 검증", en: "Google OAuth token verification" },
  },
  {
    name: "image-js",
    version: "1.7.0",
    license: "MIT",
    url: "https://github.com/image-js/image-js#readme",
    surface: "api",
    role: { ko: "서버 측 이미지 분석과 처리", en: "Server-side image analysis and processing" },
  },
  {
    name: "js-base64",
    version: "3.9.0",
    license: "BSD-3-Clause",
    url: "https://github.com/dankogai/js-base64",
    surface: "api",
    role: { ko: "Base64 인코딩 유틸리티", en: "Base64 encoding utility" },
  },
  {
    name: "nestjs-pino",
    version: "4.6.1",
    license: "MIT",
    url: "https://github.com/iamolegga/nestjs-pino#readme",
    surface: "api",
    role: { ko: "Nest 구조화 로깅 연결", en: "Structured logging bridge for Nest" },
  },
  {
    name: "nestjs-zod",
    version: "5.4.0",
    license: "MIT",
    url: "https://github.com/BenLorantfy/nestjs-zod",
    surface: "api",
    role: { ko: "Nest 스키마 검증 연결", en: "Schema validation bridge for Nest" },
  },
  {
    name: "pg",
    version: "8.21.0",
    license: "MIT",
    url: "https://github.com/brianc/node-postgres",
    surface: "api",
    role: { ko: "PostgreSQL 드라이버", en: "PostgreSQL driver" },
  },
  {
    name: "pino-http",
    version: "11.0.0",
    license: "MIT",
    url: "https://github.com/pinojs/pino-http#readme",
    surface: "api",
    role: { ko: "API HTTP 요청 로깅", en: "HTTP request logging for the API" },
  },
  {
    name: "reflect-metadata",
    version: "0.2.2",
    license: "Apache-2.0",
    url: "https://github.com/microsoft/reflect-metadata",
    surface: "api",
    role: { ko: "Nest 데코레이터 메타데이터 폴리필", en: "Decorator metadata polyfill for Nest" },
  },
  {
    name: "rxjs",
    version: "7.8.2",
    license: "Apache-2.0",
    url: "https://rxjs.dev",
    surface: "api",
    role: { ko: "API 반응형 스트림 처리", en: "Reactive stream handling in the API" },
  },
  {
    name: "socket.io",
    version: "4.8.3",
    license: "MIT",
    url: "https://github.com/socketio/socket.io/tree/main/packages/socket.io#readme",
    surface: "api",
    role: { ko: "실시간 협업 서버", en: "Realtime collaboration server" },
  },
  {
    name: "web-push",
    version: "3.6.7",
    license: "MPL-2.0",
    url: "https://github.com/web-push-libs/web-push#readme",
    surface: "api",
    flag: "weak-copyleft",
    role: { ko: "웹 푸시 알림 발송", en: "Sending web push notifications" },
  },
  {
    name: "@capacitor/android",
    version: "8.5.2",
    license: "MIT",
    url: "https://capacitorjs.com",
    surface: "mobile",
    role: { ko: "모바일 앱 안드로이드 네이티브 셸", en: "Android native shell for the mobile app" },
  },
  {
    name: "@capacitor/app",
    version: "8.1.1",
    license: "MIT",
    url: "https://github.com/ionic-team/capacitor-plugins",
    surface: "mobile",
    role: { ko: "모바일 앱 생명주기 플러그인", en: "Mobile app lifecycle plugin" },
  },
  {
    name: "@capacitor/browser",
    version: "8.0.4",
    license: "MIT",
    url: "https://github.com/ionic-team/capacitor-plugins",
    surface: "mobile",
    role: { ko: "모바일 인앱 브라우저 플러그인", en: "In-app browser plugin for mobile" },
  },
  {
    name: "@capacitor/core",
    version: "8.5.2",
    license: "MIT",
    url: "https://capacitorjs.com",
    surface: "mobile",
    role: { ko: "모바일 하이브리드 앱 런타임", en: "Hybrid runtime for the mobile app" },
  },
  {
    name: "@capacitor/ios",
    version: "8.5.2",
    license: "MIT",
    url: "https://capacitorjs.com",
    surface: "mobile",
    role: { ko: "모바일 앱 iOS 네이티브 셸", en: "iOS native shell for the mobile app" },
  },
  {
    name: "@capacitor/keyboard",
    version: "8.0.5",
    license: "MIT",
    url: "https://github.com/ionic-team/capacitor-keyboard",
    surface: "mobile",
    role: { ko: "모바일 키보드 플러그인", en: "Mobile keyboard plugin" },
  },
  {
    name: "@capacitor/splash-screen",
    version: "8.0.2",
    license: "MIT",
    url: "https://github.com/ionic-team/capacitor-plugins",
    surface: "mobile",
    role: { ko: "모바일 스플래시 화면 플러그인", en: "Mobile splash-screen plugin" },
  },
  {
    name: "@capacitor/status-bar",
    version: "8.0.3",
    license: "MIT",
    url: "https://github.com/ionic-team/capacitor-plugins",
    surface: "mobile",
    role: { ko: "모바일 상태바 플러그인", en: "Mobile status-bar plugin" },
  },
  {
    name: "@babylonjs/serializers",
    version: "9.19.0",
    license: "Apache-2.0",
    url: "https://www.babylonjs.com",
    surface: "labs",
    role: { ko: "캐릭터 랩 3D 장면 직렬화", en: "Serializing 3D scenes in the character lab" },
  },
  {
    name: "@napi-rs/keyring",
    version: "1.3.0",
    license: "MIT",
    url: "https://github.com/Brooooooklyn/keyring-node",
    surface: "labs",
    role: { ko: "데스크톱 동기화 앱의 OS 키링 접근", en: "OS keyring access for the desktop sync app" },
  },
];

// 모델 자산 라이선스는 engineering-license-model-assets.ts에 있고 기존 import 경로를 위해 재수출한다.
export {
  ENGINEERING_MODEL_ASSET_LICENSES,
  type EngineeringModelAssetLicense,
} from "./engineering-license-model-assets";
