import { sampleSource, t } from "./engineering-atlas-web-platform-helpers";

import type { EngineeringAtlasEntry } from "./engineering-atlas-types";

/** 기술 도감 · web-platform · 전달과 정책 세 장(응답 헤더 계약, 능력 감지 레지스트리, 큰 자산 전달). 계약과 작성 규칙은 engineering-atlas-types.ts 를 따른다. */
export const ENGINEERING_ATLAS_WEB_PLATFORM_DELIVERY: readonly EngineeringAtlasEntry[] = [
  {
    id: "response-header-contract-csp",
    category: "web-platform",
    name: "Security headers",
    title: t("보안 헤더를 한 곳에서 관리해 세 곳에 맞추기", "Security headers kept in one place and synced to three"),
    status: "live",
    tagline: t(
      "CSP·Permissions-Policy·COOP/COEP 를 JSON 한 곳에 두고, 사본이 어긋나면 검증이 실패합니다.",
      "CSP, Permissions-Policy and COOP/COEP live in one JSON; verification fails if a copy drifts.",
    ),
    background: [
      t(
        "웹사이트의 보안 규칙 중 상당수는 코드가 아니라 서버가 응답에 붙이는 헤더로 정해집니다. 이 사이트가 어디의 스크립트를 실행해도 되는지(CSP), 카메라·위치 같은 기능을 쓸 수 있는지(Permissions-Policy), 스튜디오를 격리 문서로 만들지(COOP/COEP)가 모두 헤더입니다. 문제는 같은 규칙을 여러 곳에 적어야 한다는 점입니다. 한 곳만 고치고 나머지를 잊으면 환경마다 보안이 달라집니다.",
        "Many of a website's security rules are set not in code but in headers the server attaches to responses. Where scripts may run from (CSP), whether features like camera or location are allowed (Permissions-Policy), and whether the studio becomes an isolated document (COOP/COEP) are all headers. The trouble is that the same rule has to be written in several places; fix one and forget the rest, and security differs per environment.",
      ),
      t(
        "그래서 원천을 config/http-response-headers.json 한 곳(규칙 39개)에 두고 사본 세 곳을 맞춥니다. 하나, apps/web/public/_headers 는 스크립트가 통째로 생성합니다. 둘, Worker 가 직접 응답하는 경로의 COMMON_SECURITY_HEADERS 는 CSP 문자열을 스크립트가 다시 써 주고 나머지 값은 테스트가 JSON 과 대조합니다. 셋, 개발·미리보기 서버의 격리 헤더 상수는 테스트가 값을 고정합니다(Permissions-Policy 는 JSON 과 직접 대조). 어긋나면 pnpm verify:cloudflare-static 같은 검증이 실패합니다.",
        "So the source lives in one file, config/http-response-headers.json (39 rules), and three copies are kept in line. One, apps/web/public/_headers is fully generated by a script. Two, COMMON_SECURITY_HEADERS for responses the Worker produces directly has its CSP string rewritten by the script while a test compares the other values with the JSON. Three, the isolation header constants of the dev and preview servers are pinned by a test (Permissions-Policy is compared with the JSON directly). If they drift, checks such as pnpm verify:cloudflare-static fail.",
      ),
      t(
        "헤더를 읽는 코드도 있습니다. document.permissionsPolicy.allowsFeature('geolocation') 로 지금 문서에서 위치 기능이 허용되는지 물어, 운영 헤더가 geolocation=() 로 막은 위치 버튼은 시도하지 않습니다. 보안 정책 때문에 기능이 조용히 죽는 문제를 코드가 스스로 진단하는 셈입니다. 메타 태그나 서버별 설정을 따로 두는 대안은 사본이 늘어 어긋나기 쉽습니다.",
        "Some code also reads the headers. It asks document.permissionsPolicy.allowsFeature('geolocation') whether location is allowed in this document and does not even try the location button that the production header blocks with geolocation=(). The code diagnoses, by itself, the problem of a feature dying silently under a security policy. The alternatives, meta tags or per-server settings, multiply the copies and drift more easily.",
      ),
      t(
        "한계: Cloudflare 정적 자산의 _headers 는 줄당 2,000자, 규칙 100개 제한이 있는데(Cloudflare 문서) CSP 줄이 이미 1,634자라 허용 호스트를 몇 개만 더해도 한계에 닿습니다. Trusted Types 와 import maps 는 쓰지 않습니다. 이 카드는 운영 응답 헤더를 직접 받아 본 것이 아니라 저장소의 원천·생성물·테스트를 확인한 것입니다.",
        "Limits: Cloudflare Static Assets _headers allows 2,000 characters per line and 100 rules (Cloudflare docs), and the CSP line is already 1,634 characters, so adding a few allowed hosts would reach the limit. Trusted Types and import maps are not used. This card was checked against the repository's source, generated file and tests, not against live production response headers.",
      ),
    ],
    keyPoints: [
      t("원천은 JSON 한 곳, 규칙 39개", "One JSON source with 39 rules"),
      t("사본 세 곳이 어긋나면 검증이 실패한다", "Verification fails when a copy drifts"),
      t("CSP 줄 1,634자, 줄당 한도 2,000자에 근접", "The CSP line is 1,634 of 2,000 characters"),
      t("permissionsPolicy 로 막힌 기능은 시도하지 않는다", "Blocked features are not tried, via permissionsPolicy"),
    ],
    diagram: {
      id: "response-header-contract-csp-diagram",
      kind: "layers",
      title: t("헤더 원천 한 곳과 사본 세 곳", "One header source and three copies"),
      caption: t(
        "사본은 생성하거나 테스트로 대조하고, 앱은 헤더가 막은 기능을 스스로 알아챕니다.",
        "Copies are generated or checked by tests, and the app notices features the headers block.",
      ),
      alt: t(
        "맨 위에 헤더 원천 JSON 이 있고, 그 아래로 정적 자산용 _headers, Worker 직접 응답용 상수, 개발·미리보기 서버 상수의 세 사본이 있습니다. 그 아래에서 실브라우저 재생 검증 스크립트가 JSON 규칙을 경로별로 재현해 확인하고, 맨 아래 앱 안에서는 document.permissionsPolicy 로 막힌 기능을 알아챕니다.",
        "At the top is the header source JSON, with three copies below it: _headers for static assets, constants for Worker direct replies, and constants for the dev and preview servers. Next a real-browser replay script checks by path what the JSON rules produce, and at the bottom the app notices blocked features through document.permissionsPolicy.",
      ),
      layers: [
        {
          id: "source",
          label: t("원천: http-response-headers.json", "Source: http-response-headers.json"),
          sub: t("규칙 39개 · CSP, Permissions-Policy, COOP/COEP", "39 rules: CSP, Permissions-Policy, COOP/COEP"),
          tone: "neutral",
        },
        {
          id: "static",
          label: t("사본 1 · public/_headers", "Copy 1: public/_headers"),
          sub: t("스크립트가 통째로 생성 · --check 가 드리프트 검출", "fully generated; --check catches drift"),
          tone: "edge",
          chips: ["Cloudflare Static Assets"],
        },
        {
          id: "worker",
          label: t("사본 2 · Worker 직접 응답", "Copy 2: Worker direct replies"),
          sub: t("COMMON_SECURITY_HEADERS · CSP 재작성, 나머지는 테스트 대조", "COMMON_SECURITY_HEADERS; CSP rewritten, rest tested"),
          tone: "edge",
          chips: ["Cloudflare Workers"],
        },
        {
          id: "dev",
          label: t("사본 3 · 개발·미리보기 서버", "Copy 3: dev and preview servers"),
          sub: t("격리 헤더 상수 · 테스트가 값 고정", "isolation header constants pinned by tests"),
          tone: "local",
          chips: ["Vite"],
        },
        {
          id: "replay",
          label: t("실브라우저 재생 검증", "Real-browser replay"),
          sub: t("JSON 규칙을 경로별로 재현해 격리를 확인", "replays the JSON rules by path to check isolation"),
          tone: "neutral",
          chips: ["Playwright"],
        },
        {
          id: "self",
          label: t("앱의 자기 진단", "The app's self-diagnosis"),
          sub: t("document.permissionsPolicy 로 막힌 기능은 시도 안 함", "blocked features are skipped via document.permissionsPolicy"),
          tone: "local",
        },
      ],
      brackets: [{ label: t("한 원천 → 세 사본", "One source, three copies"), layerIds: ["static", "worker", "dev"] }],
    },
    usage: [
      {
        feature: t("모든 페이지의 응답 보안 규칙", "Security rules for every page response"),
        role: t(
          "script-src 는 self·해시·wasm-unsafe-eval·외부 호스트 4곳, frame-ancestors 는 none, HSTS 는 2년으로 원천에서 한 번 정의합니다.",
          "script-src (self, a hash, wasm-unsafe-eval and four outside hosts), frame-ancestors none and a two-year HSTS are defined once at the source.",
        ),
        paths: ["config/http-response-headers.json", "apps/web/public/_headers"],
      },
      {
        feature: t("Worker 가 직접 응답하는 경로", "Paths the Worker answers directly"),
        role: t(
          "API 프록시·오류 응답 같은 Worker 응답에도 같은 CSP·Permissions-Policy 를 붙이고, 생성 스크립트가 CSP 문자열을 원천과 맞춥니다.",
          "Worker replies such as API proxying and errors carry the same CSP and Permissions-Policy, and the generator keeps the CSP string equal to the source.",
        ),
        paths: ["deploy/cloudflare-static/src/index.ts#COMMON_SECURITY_HEADERS", "scripts/cloudflare-static-rules.mjs"],
      },
      {
        feature: t("날씨 위치 버튼 (운영에서는 막힘)", "Weather location button (blocked in production)"),
        role: t(
          "운영 헤더가 geolocation=() 로 막은 것을 document.permissionsPolicy 로 알아채 위치 기능을 시도하지 않습니다.",
          "Notices through document.permissionsPolicy that the production header blocks geolocation=() and does not attempt location.",
        ),
        paths: ["apps/web/src/shared/ambient/ambient-weather.ts"],
      },
      {
        feature: t("검증 파이프라인", "Verification pipeline"),
        role: t(
          "생성물 드리프트와 타입·테스트(verify:cloudflare-static), index.html 인라인 스크립트 해시(verify:csp), 실브라우저 재생 스크립트로 헤더를 지킵니다.",
          "Headers are guarded by generated-file drift plus types and tests (verify:cloudflare-static), the index.html inline-script hash (verify:csp) and a real-browser replay script.",
        ),
        paths: [
          "scripts/cloudflare-static-rules.mjs",
          "scripts/verify-static-csp.mjs",
          "scripts/verify-studio-service-worker.mts",
        ],
      },
    ],
    samples: [
      {
        kind: "teaching",
        title: t("정책이 막은 기능을 스스로 알아채기", "Noticing a feature the policy blocks"),
        language: "ts",
        ...sampleSource([
          ["type Policy = { allowsFeature(name: string): boolean };"],
          [""],
          ["export function isFeatureAllowed(name: string): boolean {"],
          ["  const doc = document as Document & { permissionsPolicy?: Policy; featurePolicy?: Policy };"],
          ["  const policy = doc.permissionsPolicy ?? doc.featurePolicy;"],
          ["  try {"],
          ["    return policy ? policy.allowsFeature(name) : true;", "응답 헤더가 막았다면 false", "false when a response header blocks it"],
          ["  } catch {"],
          ["    return true;", "판별 불가면 실제 호출 결과로 판단한다", "if unknown, judge by the real call"],
          ["  }"],
          ["}"],
          [""],
          ["", '예: 헤더가 geolocation=() 면 isFeatureAllowed("geolocation") 는 false 이고, 위치 버튼을 숨긴다', 'e.g. with geolocation=() in the header, isFeatureAllowed("geolocation") is false and the location button is hidden'],
        ]),
        explain: t(
          "실제 코드(ambient-weather.ts)는 navigator.geolocation 이 있는지도 함께 확인합니다. 헤더 때문에 기능이 조용히 죽는 일을 화면에서 미리 걸러 내는 방법입니다.",
          "The real code (ambient-weather.ts) also checks for navigator.geolocation. It filters out, on screen, features that would otherwise die silently because of a header.",
        ),
        verify: "types",
      },
      {
        kind: "simplified",
        title: t("원천 JSON 에서 _headers 만들기", "Generating _headers from the source JSON"),
        language: "js",
        ...sampleSource([
          ["export function renderHeaders(policy) {"],
          ['  const blocks = ["# Generated from config/http-response-headers.json"];'],
          ["  for (const rule of policy.headers) {"],
          ['    const pattern = rule.source === "/(.*)" ? "/*" : rule.source.replace(/\\/\\(\\.\\*\\)$/u, "/*");'],
          ['    blocks.push("", pattern);'],
          ["    for (const header of rule.headers) blocks.push(`  ${header.key}: ${header.value}`);"],
          ["  }"],
          ['  return `${blocks.join("\\n")}\\n`;'],
          ["}"],
          [""],
          ["", "--check 모드는 이 결과와 실제 파일을 비교해 다르면 실패한다", "--check mode compares this output with the real file and fails if they differ"],
        ]),
        explain: t(
          "scripts/cloudflare-static-rules.mjs 의 생성기를 줄였습니다. 원천의 /(.*) 는 _headers 문법의 /* 로, 끝의 /(.*) 는 /* 로 바뀝니다. 실제 스크립트는 Worker 상수의 CSP 줄도 같은 원천으로 다시 씁니다.",
          "Condensed from the generator in scripts/cloudflare-static-rules.mjs. The source's /(.*) becomes /* in _headers syntax, and a trailing /(.*) becomes /*. The real script also rewrites the CSP line of the Worker constant from the same source.",
        ),
        source: "scripts/cloudflare-static-rules.mjs",
      },
    ],
    links: [
      {
        title: "MDN · Permissions-Policy",
        url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Permissions_Policy",
        kind: "docs",
      },
      {
        title: "MDN · Content Security Policy (CSP)",
        url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP",
        kind: "docs",
      },
      {
        title: "Cloudflare · Static Assets headers",
        url: "https://developers.cloudflare.com/workers/static-assets/headers/",
        kind: "docs",
        note: t("줄당 2,000자·규칙 100개 제한이 적힌 문서", "Documents the 2,000-character and 100-rule limits"),
      },
      {
        title: "W3C · Permissions Policy",
        url: "https://www.w3.org/TR/permissions-policy/",
        kind: "spec",
        note: t("document.permissionsPolicy 의 정의", "Defines document.permissionsPolicy"),
      },
      {
        title: "W3C · Content Security Policy Level 3",
        url: "https://www.w3.org/TR/CSP3/",
        kind: "spec",
      },
    ],
    chapterIds: ["pwa-continuity", "infrastructure"],
    talk: {
      pitch: t(
        "보안 규칙의 상당수는 서버가 응답에 붙이는 헤더로 정해집니다. 이 규칙의 원본을 JSON 한 곳에 두고, 정적 파일용·Worker 용·개발 서버용 사본을 스크립트와 테스트로 맞춥니다. 사본이 어긋나면 검증이 실패하고, 앱은 헤더가 막은 기능을 스스로 알아채 시도하지 않습니다.",
        "Many security rules are set by headers the server attaches to responses. The original of those rules sits in one JSON, and copies for static files, the Worker and the dev server are kept in line by scripts and tests. If a copy drifts, verification fails, and the app notices features the headers block and does not try them.",
      ),
      analogy: t(
        "건물 출입 규칙을 한 장의 원본 문서로 두고, 정문·후문·공사장 출입구의 안내판을 그 원본에서 인쇄하는 것과 같습니다. 원본과 안내판이 다르면 검수에서 걸립니다.",
        "It is like keeping one master sheet of building access rules and printing the signs for the front, back and construction entrances from it; a sign that differs from the master is caught at inspection.",
      ),
      questions: [
        {
          question: t("CSP 가 뭔가요?", "What is CSP?"),
          answer: t(
            "페이지가 불러와도 되는 스크립트·이미지·연결 대상을 서버가 미리 적어 두는 허용 목록입니다. 악성 스크립트가 끼어들어도 목록 밖이면 실행되지 않게 막습니다.",
            "An allow-list in which the server states in advance which scripts, images and connection targets a page may load, so injected malicious scripts outside the list do not run.",
          ),
        },
        {
          question: t("왜 JSON 하나로 모으나요?", "Why gather it into a single JSON?"),
          answer: t(
            "같은 규칙을 정적 파일, Worker, 개발 서버에 따로 적으면 하나만 고치고 잊기 쉽습니다. 원천을 하나로 두고 생성과 대조로 어긋남을 잡습니다.",
            "Writing the same rule separately for static files, the Worker and the dev server makes it easy to fix one and forget the others. One source plus generation and comparison catches drift.",
          ),
        },
        {
          question: t("Trusted Types 도 쓰나요?", "Is Trusted Types used too?"),
          answer: t(
            "아니요. require-trusted-types-for 지시자도 trustedTypes 코드도 없습니다. 도입 후보로만 검토합니다.",
            "No. There is neither a require-trusted-types-for directive nor trustedTypes code. It is only a candidate for adoption.",
          ),
        },
      ],
      pitfall: t(
        "운영 응답 헤더를 직접 받아 확인한 것이 아니라 저장소의 원천·생성물·테스트를 확인한 카드입니다. 운영 헤더가 geolocation=() 로 날씨 위치 기능을 막고 있다는 점과 CSP 줄이 줄당 한도(2,000자)에 가깝다는 점을 숨기지 마세요. 카메라·마이크 권한 정책은 협업 쪽 카드가 따로 다룹니다.",
        "This card was checked against the repository's source, generated file and tests, not against live production response headers. Do not hide that the production header blocks the weather location feature with geolocation=() or that the CSP line is close to the 2,000-character limit. The camera and microphone permission policy is covered by a collaboration card.",
      ),
    },
    technologies: ["CSP", "Permissions-Policy", "COOP", "COEP", "HSTS", "Cloudflare Workers"],
    facts: [
      {
        value: "39",
        label: t("원천 JSON 의 헤더 규칙 수(Cloudflare 한도 100)", "Header rules in the source JSON (Cloudflare limit 100)"),
        source: "config/http-response-headers.json",
      },
      {
        value: "1,634자",
        label: t("가장 긴 _headers 줄(CSP), 줄당 한도 2,000자", "Longest _headers line (CSP); the per-line limit is 2,000"),
        source: "apps/web/public/_headers",
      },
      {
        value: "63072000",
        label: t("HSTS max-age(초), 약 2년", "HSTS max-age in seconds, about two years"),
        source: "config/http-response-headers.json",
      },
    ],
    reviewedAt: "2026-10-07",
  },
  {
    id: "capability-detection-registry-27",
    category: "web-platform",
    name: "Capability detection",
    title: t("차세대 API 27종을 감지·표지·끄기로 다루기", "Handling 27 next-gen APIs: detect, mark, switch off"),
    status: "experimental",
    tagline: t(
      "27개 새 API의 지원 여부를 한곳에서 감지해 설정에 표지하고, 3개는 끌 수 있습니다.",
      "Support for 27 new APIs is detected in one place, shown in settings, and three can be switched off.",
    ),
    background: [
      t(
        "브라우저에는 해마다 새 기능이 들어옵니다. 어떤 기능은 한두 브라우저에만 있고 어떤 기능은 아직 초안입니다. 그래서 새 기능을 쓸 때의 첫 질문은 이 브라우저에 있나입니다. ToonStudio 는 이 질문을 27개 기능에 대해 한 모듈(nextgen-web-capabilities)에 모아, 항상 있다 없다만 답하고 절대 오류를 던지지 않게 만들었습니다.",
        "Browsers gain new features every year. Some exist in only one or two browsers and some are still drafts, so the first question before using a new feature is whether this browser has it. ToonStudio gathers that question for 27 features into one module (nextgen-web-capabilities) that only ever answers yes or no and never throws.",
      ),
      t(
        "흐름은 세 단계입니다. 감지(try/catch 로 감싼 탐지기가 true 나 false 를 돌려줌), 표지(설정의 실험 기능 화면이 27개를 지원 또는 미지원으로 보여 줌), 끄기(실제로 연결된 3개 기능은 토글로 사용자가 끌 수 있고 기본은 켜짐)입니다. 실험 기능은 미지원 환경에서 조용히 없는 것이 허용되는 운용 방침이라 별도 폴백을 만들지 않습니다.",
        "There are three steps: detect (detectors wrapped in try/catch return true or false), mark (the experimental screen in settings shows all 27 as supported or unsupported) and switch off (three features that are really wired can be turned off by users, on by default). By operating policy an experimental feature may be quietly absent where unsupported, so no separate fallback is built.",
      ),
      t(
        "정직하게 구분할 점이 많습니다. 27종 중 실제 기능에 이어진 것은 화면 꺼짐 방지, 스튜디오 미리 준비, 화면 전환, 스포이트 정도이고, 기기 압력(Compute Pressure)은 설정 화면에 현재 압력을 보여 주는 데서 끝나며 그 값을 읽는 소비처가 없습니다. 나머지 20여 종은 지원 여부만 보여 주는 후보입니다. 감지가 레지스트리와 각 기능 모듈에 중복돼 있어 레지스트리 결과는 설정 목록 표시에만 쓰입니다.",
        "There is a lot to distinguish honestly. Of the 27, the ones wired to features are screen wake lock, studio prerender, view transitions and the eyedropper, while Compute Pressure ends at showing the current pressure in settings and has no consumer reading the value. The other twenty-odd are candidates that only show support. Detection exists both in the registry and in each feature module, so registry results feed only the settings list.",
      ),
      t(
        "한계: 지원 시점 같은 외부 사실(Compute Pressure 는 Chrome/Edge 125+ 데스크톱, Temporal 은 Chrome 144·Firefox 139 출시, 내장 Prompt API 는 Chrome 148부터)은 코드 주석에서 온 문장이라 발표 전에 MDN 으로 다시 확인해야 합니다. 설정 화면 문구 품질 조절에 씁니다도 현재 소비처가 없는 것과 어긋납니다.",
        "Limits: external facts such as support dates (Compute Pressure on Chrome and Edge 125+ desktop, Temporal in Chrome 144 and Firefox 139, the built-in Prompt API from Chrome 148) come from code comments and must be rechecked on MDN before presenting. The settings wording that it adapts quality also disagrees with the fact that no consumer exists today.",
      ),
    ],
    keyPoints: [
      t("27종을 한 모듈에서 감지, 오류는 던지지 않는다", "27 APIs detected in one module; it never throws"),
      t("감지 → 표지(지원/미지원) → 끄기(토글 3개)", "Detect, mark as supported or not, switch off (3 toggles)"),
      t("실제 연결은 일부, 대부분은 표시용 후보", "Only a few are wired; most are display-only candidates"),
      t("Compute Pressure 는 표시까지만, 소비처 없음", "Compute Pressure stops at display; no consumer"),
    ],
    diagram: {
      id: "capability-detection-registry-27-diagram",
      kind: "sequence",
      title: t("감지 → 표지 → 끄기", "Detect, mark, switch off"),
      caption: t(
        "감지 결과는 설정 화면의 표지로 보이고, 연결된 기능만 사용자가 끌 수 있습니다.",
        "Detection results appear as marks in settings, and users can switch off only the wired features.",
      ),
      alt: t(
        "사용자가 설정의 실험 기능을 열면 설정 화면이 감지 레지스트리에 27개 기능의 지원 여부를 묻고, 레지스트리의 탐지기는 오류를 던지지 않고 true 나 false 를 돌려줍니다. 화면은 지원 또는 미지원 표지를 보여 주며, 사용자가 토글을 끄면 설정이 저장되고 해당 기능 모듈이 자체 감지와 함께 그 값을 따릅니다.",
        "When the user opens experimental features in settings, the screen asks the detection registry about 27 features and its detectors return true or false without throwing. The screen shows supported or unsupported marks, and when the user turns a toggle off the setting is saved and the feature module follows it, together with its own detection.",
      ),
      actors: [
        { id: "user", label: t("사용자", "User"), tone: "neutral" },
        { id: "settings", label: t("설정 화면", "Settings screen"), sub: t("실험 기능 섹션", "experimental section"), tone: "local" },
        { id: "registry", label: t("감지 레지스트리", "Detection registry"), sub: t("27개 탐지기", "27 detectors"), tone: "local" },
        { id: "feature", label: t("기능 모듈", "Feature module"), sub: t("Wake Lock · 전환 · 프리렌더", "Wake Lock, transitions, prerender"), tone: "good" },
      ],
      messages: [
        { from: "user", to: "settings", label: t("실험 기능 열기", "Open experimental features") },
        { from: "settings", to: "registry", label: t("detectNextgenCapabilities()", "detectNextgenCapabilities()") },
        {
          from: "registry",
          to: "registry",
          label: t("탐지기 27개 실행", "Run 27 detectors"),
          note: t("try/catch: 미지원은 false", "try/catch: unsupported is false"),
        },
        { from: "registry", to: "settings", label: t("{ 기능: 지원 여부 }", "{ feature: supported }"), style: "dashed" },
        {
          from: "settings",
          to: "user",
          label: t("지원 / 미지원 표지", "Supported / unsupported marks"),
          style: "dashed",
          note: t("27개 모두 표시", "All 27 are shown"),
        },
        {
          from: "user",
          to: "settings",
          label: t("토글 끄기", "Switch a toggle off"),
          note: t("연결된 3개만 해당", "Only the three wired ones"),
        },
        {
          from: "settings",
          to: "feature",
          label: t("저장 + 구독 알림", "Save + notify subscribers"),
          style: "dashed",
          note: t("localStorage, 다른 탭에도 반영", "localStorage, other tabs too"),
        },
        {
          from: "feature",
          to: "feature",
          label: t("자체 감지로 한 번 더 확인", "Check again with own detection"),
          note: t("레지스트리와 별개로 탐지", "Detected apart from the registry"),
        },
      ],
    },
    usage: [
      {
        feature: t("설정 · 실험 기능", "Settings · experimental features"),
        role: t(
          "27개 기능의 지원 여부를 표지로 보여 주고, 연결된 3개(화면 켜 두기·스튜디오 미리 준비·화면 전환) 토글을 둡니다.",
          "Shows support for 27 features as marks and offers toggles for the three wired ones (keep screen on, prepare the studio, screen transition).",
        ),
        paths: [
          "apps/web/src/domains/account/NextgenLabSettingsSection.tsx",
          "apps/web/src/shared/lib/nextgen-web-capabilities.ts",
          "apps/web/src/shared/lib/nextgen-lab-settings.ts",
        ],
        route: "/settings",
      },
      {
        feature: t("작품 리더 · 화면 꺼짐 방지", "Title reader · screen wake lock"),
        role: t(
          "리더를 여는 동안 화면이 꺼지지 않게 하고, 미지원이거나 거부되면 조용히 아무 일도 하지 않습니다.",
          "Keeps the screen on while the reader is open, and quietly does nothing when unsupported or refused.",
        ),
        paths: [
          "apps/web/src/shared/lib/screen-wake-lock.ts",
          "apps/web/src/shared/hooks/use-screen-wake-lock.ts",
          "apps/web/src/domains/catalog/TitleReaderPage.tsx",
        ],
      },
      {
        feature: t("색을 투명으로 (스포이트)", "Color to transparent (eyedropper)"),
        role: t(
          "EyeDropper 생성자가 있을 때만 화면 색 추출 버튼을 그립니다. 레지스트리와 별개로 감지하며 설정 토글은 없습니다.",
          "Draws the screen-color picker button only when the EyeDropper constructor exists. It detects on its own, apart from the registry, and has no settings toggle.",
        ),
        paths: ["apps/web/src/domains/creator/StudioColorToAlphaPanel.tsx"],
        route: "/studio",
      },
      {
        feature: t("기기 압력 표시 (소비처 없음)", "Device pressure display (no consumer)"),
        role: t(
          "설정 화면에 현재 CPU 압력 단계를 보여 주는 데서 끝나고, 그 값으로 품질을 조절하는 기능은 아직 없습니다.",
          "Ends at showing the current CPU pressure level in settings; nothing adjusts quality from that value yet.",
        ),
        paths: ["apps/web/src/shared/lib/compute-pressure.ts"],
      },
    ],
    samples: [
      {
        kind: "teaching",
        title: t("절대 던지지 않는 감지 레지스트리", "A detection registry that never throws"),
        language: "ts",
        ...sampleSource([
          ["const DETECTORS = {"],
          ['  wakeLock: () => typeof navigator.wakeLock?.request === "function",'],
          ['  viewTransitions: () => typeof document.startViewTransition === "function",'],
          ['  speculationRules: () => HTMLScriptElement.supports?.("speculationrules") === true,'],
          ['  eyeDropper: () => "EyeDropper" in globalThis,'],
          ["} as const;"],
          [""],
          ["export type Capability = keyof typeof DETECTORS;"],
          [""],
          ["export function detect(id: Capability): boolean {"],
          ["  try {"],
          ["    return DETECTORS[id]();"],
          ["  } catch {"],
          ["    return false;", "감지는 던지지 않는다. 미지원은 그냥 false", "detection never throws; unsupported is simply false"],
          ["  }"],
          ["}"],
          [""],
          ["export const detectAll = () =>"],
          ["  Object.fromEntries((Object.keys(DETECTORS) as Capability[]).map((id) => [id, detect(id)])) as Record<Capability, boolean>;"],
        ]),
        explain: t(
          "실제 레지스트리는 27개 탐지기를 같은 모양으로 갖고 있습니다. 감지 결과는 켜도 되는지를 알려 줄 뿐 폴백 구현을 강제하지 않습니다.",
          "The real registry holds 27 detectors of the same shape. A result says only whether it is fine to turn the feature on and forces no fallback implementation.",
        ),
        verify: "types",
      },
      {
        kind: "simplified",
        title: t("끌 수 있는 설정 저장소", "A settings store users can switch off"),
        language: "ts",
        ...sampleSource([
          ["export interface LabSettings { readerWakeLock: boolean; studioPrerender: boolean; viewTransitions: boolean }"],
          ['const KEY = "toonstudio.nextgen-lab.settings.v1";'],
          ["const DEFAULTS: LabSettings = { readerWakeLock: true, studioPrerender: true, viewTransitions: true };", "기본은 모두 켜짐", "everything is on by default"],
          ["const listeners = new Set<() => void>();"],
          [""],
          ["function read(): LabSettings {"],
          ["  try {"],
          ["    const raw = localStorage.getItem(KEY);"],
          ["    return raw ? { ...DEFAULTS, ...(JSON.parse(raw) as Partial<LabSettings>) } : DEFAULTS;"],
          ["  } catch {"],
          ["    return DEFAULTS;", "저장소를 못 읽어도 기본값으로 동작한다", "without readable storage, run on defaults"],
          ["  }"],
          ["}"],
          [""],
          ["let snapshot = read();"],
          ["export function update(patch: Partial<LabSettings>): LabSettings {"],
          ["  snapshot = { ...snapshot, ...patch };"],
          ["  try {"],
          ["    localStorage.setItem(KEY, JSON.stringify(snapshot));"],
          ["  } catch {", "저장 실패(프라이빗 모드·용량)는 세션 안에서만 유지", "a failed save (private mode, quota) lives only in this session"],
          ["    ", "계속 동작한다", "keep working"],
          ["  }"],
          ["  for (const listener of [...listeners]) listener();"],
          ["  return snapshot;"],
          ["}"],
          [""],
          ["export function subscribe(listener: () => void): () => void {"],
          ["  listeners.add(listener);"],
          ["  return () => void listeners.delete(listener);"],
          ["}"],
        ]),
        explain: t(
          "nextgen-lab-settings.ts 를 줄였습니다. 실제 코드는 각 값이 불리언인지도 확인하고, 다른 탭에서 바꾼 값을 storage 이벤트로 반영합니다. 서버로 동기화하지 않는 기기별 설정입니다.",
          "Condensed from nextgen-lab-settings.ts. The real code also checks that each value is a boolean and applies values changed in another tab via the storage event. These are per-device settings, not synced to a server.",
        ),
        source: "apps/web/src/shared/lib/nextgen-lab-settings.ts",
        verify: "types",
      },
    ],
    links: [
      {
        title: "web.dev · Baseline",
        url: "https://web.dev/baseline",
        kind: "guide",
        note: t("어떤 기능이 주요 브라우저에서 쓸 만한지 판단하는 기준", "A yardstick for which features are safe across major browsers"),
      },
      {
        title: "web-platform-dx · web-features",
        url: "https://github.com/web-platform-dx/web-features",
        kind: "repo",
        note: t("Baseline 상태의 원천 데이터", "The source data behind Baseline status"),
      },
      {
        title: "MDN · Compute Pressure API",
        url: "https://developer.mozilla.org/en-US/docs/Web/API/Compute_Pressure_API",
        kind: "docs",
      },
      {
        title: "MDN · @supports",
        url: "https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/At-rules/@supports",
        kind: "docs",
        note: t("CSS 기능 감지의 표준 방법", "The standard way to detect CSS features"),
      },
    ],
    chapterIds: ["nextgen-web-experiments", "performance"],
    talk: {
      pitch: t(
        "새 웹 기능은 브라우저마다 지원이 달라서, 쓰기 전에 있는지부터 묻습니다. 27개 기능의 감지를 한 모듈에 모았고 감지는 절대 오류를 던지지 않습니다. 설정 화면에서 지원 여부를 보여 주고, 실제로 연결된 기능 3개는 사용자가 끌 수 있습니다. 다만 대부분은 아직 표시용 후보이고 기기 압력은 표시까지만 되어 있다는 점을 같이 말씀드립니다.",
        "New web features vary by browser, so we ask whether they exist before using them. Detection for 27 features is gathered in one module and never throws. Settings shows what is supported, and users can switch off the three features that are really wired. Most are still display-only candidates, and device pressure stops at display, which I should say alongside.",
      ),
      analogy: t(
        "새 가전제품을 사기 전에 우리 집 콘센트에 맞는지 보는 점검표와 같습니다. 맞는 제품만 스위치를 켜고, 맞지 않는 것은 조용히 꺼 둡니다.",
        "It is a checklist for whether a new appliance fits your outlets before buying: only products that fit get switched on, and the rest stay quietly off.",
      ),
      questions: [
        {
          question: t("미지원 브라우저에서는 기능이 깨지나요?", "Does anything break in unsupported browsers?"),
          answer: t(
            "아니요. 실험 기능은 미지원이면 조용히 없고 기존 기능은 그대로 동작합니다.",
            "No. An experimental feature is quietly absent where unsupported and existing features work as before.",
          ),
        },
        {
          question: t("27개를 모두 쓰고 있나요?", "Are all 27 in use?"),
          answer: t(
            "아닙니다. 연결된 것은 화면 꺼짐 방지·스튜디오 미리 준비·화면 전환·스포이트 정도이고, 나머지는 지원 여부만 보여 주는 후보입니다.",
            "No. The wired ones are screen wake lock, studio prerender, view transitions and the eyedropper; the rest are candidates that only show support.",
          ),
        },
        {
          question: t("기기 압력은 무엇을 하나요?", "What does device pressure do?"),
          answer: t(
            "CPU 압력 단계를 설정 화면에 보여 줍니다. 아직 그 값으로 품질을 조절하는 소비처는 없습니다.",
            "It shows the CPU pressure level in settings. Nothing uses that value to adjust quality yet.",
          ),
        },
      ],
      pitfall: t(
        "설정 화면 문구는 기기 압력으로 무거운 기능의 품질을 조절한다고 적지만 현재는 표시뿐입니다. 레지스트리의 감지와 각 기능 모듈의 자체 감지가 이중으로 있고, 코드 주석의 지원 시점은 재확인 전에 단정하면 안 됩니다.",
        "The settings wording says device pressure adjusts the quality of heavy features, but today it only displays. Detection exists twice, in the registry and in each feature module, and support dates from code comments must not be asserted before rechecking.",
      ),
    },
    technologies: ["Compute Pressure", "Screen Wake Lock", "View Transitions", "Speculation Rules", "EyeDropper"],
    facts: [
      {
        value: "27",
        label: t("등록된 차세대 API 감지 항목 수", "Registered next-gen API detectors"),
        source: "apps/web/src/shared/lib/nextgen-web-capabilities.ts",
      },
      {
        value: "3",
        label: t("사용자가 끌 수 있는 실험 기능 토글 수", "Experimental toggles users can switch off"),
        source: "apps/web/src/shared/lib/nextgen-lab-settings.ts",
      },
    ],
    reviewedAt: "2026-10-07",
  },
  {
    id: "large-asset-delivery-r2-range",
    category: "web-platform",
    name: "Cloudflare R2",
    title: t("25 MiB 한계를 넘는 큰 파일의 배달 길", "Delivering files past the 25 MiB limit"),
    status: "live",
    tagline: t(
      "정적 호스팅의 25 MiB 한계를 R2 원본·압축 사이드카·Range 응답으로 돌아갑니다.",
      "R2 originals, compressed sidecars and Range replies get around the 25 MiB hosting limit.",
    ),
    background: [
      t(
        "Cloudflare 정적 자산 호스팅은 파일 하나가 25MiB 를 넘으면 올릴 수 없습니다(Cloudflare 문서). 그런데 CAD 형상 엔진 WASM 이나 온디바이스 AI 모델은 그보다 큽니다. 그래서 큰 파일 6개 경로만 Worker 가 먼저 받아 처리하고, 나머지 수많은 파일은 평소처럼 정적 호스팅이 처리합니다. 앱 코드는 주소가 달라지지 않아 이 구조를 알 필요가 없습니다.",
        "Cloudflare static asset hosting cannot take a single file over 25 MiB (Cloudflare docs). Yet the CAD geometry engine WASM and on-device AI models are bigger. So only six large-file paths are taken first by the Worker, and the many other files are served by static hosting as usual. App code sees no address change and need not know about this structure.",
      ),
      t(
        "요청이 오면 세 갈래로 나뉩니다. 첫째, Range 헤더가 없고 브라우저가 압축을 받을 수 있으면 같은 주소로 Brotli·gzip 압축 사이드카(.br, .gz)를 돌려줍니다. 둘째, Range 가 있거나 사이드카가 없으면 R2 버킷의 원본을 읽어, 부분 바이트(Range, If-Range)와 ETag 조건 요청을 처리하고 1년 immutable 캐시를 붙입니다. 셋째, 둘 다 없을 때만 명시적으로 설정한 폴백 원점으로 가며 쿠키와 인증 헤더는 넘기지 않습니다. 파일 형식별 Content-Type(예: application/wasm)도 Worker 가 정해 스트리밍 컴파일이 되게 합니다.",
        "A request then splits three ways. First, with no Range header and a browser that accepts compression, the same address returns a Brotli or gzip sidecar (.br, .gz). Second, with a Range or no sidecar, the original is read from the R2 bucket, handling partial bytes (Range, If-Range) and ETag conditional requests with a one-year immutable cache. Third, only when both are missing does it go to an explicitly configured fallback origin, forwarding no cookies or auth headers. The Worker also sets the Content-Type per file type, such as application/wasm, so streaming compilation works.",
      ),
      t(
        "받은 뒤에는 브라우저가 맡습니다. 서비스 워커가 .wasm 과 .onnx 를 heavy 보관함에 64개까지 cache-first 로 담아 두 번째부터는 다시 받지 않습니다(프리캐시 목록에서는 빠지지만 런타임에는 담깁니다). 배포 때는 prepare 스크립트가 사이드카를 만들고 새로 25MiB 를 넘는 미검토 파일이 생기면 배포를 멈춥니다. 대안인 외부 CDN 이나 파일 쪼개기는 주소·헤더 통제를 흩뜨리거나 로딩 코드를 바꿔야 합니다.",
        "After delivery, the browser takes over. The Service Worker keeps up to 64 .wasm and .onnx files in a heavy store, cache-first, so they are not fetched again (they are left out of the precache list but stored at runtime). At deploy time a prepare script builds the sidecars and stops the release if a new unreviewed file passes 25 MiB. The alternatives, an outside CDN or splitting files, scatter control of addresses and headers or require changing the loading code.",
      ),
      t(
        "한계: tag2pix 모델(약 79MB)은 압축본(약 73MB)도 25MiB 를 넘어 사이드카 없이 R2 단독입니다. 이 카드는 저장소의 코드·설정·문서를 확인한 것이고, 운영 R2 버킷의 실제 객체와 배포 결과는 Cloudflare 에서 직접 확인하지 않았습니다. README 의 Worker 우선 경로 목록은 wrangler.jsonc 보다 짧아 한쪽이 낡았습니다.",
        "Limits: the tag2pix model (about 79 MB) is still over 25 MiB even compressed (about 73 MB), so it has no sidecar and lives only in R2. This card reflects the repository's code, config and docs; the actual objects in the production R2 bucket and the deploy result were not checked in Cloudflare. The README's Worker-first path list is shorter than wrangler.jsonc, so one of them is out of date.",
      ),
    ],
    keyPoints: [
      t("25 MiB 한계는 큰 파일 6개 경로만 따로 처리", "Only six large-file paths bypass the 25 MiB limit"),
      t("일반 요청은 압축 사이드카, Range 는 R2 원본", "Plain requests get sidecars; Range goes to R2"),
      t("서비스 워커 heavy 보관함에 64개 cache-first", "The Service Worker heavy store holds 64, cache-first"),
      t("tag2pix 는 압축해도 커서 R2 단독", "tag2pix is too big even compressed: R2 only"),
    ],
    diagram: {
      id: "large-asset-delivery-r2-range-diagram",
      kind: "layers",
      title: t("큰 자산이 지나는 전달 계층", "The delivery layers a large asset crosses"),
      caption: t(
        "위에서부터 내려가며 처리하고, 압축본이 없거나 Range 면 R2 원본에서 읽습니다.",
        "Handled top to bottom: with no sidecar or with a Range request, the original is read from R2.",
      ),
      alt: t(
        "맨 위의 브라우저에서는 서비스 워커의 heavy 보관함이 한 번 받은 파일을 cache-first 로 돌려줍니다. 그 아래 Worker 가 큰 파일 6개 경로를 먼저 받아, 일반 요청에는 압축 사이드카를, Range 요청이나 사이드카가 없을 때는 R2 원본을 돌려주며, 둘 다 없을 때만 설정된 폴백 원점을 씁니다.",
        "At the top, the browser's Service Worker heavy store returns a file it already received, cache-first. Below, the Worker takes the six large-file paths first, returns a compressed sidecar for plain requests, serves the R2 original for Range requests or when no sidecar exists, and uses a configured fallback origin only when both are missing.",
      ),
      layers: [
        {
          id: "browser",
          label: t("브라우저 · heavy 보관함", "Browser: heavy store"),
          sub: t(".wasm·.onnx 는 서비스 워커가 64개까지 cache-first 로 보관", "the Service Worker keeps up to 64 .wasm and .onnx files, cache-first"),
          tone: "local",
          chips: ["Service Worker", "Cache Storage"],
        },
        {
          id: "worker",
          label: t("Worker 가 먼저 받음", "Worker answers first"),
          sub: t("run_worker_first 에 큰 파일 6개 경로를 등록", "run_worker_first lists the six large-file paths"),
          tone: "edge",
          chips: ["Cloudflare Workers"],
        },
        {
          id: "sidecar",
          label: t("압축 사이드카 (.br · .gz)", "Compressed sidecars (.br, .gz)"),
          sub: t("Range 없는 일반 요청에 Accept-Encoding 대로 응답", "plain requests without Range, answered per Accept-Encoding"),
          tone: "edge",
          chips: ["Cloudflare Static Assets"],
        },
        {
          id: "r2",
          label: t("R2 원본 (LARGE_ASSETS)", "R2 original (LARGE_ASSETS)"),
          sub: t("Range·If-Range·ETag 처리, 1년 immutable 캐시", "handles Range, If-Range and ETag, one-year immutable cache"),
          tone: "server",
          chips: ["Cloudflare R2"],
        },
        {
          id: "origin",
          label: t("지정 폴백 원점", "Configured fallback origin"),
          sub: t("LARGE_ASSET_ORIGIN 설정 시에만 · 쿠키·인증 헤더 미전달", "only if LARGE_ASSET_ORIGIN is set; no cookies or auth headers"),
          tone: "external",
        },
      ],
      brackets: [{ label: t("25 MiB 한계를 돌아가는 길", "Around the 25 MiB limit"), layerIds: ["worker", "sidecar", "r2"] }],
    },
    usage: [
      {
        feature: t("CAD 형상 처리 (OpenCascade WASM)", "CAD geometry (OpenCascade WASM)"),
        role: t(
          "25MiB 를 넘는 OpenCascade WASM 을 같은 주소로 내려받게 하고, 압축 사이드카와 R2 원본으로 나눠 서빙합니다.",
          "Lets the OpenCascade WASM over 25 MiB be fetched from the same address, served as compressed sidecars and an R2 original.",
        ),
        paths: [
          "deploy/cloudflare-static/src/large-static-assets.ts",
          "deploy/cloudflare-static/wrangler.jsonc",
          "deploy/cloudflare-static/src/index.ts",
        ],
        route: "/studio",
      },
      {
        feature: t("온디바이스 AI (ORT WASM · tag2pix 모델)", "On-device AI (ORT WASM and the tag2pix model)"),
        role: t(
          "ORT WASM 두 개와 약 79MB tag2pix 모델을 R2 에서 서빙하고, 모델은 받은 뒤 SHA-256 으로 무결성을 확인합니다.",
          "Serves two ORT WASM files and the roughly 79 MB tag2pix model from R2; the model's integrity is checked with SHA-256 after download.",
        ),
        paths: [
          "deploy/cloudflare-static/src/large-static-assets.ts",
          "apps/web/src/domains/creator/studio-onnx-inference-provider.ts",
        ],
      },
      {
        feature: t("서비스 워커 · 오프라인 재사용", "Service Worker · offline reuse"),
        role: t(
          ".wasm·.onnx 를 heavy 보관함(64개)에 cache-first 로 담아 한 번 받은 큰 파일을 다시 받지 않습니다.",
          "Keeps .wasm and .onnx files in the 64-entry heavy store, cache-first, so a large file already received is not fetched again.",
        ),
        paths: ["apps/web/src/app/service-worker/studio-service-worker-policy.ts"],
      },
      {
        feature: t("배포 파이프라인", "Deploy pipeline"),
        role: t(
          "사이드카를 만들고, 새 미검토 대형 파일이 생기면 배포를 멈추며, 승인된 원본만 R2 에 올린 뒤 Worker 를 배포합니다.",
          "Builds the sidecars, stops the release on any new unreviewed large file, uploads only approved originals to R2, then deploys the Worker.",
        ),
        paths: [
          "scripts/prepare-cloudflare-static-assets.mts",
          "scripts/sync-cloudflare-r2-assets.mts",
          "scripts/deploy-cloudflare-static.mjs",
          "deploy/cloudflare-static/README.md",
        ],
      },
    ],
    samples: [
      {
        kind: "teaching",
        title: t("Range 요청에 부분 응답하기", "Answering a Range request with a partial reply"),
        language: "ts",
        ...sampleSource([
          ["interface StoredObject {"],
          ["  readonly size: number;"],
          ["  read(range?: { offset: number; length: number }): Promise<Uint8Array<ArrayBuffer>>;"],
          ["}"],
          [""],
          ["export async function serve(object: StoredObject, rangeHeader: string | null): Promise<Response> {"],
          ['  const headers = { "accept-ranges": "bytes", "content-type": "application/wasm" };', "Content-Type 을 서버가 정해 스트리밍 컴파일을 돕는다", "the server sets Content-Type so streaming compilation works"],
          ["  const match = /^bytes=(\\d+)-(\\d*)$/u.exec(rangeHeader ?? \"\");"],
          ["  if (!match) return new Response(await object.read(), { headers });"],
          ["  const start = Number(match[1]);"],
          ["  const end = match[2] ? Math.min(Number(match[2]), object.size - 1) : object.size - 1;"],
          ["  if (start > end) return new Response(null, { status: 416, headers: { \"content-range\": `bytes */${object.size}` } });"],
          ["  const body = await object.read({ offset: start, length: end - start + 1 });"],
          ["  return new Response(body, {"],
          ["    status: 206,", "부분 내용", "partial content"],
          ["    headers: { ...headers, \"content-range\": `bytes ${start}-${end}/${object.size}` },"],
          ["  });"],
          ["}"],
        ]),
        explain: t(
          "실제 Worker(index.ts)는 R2 객체의 range 옵션, If-Range·ETag 비교, HEAD 요청, 1년 immutable 캐시까지 처리합니다. 여기서는 Range 헤더를 부분 응답(206)으로 바꾸는 핵심만 보여 줍니다.",
          "The real Worker (index.ts) also handles the R2 range option, If-Range and ETag comparison, HEAD requests and a one-year immutable cache. This shows only the core of turning a Range header into a partial (206) reply.",
        ),
        verify: "types",
      },
      {
        kind: "simplified",
        title: t("Worker 가 먼저 받는 경로와 R2 연결(요약)", "Worker-first paths and the R2 binding (abridged)"),
        language: "json",
        code: '{\n  "assets": {\n    "directory": "../../dist",\n    "run_worker_first": [\n      "/assets/opencascade.wasm-*.wasm",\n      "/assets/ort-wasm-simd-threaded.jsep-*.wasm",\n      "/assets/tag2pix-*.onnx"\n    ]\n  },\n  "r2_buckets": [{ "binding": "LARGE_ASSETS", "bucket_name": "toonspectrum-public-assets" }]\n}',
        explain: t(
          "deploy/cloudflare-static/wrangler.jsonc 에서 대형 파일 경로 3개만 골라 줄였습니다(실제로는 6개 경로와 동적 경로 20개가 함께 있습니다). 이 경로들만 정적 호스팅보다 Worker 가 먼저 받습니다.",
          "Abridged from deploy/cloudflare-static/wrangler.jsonc to three large-file paths (the real list has six of them plus twenty dynamic routes). Only these paths reach the Worker before static hosting.",
        ),
        source: "deploy/cloudflare-static/wrangler.jsonc",
      },
    ],
    links: [
      {
        title: "Cloudflare · Workers limits (Static Assets)",
        url: "https://developers.cloudflare.com/workers/platform/limits/",
        kind: "docs",
        note: t("개별 정적 파일 25 MiB 한도가 적힌 표", "The table that lists the 25 MiB per-file limit"),
      },
      {
        title: "Cloudflare · R2",
        url: "https://developers.cloudflare.com/r2/",
        kind: "docs",
      },
      {
        title: "Cloudflare · R2 Workers API reference",
        url: "https://developers.cloudflare.com/r2/api/workers/workers-api-reference/",
        kind: "docs",
        note: t("Worker 에서 R2 객체와 range 옵션을 읽는 방법", "Reading R2 objects and the range option from a Worker"),
      },
      {
        title: "MDN · HTTP range requests",
        url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Range_requests",
        kind: "docs",
      },
      {
        title: "Cloudflare · Static Assets",
        url: "https://developers.cloudflare.com/workers/static-assets/",
        kind: "docs",
      },
    ],
    chapterIds: ["infrastructure", "cost-engineering", "pwa-continuity"],
    talk: {
      pitch: t(
        "Cloudflare 정적 호스팅은 파일 하나가 25MiB 를 넘으면 올릴 수 없는데, CAD 엔진 WASM 과 AI 모델은 그보다 큽니다. 그래서 큰 파일 6개 경로만 Worker 가 먼저 받아, 압축본이 있으면 그것을, 부분 요청이면 R2 원본에서 잘라 주고, 브라우저는 한 번 받은 파일을 서비스 워커의 heavy 보관함에 둡니다. 앱 코드는 주소가 그대로라 이 구조를 모릅니다.",
        "Cloudflare static hosting cannot take a file over 25 MiB, yet the CAD engine WASM and AI models are larger. So the Worker takes just six large-file paths first, returns the compressed copy when there is one, cuts the requested range from the R2 original for partial requests, and the browser keeps a received file in the Service Worker heavy store. The address is unchanged, so app code does not know.",
      ),
      analogy: t(
        "엘리베이터에 싣지 못하는 큰 짐을 화물 전용 입구로 따로 받는 것과 같습니다. 같은 건물 주소로 오지만 문이 다릅니다.",
        "It is like receiving bulky freight that does not fit the elevator through a separate cargo entrance: same building address, different door.",
      ),
      questions: [
        {
          question: t("왜 그냥 외부 CDN 에 올리지 않나요?", "Why not just put it on an outside CDN?"),
          answer: t(
            "같은 주소로 서빙하면 앱 코드를 바꿀 필요가 없고, Worker 가 파일별 Content-Type(application/wasm 등)을 정해 WASM 스트리밍 컴파일이 되게 할 수 있습니다.",
            "Serving from the same address means no app-code change, and the Worker can set the per-file Content-Type (such as application/wasm) so WASM streaming compilation works.",
          ),
        },
        {
          question: t("Range 요청이 뭔가요?", "What is a Range request?"),
          answer: t(
            "파일의 일부 바이트만 달라는 요청입니다. Range 가 오면 압축본 대신 R2 원본에서 해당 구간을 잘라 주고, 일반 요청에는 압축 사이드카를 돌려줍니다.",
            "A request for only some bytes of a file. A Range request is answered from the R2 original instead of a sidecar, and plain requests get the compressed sidecar.",
          ),
        },
        {
          question: t("비용은 얼마나 드나요?", "How much does it cost?"),
          answer: t(
            "이 카드는 비용 수치를 다루지 않습니다. README 는 압축본(정적 자산) 요청을 우선 활용하고 R2 는 원본과 Range 용이라고 설명합니다.",
            "This card gives no cost figures. The README explains that compressed (static asset) requests are preferred and R2 serves originals and Range requests.",
          ),
        },
      ],
      pitfall: t(
        "tag2pix 모델은 압축본(약 73MB)도 25MiB 를 넘어 R2 단독이며 사이드카가 없습니다. 운영 R2 버킷의 실제 객체와 배포 결과는 Cloudflare 에서 직접 확인하지 않았습니다. README 의 Worker 우선 경로 목록은 wrangler.jsonc 와 일치하지 않습니다.",
        "The tag2pix model is over 25 MiB even compressed (about 73 MB), so it is R2-only with no sidecar. The actual objects in the production R2 bucket and the deploy result were not checked in Cloudflare. The README's Worker-first path list does not match wrangler.jsonc.",
      ),
    },
    technologies: ["Cloudflare R2", "Cloudflare Static Assets", "Cloudflare Workers", "Service Worker", "Brotli"],
    facts: [
      {
        value: "25 MiB",
        label: t("Cloudflare Static Assets 개별 파일 한도", "Cloudflare Static Assets per-file limit"),
        source: "deploy/cloudflare-static/src/large-static-assets.ts",
      },
      {
        value: "6",
        label: t("Worker 가 먼저 받도록 등록한 대형 파일 경로 수", "Large-file paths registered for Worker-first handling"),
        source: "deploy/cloudflare-static/wrangler.jsonc",
      },
      {
        value: "64",
        label: t("서비스 워커 heavy 보관함 항목 상한", "Entry cap of the Service Worker heavy store"),
        source: "apps/web/src/app/service-worker/studio-service-worker-policy.ts",
      },
    ],
    reviewedAt: "2026-10-07",
  },
];
