/**
 * 기술·발표 자료가 이름으로 언급하는 외부 제품·라이브러리·표준의 공식 링크 레지스트리.
 *
 * 플레이북 벤치마크, 제작 스토리 챕터의 기술 칩, 발표 덱·세미나의 기술 스택 칩,
 * 참고 자료 카드가 모두 이 표 하나로 링크를 해결한다. 링크가 없는 이름은 내부 개념
 * (예: "Document authority")이거나 공식 주소를 확정하지 못한 항목이며, 그 경우 칩은
 * 링크 없는 텍스트로 남는다 — 주소를 지어내지 않는 것이 이 표의 원칙이다.
 *
 * 수록 근거 (2026-10-07 확인):
 * - 저장소 안 기록: EngineeringSeminarResources의 공식 문서 표, 필드노트의 ref(),
 *   ENGINEERING_REFERENCE_PRODUCTS의 url, docs/operations의 제품 비교 문서.
 * - 설치본 package.json의 homepage·repository (scripts/collect-engineering-licenses.mjs 수집값).
 * - 그 외에는 공식 도메인이 확실한 제품 홈페이지·MDN·표준 문서만 넣었다.
 * 의도적으로 링크를 걸지 않은 항목: KMAS(공식 주소를 저장소 기록으로 확정하지 못함),
 * PWA 같은 일반 개념. Hokusai는 자체 제작물이 아니라 외부 crate(reearth/hokusai 0.3.0)를
 * packages/studio-hokusai-wasm이 감싼 것이라 업스트림 저장소로 링크한다.
 */
export interface EngineeringExternalLink {
  readonly name: string;
  readonly url: string;
}

export const ENGINEERING_EXTERNAL_LINKS: readonly EngineeringExternalLink[] = [
  // 벤치마크·참고 제품 (플레이북 #benchmarks와 참고 자료 카드)
  { name: "Clip Studio Paint", url: "https://www.clipstudio.net/en/" },
  { name: "Krita", url: "https://krita.org/" },
  { name: "Photoshop", url: "https://www.adobe.com/products/photoshop.html" },
  { name: "Adobe Photoshop", url: "https://www.adobe.com/products/photoshop.html" },
  { name: "Procreate", url: "https://procreate.com/" },
  { name: "MediBang Paint", url: "https://medibangpaint.com/" },
  { name: "MediBang", url: "https://medibangpaint.com/" },
  { name: "Figma", url: "https://www.figma.com/" },
  { name: "Figma Slides", url: "https://www.figma.com/slides/" },
  { name: "tldraw", url: "https://www.tldraw.com/" },
  { name: "Magma", url: "https://magma.com/" },
  { name: "Excalidraw", url: "https://excalidraw.com/" },
  { name: "Spline", url: "https://spline.design/" },
  { name: "Blender", url: "https://www.blender.org/" },
  { name: "SketchUp", url: "https://sketchup.trimble.com/en" },
  { name: "ACON3D", url: "https://www.acon3d.com/" },
  { name: "VRoid Studio", url: "https://vroid.com/en/studio" },
  { name: "MetaHuman", url: "https://www.metahuman.com/" },
  { name: "Gather", url: "https://www.gather.town/" },
  { name: "Gather 2.0", url: "https://www.gather.town/" },
  { name: "WorkAdventure", url: "https://workadventu.re/" },
  { name: "Kumospace", url: "https://www.kumospace.com/" },
  { name: "Canva", url: "https://www.canva.com/" },
  { name: "Adobe Express", url: "https://www.adobe.com/express/" },
  { name: "Dia", url: "https://www.diabrowser.com/" },
  { name: "Browser Use Cloud", url: "https://docs.browser-use.com/cloud/quickstart" },
  { name: "Vercel AI Gateway", url: "https://vercel.com/docs/ai-gateway" },
  { name: "OpenRouter", url: "https://openrouter.ai/" },

  // AI 공급자·무료 티어 공식 문서 (무료 AI 토큰 가이드용, 2026-10-08 공식 페이지 확인)
  { name: "Google AI Studio", url: "https://ai.google.dev/gemini-api/docs/rate-limits" },
  { name: "Groq", url: "https://console.groq.com/docs/rate-limits" },
  { name: "Cerebras", url: "https://inference-docs.cerebras.ai/introduction" },
  { name: "Mistral", url: "https://mistral.ai/pricing" },
  { name: "SambaNova", url: "https://cloud.sambanova.ai/" },
  { name: "Cohere", url: "https://docs.cohere.com/docs/rate-limits" },
  { name: "SiliconFlow", url: "https://docs.siliconflow.com/" },
  { name: "DeepSeek", url: "https://api-docs.deepseek.com/quick_start/pricing" },
  { name: "Z.AI", url: "https://docs.z.ai/guides/overview/pricing" },
  { name: "Alibaba Model Studio", url: "https://help.aliyun.com/en/model-studio/new-free-quota" },
  { name: "Ollama", url: "https://ollama.com/" },
  { name: "LM Studio", url: "https://lmstudio.ai/" },
  { name: "llama.cpp", url: "https://github.com/ggml-org/llama.cpp" },
  { name: "Cloudflare Workers AI", url: "https://developers.cloudflare.com/workers-ai/platform/pricing/" },
  { name: "GitHub Models", url: "https://docs.github.com/en/github-models/prototyping-with-ai-models" },
  { name: "Hugging Face Inference Providers", url: "https://huggingface.co/docs/inference-providers/index" },
  { name: "NVIDIA NIM", url: "https://build.nvidia.com/" },

  // 사용 라이브러리·엔진 (설치본 package.json homepage·repository와 저장소 기록 기준)
  { name: "Three.js", url: "https://threejs.org/" },
  { name: "React Three Fiber", url: "https://r3f.docs.pmnd.rs/" },
  { name: "React Three Fiber · Drei", url: "https://r3f.docs.pmnd.rs/" },
  { name: "Drei", url: "https://github.com/pmndrs/drei" },
  { name: "Babylon.js", url: "https://www.babylonjs.com/" },
  { name: "VRM", url: "https://vrm.dev/" },
  { name: "@pixiv/three-vrm", url: "https://github.com/pixiv/three-vrm" },
  { name: "OpenCascade.js", url: "https://github.com/donalffons/opencascade.js" },
  { name: "OpenCascade WASM", url: "https://github.com/donalffons/opencascade.js" },
  { name: "Manifold", url: "https://github.com/elalish/manifold" },
  { name: "Rhino3dm", url: "https://github.com/mcneel/rhino3dm" },
  { name: "xatlas", url: "https://github.com/jpcy/xatlas" },
  { name: "Blender MCP", url: "https://github.com/ahujasid/mcp-for-blender" },
  { name: "Blender bpy", url: "https://docs.blender.org/api/current/" },
  { name: "Helia", url: "https://github.com/ipfs/helia" },
  { name: "IPFS", url: "https://ipfs.tech/" },
  { name: "IPFS CID", url: "https://docs.ipfs.tech/concepts/content-addressing/" },
  { name: "multiformats", url: "https://github.com/multiformats/js-multiformats" },
  { name: "Phaser", url: "https://phaser.io/" },
  { name: "Phaser 3", url: "https://phaser.io/" },
  { name: "Yjs", url: "https://docs.yjs.dev/" },
  { name: "Automerge", url: "https://automerge.org/docs/hello/" },
  { name: "Socket.IO", url: "https://socket.io/" },
  { name: "NestJS", url: "https://nestjs.com/" },
  { name: "NestJS 11", url: "https://nestjs.com/" },
  { name: "React", url: "https://react.dev/" },
  { name: "TypeScript", url: "https://www.typescriptlang.org/" },
  { name: "Transformers.js", url: "https://github.com/huggingface/transformers.js" },
  { name: "@huggingface/transformers", url: "https://github.com/huggingface/transformers.js" },
  { name: "OPUS-MT ko→en", url: "https://huggingface.co/Xenova/opus-mt-ko-en" },
  { name: "OPUS-MT", url: "https://huggingface.co/Xenova/opus-mt-ko-en" },
  { name: "MediaPipe", url: "https://developers.google.com/edge/mediapipe/solutions/guide" },
  { name: "MediaPipe Tasks Vision", url: "https://developers.google.com/edge/mediapipe/solutions/vision/pose_landmarker/web_js" },
  { name: "ONNX Runtime Web", url: "https://onnxruntime.ai/docs/tutorials/web/" },
  { name: "onnxruntime-web", url: "https://onnxruntime.ai/docs/tutorials/web/" },
  { name: "Remotion", url: "https://www.remotion.dev/" },
  { name: "Remotion Player", url: "https://www.remotion.dev/docs/player" },
  { name: "Rapier", url: "https://rapier.rs/" },
  { name: "CanvasKit", url: "https://skia.org/docs/user/modules/canvaskit/" },
  { name: "CanvasKit / Skia", url: "https://skia.org/docs/user/modules/canvaskit/" },
  { name: "CanvasKit (Skia)", url: "https://skia.org/docs/user/modules/canvaskit/" },
  { name: "Konva", url: "https://konvajs.org/docs/" },
  { name: "Konva / React Konva", url: "https://konvajs.org/docs/" },
  { name: "Paper.js", url: "https://paperjs.org/" },
  { name: "p5.brush", url: "https://github.com/acamposuribe/p5.brush" },
  { name: "perfect-freehand", url: "https://github.com/steveruizok/perfect-freehand" },
  { name: "Google Ink", url: "https://github.com/google/ink" },
  { name: "three-mesh-bvh", url: "https://github.com/gkjohnson/three-mesh-bvh" },
  { name: "three-bvh-csg", url: "https://github.com/gkjohnson/three-bvh-csg" },
  { name: "Mixbox", url: "https://scrtwpns.com/mixbox" },
  { name: "spectral.js", url: "https://github.com/rvanwijnen/spectral.js" },
  { name: "ThorVG", url: "https://www.thorvg.org/" },
  { name: "Vello", url: "https://github.com/linebender/vello" },
  { name: "Hokusai", url: "https://github.com/reearth/hokusai" },
  { name: "OpenCV.js", url: "https://github.com/TechStark/opencv-js" },
  { name: "Zustand", url: "https://github.com/pmndrs/zustand" },
  { name: "glTF Transform", url: "https://gltf-transform.dev/" },
  { name: "Meshoptimizer", url: "https://github.com/zeux/meshoptimizer" },
  { name: "Playwright", url: "https://playwright.dev/" },
  { name: "@axe-core/playwright", url: "https://github.com/dequelabs/axe-core-npm" },
  { name: "Vitest", url: "https://vitest.dev/" },
  { name: "Testing Library", url: "https://testing-library.com/" },
  { name: "GitHub Actions", url: "https://docs.github.com/en/actions" },
  { name: "ESLint", url: "https://eslint.org/" },

  // 플랫폼·공급자·표준 문서
  { name: "Cloudflare", url: "https://www.cloudflare.com/" },
  { name: "Cloudflare Workers", url: "https://www.cloudflare.com/products/workers/" },
  { name: "Cloudflare Static Assets", url: "https://developers.cloudflare.com/workers/static-assets/" },
  { name: "Durable Objects", url: "https://developers.cloudflare.com/durable-objects/" },
  { name: "Cloudflare Durable Objects", url: "https://developers.cloudflare.com/durable-objects/" },
  { name: "Cloudflare Realtime TURN", url: "https://developers.cloudflare.com/realtime/turn/" },
  { name: "Render", url: "https://render.com/" },
  { name: "Supabase", url: "https://supabase.com/" },
  { name: "Supabase PostgreSQL", url: "https://supabase.com/docs/guides/database/overview" },
  { name: "Upstash Redis", url: "https://upstash.com/docs/redis/overall/getstarted" },
  { name: "Neon", url: "https://neon.com/" },
  { name: "Neon PostgreSQL", url: "https://neon.com/" },
  { name: "PostgreSQL", url: "https://www.postgresql.org/" },
  { name: "PostgreSQL / Neon", url: "https://www.postgresql.org/" },
  { name: "SQLite WASM", url: "https://sqlite.org/wasm/doc/trunk/index.md" },
  { name: "Poly Haven", url: "https://polyhaven.com/" },
  { name: "Poly Haven API", url: "https://polyhaven.com/" },
  { name: "Google Books", url: "https://books.google.com/" },
  { name: "Google Books API", url: "https://developers.google.com/books" },
  { name: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/Main_Page" },
  { name: "Google Drive", url: "https://developers.google.com/workspace/drive/api/guides/about-sdk" },
  { name: "Dropbox", url: "https://www.dropbox.com/developers" },
  { name: "OneDrive", url: "https://learn.microsoft.com/en-us/graph/onedrive-concept-overview" },
  { name: "Kakao SDK", url: "https://developers.kakao.com/" },
  { name: "MCP", url: "https://modelcontextprotocol.io/" },
  { name: "OAuth 2.0", url: "https://oauth.net/2/" },
  { name: "OAuth / OIDC", url: "https://oauth.net/2/" },
  { name: "OpenID Connect", url: "https://openid.net/developers/how-connect-works/" },
  { name: "SPDX", url: "https://spdx.org/licenses/" },
  { name: "GLB", url: "https://www.khronos.org/gltf/" },
  { name: "GLB / glTF", url: "https://www.khronos.org/gltf/" },
  { name: "GLB/glTF", url: "https://www.khronos.org/gltf/" },
  { name: "KTX2", url: "https://github.com/KhronosGroup/KTX-Software" },
  { name: "WebAssembly", url: "https://webassembly.org/" },
  { name: "WASM", url: "https://webassembly.org/" },
  { name: "Rust / WASM", url: "https://rust-lang.org/" },
  { name: "Rust/WASM", url: "https://rust-lang.org/" },
  { name: "C++ / Emscripten", url: "https://emscripten.org/" },
  { name: "Open Graph", url: "https://ogp.me/" },
  { name: "openskp", url: "https://openskp.com/" },

  // 웹 플랫폼 API (MDN·W3C — 저장소에 이미 인용된 문서와 같은 출처)
  { name: "WebRTC", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API" },
  { name: "RTCDataChannel", url: "https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel" },
  { name: "RTCPeerConnection", url: "https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection" },
  { name: "WebGPU", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API" },
  { name: "Web Workers", url: "https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers" },
  { name: "Dedicated Worker", url: "https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers" },
  { name: "Service Worker", url: "https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API" },
  { name: "OPFS", url: "https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system" },
  { name: "IndexedDB", url: "https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API" },
  { name: "Web Locks", url: "https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API" },
  { name: "Pointer Events", url: "https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events" },
  { name: "OffscreenCanvas", url: "https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas" },
  { name: "Web Share API", url: "https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API" },
  { name: "Web App Manifest", url: "https://www.w3.org/TR/appmanifest/" },
  { name: "View Transitions", url: "https://developer.mozilla.org/en-US/docs/Web/API/View_Transition_API" },
  { name: "WebTransport", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebTransport_API" },
  { name: "Clipboard API", url: "https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API" },
  { name: "Screen Wake Lock", url: "https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API" },
  { name: "getUserMedia", url: "https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia" },
  { name: "getDisplayMedia", url: "https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia" },
  { name: "WebGL2", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API" },
  { name: "Canvas2D", url: "https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API" },
  { name: "SharedArrayBuffer", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer" },
  { name: "Transferable", url: "https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects" },
  { name: "Cache Storage", url: "https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage" },
  { name: "HTMLMediaElement", url: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement" },
  { name: "AbortController", url: "https://developer.mozilla.org/en-US/docs/Web/API/AbortController" },
  { name: "WebVTT", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API" },
  { name: "SRI", url: "https://developer.mozilla.org/en-US/docs/Web/Security/Defenses/Subresource_Integrity" },
  { name: "Speculation Rules", url: "https://developer.mozilla.org/en-US/docs/Web/API/Speculation_Rules_API" },
  { name: "Compute Pressure", url: "https://developer.mozilla.org/en-US/docs/Web/API/Compute_Pressure_API" },
  { name: "EyeDropper", url: "https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper_API" },
  { name: "localStorage", url: "https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage" },

  // 프로토콜·표준·개념 (RFC·MDN·공식 문서, 2026-10-07 응답 확인)
  { name: "PKCE", url: "https://datatracker.ietf.org/doc/html/rfc7636" },
  { name: "PKCE S256", url: "https://datatracker.ietf.org/doc/html/rfc7636" },
  { name: "Authorization Code", url: "https://datatracker.ietf.org/doc/html/rfc6749" },
  { name: "nonce", url: "https://openid.net/specs/openid-connect-core-1_0.html" },
  { name: "robots.txt", url: "https://www.rfc-editor.org/rfc/rfc9309.html" },
  { name: "ICE", url: "https://datatracker.ietf.org/doc/html/rfc8445" },
  { name: "STUN/TURN", url: "https://datatracker.ietf.org/doc/html/rfc8656" },
  { name: "CRDT", url: "https://crdt.tech/" },
  { name: "R2", url: "https://developers.cloudflare.com/r2/" },
  { name: "Workers", url: "https://www.cloudflare.com/products/workers/" },
  { name: "wasm-pack", url: "https://rustwasm.github.io/docs/wasm-pack/" },
  { name: "WebGPU execution provider", url: "https://onnxruntime.ai/docs/tutorials/web/ep-webgpu.html" },
  { name: "Socket.IO signaling", url: "https://socket.io/" },

  // 도감 카드 칩 보강 (2026-10-08): 브라우저 표준(MDN·W3C)·프로토콜(RFC)·개발 도구. 응답을 확인한 공식 주소만 둔다.
  { name: "SHA-256", url: "https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest" },
  { name: "SubtleCrypto", url: "https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto" },
  { name: "Web Crypto API", url: "https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API" },
  { name: "HTML Drag and Drop", url: "https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API" },
  { name: "DataTransfer", url: "https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer" },
  { name: "DataTransfer.files", url: "https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/files" },
  { name: "requestAnimationFrame", url: "https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame" },
  { name: "requestIdleCallback", url: "https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback" },
  { name: "scheduler.yield()", url: "https://developer.mozilla.org/en-US/docs/Web/API/Scheduler/yield" },
  { name: "isInputPending", url: "https://developer.mozilla.org/en-US/docs/Web/API/Scheduling/isInputPending" },
  { name: "structuredClone", url: "https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone" },
  { name: "Intl.Segmenter", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter" },
  { name: "WebCodecs", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API" },
  { name: "VideoEncoder", url: "https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder" },
  { name: "ImageDecoder", url: "https://developer.mozilla.org/en-US/docs/Web/API/ImageDecoder" },
  { name: "MediaRecorder", url: "https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder" },
  { name: "Compression Streams", url: "https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API" },
  { name: "Streams API", url: "https://developer.mozilla.org/en-US/docs/Web/API/Streams_API" },
  { name: "File System Access API", url: "https://developer.mozilla.org/en-US/docs/Web/API/File_System_API" },
  { name: "Navigation Preload", url: "https://developer.mozilla.org/en-US/docs/Web/API/NavigationPreloadManager" },
  { name: "BroadcastChannel", url: "https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel" },
  { name: "Window Controls Overlay", url: "https://developer.mozilla.org/en-US/docs/Web/API/Window_Controls_Overlay_API" },
  { name: "WebXR", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API" },
  { name: "Container Queries", url: "https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Containment/Container_queries" },
  { name: ":has()", url: "https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Selectors/:has" },
  { name: "content-visibility", url: "https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/content-visibility" },
  { name: "Scroll-driven Animations", url: "https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Scroll-driven_animations" },
  { name: "Permissions-Policy", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Permissions-Policy" },
  { name: "Permissions API", url: "https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API" },
  { name: "CSP", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP" },
  { name: "COOP", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cross-Origin-Opener-Policy" },
  { name: "COEP", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cross-Origin-Embedder-Policy" },
  { name: "HSTS", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Strict-Transport-Security" },
  { name: "Retry-After", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Retry-After" },
  { name: "Cache-Control", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cache-Control" },
  { name: "WebSocket", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" },
  { name: "Fetch API", url: "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API" },
  { name: "WAI-ARIA", url: "https://www.w3.org/WAI/ARIA/apg/" },
  { name: "WGSL", url: "https://www.w3.org/TR/WGSL/" },
  { name: "Memory64", url: "https://github.com/WebAssembly/memory64" },
  { name: "fixed SIMD128", url: "https://github.com/WebAssembly/simd" },
  { name: "WebP", url: "https://developers.google.com/speed/webp" },
  { name: "PNG", url: "https://www.w3.org/TR/png/" },
  { name: "Brotli", url: "https://www.rfc-editor.org/rfc/rfc7932.html" },
  { name: "WebM", url: "https://www.webmproject.org/" },
  { name: "STUN", url: "https://www.rfc-editor.org/rfc/rfc8489.html" },
  { name: "TURN", url: "https://www.rfc-editor.org/rfc/rfc8656.html" },
  { name: "JSEP (RFC 9429)", url: "https://www.rfc-editor.org/rfc/rfc9429.html" },
  { name: "SFU", url: "https://www.rfc-editor.org/rfc/rfc7667.html" },
  { name: "SDP", url: "https://www.rfc-editor.org/rfc/rfc8866.html" },
  { name: "DTLS", url: "https://www.rfc-editor.org/rfc/rfc9147.html" },
  { name: "SCTP", url: "https://www.rfc-editor.org/rfc/rfc9260.html" },
  { name: "perfect negotiation", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation" },
  { name: "coturn", url: "https://github.com/coturn/coturn" },
  { name: "HTTP/3 (QUIC)", url: "https://www.rfc-editor.org/rfc/rfc9000.html" },
  { name: "ICE restart", url: "https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/restartIce" },
  { name: "JWT", url: "https://www.rfc-editor.org/rfc/rfc7519.html" },
  { name: "HMAC", url: "https://www.rfc-editor.org/rfc/rfc2104.html" },
  { name: "PBKDF2", url: "https://www.rfc-editor.org/rfc/rfc8018.html" },
  { name: "AES-GCM", url: "https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt" },
  { name: "Idempotency-Key", url: "https://datatracker.ietf.org/doc/draft-ietf-httpapi-idempotency-key-header/" },
  { name: "SSRF", url: "https://community.owasp.org/attacks/Server_Side_Request_Forgery" },
  { name: "C2PA", url: "https://c2pa.org/" },
  { name: "CC0 1.0", url: "https://creativecommons.org/publicdomain/zero/1.0/" },
  { name: "Vite", url: "https://vite.dev/" },
  { name: "Zod", url: "https://zod.dev/" },
  { name: "Node.js", url: "https://nodejs.org/" },
  { name: "pnpm", url: "https://pnpm.io/" },
  { name: "Corepack", url: "https://github.com/nodejs/corepack" },
  { name: "Tailwind CSS", url: "https://tailwindcss.com/" },
  { name: "Drizzle ORM", url: "https://orm.drizzle.team/" },
  { name: "SQLite", url: "https://www.sqlite.org/" },
  { name: "Secretlint", url: "https://github.com/secretlint/secretlint" },
  { name: "CodeQL", url: "https://codeql.github.com/docs/" },
  { name: "AGENTS.md", url: "https://agents.md/" },
  { name: "OpenCode", url: "https://opencode.ai/" },
  { name: "Capacitor", url: "https://capacitorjs.com/" },
  { name: "Cloudflare R2", url: "https://developers.cloudflare.com/r2/" },
  { name: "Hugging Face", url: "https://huggingface.co/" },
  { name: "FastAPI", url: "https://fastapi.tiangolo.com/" },
  { name: "Wan2.1", url: "https://github.com/Wan-Video/Wan2.1" },
  { name: "TripoSR", url: "https://github.com/VAST-AI-Research/TripoSR" },
  { name: "ElevenLabs Music", url: "https://elevenlabs.io/music" },
  { name: "wasm-bindgen", url: "https://github.com/wasm-bindgen/wasm-bindgen" },
  { name: "wgpu", url: "https://wgpu.rs/" },
  { name: "libmypaint", url: "https://github.com/mypaint/libmypaint" },
  { name: "HarfBuzz", url: "https://harfbuzz.github.io/" },
  { name: "ag-psd", url: "https://github.com/Agamnentzar/ag-psd" },
  { name: "Tiled", url: "https://www.mapeditor.org/" },
  { name: "Pillow", url: "https://python-pillow.org/" },
  { name: "Redis Lua", url: "https://redis.io/docs/latest/develop/programmability/eval-intro/" },
  { name: "Rendezvous hashing", url: "https://en.wikipedia.org/wiki/Rendezvous_hashing" },
  { name: "A* pathfinding", url: "https://en.wikipedia.org/wiki/A*_search_algorithm" },
  { name: "One Euro filter", url: "https://gery.casiez.net/1euro/" },
  { name: "Sobel", url: "https://en.wikipedia.org/wiki/Sobel_operator" },
  { name: "Hexagonal architecture", url: "https://alistair.cockburn.us/hexagonal-architecture/" },
  { name: "Circuit breaker", url: "https://martinfowler.com/bliki/CircuitBreaker.html" },
  { name: "KHR_materials_unlit", url: "https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_unlit" },
  { name: "MToon", url: "https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_materials_mtoon-1.0/README.md" },
  { name: "Tripo", url: "https://www.tripo3d.ai/" },
  { name: "Arcade Physics", url: "https://docs.phaser.io/phaser/concepts/physics/arcade" },
  { name: "Universal LPC", url: "https://github.com/LiberatedPixelCup/Universal-LPC-Spritesheet-Character-Generator" },
  { name: "lazy-brush", url: "https://github.com/dulnan/lazy-brush" },
  { name: "PostgreSQL advisory lock", url: "https://www.postgresql.org/docs/current/explicit-locking.html" },
  { name: "axe-core", url: "https://github.com/dequelabs/axe-core" },
  { name: "WCAG 2.2", url: "https://www.w3.org/TR/WCAG22/" },
  { name: "Toss Payments", url: "https://docs.tosspayments.com/reference" },
  { name: "nestjs-zod", url: "https://github.com/BenLorantfy/nestjs-zod" },
  { name: "Wrangler", url: "https://developers.cloudflare.com/workers/wrangler/commands/" },
  { name: "Drizzle Kit", url: "https://orm.drizzle.team/docs/drizzle-kit-generate" },
];

const BY_EXACT_NAME = new Map(ENGINEERING_EXTERNAL_LINKS.map((link) => [link.name, link.url]));
const BY_LOWER_NAME = new Map(ENGINEERING_EXTERNAL_LINKS.map((link) => [link.name.toLowerCase(), link.url]));

/**
 * 칩 이름으로 공식 링크를 찾는다. 정확히 일치 → 대소문자 무시 → 뒤에 붙은 버전
 * 표기(" 13.6.31" 등)를 떼고 재시도 순으로 해결하고, 없으면 undefined를 돌려준다.
 */
export function externalLinkForName(name: string): string | undefined {
  const trimmed = name.trim();
  const exact = BY_EXACT_NAME.get(trimmed) ?? BY_LOWER_NAME.get(trimmed.toLowerCase());
  if (exact) return exact;
  const withoutVersion = trimmed.replace(/\s+\d+(?:\.\d+)*[-\w.]*$/u, "");
  if (withoutVersion !== trimmed) {
    return BY_EXACT_NAME.get(withoutVersion) ?? BY_LOWER_NAME.get(withoutVersion.toLowerCase());
  }
  return undefined;
}
