/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const adapter_version: () => [number, number];
export const adopt_gpu_device: (a: any) => [number, number];
export const audit_svg_native_json: (a: number, b: number) => [number, number, number, number];
export const fabric_device_adopted: () => number;
export const fabric_device_handle: () => any;
export const fit_polyline_json: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const probe_webgpu: () => any;
export const render_lottie_gpu_json: (a: number, b: number, c: number, d: number, e: number) => any;
export const render_scene_gpu_json: (a: number, b: number) => any;
export const render_scene_gpu_texture_json: (a: number, b: number) => any;
export const render_scene_hybrid_gpu_texture_json: (a: number, b: number) => any;
export const render_scene_json: (a: number, b: number) => [number, number, number, number];
export const render_svg_cpu_json: (a: number, b: number, c: number, d: number) => [number, number, number];
export const render_svg_gpu_json: (a: number, b: number, c: number, d: number) => any;
export const shape_text_json: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const shape_text_vertical_json: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const wasm_bindgen_20dbe0276f26da23___convert__closures_____invoke___wasm_bindgen_20dbe0276f26da23___JsValue__core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_20dbe0276f26da23___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_20dbe0276f26da23___convert__closures_____invoke___js_sys_7101fe72579637ae___Function_fn_wasm_bindgen_20dbe0276f26da23___JsValue_____wasm_bindgen_20dbe0276f26da23___sys__Undefined___js_sys_7101fe72579637ae___Function_fn_wasm_bindgen_20dbe0276f26da23___JsValue_____wasm_bindgen_20dbe0276f26da23___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_20dbe0276f26da23___convert__closures_____invoke___wasm_bindgen_20dbe0276f26da23___JsValue______true_: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
