import { Navigate } from "react-router-dom";

import { LearnSectionShell } from "@/domains/learn/public/learn-section-shell";
import { defineAppRoutes } from "../app-route-definition";
import {
  CatalogResearchPage,
  CreatorHubPage,
  MaterialAtlasPage,
  NowPage,
  OpportunitiesPage,
  ReferenceAssetsPage,
  WorksPage,
  PolyHavenPage,
  AmbientCgPage,
  NasaImagesPage,
  VamCollectionsPage,
  RijksmuseumPage,
  GoogleFontsPage,
  GbifPage,
  MusicBrainzPage,
  InternetArchivePage,
  MetWeatherPage,
  KoreanHeritagePage,
  NeisSchoolPage,
  TourApiPage,
  KoreanDictionaryPage,
  SmithsonianPage,
  WikimediaInterestPage,
  EuropeanaPage,
  DplaPage,
  OpenDataLabPage,
  GlobalBooksPage,
  RecipesPage,
  StoryLabPage,
  OpenCreationPage,
  SourcesPage,
  ContentPacksPage,
  EducationHubPage,
  CollaborationHubPage,
  FandomCosplayPage,
  ComicLibraryPage,
} from "./creator-resource-pages";

export const creatorResourcesRoutes = defineAppRoutes([
  { id: "resources-make", path: "/make", element: <Navigate to="/studio/new" replace /> },
  { id: "resources-hub", path: "/creator-hub", element: <Navigate to="/studio" replace /> },
  { id: "resources-publishing", path: "/publishing", element: <Navigate to="/studio/publish" replace /> },
  { id: "resources-now", path: "/now", element: <NowPage /> },
  { id: "research-catalog", path: "/research/catalog", element: <CatalogResearchPage /> },
  { id: "research-catalog-notebook", path: "/research/catalog/notebook", element: <CatalogResearchPage /> },
  { id: "research-home", path: "/research", element: <CreatorHubPage /> },
  { id: "research-assets", path: "/research/assets", element: <ReferenceAssetsPage /> },
  { id: "research-open-creation", path: "/research/open-creation", element: <OpenCreationPage /> },
  { id: "research-content-packs", path: "/research/packs", element: <ContentPacksPage /> },
  { id: "research-books", path: "/research/books", element: <GlobalBooksPage /> },
  { id: "research-polyhaven", path: "/research/3d-assets", element: <PolyHavenPage /> },
  { id: "research-ambientcg", path: "/research/material-assets", element: <AmbientCgPage /> },
  { id: "resources-materials", path: "/research/materials", element: <MaterialAtlasPage /> },
  { id: "research-nasa-images", path: "/research/space-assets", element: <NasaImagesPage /> },
  { id: "research-vam", path: "/research/vam", element: <VamCollectionsPage /> },
  { id: "research-rijksmuseum", path: "/research/rijksmuseum", element: <RijksmuseumPage /> },
  { id: "research-google-fonts", path: "/research/fonts", element: <GoogleFontsPage /> },
  { id: "research-gbif", path: "/research/creatures", element: <GbifPage /> },
  { id: "research-musicbrainz", path: "/research/music-metadata", element: <MusicBrainzPage /> },
  { id: "research-internet-archive", path: "/research/archive", element: <InternetArchivePage /> },
  { id: "research-met-weather", path: "/research/weather-light", element: <MetWeatherPage /> },
  { id: "research-open-data", path: "/research/open-data", element: <OpenDataLabPage /> },
  { id: "research-open-data-heritage", path: "/research/open-data/kheritage", element: <KoreanHeritagePage /> },
  { id: "research-open-data-schools", path: "/research/open-data/neis", element: <NeisSchoolPage /> },
  { id: "research-open-data-tour", path: "/research/open-data/tourapi", element: <TourApiPage /> },
  { id: "research-open-data-korean", path: "/research/open-data/korean", element: <KoreanDictionaryPage /> },
  { id: "research-open-data-smithsonian", path: "/research/open-data/smithsonian", element: <SmithsonianPage /> },
  { id: "research-open-data-wikimedia", path: "/research/open-data/wikimedia", element: <WikimediaInterestPage /> },
  { id: "research-open-data-europeana", path: "/research/open-data/europeana", element: <EuropeanaPage /> },
  { id: "research-open-data-dpla", path: "/research/open-data/dpla", element: <DplaPage /> },
  { id: "research-open-data-ambientcg", path: "/research/open-data/ambientcg", element: <AmbientCgPage /> },
  { id: "research-open-data-vam", path: "/research/open-data/vam", element: <VamCollectionsPage /> },
  { id: "research-open-data-nasa", path: "/research/open-data/nasa", element: <NasaImagesPage /> },
  { id: "research-open-data-gbif", path: "/research/open-data/gbif", element: <GbifPage /> },
  { id: "research-open-data-musicbrainz", path: "/research/open-data/musicbrainz", element: <MusicBrainzPage /> },
  { id: "research-open-data-internet-archive", path: "/research/open-data/internetarchive", element: <InternetArchivePage /> },
  { id: "resources-references", path: "/creator-hub/references", element: <Navigate to="/research/assets" replace /> },
  { id: "resources-opportunities", path: "/opportunities", element: <OpportunitiesPage /> },
  // 제작 레시피는 /learn 아래에 사는 학습 화면이다 — LearnPage 밖 라우트라 학습 셸을
  // 라우트 레이어에서 감싼다(셸의 공개 경계는 learn/public 배럴이 소유한다).
  { id: "resources-recipes", path: "/learn/recipes", element: <LearnSectionShell><RecipesPage /></LearnSectionShell> },
  { id: "resources-story", path: "/story-lab", element: <StoryLabPage /> },
  { id: "resources-works", path: "/discover/works", element: <WorksPage /> },
  { id: "resources-sources", path: "/insights/resources", element: <SourcesPage /> },
  { id: "ecosystem-home", path: "/ecosystem", element: <Navigate to="/ecosystem/education" replace /> },
  { id: "ecosystem-education-legacy", path: "/learn/education", element: <Navigate to="/ecosystem/education" replace /> },
  { id: "ecosystem-education", path: "/ecosystem/education", element: <EducationHubPage /> },
  { id: "ecosystem-collaboration", path: "/ecosystem/collaboration", element: <CollaborationHubPage /> },
  { id: "ecosystem-fandom", path: "/ecosystem/fandom", element: <FandomCosplayPage /> },
  { id: "ecosystem-library", path: "/ecosystem/library", element: <ComicLibraryPage /> },
  { id: "resources-showcase", path: "/challenges", element: <Navigate to="/showcase/challenges" replace /> },
]);
